### ISSUE TITLE
Dynamic publicPath

### ISSUE THREAD

**Issue by adamhaeger** [module-federation/module-federation-examples#102]
Hi! 

Im amazed and grateful by all this work, truly a gamechanger!
Very smooth to implement, but the one thing Im struggling with is publicPath. I know there is a pr up to solve this, but there seems to be debate about whether it should be merged or not.

In our case, we have a host application that has dev, test and prod environments, and then the remote apps also have dev, test and prod environments. So the host app in dev, needs to load the remote code from dev etc. It seems to me that the only way to achieve this currently is to create a separate build for each environment. Is this correct or is there a workaround?

Thanks again!

**Comment by zhangwilling** [comment]
that's what your outer config should do. 

you can write all env config in a Map, and get corresponding publicPath by juding env. 

env variable can be supplied by your package scripts or npm scripts.

'create a separate build for each environment' is right, all remotes should be served by local server, such as webpack-dev-server.

**Comment by zhangwilling** [comment]
if you want more flexiable, you can download config from server and use advanced api in MF at runtime.

**Comment by adamhaeger** [comment]
> if you want more flexiable, you can download config from server and use advanced api in MF at runtime.

Thanks for the super swift answer! Sounds like Im on the right track then. I am interested in a more flexible way to set the path though, would be nice to not have to run the build once for each environment. 

Is there any examples on how to use the advanced API that you mention? I haven't found this in the docs anywhere.

**Comment by ScriptedAlchemy** [comment]
public path is on the docket for a future release. Allowing hosts to execute initialization code in a remote, like changing public path. For right now. you're stuck with defining it in a hard-coded webpack config. The only solution beyond waiting for us to do it is for webpack

**Comment by ScriptedAlchemy** [comment]
You can reverse engineer this -> https://gist.github.com/ScriptedAlchemy/60d0c49ce049184f6ce3e86ca351fdca

**Comment by devonChurch** [comment]
I can confirm that the intermediary approach @ScriptedAlchemy outlined above ☝️  works well in the context of assigning `publicPath`'s to individual remotes at run time.

We have a Micro Front-end setup using Federated Modules. We can build our artifact once and move it along our environment flow _(**Dev**, **Test**, **Stage**, **UAT**, **Prod**)_ without re-building our bundle 🎉 

![deployment-flow](https://user-images.githubusercontent.com/15273233/93658783-d55c8100-fa92-11ea-84a0-7ed406b25cf6.png)

---

I will describe a simplified version of our system below and hope that it can help others get set up and working with the Federated Module paradigm 🙏 

## Configuration
To achieve this environment agnostic setup, we use two configuration files:
1. `location.config.json`
   [A global reference](https://gist.github.com/devonChurch/c8f43d0270fc71168cdf23765043f679#file-location-config-json) of each Micro Front-end's endpoints on a per-environment basis.

2. `environment.config.json`
   [A file scoped to the root of each environment bucket](https://gist.github.com/devonChurch/c8f43d0270fc71168cdf23765043f679#file-environment-config-json) that gives the application its context at run time.

## Webpack
1. When we build our artifact, [we exchange the static public path for a function that will execute at run time](https://gist.github.com/devonChurch/c8f43d0270fc71168cdf23765043f679#file-webpack-config-js-L10-L52). 

2. The function expects [global variables to be present in the windows scope](https://gist.github.com/devonChurch/c8f43d0270fc71168cdf23765043f679#file-webpack-config-js-L40), so we need to set them up at run time **before** calling the function _(see below)_ 👇 .

## Browser
1. First, [we fetch our configuration files](https://gist.github.com/devonChurch/c8f43d0270fc71168cdf23765043f679#file-index-html-L29-L32) _(`location.config.json` and `environment.config.json`)_, [then assign them to global variables](https://gist.github.com/devonChurch/c8f43d0270fc71168cdf23765043f679#file-index-html-L34-L38).

2. From there, [we fetch all of the required Javascript](https://gist.github.com/devonChurch/c8f43d0270fc71168cdf23765043f679#file-index-html-L43-L56) (generic bundle and `remoteEntry.js` data) [and add it to the page](https://gist.github.com/devonChurch/c8f43d0270fc71168cdf23765043f679#file-index-html-L57-L63).

3. When the Javascript added above ☝️  initialises, it will generate a `publicPath` based on the global variables that hold our configuration files 🎊 

![run-time-flow](https://user-images.githubusercontent.com/15273233/93658796-e2797000-fa92-11ea-8226-bf1e528251c5.png)

---

I hope that this helps someone 🙏  

This has proven effective in our team so far. The Webpack and HTML _(shell)_ orchestration is generic and can be used for each Micro Front-end as part of a boilerplate 👍 

This would be a great topic to cover in [Practical Module Federation](https://module-federation.myshopify.com/products/practical-module-federation) _(which I enjoyed reading BTW)_ 😃 .

**Comment by ScriptedAlchemy** [comment]
This has been resolved. https://link.medium.com/odRa0yWMdab

**Comment by waldronmatt** [comment]
For anyone needing a working solution, I put together a repository using the code and methods outlined by devonChurch and ScriptedAlchemy above; thank you both for sharing your insights!

https://github.com/waldronmatt/dynamic-host-module-federation

https://dev.to/waldronmatt/tutorial-a-guide-to-module-federation-for-enterprise-n5

**Comment by maitrungduc1410** [comment]
at the moment, 2022, set `publicPath: 'auto'` works perfectly.

Anyway, thanks @devonChurch for his solution with `DynamicPublicPathPlugin`, I have followed that solution, it has been working fine for a while.

**Comment by ScriptedAlchemy** [comment]
yep publicPath: auto is the built in way, it uses document.currentScript.src to get the base path based on where the remote came from to begin with

**Comment by cyberfury10** [comment]
`publicPath : auto` is not working as expected . In my react micro frontend project which uses module federation plugin remoteEntry.js path is incorrectly fetched and application crashes.

With hard-coded ```publicPath``` in webpack things work as expected.
Due existing CI/CD setup in my project, I couldn't hard-code publicPath at the build time.

it was recommended to use `publicPath : auto` in the webpack config of the application.
Yes `publicPath : auto` solves the issue of hard coding at build time.

But during page refresh, `remoteEntry.js` is fetched from incorrect url.

To simulate the scenario I created a simple react application using webpack and module federation plugin

On the initial load remoteEntry.js is fetched from `http://localhost:3000/remoteEntry.js` as expected
<img width="1168" alt="Screenshot 2022-09-08 at 15 14 54" src="https://user-images.githubusercontent.com/45261873/189097864-499e2b17-65cb-4c6f-ac5f-67a25c5d58e9.png">

When under nested URL `http://localhost:3000/home/foo/about`, On refresh main.js and remoteEntry.js is fetched from `http://localhost:3000/home/foo/remoteEntry.js` - application crashes

<img width="1176" alt="Screenshot 2022-09-08 at 15 18 59" src="https://user-images.githubusercontent.com/45261873/189098011-57f3210e-3e32-4400-86bf-468e1e911f3b.png">

Github link for the project simulating the scenario https://github.com/jidu0106/mf-page-refresh-issue

I am using "react-router-dom": "^6.3.0" and also tried with "@reach/router": "^1.3.4", but the issue is same

**Comment by ScriptedAlchemy** [comment]
probably a config issue with how youre serving the spa. it always is

**Comment by chladog** [comment]
,,

Dne pá 9. 9. 2022 7:39 uživatel Zack Jackson ***@***.***>
napsal:

**Comment by cyberfury10** [comment]
> probably a config issue with how youre serving the spa. it always is

Thanks for the response. 
With reference to  https://github.com/module-federation/module-federation-examples/pull/2170 adding another `publicPath : '/'` in HtmlWebpackPlugin() solved the issue

 ```
 new HtmlWebPackPlugin({
    template: './public/index.html',
    favicon: './public/favicon.png',
    assets: './public/assets',
    publicPath: '/',
  }),
```

**Comment by taylous** [comment]
@cyberfury10 

assigned to `HtmlWebpackPlugin` as above code, but **still request bundle file in wrong place when refreshed.** 😥

the publicPath of the host app is set to` 'auto'` and the publicPath of the remote app is set to `domain`(ex: http://localhost:4000).

is there anything I set wrong?
I'd appreciate your advice.

**Comment by darktasevski** [comment]
@taylous I had the same issue and setting the base field in the `HtmlWebPackPlugin` config, seems to help:

```js
new HtmlWebPackPlugin({
   template: './public/index.html',
   // ...
   base: { href: '/' }
 }),
 ```

**Comment by robinsout** [comment]
> Thanks for the response.
> With reference to #2170 adding another `publicPath : '/'` in HtmlWebpackPlugin() solved the issue

Man! That is really helpfull! I've spent so much time trying to configure my project to work as standalone and via module federation at once and this fixed the issue with page refresh in standalone mode.

Now I have in my webpack config:
```
output: {
  publicPath: 'auto', // this is for Module Federation exposition
},
...
plugins[
  new HtmlWebpackPlugin({
    publicPath: '/', // this is for standalone mode
    ...
],
```

**Comment by Likhitha4131** [comment]
Having this error I am unable to resolve this @robinsout 
[ Module Federation Manifest Plugin ]: Manifest will not generate, because publicPath can only be absolute path, but got 'auto'
(node:20292) [DEP_WEBPACK_PRE_COMPILED_SCHEMA_INVALID] 
import {  NextFederationPlugin } from '@module-federation/nextjs-mf';

const nextConfig = {
  reactStrictMode: true,
  webpack: (config, options) => {
    const { isServer } = options;
    config.plugins.push(
      new NextFederationPlugin({
        name: 'shop',
        remotes: {
          main: `main@http://localhost:3000/_next/static/${isServer ? 'ssr' : 'chunks'}/remoteEntry.js`,
        },
        filename: 'static/chunks/remoteEntry.js',
        exposes:{
          './catalog': "./src/components/MISCard.tsx"
        },
        extraOptions: {
          exposePages: true
        },
        // publicPath:'/'
      })
    );
    config.output.publicPath='auto';
    console.log(config.output);
    return config;
  }
  
};
   export default nextConfig;
I have tried to set the both you said either of them haven't solved this error 
I am also unable to run my application
My OS-Windows 10
I am using 
"webpack": "5.1.3", 
"next": "14.1.4"

**Comment by ScriptedAlchemy** [comment]
look into runtime plugins from module-federation/enhanced and /runtime - this would let you control more aspects

**Comment by kalraDikshit** [comment]
> look into runtime plugins from module-federation/enhanced and /runtime - this would let you control more aspects

https://module-federation.io/configure/getpublicpath.html

This worked for me.
