### ISSUE TITLE
Question: reloading/unmounting a FM

### ISSUE THREAD

**Issue by csvan** [module-federation/module-federation-examples#1025]
I use logic similar to the following in order to dynamically load FMs for my app:

https://github.com/module-federation/module-federation-examples/blob/master/dynamic-system-host/app1/src/App.js#L16

However, say the remote version of an FM changes and I want to reload it in its entirety, or remove it from my app context altogether - is this even possible and what is the preferred pattern of doing so?

**Comment by ScriptedAlchemy** [comment]
You'd have to remove/readd the remote script. But I'm not sure that would detach the on memory references other hosts might have started to use from earlier on in the render / consumption


You might be able to garbage called it by removing the script and setting window.remote=null 

However I don't know if it would clear internal webpack references that have already been created or consumed. Would need to be tested 

It sounds like you're looking for hot reloading in production. Something we cannot do with federation

**Comment by csvan** [comment]
@ScriptedAlchemy in my case, it's meant for hot reloading only during development (we do not use HMR for various reasons, and as far as I understand it is not compatible with MF anyhow).

My use case is to detect changes to FMs during development, and perform a client-side reload. I will try the approaches you suggested here and come back with results, thanks!

**Comment by ScriptedAlchemy** [comment]
We built a live reloading system for MF, it'll be out in the next few days which aims at hmr like reloading for the client side

**Comment by csvan** [comment]
@ScriptedAlchemy that sounds awesome, looking forward to it! 

For the sake of completeness, I managed to get ours working - the only headache is that dynamic imports are not reloaded and hence code changed in them is not reflected. I suppose this needs cache busting at a deeper level. Looking forward to see how you have solved it.

**Comment by ScriptedAlchemy** [comment]
We basically reload the page haha, but wrote a webpack plugin a socket layer to communicate with other remotes and detect changes from any of them, if you have dev tools open then check the disable cache checkbox to avoid browser caching the remote

**Comment by csvan** [comment]
@ScriptedAlchemy ah ok, that's exactly how our current setup works I think - each remote runs on its own webpack-dev-server and notifies the host when they rebuild, causing the host to trigger a page reload.

The reason I wanted to go towards hot reloading is because our host is pretty huge in non-production mode, and it takes about 10s to reload the page. The remotes are a lot smaller, and DX would be better if we could just reload them.

Regarding the cache issue - even if I disable cache both in the browser dev server the FMs still do not update. I guess that once webpack resolves a reference, it keeps the resolved version in memory and does not bother to look it up again even if a new version of the same module has been injected. If I could just find a way to make Webpack invalidate that cache I could probably go further.

**Comment by csvan** [comment]
@ScriptedAlchemy was this landed in one of the recent releases? Would like to check it out :)

**Comment by ScriptedAlchemy** [comment]
Module-federation/fmr is the package

**Comment by norman-ags** [comment]
Mmmmmm

**Comment by ScriptedAlchemy** [comment]
Also someone got HMR working. On federated code. Use FMR / live reload on the hot application and HMR only on the remote containers seemed to work for some users.

**Comment by csvan** [comment]
@ScriptedAlchemy do you know if that code is public somewhere? Would love to look at the setup

**Comment by ScriptedAlchemy** [comment]
Check this repos recent merges. Someone added PRd it recently.

**Comment by csvan** [comment]
PR with example: https://github.com/module-federation/module-federation-examples/pull/1164
