### ISSUE TITLE
How to have multiple instance of the same remoteEntry file

### ISSUE THREAD

**Issue by dr194** [module-federation/module-federation-examples#1050]
I  have used module federation in Angular 12 with GraphQL integration in the below pattern
1. Child2: Consists of two different modules(a and b) which are exposes to other mfes
2. Child1: Consumes 1 of the module(a) of Child2 and exposes module of its own
3. Mfe_Parent: Consumes both Child1 and Child2(with module(b))

To overcome cache busting, I've used timestamp as queryparam along with remotePaths
**In Parent Mfe_Parent:**

```const todayTs = new Date().setHours(0, 0, 0, 0);
module.exports = {
    plugins: [
        new ModuleFederationPlugin({
            remotes: {
                "child1": `child1@https://child1.com/child1RemoteEntry.js?v=${todayTs}`,
                "child2": `child2@https://child2.com/child2RemoteEntry.js?v=${todayTs}`,
            },
       })
]};
```

**In Child1 Mfe:**
```
const todayTs = new Date().setHours(0, 0, 0, 0);
module.exports = {
    plugins: [
        new ModuleFederationPlugin({
            remotes: {
                "child2": `child2@https://child2.com/child2RemoteEntry.js?v=${todayTs}`,
            },
       })
]};
```
So with this approach the timestamp "todayTs" used will be the same while build and there will be only 1 instance of child2 is created which will be consumed by both Mfe_Parent and Child1. But with this approach if there is any change in Mfe_Parent which requires a deployment, we will still have to deploy Child1 even if there are no changes made, if not the "todayTs" will be different in both the remote paths and two instances will be created for Child2. Due to two instances created, GraphQL is not able to create two difference instance of the module from respective called mfes.

Is there any possible configuration or any way using which this dependency can be eliminated and only Mfe_Parent can be deployed without having to deploy Child1 always.

**Comment by ScriptedAlchemy** [comment]
You could configure it at runtime with something like this. 

https://github.com/module-federation/external-remotes-plugin

I always cache bust the remotes to the millisecond or I'll use the cdn to control the cache headers

**Comment by ScriptedAlchemy** [comment]
If I understand you want to avoid two different cached variations of the same remote?

**Comment by SavvasDivyaR** [comment]
> If I understand you want to avoid two different cached variations of the same remote?

That's right. With using the 'todayTs' also i'm able to achieve it now since same remote from both mfes will use same timestamp. So, everyday we will have to deploy Child1 and Parent mfes even if Child1 has no changes done and doesn't require a deployment.

But if i try to add different timestamps then the issue i'm facing is with GraphQL which only creates one instance(Parent) of the module and does not create another GraphQL instance for Child1 and the created instance is not shared with Child1 from Parent_mfe. GraphQL throws attached error where milliseconds are added to the remoteEntry files(235 added from Parent and 580 is added from Child1)
![image](https://user-images.githubusercontent.com/77712241/127967295-9b1ca1ba-ac0d-40ea-b8d3-f8d59fc786c0.png)

![image](https://user-images.githubusercontent.com/77712241/127966828-3ed41c74-45bb-4f4a-8158-d38967d471dd.png)

**Comment by dr194** [comment]
> If I understand you want to avoid two different cached variations of the same remote?

That's right. With using the 'todayTs' also i'm able to achieve it now since same remote from both mfes will use same timestamp. So, everyday we will have to deploy Child1 and Parent mfes even if Child1 has no changes done and doesn't require a deployment whereas Parent has some changes to be deployed.

But if i try to add different timestamps then the issue i'm facing is with GraphQL which only creates one instance(Parent) of the module and does not create another GraphQL instance for Child1 and the created instance is not shared with Child1 from Parent_mfe. GraphQL throws attached error where milliseconds are added to the remoteEntry files(235 added from Parent and 580 is added from Child1 for Child2 mfe)
![image](https://user-images.githubusercontent.com/77712241/127967295-9b1ca1ba-ac0d-40ea-b8d3-f8d59fc786c0.png)

![image](https://user-images.githubusercontent.com/77712241/127966828-3ed41c74-45bb-4f4a-8158-d38967d471dd.png)

**Comment by cjz9032** [comment]
> > If I understand you want to avoid two different cached variations of the same remote?
> 
> That's right. With using the 'todayTs' also i'm able to achieve it now since same remote from both mfes will use same timestamp. So, everyday we will have to deploy Child1 and Parent mfes even if Child1 has no changes done and doesn't require a deployment whereas Parent has some changes to be deployed.
> 
> But if i try to add different timestamps then the issue i'm facing is with GraphQL which only creates one instance(Parent) of the module and does not create another GraphQL instance for Child1 and the created instance is not shared with Child1 from Parent_mfe. GraphQL throws attached error where milliseconds are added to the remoteEntry files(235 added from Parent and 580 is added from Child1 for Child2 mfe)
> ![image](https://user-images.githubusercontent.com/77712241/127967295-9b1ca1ba-ac0d-40ea-b8d3-f8d59fc786c0.png)
> 
> ![image](https://user-images.githubusercontent.com/77712241/127966828-3ed41c74-45bb-4f4a-8158-d38967d471dd.png)

so, the totally dynamic solution , i think it can work fine
https://codesandbox.io/s/dynamic-remotes-webpack-module-federation-o51ho?from-embed=&file=/home/app.jsx
