### ISSUE TITLE
angular-universal-ssr example has issues with Beta.18

### ISSUE THREAD

**Issue by ScriptedAlchemy** [module-federation/module-federation-examples#106]
@newvladimirov when upgrading to beta.18, i run into issues on angular-universal-ssr
Mind taking a look?
https://github.com/module-federation/module-federation-examples/pull/105

**Comment by newvladimirov** [comment]
@ScriptedAlchemy yep, I see. 
After several fixes I'm getting "Shared module is not available for eager consumption" related to @angular/core. Unfortunately i can't debug it right today, but for sure i'll take a closer look in a couple of days.

**Comment by ScriptedAlchemy** [comment]
thats fine, do this in shared
```
react: {
          eager: true,
          singleton: true,
          requiredVersion: deps.react,
        },
```

**Comment by ScriptedAlchemy** [comment]
or something like that. https://medium.com/dev-genius/module-federation-advanced-api-inwebpack-5-0-0-beta-17-71cd4d42e534

**Comment by newvladimirov** [comment]
Now i'm getting  "fn is not a function" in NodeJS. I double checked that remoteEntry is loaded and all paths are correct. 
Here is configs: 

```
new ModuleFederationPlugin({
        name: "hostApp",
        filename: "remoteEntry.js",
        library: { type: "commonjs2" },
        remotes: {
          clientApp: resolve(__dirname, "../../client-app/dist/server/remoteEntry.js"),
        },
        shared: [
          { "@angular/core": { singleton: true, eager: true } },
          { "@angular/common": { singleton: true, eager: true } },
          { "@angular/router": { singleton: true, eager: true } },
        ],
      }),

```

```
new ModuleFederationPlugin({
        name: "clientApp",
        filename: "remoteEntry.js",
        library: { type: "commonjs2" },
        exposes: {
          "./Component": "./src/app/client-cities/client-city/client-city.component.ts",
          "./Module": "./src/app/client-cities/client-cities.module.ts",
        },
        shared: [
          { "@angular/core": { singleton: true, eager: true } },
          { "@angular/common": { singleton: true, eager: true } },
          { "@angular/router": { singleton: true, eager: true } },
        ],
      }),
```

@ScriptedAlchemy maybe you have any thoughts?

**Comment by ScriptedAlchemy** [comment]
try loading the remote of each host app as well. So have the host load its own remote

**Comment by ScriptedAlchemy** [comment]
@newvladimirov want to give it another attempt with the latest webpack beta.21?

**Comment by newvladimirov** [comment]
@ScriptedAlchemy I had absolutely no time last two weeks, but i gonna fix my example in the next couple of days.

**Comment by ScriptedAlchemy** [comment]
No worries, just bumping - i know we are all busy!

**Comment by ScriptedAlchemy** [comment]
Closing as i think this was updated
