### ISSUE TITLE
Cannot npm install nextjs example - nextjs-shared: Not found

### ISSUE THREAD

**Issue by dreamerkumar** [module-federation/module-federation-examples#1066]
I have bought the module and am able to install  `@module-federation/nextjs-mf`

However the checkout, home and shop apps have `"nextjs-shared": "*"` as a dependency. Running `npm install` or `yarn` within these folders is giving me the following error:

An unexpected error occurred: "https://registry.yarnpkg.com/nextjs-shared: Not found".

**Comment by ScriptedAlchemy** [comment]
It sounds like for some reason the  monorepo isn't registering the shared package. A workaround is to point it at the file location if you need to. Like ../shared inside package json

**Comment by ScriptedAlchemy** [comment]
What happens if you try using yarn? Or deleting any lock file that might be commuted accidentally

**Comment by gnoyixiang** [comment]
@ScriptedAlchemy  Facing the same issue. Why is the nextjs-shared being added as an npm dependency? Are we supposed to publish nextjs-shared?

**Comment by dreamerkumar** [comment]
@ScriptedAlchemy deleting package lock or using yarn didn't help. I actually got past this issue yesterday by removing that package dependency and changing the imports in the other project to straight to that file in the `nextjs-shared` folder. 

After realizing that `nextjs-shared` is just a sibling folder, there are some other options as well. I know I have previously successfully used a package reference pattern like this 
```
...
"dependencies": {
"common": "file:../common/"
}
```

Npm link could be another solution as well.

**Comment by ScriptedAlchemy** [comment]
Yeah using the file path should work. I'm not sure why some experience this issue. I'll try again on a clean pull and see if anything happens on my end

**Comment by rahul3103** [comment]
Hey, I am also facing the same issue. I have purchased the module but now I am trying to install packages it's saying 
``` npm install
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/nextjs-shared - Not found
npm ERR! 404
npm ERR! 404  'nextjs-shared@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'checkout'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:```

**Comment by rahul3103** [comment]
@ScriptedAlchemy I was able to install packages after changing
```
 "dependencies": {
    "@module-federation/nextjs-mf": "^3.2.0",
    "lodash": "4.17.21",
    "next": "11.1.2",
    "next-compose-plugins": "^2.2.1",
    "nextjs-shared": "../shared/",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "webpack": "5.52.1",
    "webpack-merge": "^5.8.0"
  }
 ```
 
But, after this, I am getting a new error
 
```
  [0] event - build page: /
[0] wait  - compiling...
[0] error - Module not found: Error: Can't resolve 'react' in '/Users/rahulshrivastava/projects/multi-universe/module-federation-examples/nextjs/shared'
[0] Could not find files for / in .next/build-manifest.json
[0] Could not find files for / in .next/build-manifest.json
[0] wait  - compiling...
[0] event - compiled successfully
```

**Comment by rahul3103** [comment]
@dreamerkumar Can you able to help regarding the above

**Comment by victorseara** [comment]
@rahul3103 to run this application in my local environment I needed to make some tweaks. Here it is a workaround for this problem:

``` bash
# installdeps.sh
npm install
cd checkout && npm install && npm link nextjs-shared
cd ..
cd home && npm install && npm link nextjs-shared
cd ..
cd shop && npm install && npm link nextjs-shared
cd .. 
cd shared && npm install react 
```

I think this is happening because the monorepo configs are not working properly after you clone the repo. You can use the script above to have it working for now.

**Comment by ghost** [comment]
For those who are experiencing this issue, I recommend to install the dependencies using yarn from the root directory. This will link the local dependencies automatically for you because of the yarn workspaces config.

**Comment by Saoirse-Derry** [comment]
Is this related to Yarn 2 - I just upgraded, have deleted lock/node_modules etc. but receive the following when running yarn/install from the monorepo root @module-federation/nextjs-mf@npm:^3.4.1: No candidates found

**Comment by ScriptedAlchemy** [comment]
Read the readme. It depends on a paid package. MF for next is expensive to maintain & I don't have enough funding to OSS it :/

**Comment by Bleiwis** [comment]
Hi, today i was trying to install nextjs-react and i got this error trying to install @module-federation/nextjs-mf

Exit code: 1
Command: npm install @module-federation/nextjs-mf --registry https://r.privjs.com
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://r.privjs.com/@module-federation%2fnextjs-mf - You must be logged in to install/publish packages.
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

**Comment by to-long** [comment]
https://app.privjs.com/buy/packageDetail?pkg=@module-federation/nextjs-mf I think this guy want to shell his code

**Comment by ScriptedAlchemy** [comment]
All nextjs related things require commercial plugins from privjs
