### ISSUE TITLE
What does this comment mean?

### ISSUE THREAD

**Issue by Bobert-Brockson** [module-federation/module-federation-examples#1074]
https://github.com/module-federation/module-federation-examples/blob/783a5a56de3b88b4c9655ea8f8c0d2df5ee863ef/advanced-api/dynamic-remotes/app1/webpack.config.js#L38

Maybe I'm just not understanding this comment, but I can't for the life of me figure out what this means. Would it be possible for further clarification to be provided here (and perhaps a comment refactor, I'll gladly spin up the PR after this issue is resolved).

**Comment by JohnDaly** [comment]
This is what the Webpack docs have to say about this configuration hint:

> **import**
`false | string`
The provided module that should be placed in the shared scope. This provided module also acts as fallback module if no shared module is found in the shared scope or version isn't valid. (The value for this hint defaults to the property name.)

From: https://webpack.js.org/plugins/module-federation-plugin/#import

I think you might use it if the property name that you're passing to the `shared` object doesn't match the actual `module` name? It seems like the usage of this override would be rare.

As far as I can tell in this example, it looks like all of the hints here are the defaults (except for `singleton`). I think this example could be re-written as:

```typescript
new ModuleFederationPlugin({
  name: "app1",
  // adds react as shared module
  // version is inferred from package.json
  // there is no version check for the required version
  // so it will always use the higher version found
  shared: {
    react: {
      singleton: true, // only a single version of the shared module is allowed
    },
    "react-dom": {
      singleton: true, // only a single version of the shared module is allowed
    },
  },
}),
```
