### ISSUE TITLE
Remove paid example next-mf

### ISSUE THREAD

**Issue by popuguytheparrot** [module-federation/module-federation-examples#1075]
It is unacceptable to use paid plugins based on free solutions in open source examples.

This should be remove
https://github.com/module-federation/module-federation-examples/tree/master/nextjs

**Comment by micro-chipset** [comment]
No need to delete. Helpful information.

**Comment by ScriptedAlchemy** [comment]
I could make the whole repo closed source if you'd like. 

The example is useful. Next can't work without the plugin so them the rules. 

This repo showcases examples. Free or not
