### ISSUE TITLE
[HMR] Update failed: ChunkLoadError: Loading hot update chunk main failed.

### ISSUE THREAD

**Issue by 94cstyles** [module-federation/module-federation-examples#1124]
node:  14.17.4
rep: [automatic-vendor-sharing](https://github.com/module-federation/module-federation-examples/tree/master/advanced-api/automatic-vendor-sharing)

![image](https://user-images.githubusercontent.com/3605154/131670592-686ed6ad-ce6c-4d15-aa7e-64551997fbc9.png)

**Comment by ScriptedAlchemy** [comment]
Cant use HMR with module federation.

use @module-federation/fmr package

**Comment by ttttttw** [comment]
> Cant use HMR with module federation.
> 
> use @module-federation/fmr package

This package will reload my page. I think this is【Hot Page Reload】, not【Hot Module Replacement】.
Is this caused by the running mechanism of module federation? Is there a better solution?
By the way, I wanted to run the remote for debugging and encountered this issue.
