### ISSUE TITLE
microfrontend localhost development with a deployed remote app shell

### ISSUE THREAD

**Issue by thunderousNinja** [module-federation/module-federation-examples#1130]
Hey,

I wanted to get some guidance around a problem I am facing. Basically I am following the app shell pattern from [here](https://github.com/module-federation/module-federation-examples/tree/master/shared-routing), where I have an app shell that microfrontend applications consume during development.

The example above works great when all the microfrontend apps are running locally via webpack dev server. However, I have a use-case where I want to be able to develop on microfrontend apps without needing to run any of its remotes locally, specifically the Shell, and just point to the remotes that are already in the CDN. The problem I am facing is that the deployed remotes already have their microfrontend apps remote urls set via [external-remotes-plugin](https://www.npmjs.com/package/external-remotes-plugin) so it won't ever know about the localhost microfrontend app that is currently being developed on.

My current solution to this is to leverage `localStorage` and dynamically check if there is an override url (which just points to the localhost + port of the app that is being developed on) before using the remote CDN value. So in my deployed `Shell`'s `index.ts` file I have something like:

```
...
window.app2Url = localStorage.getItem('app2LocalhostOverrideUrl') ||  `${APP_2_CDN_URL}/remoteEntry.js`;

import("./bootstrap");
...
```
I just wanted to know if I am I on the right path or is there another way this can be done that doesn't seem less hacky.

Thanks in advance!

**Comment by ScriptedAlchemy** [comment]
you could use `promise new Promise` and inject + resolve the object yourself as needed
