### ISSUE TITLE
Changing routes in remote module using history.push is throwing an error

### ISSUE THREAD

**Issue by athapliyal** [module-federation/module-federation-examples#1169]
I currently have a Shell that has the following routes set in it

![image](https://user-images.githubusercontent.com/20395556/133011812-3ead92d6-1635-48dc-b7f0-9e57155ff8f7.png)

where remoteRoutes are being exposed from a child module which in return has its own set of routes as per below

![image](https://user-images.githubusercontent.com/20395556/133011871-a12eebe0-fd57-4818-af37-58a7a5268048.png)

The child module simply renders a store list table and on row click routes to details page as per below
![image](https://user-images.githubusercontent.com/20395556/133012262-801aae1d-8754-48bf-aac0-da0fffbf66d8.png)

From the parent when I browse to  `/operations` I am able to see the child module's StoreList table but I am unable to route to a child route within the child module which is at` /operations/:id`

![image](https://user-images.githubusercontent.com/20395556/133012437-8eb3aafb-7e03-4fa6-8014-ecb09fefca73.png)

If I console log the list of routes from parent; I can see the remote routes present however, only /operations seems to be working
![image](https://user-images.githubusercontent.com/20395556/133012171-562f2b18-6d78-426a-81ca-dc544e640cd3.png)

The routing in the child app when running in standalone mode happens without any issues so I am assuming that the react-router's history is throwing an error as its instance is different from the one in the parent?

**Comment by athapliyal** [comment]
history object in the child component is undefined when invoked from parent
![image](https://user-images.githubusercontent.com/20395556/133020975-4a1e524d-b58e-4e2e-adb8-23a3a6ef7df4.png)

Any ideas how we can work around this?

**Comment by athapliyal** [comment]
I guess the problem lies here?

The child app is currently running on port 3001 while the Shell App is on 3000. Now the Shell App controls the routing and so when the child route tries to do a history.push it won't be allowed to do so as the child running on 3001 should not be able to control the history of shell running on 3000

If it is able to do so then this is a major security flaw

![image](https://user-images.githubusercontent.com/20395556/133023597-bfa61995-ed17-4e70-984b-bbf003cdba06.png)

**Comment by ScriptedAlchemy** [comment]
Feels like the history dependency or something isn’t being shared or is not a singleton. So it’s getting recreated lower down in the tree and is empty.

**Comment by athapliyal** [comment]
Thanks for your response mate! I checked the code and in the domain app we were consuming a new instance of `useHistory` which could be the cause for this. Will give this recommendation a shot

https://github.com/module-federation/module-federation-examples/discussions/754#discussioncomment-696211
