### ISSUE TITLE
Host App cannot load Remote page because is not served inside its state provider

### ISSUE THREAD

**Issue by Beslinda** [module-federation/module-federation-examples#1177]
I have a Host App that uses mobx as store provider and Remote App that uses recoil as store provider. 

The remote App exposes the bootstrap file and its routes in the following way.:

```
    new ModuleFederationPlugin({
      name: 'items_list',
      filename: 'items-list-plugin-app-entry.js',
      exposes: {
        './ItemsListApp': './src/bootstrap',
        './routes': './src/routes',
      },
```

The routes page contains the following:

```
import { lazy } from 'react';

const ItemDetails = lazy(() => import('./app/components/ItemDetails'));

const itemsListRoutes = [
  {
    path: '/item-list/:id',
    component: ItemDetails,
    exact: false,
  },
];

export { itemsListRoutes };
```
The host app loads the `ItemsListApp` fine, but when trying to load a component from the routes, in this case ItemDetails, then it throws an error stating: **This component must be used inside a RecoilRoot component.** 

The ItemDetails page is used inside the RecoilRoot in the remote app, but in the host app is not. So what is the best approach to solve this issue ?

**Comment by ScriptedAlchemy** [comment]
Create an app shell. That’s the most reliable pattern. Otherwise you need to have some powerful composition patterns in place to enable decentralized encapsulation

**Comment by guowenjuan341** [comment]
what do you mean to create an app shell?

**Comment by guowenjuan341** [comment]
If I just want to use the single page with all functions in the other app

**Comment by ScriptedAlchemy** [comment]
Book a consult

**Comment by ScriptedAlchemy** [comment]
Or expose a module wrapper around the components and make recoil as shared. That way you can encapsulate the component and ensure it's inside recoil
