### ISSUE TITLE
Matriel-ui 5 with diffrents react versions not working

### ISSUE THREAD

**Issue by OriAmir** [module-federation/module-federation-examples#1233]
I'm not sure if this issue relates to `MUI` or to here so I open the same ticket in 2 places:
https://github.com/mui-org/material-ui/issues/29038

**summary**: I run 2 application with 2 diff react version (17.0.0 and 17.0.2) and I'm getting error when loading MUI elements:
![image](https://user-images.githubusercontent.com/17565646/138726222-1abbf418-4f04-4d4a-b66f-17e2410c2b3e.png)

**sandbox:**
https://codesandbox.io/s/webpack-module-f-forked-8vto1?
it's the very basic and regular implementation of the module federation that includes 2 apps.
one app is with react&react dom in 17.0.0 and the second with 17.0.2 and it didn't work.

**Comment by ScriptedAlchemy** [comment]
If Package json uses strict versions the webpack will do the same. Needs to be singleton or required version set to false

**Comment by BenByrdInMarket** [comment]
Hey @OriAmir did you ever get this working? I have the exact same issue. The minimal example using React 17 in the container and React 18 in the remote works, and I can use MUI if the applications are on the same version of React, but 17/18 + MUI fails with the hooks error. 

I can see how this is outside the scope of Module Federation and MUI, but figured I'd check just in case!

**Comment by natirada** [comment]
@OriAmir Hi, I have the same issue how did you solve it?

**Comment by ScriptedAlchemy** [comment]
Mount two different react apps. Cant share context across two different reacts so you need to pass props down to another app that mounts onto a ref etc. If it uses react context, you cannot share them across different react versions or use the JSX style of federation like normal
