### ISSUE TITLE
Using Module Federation with global exposed packages gets undefined

### ISSUE THREAD

**Issue by J4v4Scr1pt** [module-federation/module-federation-examples#1243]
Hi!
First off, MF is awesome! 🤩

Have tried different approches to solve my issue but cant find a good solution anywhere. 
We have a complex project with razorViews, reactViews and react components all mixed thogether. One step to strip this monolith down is to start doing mfe's.

We need to expose different packages like moment, react, react-dom, jQuery, etc. globaly for the razorviews and thirdparty librarys to work. We have several of these entryfiles in the webpack config. All of them look something like this:

```
import "core-js/stable";
import "regenerator-runtime/runtime";
import "expose-loader?exposes=React!react";
import "expose-loader?exposes=ReactDOM!react-dom";
import "expose-loader?exposes=moment!moment"; 
import "expose-loader?exposes=Tours!./tours.js";

window.onpopstate = function (event) {
    window.location.reload();
};
```

Because of `Shared module is not available for eager consumption` error I moved all of these entry files to a bootstrap file according to the documentation.

Then my mfe started to work and everything was fine. Until I navigated to one of our razorViews. With the boostrap approach all exposed packages are not defined anymore. For example `Uncaught ReferenceError: jQuery is not defined` or `Uncaught ReferenceError: ReactDOM is not defined`.

I reverted the bootstrap solution and also needed to remove config for ModuleFederationPlugin and it worked again. As soon as I add the ModuleFederationPluginConfig again even without the bootsrap files my exposed packages get undefined.
I guess how the Federation works with serving packages in a more dynamic way is the reason it dont work, but I could be wrong.

```
new ModuleFederationPlugin({
            name: "app1",
            remotes: {
                buttonTest: "buttonTest@http://localhost:5001/remoteEntry.js",
            },
            shared: {
                ...deps,
                react: {
                    eager: false,
                    singleton: false,
                    requiredVersion: ">=16.14.0 <=17.0.2"
                },
                "react-dom": {
                    eager: false,
                    singleton: false,
                    requiredVersion: ">=16.14.0 <=17.0.2"
                },
            }
        }),
```

Hope im clear about my problem 😊, otherwise let me know if more information is needed.

Regards

**Comment by alex-vukov** [comment]
react and react-dom can only have one instance loaded in memory unless you have a ReactDOM wrapped around each of your applications. That's why you should most likely set singleton to "true" for them. Also for jQuery.

**Comment by J4v4Scr1pt** [comment]
If anyone reading this, I figure out that it depends on when we render the bundle in the razor view.
I trided to move it as early as possible and then ReactDOM exists.
So no MF issue at all, sorry for the confusion :) 

Have a great day

**Comment by ScriptedAlchemy** [comment]
Eager true or you need a async bootstrap wrappers
