### ISSUE TITLE
can't import circular dependency in dynamic-remotes-synchronous-imports demo?

### ISSUE THREAD

**Issue by elevensky** [module-federation/module-federation-examples#1246]
first, i create a Test Compnent in app1 and exposed it
![image](https://user-images.githubusercontent.com/6904834/142394290-c62eb74f-fdb0-468d-80bb-d631447f62dc.png)
and then synch imports it in app2
![image](https://user-images.githubusercontent.com/6904834/142430899-00e6d6b3-5f7f-4606-b8a7-586d688e3c18.png)
but get error,like this
![image](https://user-images.githubusercontent.com/6904834/142430997-6b02c899-b45a-4c5d-933e-78b9802a8580.png)

i don't know what wrong with that?

**Comment by asnow73** [comment]
I had something similar. Which is the value in **publicPath** in your webpack config?
Try 
```
module.exports = {
  output: {
    publicPath: 'auto',
  },
};
```

**Comment by elevensky** [comment]
@asnow73 yes, both。 your ok?

**Comment by asnow73** [comment]
OK. Also try to comment **optimization** section in your webpack config (if you have such) for project which exposes component.

**Comment by elevensky** [comment]
@asnow73 thks, i upgraded webpack to latest version then resolved it,  and i use the external-remotes-plugin not the file in project.

**Comment by nidhin038** [comment]
> @asnow73 thks, i upgraded webpack to latest version then resolved it, and i use the external-remotes-plugin not the file in project.

To which Version ?
