### ISSUE TITLE
Dependency versions mismatch

### ISSUE THREAD

**Issue by Amirko28** [module-federation/module-federation-examples#1250]
I've built a host app that loads dynamically multiple remote apps. In each app I've put react as a shared dependency. Because of the fact that you can't load multiple versions of react, I've put the 'singelton: true' attribute in the ModuleFederationPlugin section, and it is written in each app (the host app and the remote apps).

In the host app I use react version ^16.8.0, and in the remote apps I also use react version ^16.8.0.

However, in a new remote app I wrote, I use a package that has a peer dependency of react version ^17.0.0.
That means that this specific remote app uses react version ^17.0.0, while all the others use ^16.8.0.

When I try to load this remote app in the host app, it loads the remote app with the newer react version, but the other remote apps crash because of the multiple react versions.

Is there a way to enforce the version of specific dependencies in ModuleFederationPlugin?
Preferably, I'd like to get an error when I try to load the remote app with the react ^17.0.0 version, while the other remote apps will load successfully. Basically, the host app will block remote apps that use newer versions of react (or any other dependency I'd like).

Any advice/ways to enforce it will be appreciated 🙌🏻

**Comment by ScriptedAlchemy** [comment]
It respects semver those are different major versions. Mark it as a singleton or use the adapter pattern to mount a new version of react inside am an old one. I have an example in this repo called different react versions

**Comment by ScriptedAlchemy** [comment]
You can also set singleton:true eager true in one of the apps to force webpack to use the one thats already loaded. Enforcement is tricky, but a workaround i have used is to side load or eager share it and mark it as singleton.
