### ISSUE TITLE
Shared modules loaded via remote url (not NPM)

### ISSUE THREAD

**Issue by AlissonRS** [module-federation/module-federation-examples#1252]
Hello!

I have a use case where my remote module has a dependency to a script loaded via <script> tag in the index.html (so it's not installed as a npm package). Is there a way I can add this as "shared" module?

Normally you'd declare a remote module with shared modules like below:

    new ModuleFederationPlugin({
      name: 'app2',
      filename: 'remoteEntry.js',
      exposes: {
        './MyComponent': './src/MyComponent',
      },
      shared: {
        'react': { singleton: true },
        'react-dom': { singleton: true }
      },
    }),

So I was looking for something like this:

    new ModuleFederationPlugin({
      name: 'app2',
      filename: 'remoteEntry.js',
      exposes: {
        './MyComponent': './src/MyComponent',
      },
      shared: {
        'react': { singleton: true },
        'react-dom': { singleton: true },
        'third-party-lib': { singleton: true, url: 'https://somecdn.com/the-libs-code.js' }
      },
    })

I understand one solution would be to create an npm package myself with this third-party-lib code, install in the microfrontend app and add into shared just as we do with react and react-dom, however this code may be changed on the fly, so it'd be cool if the host (shell) app could automatically fetch this third-party-lib module from CDN on the fly when loading the microfrontend.

Thanks!

**Comment by ScriptedAlchemy** [comment]
It's possible to do so. Book a consult if you need further information. Some of this depends on order of initialization but it's possible to achieve these kinds of things. 

You can also use the build http target or share a module that looks for it on the window or some third party before choosing to lazy load the npm dependency and so on. We Also support url imports with buildHTTP targets
