### ISSUE TITLE
Multiple entry points that leverage the same remote

### ISSUE THREAD

**Issue by eslawski** [module-federation/module-federation-examples#1253]
Consider the situation where there isn't necessarily one single "entry point" for a webpage, but many. Then perhaps each of those entry points leverage ModuleFederation to import some `remotes`. Now assume that each entry point attempts to load the same remote independently. Finally, assume that the remote in question is configured to "share" some modules.

I've created a repo [here](https://github.com/eslawski/duplicate-mfe-issue) that reproduces and helps visualize this scenario.

When all of these conditions are met, a console error like the following is thrown:

```
Container initialization failed as it has already been initialized with a different share scope
while loading "./MfeButton" from webpack/container/reference/mfeButton
```

This error goes away if you elect to not use the `shared` functionality, or you refactor the application such that there is only one entry point that leverage ModuleFederation.

### Question:
Is there anything preventing ModuleFederation from being able to detect this situation and "ignore" duplicate initializations of same remote? Or are there other recommendations for supporting this use case?

Thanks!

**Comment by ScriptedAlchemy** [comment]
Use the hosts own remote and make entry points just call the exposed module. Main entry serves as a orchestrate or scout file. No need for more than 1 entry point

**Comment by daneah** [comment]
@ScriptedAlchemy Thank you for your reply! I'm trying to understand it a little bit better. Our pages are currently not all using module federation for everything, but are still composed of independent work by multiple teams. This means they each have a couple of independent bundles on them, each built in a different Webpack runtime and therefore with their own entry points. This differs from the linked example repo, where there is a single runtime that could ensure a single entry point.

Does what you're suggesting work in this multiple bundle land, or is getting down to a single "final" entry point the only way to mitigate this? We're trying to move that way anyway, but incrementally if possible 😄

**Comment by joris77** [comment]
@ScriptedAlchemy Would this also mean that module federation is incompatible with "server side composition" solutions like zalando's tailorjs, which composes templates/pages out of multiple fragments that each have their own entry point.

If yes would you then advice to move away from such a "server side composition" solution, because module federation will make it obsolete?

**Comment by ScriptedAlchemy** [comment]
In my opinion yes. Composition and stitching systems are effectively obsolete. 

For multiple entry points you can try setting runtime:false but in general multiple entry points cause async issues. It can be solved but it requires the right patterns. 

Entry points is how nextjs works. Similar problems as well. It can be worked around but runtime might need something like dependOn flags, sharing shims or something else to workaround the single runtime chunk or eager sharing issues that arise from these frameworks
