### ISSUE TITLE
ScriptExternalLoadError: Loading script failed

### ISSUE THREAD

**Issue by viviScript** [module-federation/module-federation-examples#1273]
project vue_components
module.exports = {
  name: "vue_components",
  filename: 'remoteEntry.js',
  library: { type: 'var', name: 'vue_components' },
  exposes: {
   './Demo': './src/components/demo.vue'
 },
 remotes: {
 },
 shared: ['vue/dist/vue.esm.js'],
}

project jcj_front
module.exports = {
  name: "jcj_front",
 filename: 'jcj_front.js',
  exposes: {
 },
 remotes: {
   'vue_components': 'vue_components@http://localhost:8080/remoteEntry.js',
 },
 shared: ['vue/dist/vue.esm.js'],
}

App.vue
<template>
     <Demo />
</template>
export default {
  name: 'App',
  components: {
    Demo: () => import('vue_components/Demo')
  }
}

![image](https://user-images.githubusercontent.com/20518195/145365727-df9d91a5-597c-4543-b6e2-d4653bb8d328.png)

**Comment by viviScript** [comment]
module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'static/js/[name].[contenthash:8].js',
    path: path.resolve(__dirname, 'dist'),
    publicPath: 'auto',
    environment: {
      arrowFunction: false,
      bigIntLiteral: false,
      const: false,
      destructuring: false,
      forOf: false,
      dynamicImport: false,
      module: false,
    },
  },
  }

**Comment by viviScript** [comment]
``
module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'static/js/[name].[contenthash:8].js',
    path: path.resolve(__dirname, 'dist'),
    publicPath: 'auto',
    // 支持 es5 输出
      // ecmaVersion: 5,
      // output.ecmaVersion is replaced with output.environment which lists features used by webpack
    environment: {
      arrowFunction: false,
      bigIntLiteral: false,
      const: false,
      destructuring: false,
      forOf: false,
      dynamicImport: false,
      module: false,
    },
  },
  }

**Comment by viviScript** [comment]
`module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'static/js/[name].[contenthash:8].js',
    path: path.resolve(__dirname, 'dist'),
    publicPath: 'auto',
    // 支持 es5 输出
      // ecmaVersion: 5,
      // output.ecmaVersion is replaced with output.environment which lists features used by webpack
    environment: {
      arrowFunction: false,
      bigIntLiteral: false,
      const: false,
      destructuring: false,
      forOf: false,
      dynamicImport: false,
      module: false,
    },
  },
}
  `

**Comment by viviScript** [comment]
In the project made according to the examples on the official website, this kind of problem appears now. How can I solve it

**Comment by ScriptedAlchemy** [comment]
Be sure the remote actually exists
