### ISSUE TITLE
Angular13 Microfrontends Lazy Components demo infinite loop

### ISSUE THREAD

**Issue by omgitsnes** [module-federation/module-federation-examples#1277]
node version: v14.17.3
npm version: 6.14.13
yarn version: 1.22.17

Followed steps in readme:

- Install packages: `yarn install`
- Build the shared library `yarn build:shared`
- Start the mdmf-shell: `yarn start:shell`
- Start the Microfrontend: `yarn start:profile`

There are no errors when building or starting, but when I open the shell in the browser, the page keeps refreshing:

![image](https://user-images.githubusercontent.com/12531526/145849989-6387e3f2-1c1c-4716-ac4f-1d55aff27cb0.png)

https://user-images.githubusercontent.com/12531526/145851019-0d39d90a-b54f-4794-b42c-6c41d0d88e52.mp4

Thanks for any reply

**Comment by timonkrebs** [comment]
Should be fixed with pr #1555

**Comment by ScriptedAlchemy** [comment]
Lifesaver

**Comment by maitrungduc1410** [comment]
Hi @timonkrebs  @ScriptedAlchemy do you have any idea how to make live-reload works for the angular example?

**Comment by maitrungduc1410** [comment]
solved the issue using `webpack-livereload-plugin`:
- place `webpack-livereload-plugin` inside profile project
- in shell project we import `<script src="http://localhost:35729/livereload.js"></script>`
