### ISSUE TITLE
Using NextJS and Federated Web Components

### ISSUE THREAD

**Issue by chadwtkns** [module-federation/module-federation-examples#1288]
So Im trying to use Federated Modules to bring in a Vanilla Web Component (Im using lit-html for the rendering piece otherwise nothing else) into a NextJS application. Im attempting to follow the example here https://github.com/module-federation/module-federation-examples/tree/master/nextjs-ssr using the @telenko/node-mf plugin but so far I have not gotten this to work. Here is the next.config.js:

```javascript

const packageJsonDeps = require("./package.json").dependencies;
const { NodeModuleFederation } = require("@telenko/node-mf");
const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");

module.exports = {
  future: { webpack5: true },
  webpack: (config, { isServer }) => {
    const mfConf = {
      remotes: {
        create_cc: "snap_payment_create_cc_v1@http://localhost:5009/payment/create_cc/v1/remoteEntry.js"
      },
      shared: {
        react: {
          eager: true,
          requiredVersion: packageJsonDeps["react"],
          singleton: true,
        },
        "react-dom": {
          eager: true,
          requiredVersion: packageJsonDeps["react-dom"],
          singleton: true,
        },
      },
    };
    return {
      ...config,
      plugins: [
        ...config.plugins,
        new (isServer ? NodeModuleFederation : ModuleFederationPlugin)(mfConf),
      ],
      experiments: { topLevelAwait: true },
    };
  },

  webpackDevMiddleware: (config) => {
    // Perform customizations to webpack dev middleware config
    // Important: return the modified config
    return config;
  },
};

```

The web component is self defining so I would expect that I could bring it in just for the side effects like so:
```javascript

await import("snap_payment_create_cc_v1/payment-create_cc")


const PaymentPaymentWrapper = async ({content}) => {
    console.log("TESTTSLKDJSLFKSJD", Test)

    return (
        <>
            <h3>{content.title}</h3>
            <div id="paymentCreation">
                <h3>{content.createMethodTitle}</h3>
                <payment-create_cc></payment-create_cc>
            </div>
        </>
    )
}

export default PaymentPaymentWrapper

```
but I get errors around using top-level-await (Error: error: top level await requires target to es2017 or higher and topLevelAwait:true for ecmascript) that I'm really struggling to solve and if I don't use await on it then I get errors around resolving the module (Can't resolve 'snap_payment_create_cc_v1/payment-create_cc'). Any thoughts on what I could be doing wrong

**Comment by chadwtkns** [comment]
Sorry I think I got the 2nd error resolved I realized my remote was wrong. It should have been as so:
```
        snap_payment_create_cc_v1: "snap_payment_create_cc_v1@http://localhost:5009/payment/create_cc/v1/remoteEntry.js"

```
But still getting the top-level-await issue. Which without the await keyword then I do get React complaining that one of the children is a promise (which makes sense since it hasn't resolved the module yet)

**Comment by chadwtkns** [comment]
Update: I was able to get past the await issue. Turns out I was on NextJS 12 which due to the Rust compiler switch it doesn't support top level await so I switched back to v10 of NextJS. Await now appears to be working but Im getting 

```
Module not found: Can't resolve 'snap_payment_create_cc_v1/payment-create_cc'
> 1 | await import('snap_payment_create_cc_v1/payment-create_cc')
```

Would the paid plugin solve this?

**Comment by ScriptedAlchemy** [comment]
Next doesn't play nice with the import syntax. Use low level api and probably need the paid plugin for it to have a chance of working 

Rust compiler requires layers experiment as well to get top-level await 

U can switch back to babel tho if needed

**Comment by chadwtkns** [comment]
Do you have a source where you could point me to on how to set up the Rust compiler to have top-level await?

**Comment by ScriptedAlchemy** [comment]
There's a stack of issues with the node MF plugin and nextjs. 


I'm about to release a open beta to bring SSR federation support to nextjs. 

Watch my twitter

**Comment by ScriptedAlchemy** [comment]
Also you can use next 12 and just keep a babelrc file. If Babel config is found SWC isn't used
