### ISSUE TITLE
Repeated loading shared lib Ant Design of Vue

### ISSUE THREAD

**Issue by WormGirl** [module-federation/module-federation-examples#1289]
one is partly loaded on demand,  another is whole load ,  shared seem not work.
![image](https://user-images.githubusercontent.com/16078260/147076541-101ea997-090d-46d4-b140-645e6cfd7ace.png)
![image](https://user-images.githubusercontent.com/16078260/147076593-9115546c-dbb2-49e8-9811-26ef1855755b.png)
![image](https://user-images.githubusercontent.com/16078260/147077125-04f2e555-27ca-4f8f-ba60-b91d60327eab.png)
![image](https://user-images.githubusercontent.com/16078260/147077172-b677b8ee-3a42-43ac-9afa-7de6f6a7f871.png)

How to resolve this problem?

**Comment by ScriptedAlchemy** [comment]
Put a trailing slash on the end of the key or mark it as a singleton

**Comment by schirrel** [comment]
Aren't you missing `singleton` or the defined version to it shared? SO the webpack knows they arent suposed to load multiple times?

**Comment by WormGirl** [comment]
> Aren't you missing `singleton` or the defined version to it shared? SO the webpack knows they arent suposed to load multiple times?

yes , if i add singleton, `Ant Design` will not load twice, but if two module-federationis both  used loaded on demand,  this will has problem,  for example, there has two module named A and B, if A loaded `button` and ` input` from Ant Design on demand, B just loaded `input` from Ant Design on demand,  when B use A module , the `button` of A never loaded. this mean B should contained A if want this work.

**Comment by ScriptedAlchemy** [comment]
Put a trailing slash on it. It's prob a lot free shaking only the used modules or you might be accessing a deeper path like lib/component and not pulling from the index.js file which is what federation is resolving to. 

Mylib/ as the share key should fix it

**Comment by ScriptedAlchemy** [comment]
Check out the bottom of this article, I speak about sharing. And use of a trailing slash 

https://scriptedalchemy.medium.com/when-should-you-leverage-module-federation-and-how-2998b132c840
