### ISSUE TITLE
linters complains

### ISSUE THREAD

**Issue by crodriguez-plitzi** [module-federation/module-federation-examples#1322]
Hi @ScriptedAlchemy 

im opening this ticket to see if is possible to update linters to support these 2 variables

```
 await __webpack_init_sharing__('default'); // eslint-disable-line
 await container.init(__webpack_share_scopes__.default); // eslint-disable-line
```

Identifier '__webpack_share_scopes__' is not in camel case.eslint camelcase
'__webpack_share_scopes__' is not defined.eslint no-undef
'__webpack_init_sharing__' is not defined.eslint no-undef

at least for future versions of eslint they will allow it without custom changes or `// eslint-disable-line`

also when we add remotes to be able to import them, same problem with eslint

example 
`
import ComponentContext from 'plitziSdkFederation/ComponentContext';
`
Unable to resolve path to module 'plitziSdkFederation/ComponentContext'. eslint import/no-unresolved

**Comment by ScriptedAlchemy** [comment]
Should be filed with eslint or something. I suppose a extended config could be created for module federation to add them as globals
