### ISSUE TITLE
how to use vue in react?

### ISSUE THREAD

**Issue by lanxisama** [module-federation/module-federation-examples#1325]
so I just find the exp of **react in vue** [https://github.com/module-federation/module-federation-examples/tree/master/react-in-vue](url),if I want use vue componet in react application  how i can do?

**Comment by ScriptedAlchemy** [comment]
https://github.com/akxcv/vuera

**Comment by jees47** [comment]
> https://github.com/akxcv/vuera

is there any simpler way?
