### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'init')

### ISSUE THREAD

**Issue by zhang-xiaoyan** [module-federation/module-federation-examples#1343]
function loadComponent(scope, module) {
  return async () => {
    // Initializes the share scope. This fills it with known provided modules from this build and all remotes
    await __webpack_init_sharing__('default');
    const container = window[scope]; // or get the container somewhere else
    // Initialize the container, it may provide shared modules
    await container.init(__webpack_share_scopes__.default);
    const factory = await window[scope].get(module);
    const Module = factory();
    return Module;
  };
}

**Comment by enurv** [comment]
How did you fix the error?

**Comment by lchung0** [comment]
same issue..

**Comment by wafflepie** [comment]
In my case, the solution was to use `runtimeChunk: false` in `webpackConfig.optimization`.

Related: https://github.com/module-federation/concat-runtime
