### ISSUE TITLE
Proposal Feature: HostExposes

### ISSUE THREAD

**Issue by crodriguez-plitzi** [module-federation/module-federation-examples#1378]
Hi @ScriptedAlchemy , the reason of this post its about a proposal feature to be able to improve the comunication between HOST and child MF 

due that the only way to access host `exposes` is using `remotes` this is introducing a limitation where basically you can have only 1 host rendered in the website because we are accesing it via url (`remotes`) instead to do this internally at webpack level for instances 

User case:

lets say we have 2 times the same host but in each one the context exposed contain different data, if the child MF try to be embed in the host, if try to get access to the context only can be via `remotes` but this is an url instead the real object reference so this can introduce problems

the suggestion of this request is to be able to share in webpack level these `exposes` from the host directely in the child MF plugin

and another thing is, why a child MF have to include the host as `remotes` if this one is getting EMBED inside the host, should not require to import it as remote, so this is one additional reason about i want to suggest `hostExposes` a way to have direct access to host `exposes` information

Example

```
new ModuleFederationPlugin({
        name: 'plitziSdkFederation',
        filename: 'plitzi-sdk-federation.js',
        exposes: {
          './usePlitziServiceContext': './src/services/hooks/usePlitziServiceContext',
          './Sdk': './src/bootstrap',
          './ComponentContext': './src/modules/Component/ComponentContext',
          './ComponentProvider': './src/modules/Component/ComponentProvider'
        },
        shared: [
          {
            react: { singleton: true, requiredVersion: false },
            'react-dom': { singleton: true, requiredVersion: false },
            'react-redux': { singleton: true, requiredVersion: false }
          },
          './src/services/hooks/usePlitziServiceContext'
          // './src/services/contexts/PlitziContext',
          // './src/modules/Component/ComponentProvider'
        ]
      })
```
      
      and the child MF something like this can be interesting
  

```
 new ModuleFederationPlugin({
        name: `PlitziPlugin${PluginName.charAt(0).toUpperCase() + PluginName.slice(1)}Federation`,
        filename: `plitzi-plugin-${PluginName}-federation.js`,
        remotes: { // THIS SHOULD NOT BE REQUIRED ANYMORE
          plitziSdkFederation: [
            'plitziSdkFederation@http://localhost:3001/plitzi-sdk-federation.js'
          ]
        },
        hostExposes: { // FEATURE REQUEST
          plitziSdkFederation: {...PROPS} // hostNamespace
          plitziSdkFederation: true // another way to skip props, and in the child MF (plugin) can be used like imports (import SOMETHING from "plitziSdkFederation/..." pretty similar like exposes works
        },
        exposes: {
          Plugin: './src/component/index.js'
        },
        shared: {
          react: { singleton: true, requiredVersion: PACKAGE.dependencies.react },
          'react-dom': { singleton: true, requiredVersion: PACKAGE.dependencies['react-dom'] },
          'react-redux': { singleton: true, requiredVersion: PACKAGE.dependencies['react-redux'] }
        }
      })
```
with this way we will be able to have Several hosts in the same rendered page, we dont will need to care where is located the js file because assets could be located in nested locations, and should works better in terms of performance

**Comment by crodriguez-plitzi** [comment]
@ScriptedAlchemy this can be related to these situations https://github.com/module-federation/module-federation-examples/issues/1291

**Comment by ScriptedAlchemy** [comment]
Federation was not designed to house multi-host containers at once, but i think there is a way to solve this. Still investigating though

**Comment by crodriguez-plitzi** [comment]
@ScriptedAlchemy not just to have multi-host, this also add limitations in the locations of the remote entry points, or if for any reason the file is in a different folder or domain, or location this crash

thats another reason of the suggestion

**Comment by ScriptedAlchemy** [comment]
If this can start off as a webpack plugin. This would be doable, avoid changing the webpack core?

**Comment by crodriguez-plitzi** [comment]
there are some parts that needs to be updated in the core because internally the core is considering that every remote is external and is being loaded as promise making crash webpack due `eager` settings, but we need to consider the scenario where the remote is the host and the information is already loaded, also i added a fix for nested bundles where now we can use references from main bundle

**Comment by crodriguez-plitzi** [comment]
closed in favor of this https://github.com/webpack/webpack/pull/15271
