### ISSUE TITLE
Consuming same remote in host and embedded MF

### ISSUE THREAD

**Issue by ivsantos** [module-federation/module-federation-examples#1381]
Hello!

I have an scenario where there is a library that exposes all its components:
```
new ModuleFederationPlugin({
    name: 'componentLibrary',
    filename: 'remoteEntry.js',
    remotes: {},
    exposes: {
      './Button': `./src/Button`,
      './Checkbox': `./src/Checkbox`,
      './Input': `./src/Input`,
      ...
    },
    shared: {
      react: {
        singleton: true,
        requiredVersion: peerDependencies.react,
      },
      'react-dom': {
        singleton: true,
        requiredVersion: peerDependencies['react-dom'],
      },
    },
 })
```

Then, I have a host app that consumes this library but **also** is the parent that **embeds** a micro-frontend using web-components approach that also needs to consume this library.

So, for the host app I have:
```
new ModuleFederationPlugin({
    name: <respective name>,
    filename: 'remoteEntry.js',
    remotes: {
      componentLibrary: componentLibrary@componentLibrary/remoteEntry.js,
    },
    exposes: {},
    shared: {
      react: {
        singleton: true,
        requiredVersion: dependencies.react,
      },
      'react-dom': {
        singleton: true,
        requiredVersion: dependencies['react-dom'],
      },
    },
 })
```

And the embedded micro-frontend contains **exactly the same** configuration as the host.

When the host is normally rendered everything works fine, but when the embedded micro-frontend in the host enters into play the following error appears in the console and the components are not rendered:
```
Error: Container initialization failed as it has already been initialized with a different share scope
while loading "./Button" from webpack/container/reference/componentLibrary
    at Object.init (container-entry:85:1)
    at initFn (sharing:29:1)
    at async Promise.all (index 0)
```

To clarify if it helps, all needed components are being lazily imported like so:
`const Button = lazy(() => import('componentLibrary/Button');`

How can I correctly consume components in the embedded micro-frontend?

Thanks in advance!!

**Comment by ScriptedAlchemy** [comment]
This is a tricky one. Like localRemotes essentially. 

The easiest answer is to just require the remoteEntry directly. 

The problem hooking it up to remotes via federation is that the remote interface doesn't support using require in its string. Also if this is on the frontend you'd want to always load the remote over the network since it could change. Remotes are treated as externals so having the remote won't bundle it's chunks along with it. 

Generally it was built to go over the network to retrieve the module. 

You may be able to make the remote a directory like ../../other/dist/remoteEntry.js with a require resolve. But I've only tested this on the server

**Comment by ScriptedAlchemy** [comment]
It looks like you're calling the init function twice. Once per each runtime.

**Comment by UNDERCOVERj** [comment]
> 

I met the same question，how do you solve the problem

`Container initialization failed as it has already been initialized with a different share scope`

![image](https://user-images.githubusercontent.com/23290513/201582065-7139313a-0596-443d-b589-1211f9d7bc8d.png)

**Comment by xuebigshuai** [comment]
why closed this issue?  it has the same question  when use qiankun micro-frontend.

**Comment by xuebigshuai** [comment]
> 
use  qiankun micro-frontend. it must call the init function twice.  remoteEntry.js and app.js(index.js)  call
