### ISSUE TITLE
Remix with Module Federation

### ISSUE THREAD

**Issue by helderberto** [module-federation/module-federation-examples#1478]
## Description

It would be amazing to see an example of Remix using Module Federation. It is possible considering Remix uses esbuild instead of Webpack?

**Comment by ScriptedAlchemy** [comment]
Vite did it. But I'm not sure if that can be applied to esbuild directly. @jacob-ebey has already implemented a sidecar solution for remix. 

Basically use webpack for exposing remotes and use esbuild for sharing modules and running everything else.

**Comment by helderberto** [comment]
Thanks for the reply @ScriptedAlchemy!

What do you think about keep this issue opened? Maybe it has any update or implementation in the future.
