### ISSUE TITLE
Next-SSR (0.0.1-beta.12) - Consuming Chakra-UI in a Remote that shares same dependencies as the UI Host

### ISSUE THREAD

**Issue by Marcelx8** [module-federation/module-federation-examples#1530]
Chakra-UI Component issues (could relate to other shared dependencies also, mentioned at the bottom):

**Setup:**
- TypeScript
- Module Federation: Next-SSR beta plugin
- Shell app (container) with required Chakra-UI imports, also wrap `<Component ... />` with `<ChakraProvider >`
- UI app - housing the components which get exposed for usage like `import('ui/SomeComponent')`. This app has all the dependencies shared in its `next.config.js`
- HomePage app - populated with UI components and whatever else

**Issue:**
If the HomePage app has Chakra-UI dependencies shared in `next.config.js`, and you wish to consume a Chakra-UI embedded component from the UI app, it seems to ignore the styling. The component renders, but without any styles applied.

The shared dependencies in the HomePage app IS unnecessary but just adding it as a note to someone who crosses the same bridge.

Maybe I'm doing something wrong?

Also, Components (React.FunctionalComponents) seem to work perfectly with normal `import Component from "remote/Component"`, as well as `const Component = dynamic(() => import("remote/Component"))` , BUT with a non-React.FunctionComponent, or rather, just some JS function, then only the `import doSomething from "remote/something"` seems to work. I believe that is possibly a typing issue on my side and to understand the dynamic module import types a bit better. Still working on it.

**Comment by ScriptedAlchemy** [comment]
Sounds like a context issue. Try putting a trailing slash on the end of the shared module key like "somePackage/"

**Comment by Marcelx8** [comment]
Unfortunately, I can't figure out why a non-component gives this specific issue, except that `dynamic` expects a component, which is understandable, but then again, I'm exposing a JS module. One thing that I did pick up though, could be related, when I build an app that consumes the non-component module, I run into an error:
```
> Build error occurred
TypeError: Cannot read property 'call' of undefined
at __webpack_require__ (C:\some-route\next-mf-ssr\pdp\.next\server\webpack-runtime.js:25:43)
at Module.100 (C:\some-route\next-mf-ssr\pdp\.next\server\pages\products.js:25:13)
...
...
...
at Module._compile (internal/modules/cjs/loader.js:1072:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10) {
  type: 'TypeError'
}
```

Tracing the issue, it seems that the chunk was not built, therefore it can't be loaded. hmmmm

Any suggestions on what to look into?


Sorry for the "close issue" - I think I hit a github shortcut

**Comment by ScriptedAlchemy** [comment]
Might be resolved with the new async import boundary i added to pages (sent you a twitter DM about)

**Comment by ScriptedAlchemy** [comment]
Fixed
