### ISSUE TITLE
I am using react-router-dom on both main and remote modules - will that work in Module Federation

### ISSUE THREAD

**Issue by AjayKumarJ** [module-federation/module-federation-examples#1539]
Hi,
I have scenario that I wanted to use react-router-dom on both main and remote modules. I don't want inject one small component in my main module instead I would like to inject a whole remote application (which has it's own react-router-dom). When I try to inject the remove module I am getting Invalid hook call error. Is this possible in module federation that my rootapp/modulex will inject a remote module called moduleX and moduleX will have it's own routing like rootapp/modulex/page1 will go inside remote module page1.

**Comment by ScriptedAlchemy** [comment]
Youd need to setup nested routing correctly for it to work but you'll still likely need router-dom as a singleton instance

**Comment by AjayKumarJ** [comment]
@ScriptedAlchemy Thanks a lot for your reply. I have added react-router-dom as a singleton instance but still it is not working. It would be great if you could share some resource if you have. Thanks once again.

**Comment by ScriptedAlchemy** [comment]
Search the GitHub issues for router, there's a few conversations about nested routing and that's probably what you're looking for
