### ISSUE TITLE
withFederatedSidecar uses shell url instead of the remote

### ISSUE THREAD

**Issue by yuriburk** [module-federation/module-federation-examples#1561]
I don't know what I'm doing wrong, tried some different settings but none of them worked for me. It throws me those errors:

remoteEntry.js:230 GET http://localhost:3000/_next/static/chunks/vendors-node_modules_react_jsx-dev-runtime_js-node_modules_styled-components_dist_styled-comp-e55394.js net::ERR_ABORTED 404 (Not Found)
remoteEntry.js:230 GET http://localhost:3000/_next/static/chunks/src_components_Main_index_tsx-webpack_sharing_consume_default_react_react.js net::ERR_ABORTED 404 (Not Found)

Can someone help me out?

My repo is https://github.com/yuriburk/micro-frontends-nextjs-module-federation just need to checkout to next-11 branch and go into each folder and run yarn dev

Its a issue only with withFederatedSidecar that it can load the remoteEntry but when it tries to get the components it tries to get in the shell app instead of the microfrontend URL (for example port 3001), how can I fix?

**Comment by ScriptedAlchemy** [comment]
Looks like publicPath needs to be set to auto. The remote is attempting to load chunks from the host domain. I'll double check the plugin to confirm we set public path to auto. 

You can hardcode public path in main builds if you're having problems
