### ISSUE TITLE
Production build of remote seems to stop host from hot reloading

### ISSUE THREAD

**Issue by AlexThurston** [module-federation/module-federation-examples#1569]
I was able to reproduce this using the example found [here](https://github.com/module-federation/module-federation-examples/tree/master/cra)

If I use `yarn start` in both the **host** and **remote** projects things work as expected.  I can make changes to the **host** source JSX and the browser reloads as it normally does.

However, if I `yarn build` the **remote** and then `serve -s build` the production version of the code the **host** app no longer hot reloads on changes to the source.  The *host* app is still being run with `yarn start`.  It is able to load the remote code, but changes to the **host** app source code do not cause a refresh in the browser.  I can see the process recompile, but am forced to refresh the browser manually.  If I simply remove the import from the **host** app of the `RemoteButton` , this **host** app begins to hot reload again.

**Comment by ScriptedAlchemy** [comment]
Not sure on this one. Most likely a problem with react refresh plugin and not webpack itself
