### ISSUE TITLE
SVG files not display from assets folder 

### ISSUE THREAD

**Issue by ofirrifo** [module-federation/module-federation-examples#1595]
SVG files not display from assets folder.

I clone the examples repo and used the angular13-microfrontends-lazy-components

I added SVG file under `projects/mdmf-profile/src/assets/notification-active-gray.svg`
and added to this file below img with the svg src

**projects/mdmf-profile/src/app/profile/components/profile/profile.component.html**
```html
<img width="100px" src="../../../../assets/notification-active-gray.svg" alt="">
```

I executed both shell and profile projects but the svg in the shell not display.
in the remote as stand alone it do display.

I didn't change anything in file `webpack.config.js`

I expected it to work since I saw there is this config

```
  output: {
    publicPath: 'http://localhost:4201/',
    uniqueName: 'mdmfprofile',
    scriptType: 'text/javascript',
  },
```

**Comment by ScriptedAlchemy** [comment]
A loader might be out of date on there that doesn't comply with automatic public path infer or you need to enable a dynamic path for image assets, not relative paths

**Comment by ofirrifo** [comment]
@ScriptedAlchemy I'm not sure what I need to change.
is there any example ?

**Comment by ScriptedAlchemy** [comment]
You'd need to file this bug against the loader that handles svgs.

**Comment by ofirrifo** [comment]
@ScriptedAlchemy  
This is not issue of the loader.
When I serve the remote I do see the image. 
When I use the shell and navigate to remote any type of image is not display.
The issue is with module federation.

I created a reproducible repo.

https://github.com/ofirrifo/webpack-module-federation-issue/tree/c31b73b2464e5817007209c6820b9ac69d9b6acd


# Microfrontends Angular 13

## Steps to reproduce 
- Clone project 
```
git clone https://github.com/ofirrifo/webpack-module-federation-issue.git
```
- Install node modules from the root project
```
npm install
```
- Serve shell
```
npm run start:shell
```
- Serve profile (remote)
```
npm run start:profile
```
- Navigate from shell to profile we get broken image but in the remote it do display

**Comment by ScriptedAlchemy** [comment]
Is that image actually getting processed or is it just using ../../../ ? 

Typically i expect images to use import image from '../../../image.jpg'

What's the html source contain when it runs correctly. 

If the image path is getting transformed then yes, this is a loader problem. Webpack doesn't understand anything other than Javascript. So anything thats not Javascript is a loader. 

Report to plugin author or loader author. This is outside of webpacks control and scope.

**Comment by Totot0** [comment]
I am a same problem. Do you have a solution

**Comment by ScriptedAlchemy** [comment]
File a bug with file loader. They should support public path auto

**Comment by jan-dolejsi** [comment]
Is there a known solution to this, @ofirrifo ?
