### ISSUE TITLE
collisions between multiple webpack runtimes with output.uniqueName already setted

### ISSUE THREAD

**Issue by lzr900515** [module-federation/module-federation-examples#1634]
i used this example [vue3-demo](https://github.com/module-federation/module-federation-examples/tree/master/vue3-demo).

reproduce step:
1. copy a project named 'home2' from 'home'.  modify home2's package.name and little change some text in the components(Button, Content), change the home2 devServer.port as 3003
2. set home, home2, layout    output.uniqueName: package.name.
3. layout import remote home2.
<img width="865" alt="image" src="https://user-images.githubusercontent.com/15673574/155095429-17479ae7-05bf-4b90-b0ac-7e181edfaeb4.png">
<img width="478" alt="image" src="https://user-images.githubusercontent.com/15673574/155095497-a6b183bf-255e-487a-8a8d-10e03a9e07b5.png">
<img width="671" alt="image" src="https://user-images.githubusercontent.com/15673574/155095584-019a6f56-9510-46c6-a0a5-4fe00fb13095.png">

what happened is the same file with same dir in different project, will be covered。
<img width="903" alt="image" src="https://user-images.githubusercontent.com/15673574/155096857-6c0b17ed-1a04-48f8-b885-003d600dee0a.png">

**Comment by ScriptedAlchemy** [comment]
Sounds like a misconfiguration when copying the home example. Confirm the remote isn't using a hard coded public path or something else like that
