### ISSUE TITLE
App breaks when library object is set

### ISSUE THREAD

**Issue by factiondavid** [module-federation/module-federation-examples#1638]
When I set the library object the app breaks and I get the following error: 
`Uncaught SyntaxError: Invalid or unexpected token main.js
Uncaught SyntaxError: Invalid or unexpected token remoteEntry.js`

Here's my configuration:
```
name: 'mfe_container',
      library: { type: 'assign', name: 'mfe_container' },
      filename: 'remoteEntry.js',
      remotes: {
        remoteapp: 'remtoteapp@http://localhost:3000/remoteEntry.js',
      },
      exposes: { './App': './src/App.tsx' }
```

The error is gone and the app works as desired if I remove the library object as the following:
```
name: 'mfe_container',
      //library: { type: 'assign', name: 'mfe_container' },
      filename: 'remoteEntry.js',
      remotes: {
        remoteapp: 'remtoteapp@http://localhost:3000/remoteEntry.js',
      },
      exposes: { './App': './src/App.tsx' }
```

Any idea why this is happening?

**Comment by ScriptedAlchemy** [comment]
The build is probably using something other than assign. 
If you don't need library, don't set it and let webpack manage that
