### ISSUE TITLE
I have implemented a framework that supports module Federation Vue SSR. Can I add examples?

### ISSUE THREAD

**Issue by lzxb** [module-federation/module-federation-examples#1640]
Code URL: 
https://github.com/fmfe/genesis/tree/master/examples/ssr-mf-home
https://github.com/fmfe/genesis/tree/master/examples/ssr-mf-about

**Comment by ScriptedAlchemy** [comment]
By all means. More examples the better! Add as many as you wish

**Comment by lzxb** [comment]
👌🏻

**Comment by ScriptedAlchemy** [comment]
How did you solve SSR modules getting stuck after being required? It looks like you have some polling which is likely similar to what I do to calculate hash when remote changes. But how do you manage the hot reload on servers?

**Comment by lzxb** [comment]
When the program is running, it will inject an object into the VM globally to obtain the remote module
https://github.com/fmfe/genesis/blob/master/packages/genesis-compiler/src/plugins/mf.ts#L75

Hot overloading is actually de referencing the previous VM object from memory

https://github.com/fmfe/genesis/blob/master/packages/genesis-core/src/renderer.ts#L432

**Comment by lzxb** [comment]
You can also wait for the remote module initialization to complete before starting the service
https://github.com/fmfe/genesis/blob/master/examples/ssr-mf-about/genesis.ts#L95

**Comment by ScriptedAlchemy** [comment]
I like your work and the design of your software. 

Do you know much about the webpack plugin api? 

Would you have any interest in helping me with some closed source work for SSR on nextjs. 

What are your rates if I'm able to source funding and you'd be interested. 

I don't often see someone who can actually build something well

**Comment by lzxb** [comment]
I'm very glad to receive your invitation, but I also like my current job, and I'm using it in our company.

**Comment by ScriptedAlchemy** [comment]
Wouldn't be a job offer. Just help for a few days in your spare time

**Comment by lzxb** [comment]
I see, but I don't have much time

**Comment by lzxb** [comment]
If I have time, I want Genesis to support Vue3.0

**Comment by ScriptedAlchemy** [comment]
That's understandable- If that ever changes. Dm me or get me on twitter ScriptedAlchemy 

Again I'll commend you on excellent work.

**Comment by lzxb** [comment]
ok
