### ISSUE TITLE
vue-cli下的三个app未改动本地运行后报错

### ISSUE THREAD

**Issue by Boom-BO** [module-federation/module-federation-examples#1686]
vue-cli下的三个app，拉下来代码之后未改动直接运行就报错，是否跟node或其他依赖版本有关系？
<img width="875" alt="image" src="https://user-images.githubusercontent.com/22814819/156535074-320870fe-0f35-43e6-a40f-96caa53b1348.png">

**Comment by zzc369** [comment]
configureWebpack -> optimization -> splitChunks: false

**Comment by ScriptedAlchemy** [comment]
Or in MF config. Set runtime:false as a option on module federation plugin. It's a hidden option
