### ISSUE TITLE
Invalid Token 

### ISSUE THREAD

**Issue by tuckerjt07** [module-federation/module-federation-examples#1737]
I'm attempting to pull in a remote from one project and use it in another that is being exposed to a shell but am getting an error where the url of the remote is passed to module.exports.

I created a StackOverflow issue for it. Any help would be appreciated!

https://stackoverflow.com/questions/71446762/module-federation-two-way-sharing-invalid-token

**Comment by ScriptedAlchemy** [comment]
Show me the MF config, it looks like you're using library.type=var or something which makes webpack interprete it incorrectly. 

Remove the library field if you're using it and see if it works for you then
