### ISSUE TITLE
Module federation ignore styles by remote module

### ISSUE THREAD

**Issue by ravecat** [module-federation/module-federation-examples#1738]
Demo - `git@gitlab.com:exmpl/webpack-module-federation.git`
Start - `npm run start` (run host with 5001 port, run remote with 5002 port)

Problem - remote module has own global styles which imported to `remote-5002/src/bootstrap.tsx` as

```
import React from 'react';
import ReactDOM from 'react-dom';
import { DemoStand } from './DemoStand';
import './global.css';

ReactDOM.render(<DemoStand />, document.getElementById('root'));
```

`remote-5002/src/global.css` inside remote module folder
```
#button {
  background-color: yellow;
}
```

So if we open `localhost:5001` we see unchanged button

<img width="600" alt="Screen Shot 2022-03-13 at 15 05 45" src="https://user-images.githubusercontent.com/24782863/158060732-d9925739-a409-452b-b993-0d1a92fd4519.png">

if we open `localhost:5002` we see changed button

<img width="600" alt="Screen Shot 2022-03-13 at 15 06 28" src="https://user-images.githubusercontent.com/24782863/158060758-03c3907b-e72e-49cd-93ff-9e2d12d83d7e.png">

Why are the styles not applied to the remote module when it runs inside the host? Didn't find enough information about that

**Comment by ScriptedAlchemy** [comment]
How is webpack supposed to know some random import in some other file is related to button in any way?

Webpack needs to know theres a dependency on a side-effect. 
You'd need to ensure the styles for button are imported in button.js itself otherwise webpack doesn't know its supposed to import side effects
