### ISSUE TITLE
Unmonetize the repo

### ISSUE THREAD

**Issue by FirstWhack** [module-federation/module-federation-examples#1739]
Move @ScriptedAlchemy's monetization outside of the Official repo.

Focus on examples here. I would like to contribute but will not do so while contributions are directly monetized.

**Comment by ScriptedAlchemy** [comment]
What exactly have I monetized here other than my own works??

I do not take users code submitted here, turn around and monetize their works. I do however keep my own examples in here that use software that I have build myself and chosen to productize due to cost of maintaining them - which is pretty much just the next.js stuff due to complexity - Both those examples clearly state in their readme that they require a paid package to run, they are excluded from yarn workspaces so to not interfere with install processes of other users who do want pull down my examples repo and play around with the various implementations. 

Other than next.js, everything in here is free and MIT 

Where's the issue?

**Comment by FirstWhack** [comment]
@ScriptedAlchemy it's the advertisements. _The appearance_ is that you are selling consultations, and a book, based on the OSS contributions of others to this repo.

Everything is an opinion so, mine could be a bad one, I'm open to it.

**Comment by ScriptedAlchemy** [comment]
Yeah but my book is literally me the author, writing abut how MF works and how to use it - its got nothing to do with MF examples other than lots of user need to know where they can learn, and many companies often go to my repo and see that im around to help if needed. 

I only commercialize my time and my works. 

What if i move it down on the page? So its not the first thing you see? 

Just understand. If i run out of money, all module federation works comes to a complete stop. What compromise can we come to where I can still be funded to invest time into the ecosystem. But not make you feel like im selling others contributions. 

Its important to understand that i kinda own most of the ecosystem and the future of MF - If i run out of funding, Module Federation will, grind to s standstill. 

I need funding, resources, and its not easy to acquire that. 
Many companies need me, few know they can get my time. MF-examples is the go-to resource for videos, blogs, how-tos, who can help. How to get in touch. 

I'm not saying BUY BUY BUY - Im just saying "We wrote a book and if you need me I can help you"

If you want to open a PR with proposed changes - I'm willing to consider shuffling it around. 

But i cannot lose my livelihood, Im the only author of MF who actively tries to build new ecosystem tools for it.

Just understand me point of view here. I must have resources to improve the internet for the greater good. I must spend my own money on copywriters, editors. I get about 400 emails a day, i cannot handle that volume - i had to do best effort to support where I can but also offer paid support to companies who wouldn't know that I would even be interested in getting on a call for an hour with them in the first place. 

Im more than open to PR edits and suggestions, readme is not my strong suit. 
But I cannot say okay to obliterating nearly all the funding that keeps MF moving forwards. 

I rarely encourage people to go spend money, its there if they want deeper understanding, if i have bandwidth ill try to help.

But i got a sick wife, and need to put food on the table and care for her, and fund all of MF mostly out of pocket. 

Ive spent easily over $100k of my own money on MF for the greater good of us all. 

Id love your contributions and help, but not at the expense of caring for my wife and progressing the ecosystem for a better internet for everyone <3 

Im not greedy, trying to sell and monetize, im trying to provide support for really complex things and let everyone know theres a book out there that can help them bootstrap their learning. 

I dont want it to appear the way you see it, so Id really like to see some proposed edits to change that assumption for everyone. I sell only things i 100% wrote, if someone has a great idea and wants to monetize it - ill help and contribute, but they get equal financial support for their works. 

I want to make lives better for devs. That's all, not here to get rich

**Comment by ScriptedAlchemy** [comment]
If anyone else is bothered by this. Send a PR. 

Till someone feels compelled to edit the readme, they'll stay as is - I've got no capacity to throw into a readme right now but happy to accept edits. 

This is open source, don't like it? Change it 😊
