### ISSUE TITLE
dynamic remotes

### ISSUE THREAD

**Issue by YahelCh** [module-federation/module-federation-examples#1740]
useFederatedComponent (dynamic remotes) throws when trying to unload remote component.
I cloned the example repo and added a button **clear all** that does:  

> function clearAll(){
>     setSystem({});
>   }

when I hit it the app crashes with the following error:

> Uncaught TypeError: Cannot read properties of undefined (reading 'init')_

I'd expect the hook to return null in case the parameters (all or partial) are undefined
(same as the inner hook **useDynamicScript** does.

**Comment by ScriptedAlchemy** [comment]
Looks like a bug, somewhere in there its trying to call init on the loadComponent function, put some logs on that and see if its trying to call init and get still
