### ISSUE TITLE
Is it possible to use remotes with CJS syntax?

### ISSUE THREAD

**Issue by grantyi** [module-federation/module-federation-examples#1800]
Hi! I'm attempting to server-side render a component that is exposed via my remote. However, I am getting an error that `Error: Cannot find module 'remote/my-component'`

I am trying to import like this `const component = require('remote/my-component');`

Here is my plugin config: 
```
    new ModuleFederationPlugin({
      name: 'app',
      library: { type: 'commonjs-module' },
      filename: 'remoteEntry.js',
      remotes: {
        remote: path.join(__dirname, 'mf/remoteEntry.js'),
      },
      exposes: {},
      shared: {

      },
    }),
```

I created a top level folder called `mf` that has the build artifacts of `yarn build` of my remote project. Am I doing something wrong or can I only use ESM to import my component?

**Comment by ScriptedAlchemy** [comment]
That should work. Check the SSR examples. 

I've done this in the past without issues.

**Comment by ScriptedAlchemy** [comment]
Maybe set the remote type on the config as well so webpack knows it's commonjs remotes as well
