### ISSUE TITLE
Is it possible to use the shell app angular version @12 & other child/shared mfe's @v13

### ISSUE THREAD

**Issue by Ravi-Royal-143** [module-federation/module-federation-examples#1834]
I am using child mfe which needs to be updated to the angular version 13 but the shell app is still in angular version 12 which will be updated later on is this possible. it's throwing some console error "Cannot read properties of undefined ( reading 'init' )

**Comment by ScriptedAlchemy** [comment]
Probably can but you'd likely need to load 2 copies of angular. And mount them as separate apps with adapters to proxy data back and forth

**Comment by Ravi-Royal-143** [comment]
Error screenshot 
![image](https://user-images.githubusercontent.com/81796854/160565138-5288b098-712a-42ec-b850-c3e5b20ab640.png)

Repo:
for shell app: [angular12-microfrontends](https://github.com/module-federation/module-federation-examples/tree/master/angular12-microfrontends)
for child app: https://github.com/manfredsteyer/module-federation-plugin-example

To start the app change done:

In module-federation-plugin-example changed all ports from 3000 to 4201.
In module-federation-plugin-example -> npm run start:mfe1
In angular12-microfrontend -> npm run start:shell
