### ISSUE TITLE
Any possibility to use with splitChunks?

### ISSUE THREAD

**Issue by cooltolia** [module-federation/module-federation-examples#1864]
First of all, let me say that the work that has been done to create this plugin is fantastic.

But right now I'm working on its implementation in the project that has its own plugin to create chunks for any specified library. Thus we end up with having `main.js, react.js, reac-dom.js, other_vendors.js`. 

And with this approach I didn't find any solution to make MF plugin friends with this custom chunks. In remote app I just see an error that says it couldn't load `remoteEnty.js`, though it is 200 status in network.
<img width="559" alt="Screen Shot 2022-04-04 at 10 05 19 PM" src="https://user-images.githubusercontent.com/20162459/161614096-e6483ea5-6238-476c-b36b-701aca84d41d.png">

Will appreciate any advices and ideas.

**Comment by cooltolia** [comment]
The only idea I have, is to teach somehow MF plugin, that in shared property `react` should be the one that is already in chunk. But again, I'm not really sure that it is possible

**Comment by ScriptedAlchemy** [comment]
yeah you can, you have to use enforce:true on the cacheGroup. 

google "module federation splitChunks cacheGroups" and theres a medium article about it. there might be a example if you search this repo for "cacheGroups" but not sure. 

But yes it is possible and i have done it before by using enforce, on a cache group to consolidate react vendors and merge chunks back together for 1 to many modules

**Comment by cooltolia** [comment]
Thank you for your answers, @ScriptedAlchemy.
Really appreciate your help. 

As I understood, you are saying about using splitChunks to group all chunks that were created by module-federation together. Yep, I've seen this article on medium.

But actually I have a bit different challenge. We already have some chunks created by splitChunks. What I want to do is to stick module-federation here. The issue I had was that federated module tried to import not only specified shared libs, but also a vendor chunk, created by splitChunks. And it failed.
The only way I found to resolve it, was to identify all libs that for some reason were places in vendor but needed by federated module and extract them to shared scope.

**Comment by ScriptedAlchemy** [comment]
prexisting chunking solutions are most likely going to fail. Youll have to gut whatever youre doing with splitChunks and start from scratch.
