### ISSUE TITLE
Validate Redux Dynamic Injection 

### ISSUE THREAD

**Issue by ScriptedAlchemy** [module-federation/module-federation-examples#188]
@MonPote would you mind verifying that your `redux-reducer-injection` still works on this branch https://github.com/module-federation/module-federation-examples/pull/180

Its the webpack beta 22 update, it runs but I'm not sure if its functioning as you had anticipated

**Comment by MonPote** [comment]
Hey @ScriptedAlchemy , yes let me try this this week :D

**Comment by ScriptedAlchemy** [comment]
Thank you!

**Comment by ScriptedAlchemy** [comment]
@MonPote bump
