### ISSUE TITLE
fn is not a function while loading while loading remote MFE

### ISSUE THREAD

**Issue by Paniraj2010** [module-federation/module-federation-examples#1886]
Hi,

I am trying to integrate React MFE in angular host. where in React MFE expecting pass props. it all works good when react MFE access in react host. But when I Try to access in Angular host I am getting **fn is not a function while loading**

**Also React MFE expecting input parameter it was implemented using Mount.**

I have implemented in Angular using a wrapper component by referring https://www.angulararchitects.io/en/aktuelles/multi-framework-and-version-micro-frontends-with-module-federation-the-good-the-bad-the-ugly/ **however when I run the application it gives me fn is not a function while loading**

```
import { mount } from `'mfeHierarchy/MfeHierarchy';`
Component({
  template: `
  <div #placeHolder></div>
`,
})
export class WrapperComponent implements AfterContentInit {

  @ViewChild('placeHolder', { read: ViewContainerRef, static: true })
    viewContainer!: ViewContainerRef;
    
  userContext:any;
 
  constructor(private route: ActivatedRoute) {
    const queryParams = new URLSearchParams(window.location.search);
    this.userContext = {
      userName: queryParams.get("NTLogin"),
      userEmail: queryParams.get("Email")
    };
   }
  
  ngAfterContentInit(): void {
    
    console.log('with in ngAfterContentInit');
   
    console.log(mount.apid);
}
```

**In the above code mount is imported from the remote module. As soon as I access Mount with in ngAfterContentInit() it is throwing error fn is not a function while loading**

I see following comment "The remote is booting after its host, which likely messes with the resolution." from https://github.com/module-federation/module-federation-examples/issues/322 but I am not sure how can we make sure Remote MFE is booting before HOST.

Please assist.

@ScriptedAlchemy @manfredsteyer

**Comment by Paniraj2010** [comment]
Hello, Angular 13 with webpack 5 causing this issue, once I update angular back to angular 12 everything started working.

Webpack 5 with Angular 13 has issue with remotes loading. **I am getting issue with below lines, which get auto generate with webpack run time** 

Due to this application was failing to load the remote module.

```
var handleFunction = (fn, arg1, arg2, d, next, first) => {
				try {
					**var promise = fn(arg1, arg2);**
					if(promise && promise.then) {
						var p = promise.then((result) => (next(result, d)), onError);
						if(first) promises.push(data.p = p); else return p;
					} else {
						return next(promise, d, first);
					}
				} catch(error) {
					onError(error);
				}
			}
```

**Comment by ScriptedAlchemy** [comment]
are you using NX? theres a bug in nx currently that has the same issue, someone tweeted me about it a few hours ago -- might be related?

**Comment by Paniraj2010** [comment]
No I am not using NX.

**Comment by ScriptedAlchemy** [comment]
Contact manfred or look at git history, see if deps changed or if theres updates. fn not a function usually is because of missing remote or export
