### ISSUE TITLE
HMR with react-app-rewired, standalone app that exposes components crashes HMR

### ISSUE THREAD

**Issue by HossamHa** [module-federation/module-federation-examples#1945]
``Hey, I have a host app that remotes an app that exposes a couple of components to be used by the host app. this works without a problem. However, to make life easier as a developer, I want to run the remote application as a standalone without the need to start up the host application. This also works without a problem. the main issue I am having is HMR.

 I followed this https://github.com/module-federation/module-federation-examples/issues/358, I am having the same issue but the way it was resolved here with setting chunk: ['main'] is not doing it for me. Each code save still requires a manual update of the page. 
By removing the "exposes property from ModuleFederationPlugin everything works as intended when the app runs standalone. 

I should include that I am using react-app-rewired and this is how my config-overrides.js looks

![image](https://user-images.githubusercontent.com/32093684/165326634-b79f77ea-0788-4c27-8499-46c4d2e6a17b.png)
![image](https://user-images.githubusercontent.com/32093684/165326746-638b04af-3e4d-47ca-838a-3bdda5a6cf58.png)

When adding chunks: ['main'] to  HtmlWebpackPlugin I get the following error, "Conflict: Multiple assets emit different content to the same filename index.html"

**Comment by ScriptedAlchemy** [comment]
is this hot reloading between remotes and hosts or hot reloading when working on a remote in standalone mode itself?

**Comment by HossamHa** [comment]
It is hot reloading when working on a remote application in a standalone mode itself, so no host application is involved at all.

**Comment by ScriptedAlchemy** [comment]
This may have been fixed with latest webpack release
