### ISSUE TITLE
Cannot find module 'vue'

### ISSUE THREAD

**Issue by yolandage** [module-federation/module-federation-examples#1953]
vue-cli don't work
![1651211527(1)](https://user-images.githubusercontent.com/34050209/165891707-49b4a31c-107e-43b0-99b7-2c5b709dec6d.jpg)

**Comment by yolandage** [comment]
webpack 5.55.1
webpack-cli 4.8.0

**Comment by ScriptedAlchemy** [comment]
send a pr, check deps are up to date, look at git history on packages and try downgrading a version
