### ISSUE TITLE
Unexpected behaviour when MFE file script file is unavailable

### ISSUE THREAD

**Issue by vadymrybak** [module-federation/module-federation-examples#1965]
Let's take a look at the HTML page below:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta content="ie=edge" http-equiv="x-ua-compatible">
    <title>Operations UI</title>
    <link href="favicon.ico" rel="shortcut icon" />
    
                <script src="/SecureRequest"></script>
                <script src="http://localhost:3001/remoteEntry_common_mfe.js"></script>
                <script src="http://localhost:3002/remoteEntry_licensing_mfe.js"></script>
                <script src="http://localhost:3003/remoteEntry_fallout_mgmt_mfe.js"></script>
                <script src="http://localhost:3004/remoteEntry_workflow_mfe.js"></script>
                <script src="http://localhost:3005/remoteEntry_manual_task_mfe.js"></script>
            
  </head>
  <body>
    <div id="output"></div>
    <script src="/main.js"></script>
  </body>
</html>
```
This web app is using 5 different MFEs that bring different functionality. Let's stop running app on host 3001 making common_mfe basically unavailable. So the browser will return us: 
GET http://localhost:3001/remoteEntry_common_mfe.js net::ERR_CONNECTION_REFUSED

Funny thing start happening now. React app freezes for exactly 2 minutes. 
![image](https://user-images.githubusercontent.com/38698086/167012282-3272fbec-2ef2-43e2-997f-01c5a5b53da1.png)

Browser console still shows connection refused but this line in the beginning of the app is frozen:
`ReactDOM.render(<App />, document.getElementById("output"));`

After 2 minutes it starts rendering the page, I have ErrorBoundary in place so that nice error message is displayed. Here is additional logs that indicate that react finally started rendering things:

![image](https://user-images.githubusercontent.com/38698086/167012581-22aa9a76-cc0e-4854-9893-2b381a22ad96.png)

There is this Entry.tsx file where import of different MFEs is happening:

```
// MFE modules
const HeaderComponent: React.LazyExoticComponent<typeof Header> = React.lazy(() => import("common_mfe/Header"));
const FooterComponent: React.LazyExoticComponent<typeof Footer> = React.lazy(() => import("common_mfe/Footer"));
const LicenseIntroComponent: React.LazyExoticComponent<typeof LicenseIntro> = React.lazy(() => import("licensing_mfe/LicenseIntro"));
const LicenseAboutComponent: React.LazyExoticComponent<typeof LicenseAbout> = React.lazy(() => import("licensing_mfe/LicenseAbout"));
const LicenseErrorComponent: React.LazyExoticComponent<typeof LicenseError> = React.lazy(() => import("licensing_mfe/LicenseError"));
const LicenseThresholdComponent: React.LazyExoticComponent<typeof LicenseThreshold> = React.lazy(() => import("licensing_mfe/LicenseThreshold"));
```
If I comment out lines related to common_mfe then app loads just fine without any lag or delay. As soon as bring them back - app freezes. There is even stranger thing: lets say I stop app on host 3002 (which is related to licensing mfe) - then there is no delay behaviour. So something is wrong with common_mfe lazy loading.

Would anyone have any idea/thoughts on this one?

Webpack ModuleFederation setup:

```
new ModuleFederationPlugin({
            name: "operations_ui",
            filename: "remoteEntry_operations_ui.js",
            remotes: {
                common_mfe: `common_mfe@${commonMfe}`,
                licensing_mfe: `licensing_mfe@${licensingMfe}}`,
                fallout_mgmt_mfe: `fallout_mgmt_mfe@${falloutMfe}`,
                workflow_mfe: `workflow_mfe@${workflowMfe}`,
                manual_task_mfe: `manual_task_mfe@${manualTaskMfe}`
            },
            shared: ["react", "react-dom", "react-router-dom", "react-bootstrap", "bootstrap", "react-icons", "mobx", "mobx-react", "react-day-picker", "react-bs-notifier"],
        }),
```

**Comment by ScriptedAlchemy** [comment]
look at splitChunks, the chunkLoading timeout defaults to 120 seconds.
