### ISSUE TITLE
[advanced-api/dynamic-remotes-runtime-environment-variables] `componentCache` is never used

### ISSUE THREAD

**Issue by vjpr** [module-federation/module-federation-examples#1966]
https://github.com/module-federation/module-federation-examples/blob/7fc92f8f7678a7af76f925b9d5d1d03eb472109e/advanced-api/dynamic-remotes-runtime-environment-variables/host/src/hooks/useFederatedComponent.js

---

Also, `useDynamicScript` will remove the script from the page when the component is unmounted.

For my use case, I have a sidebar on the left that renders a "remote" in the main content on the right. Components are replaced (via react-router).

The current code makes a call to `remoteEntry.js` for each switch.

Might be worth wrapping the `useDynamicScript` useEffect unsubscribe in:

```js
    return () => {
      if (removeOnUnmount) {
        urlCache.delete(url)
        document.head.removeChild(element)
      }
    }
```

https://github.com/module-federation/module-federation-examples/blob/7fc92f8f7678a7af76f925b9d5d1d03eb472109e/advanced-api/dynamic-remotes-runtime-environment-variables/host/src/hooks/useDynamicScript.js#L38-L41

Then user can choose whether they want it removed.

**Comment by ScriptedAlchemy** [comment]
Send a PR, i didnt write that example
