### ISSUE TITLE
vue-cli example doesn't work with npm.

### ISSUE THREAD

**Issue by shibisuriya** [module-federation/module-federation-examples#1968]
The vue-cli example given in this repo doesn't work with npm, if I run cd to the directories /core, /consumer and /others and run npm i and npm run serve one by one... Module federation is not working, that is the components from core vue project is not showing in consumer vue project... Will the example only work with yarn?

**Comment by ScriptedAlchemy** [comment]
probably, this is a yarn based monorepo. 
If you pulled the example out into your own npm based repo - it would likely work. 

feel free to send a pr if you see any bugs
