### ISSUE TITLE
Remote module chunks are not loading from remote

### ISSUE THREAD

**Issue by swapnilUI** [module-federation/module-federation-examples#1969]
First of all thanks for this awesome plugin.

I am facing problem to load remote module because its chunks are not loading remote location. 

Chunks setting
`splitChunks: isEnvProduction && {
        chunks: "all",
        name: false,
        cacheGroups: {
          default: false,
          vendors: false,
        },
      },
    },`
`
 new ModuleFederationPlugin({
      name: "host_mod",
      filename: "hostEntry.js",
      remotes: {
        "remote_module": "remote_module@[window.extAppUrl]/admin/remoteEntry.js"
      },
      exposes: {
      },
      shared: {
        ...deps,
        react: {
          singleton: true,
          requiredVersion: deps.react,
        },
        "react-dom": {
          singleton: true,
          requiredVersion: deps["react-dom"],
        },
      },
    }),
    new ExternalTemplateRemotesPlugin(),
`
`window.extAppUrl = "//localhost:3000";
import("./App");
`
Remote location - http://localhost:3000/
Remote file is loading properly from - http://localhost:3000/admin/remoteEntry.js 

However, chunk files are loading from host - http://localhost:8080/admin/static/js/node_modules_object-assign_index_js.chunk.js

Then, I tried using ExternalTemplateRemotesPlugin 
In this case chunks are loading from remote location now but URL is this -http://localhost:3000/admin/remoteEntry.js/static/js/node_modules_object-assign_index_js.chunk.js

**Comment by zhanggenlove** [comment]
> 首先感谢这个很棒的插件。
> 
> 我在加载远程模块时遇到问题，因为它的块没有加载远程位置。
> 
> 块设置 `splitChunks: isEnvProduction && { chunks: "all", name: false, cacheGroups: { default: false, vendors: false, }, }, },` `new ModuleFederationPlugin({ name: "host_mod", filename: "hostEntry.js", remotes: { "remote_module": "remote_module@[window.extAppUrl]/admin/remoteEntry.js" }, exposes: { }, shared: { ...deps, react: { singleton: true, requiredVersion: deps.react, }, "react-dom": { singleton: true, requiredVersion: deps["react-dom"], }, }, }), new ExternalTemplateRemotesPlugin(),` `window.extAppUrl = "//localhost:3000"; import("./App"); ` 远程位置 - [http://localhost:3000/远程文件从 - ](http://localhost:3000/)http://localhost:3000/admin/remoteEntry.js 正确加载[](http://localhost:3000/admin/remoteEntry.js)
> 
> 但是，块文件正在从主机加载 - http://localhost:8080/admin/static/js/node_modules_object-assign_index_js.chunk.js
> 
> 然后，我尝试使用 ExternalTemplateRemotesPlugin 在这种情况下，块现在正在从远程位置加载，但 URL 是这样的 - http://localhost:3000/admin/remoteEntry.js/static/js/node_modules_object-assign_index_js.chunk.js

@ @swapnilUI so how to solve it？？？

**Comment by HelenSilas** [comment]
I had the same problem

**Comment by swapnilUI** [comment]
@zhanggenlove, @HelenSilas - I had used static public path using environment variable at build time. But it was a problem as i had to do different builds for dev, SIT and Prod. So now i have set publish path auto for all apps and using promise based approach to load remote modules. Where i am using document.location.origin to get current host. So far it’s perfectly working for me.
