### ISSUE TITLE
Shared Routing Example - You should not use <Link> outside a <Router>

### ISSUE THREAD

**Issue by piniTayeb** [module-federation/module-federation-examples#197]
In the Shared shared-routing example, 
when the **remote component** has a Router's `<Link>` inside, 
i get an error:

 “You should not use `<Link>` outside a `<Router>`"

**Comment by ScriptedAlchemy** [comment]
You didn't share react router libs between two bi-directional instances

**Comment by piniTayeb** [comment]
Exactly what I needed! Thank you @ScriptedAlchemy :)

**Comment by ajayjaggi** [comment]
@piniTayeb i have the same issue.. Pls tell how you resolved it...
I have shared the dependencies also

**Comment by piniTayeb** [comment]
@ajayjaggi i just shared dependencies..
can you upload your webpack config?

https://github.com/module-federation/module-federation-examples/tree/master/server-side-render-only

**Comment by ajayjaggi** [comment]
![Screen Shot 2020-11-17 at 4 08 00 PM](https://user-images.githubusercontent.com/46561425/99379760-17693e00-28ef-11eb-951e-0d5b59669d35.png)
This is my component which my remote is exporting.

![Screen Shot 2020-11-17 at 4 09 11 PM](https://user-images.githubusercontent.com/46561425/99379894-41bafb80-28ef-11eb-8d3b-18d738de9b63.png)
This is config for ModuleFederationPlugin.


When i put react-dom in shared my app breaks at client side.Don't know why

**Comment by ajayjaggi** [comment]
With ./Header component everything is working fine

**Comment by piniTayeb** [comment]
can you make a repo with this error?
