### ISSUE TITLE
Angular: Importing BrowserAnimationsModule causes routes to stack on top of each other

### ISSUE THREAD

**Issue by vsimone67** [module-federation/module-federation-examples#1980]
If I use any component that requires BrowserAnimationsModule (e.g. PRIMENG) and add the Import of the BrowserAnimationsModule to the Angular module I am exporting as a Micro Front End, when I call the route from my Shell program and navigate from one route to another (and one of the routes has BrowserAnimationsModule  as part of it), that page will be stacked on the previous route instead of replacing it.

I have tried to add the following to my webpack.config.js with no luck:

 "@angular/animations": { singleton: true, strictVersion: true, requiredVersion: 'auto' },   
or 
 "@angular/platform-browser/animations": { singleton: true, strictVersion: true, requiredVersion: 'auto' }

One last item, if I use the PRIMENG calendar component it will not render properly using Module Federation, the full calendar will show up underneath a grid component I have on the next row.

**Comment by ScriptedAlchemy** [comment]
try @angular/animations/ 

with the trailing slash

**Comment by andrewdambrosio** [comment]
I'm suffering the same issue, however I'm using Angular Material. I've tried both of the above suggestions but still get the stacking of routes in the view

**Comment by ScriptedAlchemy** [comment]
Material usually (for react at least) I have to share @mui/ as a singleton to get it to work. Something else is getting imported internally. Like context or whatever. And that’s not being set as the singleton

**Comment by ScriptedAlchemy** [comment]
MUI has a lot of little packages it imports from other things I’m it’s node modules. One of them is likely the problem

**Comment by vsimone67** [comment]
Thank you for the suggestion, I tried @angular/animations/ but it did not fix the issue.  It seems that anything with BrowserAnimationsModule breaks Module Federationi.

My current apps use Angular Elements so I will probably just stick with it.

**Comment by ScriptedAlchemy** [comment]
Try trailing slash on just @angular/

**Comment by gleisonkz** [comment]
I'm having this same issue, has anyone got any solution?

**Comment by vsimone67** [comment]
I tried the @angular/ no luck :(

**Comment by ScriptedAlchemy** [comment]
Likely related to a nested dependency. Try seeing what the package depends on and share those

**Comment by vsimone67** [comment]
I will thank you
