### ISSUE TITLE
Multi Repo angular applications not working with module federation integration

### ISSUE THREAD

**Issue by pratheeshrajan** [module-federation/module-federation-examples#1985]
Hello,

I have two standalone angular applications , one is shell hosted on port 5000, and the other is mfe app which is hosted on port 3000
and added angular-architects/module-federation plugin and did the necessary wirings.

Restarted the app and shell loaded correctly which is hosted on port 5000, tried the route and loaded the mfe, could see the remote entry file hosted on 3000 loaded correctly on network tab, after that the module call to the mfe failed since it is trying to load port 5000 instead of 3000.

**"core.mjs:6509 ERROR Error: Uncaught (in promise): ChunkLoadError: Loading chunk src_app_flights_flights_module_ts-_08e11 failed.
(error: http://localhost:5000/src_app_flights_flights_module_ts-_08e11.js)**"

is there any work around for this or is this the limitation of  module federation in angular applications ?

**Comment by ScriptedAlchemy** [comment]
public path needs to be set to auto in webpack.output.publicPath
