### ISSUE TITLE
Multiple browser routers 

### ISSUE THREAD

**Issue by adarsh0d** [module-federation/module-federation-examples#1986]
Hello,

The approach which I saw in examples is where we share our routes through module federation and shell application handles the routing for all the apps.

But what if I only share a single component which has it's own internal routing mechanism, and I don't need to expose anything else. Is that possible. I tried by passing basename.

Routes work for remote application when run in standalone, but when it's integrated to shell they don't work.

for example:
Shell application

```
<BrowserRouter>
 <Route path="/app/*">
          <RemoteAppl basename="app"/>
        </Route>
</BrowserRouter>
```

Remote Application

```
<BrowserRouter  history={history} basename={props.basename}>
 <div style={{width: '100%', marginTop: 10, padding: 10, border: '5px solid gray', height: '100%' }}>
          <ul style={{ display: 'flex', margin: 20 }}>
            <li>
              <Link to="/experience-1">Internal Link 1</Link>
            </li>

            <li style={{ marginLeft: 20 }}>
              <Link to="/experience-2">Internal Link 2</Link>
            </li>
          </ul>
          <Route path="/experience-1">
            <ShoppingList />
          </Route>
      </div>
</BrowserRouter>
```

I saw this thread, but couldn't make anything out of it https://github.com/module-federation/module-federation-examples/issues/536

**Comment by ScriptedAlchemy** [comment]
Dont think you want have multiple browser routers. Youd want to use switch or something else. Only hosts should implement browser router, and only once. Usually I have a standalone wrapper that has like a mini shell for each app. Then I federate the inner component. So browser router stays on the shell layer 

https://v5.reactrouter.com/web/example/nesting

**Comment by XiaofengXie16** [comment]
Hi @adarsh0d 

This example is probably what you are looking for: https://github.com/XiaofengXie16/module-federation-nested-react-router-v6

This approach will work with react-router v5 as well (In my company, I am using v5).

However, there is one caveat, if you want to do inter-app navigation, you will need to pass the `navigation` function (useNavigation for V6) from the app shell down to the clients.

**Comment by nebarf** [comment]
I put in place a setup based on react-router-dom and module-federation leveraging on a combination of browser and in-memory history strategies to handle nested routers.

The example is available [here](https://github.com/nebarf/module-federation-react-router-dom).

@ScriptedAlchemy Please let me know if it can make sense adding it to the official module-federation examples.

**Comment by ScriptedAlchemy** [comment]
Yeah feel free to open a PR. Always welcome more examples to help others.

**Comment by OriAmir** [comment]
hi @nebarf @ScriptedAlchemy   first, thanks for the amazing work!

I didn't understand why we couldn't use `<BrowserRouter/>` both in Shell and Remote app?  what's wrong with that?
I see the great work @nebarf has done but I'm not really understand why we need this complexity ?

I implemented that in this way and it works great:

1. Define `react-router-dom` as a singleton in the module Federation config.
2. In  the`Shell` app, define the router and remote app as regular, nothing special:

```
const Home = () => (
    <div>
      home page
    </div>
)

const MyTemplateApp = () => (
  <React.Suspense fallback="Loading">
    <TemplateApp />
  </React.Suspense>
);

const TemplateApp = React.lazy(() => import("template/App"));

<BrowserRouter>
   <Suspense fallback="loading">
            <Routes>
                <Route path="/" component={<Home />} />
                <Route path="/template-app/*" component={<MyTemplateApp />} />
           </Routes>
     </Suspense>
</BrowserRouter>
```

3. In the `Remote` app, same `BrowserRouter` as wrapper and the only thing I have to do is to create a simple hook to get the resolved path:
```
import { useResolvedPath } from "react-router-dom";

//hook to get the path without the "/" at the start(because we are setting the "/" in the routes/links)
//add the NAME to the current path
const useCurrentResolvedPath = () => {
  let resolved = useResolvedPath("");
  let rootPath = resolved.pathname;

  if (rootPath?.slice(-1) === "/") {
    rootPath = rootPath.slice(0, -1);
  }
  return rootPath || "";
};

export { useCurrentResolvedPath };
```

Then, I just use that hook as a base for the `<Link/>` `to` parameter in the navbar:

```
const Navbar = () => {
  const rootPath = useCurrentResolvedPath();

  return (
    <div className="nav-bar">
        <Link to={rootPath || ""}>template app home</Link>
        <Link to={`${rootPath}/example`}>example route</Link>
    </div>
  );
};
```


It works like a charm in all the cases including inner sub-routing and include browser back/next buttons.
did you see any problems with this approach?

thanks a lot.

**Comment by nebarf** [comment]
Hi @OriAmir, thanks for the question. Your solution does work but I've two main concerns that it can be worth to consider:

1. **Decoupling**: routing in each MFE app should be isolated and extraneous from the mounting context. From my POV the fact that remote app is mounted under `/template-app` base path should not affect its internal navigation and implementation.
2. **Single source of truth**: having a single "component" updating the browser history brings a lot of flexibility (e.g. it could really help in case you're gradually migrating a legacy system following the strangler pattern).

Of course no solution is bulletproof and the complexity is something to take into account for sure.

**Comment by OriAmir** [comment]
hi, @nebarf, and thanks for the answer and the great app you provide.

1. I don't really understand what you mean- in my example every MFE routing is isolated and manages his own routing, the only "communication" between them is when the Shell load the MFE, and then MFE takes control over his routing.

2. I agree with you that always better one place that manages the browser router but as you say it makes it harder to understand.

Another point:  currently the `react-router` docs recommend using the `BrowerHistory` when it's possible:

> <BrowserRouter> is the recommended interface for running React Router in a web browser.

and the `HistoryRouter` is unstable for now, I just wonder why you choose `HistoryRouter` and not `MemoryRouter`?

Thanks a lot again.

**Comment by csharma-mdsol** [comment]
@OriAmir Your solution looks interesting. Can you share the complete code for your shell and remote app? I don't understand where Navbar is in your app.

**Comment by charvee21** [comment]
@OriAmir Your solution looks interesting. Can you share the code of your shell app and remote app where you have implemented this thing. I don't understand where Navbar is coming from.

**Comment by OriAmir** [comment]
> @OriAmir Your solution looks interesting. Can you share the code of your shell app and remote app where you have implemented this thing. I don't understand where Navbar is coming from.

Hi, sure. 
I will upload that soon and update with the link .

**Comment by ScriptedAlchemy** [comment]
Send pr if it would make a good example

**Comment by gitnupur** [comment]
[routing-module-typescript-federation.zip](https://github.com/module-federation/module-federation-examples/files/12422266/routing-module-typescript-federation.zip)
[routing-module-federation.zip](https://github.com/module-federation/module-federation-examples/files/12422267/routing-module-federation.zip)

routing-module-federation - this application works correctly. On running the host and remote both, I can directly load the remote

<img width="335" alt="working solution" src="https://github.com/module-federation/module-federation-examples/assets/113530765/f222ce82-1f32-4004-90d5-f5d2c9d452c4">

There is no link button on the page. Note I have used lazy loading for the routes. 


routing-module-typescript-federation 

This is using dynamic remotes to load the application. 


<img width="752" alt="typescript_routing_problem" src="https://github.com/module-federation/module-federation-examples/assets/113530765/93795662-60c8-4a85-bc04-e7951242bdf1">

The remote gets loaded only when admin link button is clicked. localhost:4000/admin directly does not work. I want to work it directly as I will be navigating from asp.net application to this page. 

Kindly help.
