### ISSUE TITLE
Typescript Example - Project References

### ISSUE THREAD

**Issue by RussellCanfield** [module-federation/module-federation-examples#2002]
I recently started using module federation with typescript and I have noticed most examples/articles do not make use of [project references](https://www.typescriptlang.org/docs/handbook/project-references.html). It's a relatively newer feature in typescript but it allows you to reference type declarations without any manual type creation.

Paired with aliases, it's a really effective approach for typescript with module federation. If you all agree, is it possible to submit an example?

**Comment by ScriptedAlchemy** [comment]
Go for it. We would also love you to try out module-federation/typescript and are open to feedback on that plugin

**Comment by RussellCanfield** [comment]
Thanks! Absolutely, where can I find that plug-in or any documentation for it?

**Comment by ScriptedAlchemy** [comment]
On privjs package registry

Dm me on twitter if you neee some info

**Comment by RussellCanfield** [comment]
Added and merged. Closing
