### ISSUE TITLE
Do we really need React.lazy and dymamic import?

### ISSUE THREAD

**Issue by SunHuawei** [module-federation/module-federation-examples#202]
MFE is a great idea, I'm trying to learn it.

When I see code like this [https://github.com/module-federation/module-federation-examples/blob/master/basic-host-remote/app1/src/App.js#L3](https://github.com/module-federation/module-federation-examples/blob/master/basic-host-remote/app1/src/App.js#L3)
```
const RemoteButton = React.lazy(() => import("app2/Button"));
```
a question just pop up, do we really need `React.lazy` and dynamic import here?

We know the js file is already put into HTML as a `<script>` tag, we expect the js should be loaded before this code executing.

So, I try to remove `React.lazy` and change it to
```
import RemoteButton from "app2/Button";
```
It just works.

So, anything I missed?

**Comment by ScriptedAlchemy** [comment]
You don't. But any time you use a synchronous import, you are moving the load sequence of that code to the parent async boundary. 

Anything sync, is loaded at the closest parent import() 

The more dynamic import you have, the less code that's loaded at a boundary.

**Comment by SunHuawei** [comment]
I understand dynamic import for splitting code, that can separate some code out of the main js file. That's valuable.

But, here, "app2/Button" is already in a separated file, I cannot see any value here.

I'm not sure what do you mean by "the less code that's loaded at a boundary", but when I compare the assets in dist folder, it shows like these

```diff
~ diff dist/main.js dist-lazy-dynamic/main.js
10550a10551,10573
> /******/ 	/* webpack/runtime/create fake namespace object */
> /******/ 	(() => {
> /******/ 		// create a fake namespace object
> /******/ 		// mode & 1: value is a module id, require it
> /******/ 		// mode & 2: merge all properties of value into the ns
> /******/ 		// mode & 4: return value when already ns object
> /******/ 		// mode & 8|1: behave like require
> /******/ 		__webpack_require__.t = function(value, mode) {
> /******/ 			if(mode & 1) value = this(value);
> /******/ 			if(mode & 8) return value;
> /******/ 			if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
> /******/ 			var ns = Object.create(null);
> /******/ 			__webpack_require__.r(ns);
> /******/ 			var def = {};
> /******/ 			if(mode & 2 && typeof value == 'object' && value) {
> /******/ 				for(const key in value) def[key] = () => value[key];
> /******/ 			}
> /******/ 			def['default'] = () => value;
> /******/ 			__webpack_require__.d(ns, def);
> /******/ 			return ns;
> /******/ 		};
> /******/ 	})();
> /******/ 	
10665c10688
< /******/ 			"src_bootstrap_js": [
---
> /******/ 			"-_ad8d": [
10709c10732
< /******/ 						if(true) { // all chunks have JS
---
> /******/ 						if("-_ad8d" != chunkId) {
```

```diff
~ diff dist/src_bootstrap_js.js dist-lazy-dynamic/src_bootstrap_js.js
10c10
< /*! runtime requirements: __webpack_require__, __webpack_require__.n, __webpack_exports__, __webpack_require__.d, __webpack_require__.* */
---
> /*! runtime requirements: __webpack_require__, __webpack_require__.n, __webpack_exports__, __webpack_require__.e, __webpack_require__.t, __webpack_require__.d, __webpack_require__.* */
19,21d18
< /* harmony import */ var app2_Button__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! app2/Button */ "?ad8d");
< /* harmony import */ var app2_Button__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(app2_Button__WEBPACK_IMPORTED_MODULE_1__);
< 
22a20
> const RemoteButton = react__WEBPACK_IMPORTED_MODULE_0___default().lazy(() => __webpack_require__.e(/*! import() */ "-_ad8d").then(__webpack_require__.t.bind(__webpack_require__, /*! app2/Button */ "?ad8d", 7)));
26c24
< }, /*#__PURE__*/react__WEBPACK_IMPORTED_MODULE_0___default().createElement((app2_Button__WEBPACK_IMPORTED_MODULE_1___default()), null)));
---
> }, /*#__PURE__*/react__WEBPACK_IMPORTED_MODULE_0___default().createElement(RemoteButton, null)));
```

for `src_bootstrap_js.js`, yes, dynamic version contains 3388 chars, while none-dynamic version contain 3342 chars. Save 54 chars before minify. But for main.js, dynamic contains 403403-402422=981 more chars than none-dynamic before minify, because of the section `/* webpack/runtime/create fake namespace object */`.

**Comment by ScriptedAlchemy** [comment]
anything exposed or shared is "split" out. 

dynamic importing the code means you are not downloading it somewhere higher up in the app. IF you load federated code, you **must** have a dynamic import somewhere. I usually do the import bootstrap trick. 

IF you decide not to use react lazy, you are downloading multiple scripts at the import bootstrap async boundary. 

It means you're downloading all those federated imports before your app even starts, or whatever the parent async import webpack can find. More async imports = more efficient loading. 

If you have 1 `import()` and 20 federated `import` or `require` calls. Then you're adding 20 additional scripts to the 1 `import()` call as its the only location in the application where webpack can pause execution and download additional dependencies.
