### ISSUE TITLE
MicrofrontEnd with one build and multiple releases

### ISSUE THREAD

**Issue by danielweil** [module-federation/module-federation-examples#2025]
Thanks for the awesome package. Can't quite believe you implemented this on your own!

I have a question regarding publicPath, PUBLIC_URL env and Devops CI/CD.

I can't find a way to keep only one build pipeline, and inject specific environment variables through release pipelines in azure because when I try to fetch or require a env file from the remote, it can't find its way to the correct public folder. It keeps trying to access the host's.

Do you think it is possible to do it by any means? Keep a single build and make the remote know where to look when trying to get public files?

I think I might get somewhere using startup code example, but I am still not sure.

Thanks!

**Comment by ScriptedAlchemy** [comment]
PublicPath: auto in webpack config
