### ISSUE TITLE
nextjs-ssr example not working in my local enviroment

### ISSUE THREAD

**Issue by makabakabu** [module-federation/module-federation-examples#2030]
I installed @module-federation/nextjs-ssr package and run the nextjs-ssr demo. 
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/13431496/173514844-8cdb0df2-708b-437f-a6df-c52419816bf8.png">
Some issue occurs.

My Node version:  16.4.0

**Comment by ScriptedAlchemy** [comment]
Fixed in RC.1 sorry for that!
