### ISSUE TITLE
How can isolate my styless between shell(angular 12.0.0) and mfe(angularjs v 1.8.0)

### ISSUE THREAD

**Issue by dmlgncn** [module-federation/module-federation-examples#2031]
I m using shadow dom for isolation styles like below:

```
 const template = document.createElement('template');
  template.innerHTML = `
	  <style>	  
		 
		   ${require('!raw-loader!app.css').default}
		  
	  </style>
	  <div class="root"></div>
  `;
  class MfeMain extends HTMLElement {
	  constructor(){
		  super();
			
	  }
	connectedCallback() {
	  const root = document.createElement('main-comp');
	 this.appendChild(root);
	 const mainComp= document.querySelector('angularjs-main');
	const shadowRoot =  mainComp.attachShadow({mode: 'open'});
	shadowRoot.appendChild(document.importNode(template.content, true));
	  angular.bootstrap(root, ['mainModule']);	
	shadowRoot.appendChild(document.querySelector("main-comp"));

	}
  }
  
  customElements.get('angularjs-main') || customElements.define('angularjs-main', MfeMain); 
```

My header is coming from shell. But its dropdown css  is coming from MFE Angularjs with older bootstrap. How can I overcome this issue??

![Screenshot 2022-06-15 124137](https://user-images.githubusercontent.com/35682633/173797999-affa30a9-6296-4183-9fa8-ed64812b30fe.png)

Normally my shell header is like below:

![Screenshot 2022-06-15 124704](https://user-images.githubusercontent.com/35682633/173798188-b13656a2-d49c-4330-b480-fb2947cd1fa8.png)

**Comment by ScriptedAlchemy** [comment]
Use css modules or class prefixing of some sort with postcss. This is a general problem with depending on global styles and implicit imports over explicit imports. 

Not a MF issue, it’s just made obvious by MF
