### ISSUE TITLE
Can host and remote use different React versions? Invalid hooks call error

### ISSUE THREAD

**Issue by jhoward-ts** [module-federation/module-federation-examples#2046]
Hi guys,

I've tried to figure this out myself but I can't find anything explicit. Is Webpack Module Federation meant to support clients using different React versions than their hosts? We're working on a micro frontend setup where the remotes will be owned by different teams, and we would prefer not to lock them all onto the React version used by the host. Naively, trying this results in an `Invalid hooks call` error from React, which makes sense because the client component imports a different React instance than the one rendering the host's tree.

I believe I can get around this by adding a shell around the remote component, such that it has its own React tree rendered into an element provided by the host. But this requires some infrastructure to pass dependencies between the host and the remote.

Is there a simpler, or just a more canonical, way to do this? Given the emphasis on dependency management by WMF I'm surprised not to find it addressed, but maybe I'm just not searching the right places.

**Comment by ScriptedAlchemy** [comment]
Look at the different react versions example. Feel free to pr an update to react v18 and I can take a look at refining the design. I have a few new methods. 

But basically you have to use the adapter pattern and mount app to a ref with seperate react version. If ur running it as a polylith and importing components into other apps under a single tree, only way around it is the adapter pattern to render v18 parts to a ref on the DOM

**Comment by jhoward-ts** [comment]
Got it, thank you!
