### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [module-federation/module-federation-examples#2063]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@7h3h4ckv157) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by ScriptedAlchemy** [comment]
If you’d like to get us steered or help with the setup. I’ll happily use it

**Comment by JamieSlome** [comment]
@ScriptedAlchemy - if you would like you can always point your community to:
https://huntr.dev/repos/module-federation/module-federation-examples/

Otherwise, happy to open a PR for you with an e-mail address of your choice?
