### ISSUE TITLE
het module without imports in react

### ISSUE THREAD

**Issue by gasymov-rustam** [module-federation/module-federation-examples#2064]
Hi, Right now i am working with module federation with react, i got task to get all modules without imports from window - global object, i wilд appreciate if you can help me and explain to me how can i get my modules, thanks a lot

**Comment by ScriptedAlchemy** [comment]
Look up module-federation/enhanced

**Comment by gasymov-rustam** [comment]
> Look up module-federation/enhanced

Thanks a lot!!!!
