### ISSUE TITLE
  Why does this bug appear when I use this vue-cli demo :Reason: ScriptExternalLoadError: Loading script failed.

### ISSUE THREAD

**Issue by flamingoTwoWings** [module-federation/module-federation-examples#2066]
![image](https://user-images.githubusercontent.com/74237022/178094348-5c3f8059-008d-4e42-bb3d-67a3cf14e037.png)

**Comment by cp3hnu** [comment]
You may need to modify the configuration of optimization.splitChunks

```js
optimization: {
  splitChunks: false
}
```

or 
```js
chainWebpack: config => {
  config.optimization.delete('splitChunks')
}
```

**Comment by ScriptedAlchemy** [comment]
Output.PublicPath: auto

**Comment by nuno-barreiro** [comment]
Setting any of those options didn't work in the project I started based on the vue-cli demo.
However, it seems there are further issues related to the vue-cli such as here: https://github.com/vuejs/vue-cli/issues/6823

**Comment by ScriptedAlchemy** [comment]
It's related to webpack trying to load chunks from the wrong url. Usually when public path is set to a relative like / - Audi usually fixes it otherwise you can hard code public path to an absolute location and it should work

**Comment by nuno-barreiro** [comment]
Thanks @ScriptedAlchemy. I've disabled splitChunks and set the publicPath, and it works now. Great!
My vue.config.js now has this settings:

```javascript
publicPath: 'http://localhost:5001',
  transpileDependencies: true,
  configureWebpack: {
    optimization: {
      splitChunks: false,
    },
    plugins: [
      new ModuleFederationPlugin({
        name: "products",
        filename: "remoteEntry.js",
        library: { type: "var", name: "products" },
        exposes: {
          "./ListingComponent": "./src/components/ProductsListing.vue",
        },
      }),
    ],
  },
  devServer: {
    port: 5001,
  },
```

**Comment by ScriptedAlchemy** [comment]
Awesome glad to hear
