### ISSUE TITLE
Unable to lazy load App module of remote Angular app

### ISSUE THREAD

**Issue by RajathVenkatesh** [module-federation/module-federation-examples#2087]
I'm unable to lazy load my MFE app module into my SHELL app both are using angular v13. I get console errors. 

Are lazy loading of app modules of MFEs allowed or does it have to to be a feature module within an app module of the MFE ?

**Comment by ScriptedAlchemy** [comment]
should be allowed, check the git history on the folder and see if some recent updates need to be rolled back. If so, open a pr with the rolled back changes and ill merge it back in.
