### ISSUE TITLE
404 not found on page refresh

### ISSUE THREAD

**Issue by yoav-melamed** [module-federation/module-federation-examples#2093]
**Hi,**
I'm using module federation with dynamic remotes.
When I'm going to my host root and refreshing the page - everything goes well (`http://localhost:8001`)
When I'm going to my host/app and refreshing the page - everything goes well (`http://localhost:8001/app`)

When I'm going to my host/app/internal-page and refreshing the page (`http://localhost:8001/app/internal-page`) - I'm getting a blank white page and I can see in the console the following error:

> GET http://localhost:8001/app/main.33aa404f37f7d91941c3.js net::ERR_ABORTED 404 (Not Found)

Any ideas how I can resolve it?

My files looks like the following:

**mf-host/App.tsx**
```
<Routes>
      <Route path="/mf-app/*" element={<AppContainer app="mf-app" />} />
      ...
</Routes>
```

**mf-host/AppContainer.tsx**
```
const AppContainer = ({ app }: AppContainerProps) => {
  const [system, setSystem] = useState<RemoteApp | Record<string, never>>({});

  useEffect(() => {
    function setApp() {
      const requestedApp = remoteApps.find((a) => a.remote === app);
      requestedApp && setSystem(requestedApp);
    }
    setApp();
  }, [app]);

  return (
    <ErrorBoundary app={app}>
      <System system={system} />
    </ErrorBoundary>
  );
};
```

**mf-app/App.tsx**
```
 <Routes>
      <Route element={<Layout />}>
        <Route path="/" element={<MyAppRoot />} />
        <Route path="/internal-page" element={<InternalPage />} />
        ...
      </Route>
</Routes>
```

**mf-app/webpack.config.js**
```
exposes: {
   "./App": "./src/App",
},
```

**Comment by yoav-melamed** [comment]
I managed to resolve the issue by changing the `publicPath` parameter on each micro-frontend `webpack.config.js` file to:
`publicPath: "http://localhost:<MF_PORT_NUMBER>/"` -> for dev
`publicPath: "/<MF_NAME>/<PATH>/"` -> for production

**Comment by SurjitSahoo** [comment]
I have been stuck on this for weeks!! Thanks
