### ISSUE TITLE
Issue while trying to make module fedration work with next js 

### ISSUE THREAD

**Issue by hkundnani** [module-federation/module-federation-examples#21]
I know that at some point @ScriptedAlchemy will be adding an example of module federation with next js. I wanted to get familiar with it and hence was trying to make it work with next js.
Here is the sample project that I am working on:

https://github.com/hkundnani/nextjs-mfe-demo

It's not much, I was just trying to see if I can load another component into my app but I am getting an error where my main app (app-01) can't find the component (app-02)
I have added a line like this to load the component
`const MyComponent2 = dynamic(() => import("app_02/MyComponent2"));`
but it can't find app-02 and results in error.

**Comment by ScriptedAlchemy** [comment]
I need to write a plugin for next js. Next uses a single runtime chunk which moves all the Federation code into the main runtime.  In reality I need a special runtime created that’s not bound to the normal webpack runtime

**Comment by hkundnani** [comment]
Thanks.. May be I will wait for the plugin then.

**Comment by ScriptedAlchemy** [comment]
You can make a shim for next.js. It’s what I use in production

**Comment by Kinbaum** [comment]
@ScriptedAlchemy Do you have any documentation / resources on how to do this?

**Comment by ScriptedAlchemy** [comment]
https://gist.github.com/ScriptedAlchemy/d386a094832dbd9a04324862d26570e9

window.abtests needs to be replaced with window.[remote]

**Comment by Kinbaum** [comment]
@ScriptedAlchemy Would you happen to have an example of federating pages between two separate next applications? I could see this being very useful where you would have a main shell application with some kind of discovery service that is able to locate different remotes and include their pages. Similar to the way zones work with next js, but truly a single-page experience.

I have a discovery service working for components / routes outside of the next js framework.

**Comment by ScriptedAlchemy** [comment]
all examples are proprietary and in-house to solve legacy WP4 and next js. Nothing demoed in repos mostly because I don’t use WP4 anymore lol. you pretty much paste the gist into a js file and add it as a new entrypoint then change the importAll context around based on what you want to expose to other remotes. You will need to load more than one file tho. 1 the runtime chunk next makes, 2 the remote entry containing the shim along with it dynamic importing all the pages via require.context, ugly but works

**Comment by ScriptedAlchemy** [comment]
Closing these as its a separate series of problems that will arise. There is a next.js example available now
