### ISSUE TITLE
Dynamic exposes apps

### ISSUE THREAD

**Issue by gasymov-rustam** [module-federation/module-federation-examples#2103]
Hi, I was using dynamic example for get all aps in my host using function loadcomponent(low level api). Now i need to send from my host what i want to exposes in my child apps using global object window or in some other way. its meant that i want dynamic exposes and send components on demand or according to the configuration

Thanks a lot.

**Comment by ScriptedAlchemy** [comment]
Look at module-federation/enhanced to see how you can do that. 

I’d also track what remotes you have so you can loop over all known remotes and call the expose list from them all
