### ISSUE TITLE
lerna: command not found

### ISSUE THREAD

**Issue by alejandronanez** [module-federation/module-federation-examples#218]
It seems that `lerna` needs to be installed globally in order to run any of the examples.

![](https://cdn.zappy.app/d29a74c9f73119b5a0acfacae42d0bae.png)

I'd expect this to not happen because I see `lerna` being present in `/node_modules/.bin/` 

Installing `lerna` globally fixes the issue - even though this is not ideal.

**Comment by alejandronanez** [comment]
I was thinking about adding a prefix for all the examples, go from `sidecar` to something like this `@mf-examples/sidecar`. 

I'm not really sure if this is out of scope though or if it's something you want to do.

Looking forward to your answer, happy to give a hand with this issue.

**Comment by ScriptedAlchemy** [comment]
yarn add lerna or globally install it

**Comment by ScriptedAlchemy** [comment]
not sure what the fix would be but happy to take a PR

**Comment by alejandronanez** [comment]
Alright, ~I'll work on something in the next few days!~, there you go https://github.com/module-federation/module-federation-examples/pull/252
