### ISSUE TITLE
Can we have implementation support for Vue ?

### ISSUE THREAD

**Issue by anish2690** [module-federation/module-federation-examples#219]
I have tried to put together a demo but no luck something wrong while exposing component  https://github.com/anish2690/mfe-webpack-demo-vue

**Comment by ScriptedAlchemy** [comment]
Your current repo is too broken to run. one of the apps does not resolve main.js scripts.

**Comment by anish2690** [comment]
@ScriptedAlchemy repo is updated now it works perfectly with Webpack module federation 😍

**Comment by ScriptedAlchemy** [comment]
Looking forward to your pull request!

**Comment by anish2690** [comment]
https://github.com/module-federation/module-federation-examples/pull/259
