### ISSUE TITLE
NG0303: Can't bind to 'ngIf' since it isn't a known property of 'div' 

### ISSUE THREAD

**Issue by varunpandurangaiah** [module-federation/module-federation-examples#2194]
NG0303: Can't bind to 'ngIf' since it isn't a known property of 'div' (used in the 'HomeComponent' component template).
If the 'ngIf' is an Angular control flow directive, please make sure that either the 'NgIf' directive or the 'CommonModule' is a part of an @NgModule where this component is declared.

MFE- Exposed - HomeModule
```
imports: [
    CommonModule,
    HomeRoutingModule,
    AngularMaterialModule,
    ReactiveFormsModule,
    FormsModule,
    SharedComponentsModule,
    LanguageTranslateModule,
    NumericOnlyModule,
    NgSelectModule,
    ToolTipmatModule

  ],
```

While Trying in shell Application giving this error

MFE is an Angular 13

Shell is an Angular 14

**Comment by ScriptedAlchemy** [comment]
two different versions of angular, what would you expect - angular needs to be a singleton

**Comment by varunpandurangaiah** [comment]
Got it, made the same version it’s working now!! Closing it.
