### ISSUE TITLE
How to check the end result of my bundle.

### ISSUE THREAD

**Issue by gasymov-rustam** [module-federation/module-federation-examples#2199]
Hi, I want to say thank you in advanceю
I have some questions about module federation. I use this wonderful technology, I have host-app and 10 child-apps. In all child-apps 
we have same dependencies from package.json 
{
"@apollo/client": "^3.6.2",
    "@emotion/react": "^11.9.3",
    "@emotion/styled": "^11.9.3",
    "@mui/material": "^5.8.4",
    "@ng/infra-components": "latest",
    "@ng/infra-map": "latest",
    "@reduxjs/toolkit": "^1.8.2",
    "i18next": "^21.8.14",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-i18next": "^11.18.3",
    "react-intl": "^6.0.3",
    "react-redux": "^8.0.2"
}

All of them i send to host-app from all of child-app. I use shared module in my plugin module-federation.
In my hos-app a get all of my childs using dynamic remotes, didnt write anything in my webpack.config in module federation - remotes object.

I have some questions: 
 - How can i check bundle when all childs-app will load?
 - Will i Have all dependencies that got from child-app in my host? Its means that in host-app i will have 10 copies @emotion/react etc..?
 - How can I write childs-dependencies that i didnt get them in my host-app, bacause of in host app we have same dependencies and i wont that childs-apps will use dependencies from host app...

Thanks a lot!!

**Comment by ScriptedAlchemy** [comment]
if webpack is not aware, dynamic remotes will only add the dependencies or be able to participate in sharing once they are loaded. 

If you want to fill share scope for all right away, load and initialize all remotes at once up front.
