### ISSUE TITLE
ChunkLoadError in appshell (Host)

### ISSUE THREAD

**Issue by Ghayour-vialogic** [module-federation/module-federation-examples#2200]
Hello everyone, I have multiple micro-frontends hosted in appshell. I am using module federation. However, I have encountered very strange problem. I have imported 3 micro frontends in appshell, they were working fine for some time. currently, the appshell throughs an error Uncaught (in promise) ChunkLoadError: Loading chunk vendors-node_modules_react_index_js failed. however, no change is made the same code and deployment was working fine. any idea?

**Comment by ScriptedAlchemy** [comment]
try splitChunks: false or splitChunks.chunks = 'async' not 'all' 

make sure publicPath: auto is set
