### ISSUE TITLE
Collision with components name

### ISSUE THREAD

**Issue by AndreiSoroka** [module-federation/module-federation-examples#2201]
I have component `HomeView.vue` in host and remotely

And when I load `HomeView.vue` remotely then MF overrides local `HomeView.vue`

![ezgif-2-29813dca47](https://user-images.githubusercontent.com/6079139/185634928-51364c48-feac-41d0-9eeb-0fd32451fc8e.gif)

Reproduce https://github.com/AndreiSoroka/mf-reproduce-collision-names

**Comment by ScriptedAlchemy** [comment]
make the name unique so there's no collisions.
