### ISSUE TITLE
Do shared dependencies respect alias?

### ISSUE THREAD

**Issue by csvan** [module-federation/module-federation-examples#2241]
Assume I have a shared dependency `@mui/utils`:

```
'@mui/utils': { requiredVersion: '^5.10.2' },
```

In the same Webpack setup, assume that I also have an alias for this import:

```
resolve: {
  alias: {
    '@mui/utils': '@mui/utils/modern',
  },
```

Now, will this dependency still be correctly shared, e.g. will the shared imports be made from the `/modern` path?

**Comment by ScriptedAlchemy** [comment]
I think so, worth testing to see

**Comment by ScriptedAlchemy** [comment]
NormalModuleReplacementPlugin will definitely work
