### ISSUE TITLE
umd

### ISSUE THREAD

**Issue by zhangHongEn** [module-federation/module-federation-examples#2245]
For example, I have a relatively large "AMD || system" project of "react || vue". If MF is used for new components without reconstruction, will it be considered to support it

In this case, shared needs to support UMD

**Comment by zhangHongEn** [comment]
I need to use it this way at present. I implemented an example

https://www.npmjs.com/package/usemf

Can I make a pull request for the examples warehouse? Or as a third party alternative

**Comment by ScriptedAlchemy** [comment]
Yeah please PR an example - you should not need to use third party or shim share scope though - remote can be library.type = 'umd'
