### ISSUE TITLE
Next.js support now open-source

### ISSUE THREAD

**Issue by ScriptedAlchemy** [module-federation/module-federation-examples#2253]
I've made the decision to release all my work around next.js as open source. 

https://twitter.com/scriptedalchemy/status/1567253027312246784?s=46&t=Sa4bhIDZI1i-q2GgYNGQuA

Work is needed to fold the SSR system into a single plugin. There is a open PR with the progress so far. 

Contributions are much appreciated. The sidecar design will no longer be maintained and the existing SSR plugin which uses sidecars will be open, but not published as everyone and all resources should go towards the child compiler system to support both CSR and SSR. 

Nextjs-MF has been re published to npm and currently supports CSR while SSR sits in a pr till remaining issues are resolved. 

GitHub sponsors are also welcome 🙏

**Comment by ScriptedAlchemy** [comment]
SSR support is available now, has been for a while via the plugin. 

Working on RSC but that's a bit complicated. Next 13 should work with current release.

**Comment by revskill10** [comment]
Hi @ScriptedAlchemy , would love to know if Next 13 with Server Component is supported yet ?

**Comment by ScriptedAlchemy** [comment]
@revskill10 not yet

Ive not focused on it in 2023, it will likely be one of the next things i look into after i release delegate module support. 

Last time i looked at it- i got stuck, but since then mentally figured it out. 

The main complexity is the module you get is different depending on who imported it.

If the parent file is not "use client" then we need to load a src version of the module, if it is use client, then load the normal component. So exposed modules have to be two things at the same time depending on how the consumer might use it

**Comment by starryxjl** [comment]
Hi，if I have a regular react project that is not nextJs, It just support react component, and it is exposed by regular module federation method。I have another nextJS project， Can I use nextjs-mf in this project so that to use the remote react component。
