### ISSUE TITLE
remoteType and library

### ISSUE THREAD

**Issue by zhangHongEn** [module-federation/module-federation-examples#2256]
Is remotetype inherently available? Or do you need to integrate a third-party library to use it?

I tried according to the official demo, but it failed

You can see the demo below
https://stackblitz.com/edit/github-faw5we?file=app2/webpack.config.js

**Comment by ScriptedAlchemy** [comment]
Check the console in browser. no remote entry is loaded or the origin to load it is incorrect.
Try it locally

**Comment by zhangHongEn** [comment]
> Check the console in browser. no remote entry is loaded or the origin to load it is incorrect. Try it locally

I have tried it in the local environment, but also did not send a network request. I can only succeed by using "remotetype": "script". I have tried many configurations, and I am not sure what is wrong

**Comment by ScriptedAlchemy** [comment]
open a git issue on webpack.

**Comment by zhangHongEn** [comment]
Thank you for your answers
