### ISSUE TITLE
[feature request] Improve DX

### ISSUE THREAD

**Issue by Jordan-Gilliam** [module-federation/module-federation-examples#227]
#### 1 I'm frustrated when dealing with the example naming convention
> **If the example relies on an external library**

- ex. [with-xstate](https://github.com/vercel/next.js/tree/canary/examples)
- ex. [wp5-recoil](https://github.com/jherr/wp5-recoil)

> **If the example is related to a module-federation pattern**
- ex. [pattern-bi-directional](https://github.com/module-federation/module-federation-examples/tree/master/bi-directional)

> **If the example is related to a rendering/hydration pattern**
- ex. [ssr-with-express-react]
- ex. [ssg-with-hapi-react]

#### 2 I'm frustrated when having to deal with proprietary code
> proprietary code should be moved to a separate module-federation repo
- This would reduce maintenance complexity in the examples repo + improve DX
- The readme could mention proprietary services similar to how mf book is mentioned

#### 3 I'm frustrated when creating an issue or feature request
> Create issue templates
- Necessary to reduce complexity as this repo continues to scale

**Comment by Jordan-Gilliam** [comment]
@ScriptedAlchemy I don't mind implementing the changes for problem 1 and 3 and can create separate issues. Wanted to gather thoughts first 😃

**Comment by ScriptedAlchemy** [comment]
Will GLADLY accept a PR
