### ISSUE TITLE
Some problems occurred when using ModuleFederationPlugin and DllReferencePlugin at the same time

### ISSUE THREAD

**Issue by pika1217** [module-federation/module-federation-examples#2294]
I use ModuleFederationPlugin to shared a react module, but some lib such as react、react-dom、redux and so on was builded by DllPlugin;   

webpack.pub.config
![image](https://user-images.githubusercontent.com/29992875/190669212-38fb9667-f86f-4508-8a60-7388e28fd1c3.png)

webpack.dll.config
![image](https://user-images.githubusercontent.com/29992875/190667842-1b2c820d-49d5-43ed-a038-e0abda99b4cb.png)

remoteEntry.js 
![image](https://user-images.githubusercontent.com/29992875/190668289-02874460-1c94-45cf-b760-b52ce459e945.png)

in the remoteEntry.js , the variable of dll entry name `vendor` was inserted ,  There is no doubt that an error will be reported when the remoteEntry.js file is executed, what should i do for it ? anyone can help me? please！！

**Comment by alexanderkhivrych** [comment]
I was trying to use DLL with MF. And it was working; shared dependencies that use DLL References were delegated. @pika1217

**Comment by ScriptedAlchemy** [comment]
why would you use DLL plugin at all? `shared` effectively replaced the need for DLL

**Comment by pika1217** [comment]
> I was trying to use DLL with MF. And it was working; shared dependencies that use DLL References were delegated. @pika1217

You can use DLL plugin and MF plugin at the same time without doing any processing? The dll assets are inserted into the entry html and cannot be loaded in the host, so I still don't understand why the error will not be reported. Would it be convenient for you to show relevant code examples?

**Comment by pika1217** [comment]
> I was trying to use DLL with MF. And it was working; shared dependencies that use DLL References were delegated. @pika1217

You can use DLL plugin and MF plugin at the same time without doing any processing? The dll assets are inserted into the entry html and cannot be loaded in the host, so I still don't understand why the error will not be reported. Would it be convenient for you to show relevant code examples?

**Comment by pika1217** [comment]
> why would you use DLL plugin at all? `shared` effectively replaced the need for DLL

Before using MF, the system used DLL plugin to optimize performance. Now it is faced with the scenario of using two plugins at the same time. I don't know if there is a problem with my use

**Comment by pika1217** [comment]
> why would you use DLL plugin at all? `shared` effectively replaced the need for DLL

Before using MF, the system used DLL plugin to optimize performance. Now it is faced with the scenario of using two plugins at the same time. I don't know if there is a problem with my use

**Comment by ScriptedAlchemy** [comment]
Don't use DLL with federation. Rather mark them as externals manually and use DLL only for the legacy application
