### ISSUE TITLE
How to force using shared deps from host instead of remotes

### ISSUE THREAD

**Issue by huygn** [module-federation/module-federation-examples#2311]
This is a relay of my original question from Zack's Slack workspace:

> so I faced an issue with `react`/`react-dom` shared _singleton_ version being loaded from deployed remotes which is always `react.production.min` version, this is ok for prod build but during local dev mode I'd expect to have development ver of React loaded for debugging purpose. How to force Webpack to use "react" dep from host?

Here is Zack's (awesome) solution:
> You can loop over share scope and mark host's react as `loaded = 1`. Loop over shared packages from host and mark them as loaded so host is always preferred because Webpack thinks it's loaded even if it's not.
That trick would be the most “proper” implementation.

[Example of marking host's dep `loaded = 1` from nextjs-mf](https://github.com/module-federation/nextjs-mf/blob/e411c15b3e36f305a2583b7bca2d8c21038773bc/src/internal.js#L98-L99). It will require using `promise new Promise` remote syntax.

Note that for nextjs the name is always `'_N_E'` so for normal case you'd write name of the shared dep .e.g `o.from === 'react'` instead.

Thanks again Zack!

**Comment by malcolm-kee** [comment]
Another solution (which is also shared by @ScriptedAlchemy via [twitter](https://twitter.com/ScriptedAlchemy/status/1553253872193310720))

When generating production bundle for app that is only meant to be used as remote, set the version as below:

```
{
  shared: {
    'react': {
       singleton: true,
       requiredVersion: '*',
       version: '0'
    }
  }
}
```

For local development and host you set the version as the `package.json` version, then it will always use the local/host version.

**Comment by rkistinger** [comment]
@ScriptedAlchemy @malcolm-kee I think the `version: '0'` approach is overridden by `next-mf` when trying to use a remote's version unfortunately. Opened an issue about this but let me know if you see differently https://github.com/module-federation/universe/issues/714

**Comment by ScriptedAlchemy** [comment]
You can now use resolveShare hook from module-federation/runtime package to control sharing etc. or look in runtime-plugins folder here
