### ISSUE TITLE
RemoteEntry.js Cache disabling ?

### ISSUE THREAD

**Issue by erkanisuf** [module-federation/module-federation-examples#2339]
I have my remote app's bundle deployed to aws s3 form where i get the remoteEntry.js via CloudFront. But any new changes to the bundle i make are not applied to the host app due to caching issue. I have put all the required no cache tags to the .html but it doesn't fix the issue. Is there any example/solution for this kind of case?

**Comment by otoming** [comment]
don't cache remoteEntry.js

**Comment by ScriptedAlchemy** [comment]
Query string date.now on the end of remotes. Or use https://Medusa.codes which supports hashing remote entries
