### ISSUE TITLE
How to handle the react new jsx transform api

### ISSUE THREAD

**Issue by adajoy** [module-federation/module-federation-examples#2342]
In the demo react-hmr, there is a container called libs which provides common libs including React for other containers. React introduced new jsx transform which automatically import jsx method from 'react/jsx-runtime'. Since React isn't installed locally, I got an compile error **_Can't resolve 'react/jsx-runtime'_**

I've tried add an webpack alias but it seems not working.

**Comment by adajoy** [comment]
ps:  I'm not using the config called shared because there may be different versions of React in other containers.

**Comment by ScriptedAlchemy** [comment]
You'd have to supply jsx runtime. Update to v17. It has good interop with v18

**Comment by adajoy** [comment]
I mean I am using the jsx runtime, which means the compiled code will contain `import 'react/jsx-runtime'`, but react is not installed locally, and that will lead to an error. 
Say the name of my remote lib is libs, then `import 'libs/react/jsx-runtime'` should be the correct code.

**Comment by ScriptedAlchemy** [comment]
id use shared to distribute it, you can look at the "multiple react versions" example
 What I usually do is add react/jsx-runtiem to shared directly so if a consumer needs it - its there
