### ISSUE TITLE
react-hmr project host not reload when remotes change

### ISSUE THREAD

**Issue by UNDERCOVERj** [module-federation/module-federation-examples#2346]
host app address: `http://localhost:3000`
remotes app address: `http://localhost:3001`

when I change remotes app code，`http://localhost:3001` can hot reload, but `http://localhost:3000` not reload

**Comment by ScriptedAlchemy** [comment]
Not possible

**Comment by UNDERCOVERj** [comment]
> Not possible

why not support it
