### ISSUE TITLE
Typescript react  - Cannot find module '....' or its corresponding type declarations

### ISSUE THREAD

**Issue by erkanisuf** [module-federation/module-federation-examples#2347]
I got this `tsremote-mf-decl.d.ts` file where i declare the remote modules.
```
declare module "SETTINGSMICRO/settingsView" {
    import {VFC} from 'react'
    import {IUserData} from '../../redux/action-types/userTypes';

    interface SettingsViewMicro {
        language: string;
    }

    const SettingsViewMicro: VFC<SettingsViewMicro>
    export default SettingsViewMicro
}
```

But i get this error message in my editor(Webstorm)  from TS .
`Cannot find module 'SETTINGSMICRO/settingsView' or its corresponding type declarations`

i import the component as:
`import SettingsViewMicro from 'SETTINGSMICRO/settingsView';`

Any idea how to fix this? Currently i am using `//@ts-ignore` but was hoping for better solution

**Comment by alex-vukov** [comment]
Shouldn't the import statements in the .d.ts file be on top of the file and outside of the declare {}?

**Comment by erkanisuf** [comment]
I tried that but it didn't work. Now i moved the decl file in the root of /src folder and it works fine in Webstorm editor but gives wierd error in my colleges editor which is VSCode.

**Comment by ScriptedAlchemy** [comment]
are you using module-federation/typescript

**Comment by erkanisuf** [comment]
I have tried with the plugin but i cant make it work as i get error:
`[webpack-cli] TypeError: FederatedTypesPlugin is not a constructor
    at Object.<anonymous> (/Users/skenariolabs/Desktop/skenariolabs/skenarios-banking-frontend/webpack/webpack.dev.js:60:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at module.exports (/Users/skenariolabs/Desktop/skenariolabs/skenarios-banking-frontend/webpack/webpack.config.js:6:20)
    at loadConfigByPath (/Users/skenariolabs/Desktop/skenariolabs/skenarios-banking-frontend/node_modules/webpack-cli/lib/webpack-cli.js:1439:37)
    at async Promise.all (index 0)
`

My webpack plugins look like this:
```

plugins: [
		new HtmlWebpackPlugin({
			inject: true, template: path.resolve(__dirname, '../public/ui/index.html'),
			favicon: path.resolve(__dirname, '..', './public/ui/favicon.ico'),
		}),
		new ReactRefreshWebpackPlugin(),
		new ModuleFederationPlugin(
			{
				name: 'BANKING',
				filename:
					'remoteEntry.js',
				remotes: {
					...remotes
				},
				shared: {
					...deps,
					'mapbox-gl': {
						singleton: true,
						version: deps['mapbox-gl'],
					},
					'luxon': {
						singleton: true,
						version: deps['luxon'],
					},

				}
			}
		),
		new FederatedTypesPlugin()
	],

```

**Comment by pavandv** [comment]
@erkanisuf How are you importing `FederatedTypesPlugin`? Default or named imports?

Regarding your second problem, Typescript can't read your custom declarations unless you ask it to read it.

I would like to see your `tsconfig.json` file to understand how your project is configured.

**Comment by erkanisuf** [comment]
I checked the readme example of the TS plugin and import it as :
`const FederatedTypesPlugin = require('@module-federation/typescript')`

Here is my `ts.config `
```

{
  "compilerOptions": {
    "paths": {
      "*": [
        "./@mf-typescript/*"
      ]
    },
    "target": "ES5"
    /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */,
    "module": "ESNext"
    /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */,
    "moduleResolution": "node"
    /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    /* Type declaration files to be included in compilation. */,
    "lib": [
      "DOM",
      "ESNext"
    ],
    /* Specify library files to be included in the compilation. */
    "jsx": "react-jsx"
    /* Specify JSX code generation: 'preserve', 'react-native', 'react' or 'react-jsx'. */,
    "noEmit": true
    /* Do not emit outputs. */,
    "isolatedModules": true
    /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */,
    "esModuleInterop": true
    /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */,
    "strict": true
    /* Enable all strict type-checking options. */,
    "skipLibCheck": true
    /* Skip type checking of declaration files. */,
    "forceConsistentCasingInFileNames": true
    /* Disallow inconsistently-cased references to the same file. */,
    "resolveJsonModule": true
    // "allowJs": true /* Allow javascript files to be compiled. Useful when migrating JS to TS */,
    // "checkJs": true /* Report errors in .js files. Works in tandem with allowJs. */,
  },
  "include": [
    "src/**/*",
    "index.d.ts",
    "src/*.d.ts"
  ],
  "collabee/common": [
    "d.ts"
  ]
}
```

![Screenshot 2022-11-04 at 9 27 50](https://user-images.githubusercontent.com/63913743/199916877-d3635cf3-edc2-4769-918a-adcd2b548ad4.png)

**Comment by pavandv** [comment]
I'm guessing `paths` in your ts config might be messing with your type system. Try removing that and see if it resolves the issue.

**Comment by erkanisuf** [comment]
Removing paths didn't help .
But i noticed something, so i got this code in `decl.d.ts`

```
   import { VFC } from 'react'
declare module "SETTINGSMICRO/settingsView" {
 import { IUserData, OrganisationTheme } from "./redux/action-types/userTypes";

    interface SettingsViewMicro {
        portfolioId: number;
        organizationId: number;
        translation: (translation: string) => string;
        toaster: {
            error: (l: string) => void;
        }
        user: IUserData;
        language: string;
        defaultTheme: OrganisationTheme;
        currentOrganisationTheme: OrganisationTheme;
        defaultChartColors: Array<string>;
        defaultEnergyChartColors: Array<string>
    }

    const SettingsViewMicro: VFC<SettingsViewMicro>
    export default SettingsViewMicro
}

declare module 'ESGCOMPONENTSVIEW/EsgPortfolioView' {
    import { VFC } from 'react'

    interface EsgPortfolioViewMicro {
        componentType: "FINANCE" | "REAL_ESTATE";
        portfolioId: number;
        translation: (translation: string) => string;
        abbreviate: (num: number, unit?: string | null, displayUnit = true) => string;
        toaster: {
            error: (l: string) => void;
        }
        navigate: (url: string, object) => void;
    }

    const EsgPortfolioViewMicro: VFC<EsgPortfolioViewMicro>
    export default EsgPortfolioViewMicro
}
```

then i moved `import { VFC } from 'react'` inside the declare module and now seems that TS doesn't scream for the `SettingsViewMicro` but for `EsgPortfolioViewMicro` it keeps screaming, can it be because each of them must be added to separated file?

**Comment by erkanisuf** [comment]
The fix was to create seperated declaration file for each component.
