### ISSUE TITLE
How to omit producing "main.js" for the remote?

### ISSUE THREAD

**Issue by aleckravets** [module-federation/module-federation-examples#2348]
I dont need the "main.js" entry point to be produced, all I need is "remoteEntry.js"  because I dont plan to use remote as a stand alone app - only as a source for loading modules dynamically.

How do I tell webpack to skip building "main.js" entry point?

**Comment by alex-vukov** [comment]
remoteEntry.js is just an index containing references to the bundled files of your application while main.js contains the actual bundled code. You can't remove it.

**Comment by ScriptedAlchemy** [comment]
Just make the main entrypoint be a file that exports nothing. You can delete it. It's not used. But webpack will always emit a main file as a side effect
