### ISSUE TITLE
Multiple react-router versions 5 & 6

### ISSUE THREAD

**Issue by gc23** [module-federation/module-federation-examples#2359]
Hello,

I am looking for an implementation suggestion for the following:

The problem is whether it is possible to mix different react-router-dom versions, specifically 5 & 6 when there are breaking changes in the following setup.

The app shell is using v5 and uses <BrowserRouter> at the top level while also having local routes and <Link>

The remote app uses v6 and uses <BrowserRouter> at the top level while also having local routes and <Link>

The remote app exposes its routes and modules/components that use <Link>. 

Straightaway this setup does not work with the following error:

`Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

The above works fine if both apps use identical router versions.

**Comment by ScriptedAlchemy** [comment]
Router must be a singleton. Singletons need to be on the same version across the board. Otherwise you need to write some kind of adapter module to proxy context from one version to another or switch to mounting apps onto refs.
