### ISSUE TITLE
There is a slot attribute error in webpack & vite

### ISSUE THREAD

**Issue by dlpuzhangyue** [module-federation/module-federation-examples#2364]
In the "vue3-demo-federation-with-vite" example, if the slot property is included in the webpack-side, the error "TypeError: Cannot read properties of null (reading 'isCE')" will be reported.
Is there any good solution here please?
![image](https://user-images.githubusercontent.com/29819173/199201258-e4f878f5-0a29-4a8d-bef8-f3d493012dd2.png)

**Comment by ScriptedAlchemy** [comment]
Send a pr or use the new vite federation plugin

**Comment by dlpuzhangyue** [comment]
> Send a pr or use the new vite federation plugin
#
pr already send;

local use @originjs/vite-plugin-federation@1.1.10，problem still exists

#2370

**Comment by ScriptedAlchemy** [comment]
I don't know if that's the native federation plugin. Look at its source and see if it's using softarc native federation under the hood
