### ISSUE TITLE
CSS Isolation at the host application level

### ISSUE THREAD

**Issue by MichaelJHaywood** [module-federation/module-federation-examples#2371]
In the [css-isolation](https://github.com/module-federation/module-federation-examples/tree/master/css-isolation) project it shows isolation using the Shadow DOM. This works by remote applications wrapping their content in a Shadow DOM and then overriding the `style-loader` to insert the styles inside the Shadow DOM instead of the head of the host application. 

The problem with this method is that every remote application will need to implement this.  It would be great if this could be implemented within the host application so it only has to be implemented once instead of within every remote application. 

Would it be possible for the shadow DOM to be created within the host application and for the host to move the remote applications styles into it?

**Comment by ScriptedAlchemy** [comment]
Pretty sure there's a css isolation example specifically for this. We also have some code under module federation utilities repo

**Comment by MichaelJHaywood** [comment]
I can only see [css-isolation](https://github.com/module-federation/module-federation-examples/tree/master/css-isolation) and [CSSBoundary](https://github.com/module-federation/utilities/blob/main/runtime/cssBoundary/README.md). 

These will isolate the CSS but it means that each remote application will need to wrap itself in a shadow DOM and copy the styles inside it. 

If it is possible to do this at the host level it would be great but I'm not sure? It would reduce code duplication and lower the risk of a remote application being configured incorrectly.

**Comment by ghost** [comment]
> Pretty sure there's a css isolation example specifically for this. We also have some code under module federation utilities repo

Could you please share the link?

**Comment by ScriptedAlchemy** [comment]
Ahh it depends on shadow DOM. Isolating global styles isn't possible, you'd need to use css modules and hashes for classes or something to prevent conflicts

**Comment by ChenReuven** [comment]
> Ahh it depends on shadow DOM. Isolating global styles isn't possible, you'd need to use css modules and hashes for classes or something to prevent conflicts

@ScriptedAlchemy  how this answer relevant to the question that @MichaelJHaywood ask?
he want that the host will create dynamicly a wrapper for shadow dom for remotes application.
which mean implemnt one wrapper

**Comment by ScriptedAlchemy** [comment]
Id take a look at the new runtime plugin hooks and see if any of those lifecycles can help. 
Thats the only thing capable of doing something centrally to all, via registerGlobalPlugin
