### ISSUE TITLE
ComponentMap not being used in examples

### ISSUE THREAD

**Issue by olitomlinson** [module-federation/module-federation-examples#2378]
I see that this `ComponentMap` is only ever being `set` in the code - is this ComponentMap necessary?

https://github.com/module-federation/module-federation-examples/blob/2a4120fd90a9fae8281a702f5aad8499540f83d8/advanced-api/dynamic-remotes/app1/src/App.js#L77

**Comment by ScriptedAlchemy** [comment]
Probably not needed or just not implemented to reference cache. So less optimal

**Comment by ScriptedAlchemy** [comment]
can be removed
