### ISSUE TITLE
Declare global variables for remote (vue2) in shell (vue3)

### ISSUE THREAD

**Issue by saicharan965** [module-federation/module-federation-examples#2446]
Hey there, I'm using your **vue2tovue3** function to convert my vue-2 components to vue-3. I saw that we are creating a new Vue instance everytime we are importing a component into shell.
I want to delcare a global variable for vue-2 component in vue-3's vue2tovue3-function. 
Is this possible ? if yes , then can you please explain me how to do it ?
I want to use a global variable for translations using Vue-i18n package

for reference : 
![image](https://user-images.githubusercontent.com/87169322/202643278-42165848-913a-494c-8b82-d4bb9728d214.png)

**Comment by sumanth4690** [comment]
following with the same problem
