### ISSUE TITLE
can use cache when use external-remotes-plugin

### ISSUE THREAD

**Issue by AboyL** [module-federation/module-federation-examples#2449]
When I use the persistent cache while using the external-remotes-plugin plugin, the persistent cache cannot be generated correctly。

example
```
    new ModuleFederationPlugin({
      name: 'test',
      filename: 'remoteEntry.js',
      remotes: {
        antd: `antd@[window.antdUrl]/remoteEntry.js`,
      },
      shared: {
        react: {
          singleton: true, // only a single version of the shared module is allowed
        },
        "react-dom": {
          requiredVersion: deps["react-dom"],
          singleton: true, // only a single version of the shared module is allowed
        },
      },
    }),
    // Caching cannot be generated using this plugin
    new ExternalTemplateRemotesPlugin(),
```
node_modules\.cache\webpack\default-development can`t generate。
If I comment this line of code, then it generates。
i have a example  in
https://github.com/AboyL/demo/tree/main/dynamic-remotes

you can implement 
> yarn && yarn start
reproduce this bug。

The reason for this bug is because there is no No serializer registered for RawSource。

you can open dynamic-remotes\node_modules\webpack\lib\serialization\ObjectMiddleware.js and add change
```
			write(value, key) {
				try {
					process(value);
				} catch (e) {
					if (e !== NOT_SERIALIZABLE) {
						if (hasDebugInfoAttached === undefined)
							hasDebugInfoAttached = new WeakSet();
						if (!hasDebugInfoAttached.has(e)) {
							e.message += `\nwhile serializing ${stackToString(value)}`;
							hasDebugInfoAttached.add(e);
						}
					}
					throw e;
				}
			},
```
to
```
			write(value, key) {
				try {
					process(value);
				} catch (e) {
                                         console.error('err',err);
					if (e !== NOT_SERIALIZABLE) {
						if (hasDebugInfoAttached === undefined)
							hasDebugInfoAttached = new WeakSet();
						if (!hasDebugInfoAttached.has(e)) {
							e.message += `\nwhile serializing ${stackToString(value)}`;
							hasDebugInfoAttached.add(e);
						}
					}
					throw e;
				}
			},
```

find this error

**Comment by ScriptedAlchemy** [comment]
Use promise new promise instead of dynamic remotes plugin

**Comment by AboyL** [comment]
> 

Thank you. I've solved the problem

**Comment by ScriptedAlchemy** [comment]
Yes but you shouldn't use external remotes plugin. Rather use promise new promise or look at module-federation/utilities

**Comment by mortargrind** [comment]
@ScriptedAlchemy Can you elaborate on "_you shouldn't use external remotes plugin_" part? Is it deprecated? This documentation does not mention anything: https://module-federation.io/docs/en/mf-docs/0.2/dynamic-remotes/#advantages-and-limitations-2. Is there any plans to fix caching issue for the external remotes plugin?

**Comment by ScriptedAlchemy** [comment]
Doc site is being rewritten.

do something like this: https://github.com/module-federation/universe/issues/2125
