### ISSUE TITLE
[Question] Reloading versioned dynamic remotes in React

### ISSUE THREAD

**Issue by pcostanz** [module-federation/module-federation-examples#2477]
Hello @ScriptedAlchemy!

I have an implementation of a `DynamicRemoteLoadable` component that fetches remoteEntry files, and renders a React component exposed via Module Federation. We've built an API layer in front of our requests for remoteEntry files that allows us to control when new versions of a microfrontend are 'released' to production by having the API return which remoteEntry the dynamic remote loadable component should fetch, and are currently working on building mechanisms to allow our UIs to preview these releases before they're promoted in this versioning gateway.

Example: https://platform.dash.staging.cloudflare.com/remotes?remoteName=uiplatformdemo
Returns: ```{"remoteName": "uiplatformdemo", "remoteUrl": "https://4e4579d4.cf-dash-remote-uiplatformdemo.pages.dev/remoteEntry.js"}```.

In this case, new versions of this remoteEntry are differentiated by the hash the precedes the path on the pages project.

Our Module Federation DevTool around rendering remotes can fetch a list of previous deployments from our API in order for us to be able to list deployment hashes and do things like dynamically change which version of a remote is rendered for a user (potential usage being dynamically rolling back a deployment that is throwing UI errors to a previous version in real time, but also just for dev troubleshooting and being able to debug releases and preview versions by quickly toggling between them). Right now this works just fine for hard reloads of the entire app, but I'm looking for a way to allow this to work dynamically.

<img width="382" alt="Screenshot 2022-12-05 at 10 46 30 AM" src="https://user-images.githubusercontent.com/2976552/205713074-b8d586a2-3dda-4ba9-9338-51c55fcbd615.png">
(Clicking the left and right arrows will change the hash and fetch a new remoteEntry file).

The issue I'm running into right now is basically this:

When attempting to toggle between two different versions of a deployed remote application without reloading the page, our `useDynamicScript` implementation appropriately goes and fetches the new hashed remoteEntry file, but our mechanism for `loadComponent` does not seem to be returning the new module from the container that is attached to the window. It just re-renders the previously loaded module.

Here are two deployed different versions of a remoteEntry for reference.

Version 1: https://37965885.cf-dash-remote-uiplatformdemo.pages.dev/remoteEntry.js
Version 2: https://675dc7b4.cf-dash-remote-uiplatformdemo.pages.dev/remoteEntry.js

One thing I've noted is that, since these are the same remote but different deployments, their global variable name is the same for both files.

Is there some way to adjust how we load the module from the remote container to accommodate this type of functionality? I've thought about potentially adding hashes to the federated module names, but was hoping there would be some way to nuke the reference to the previously loaded module in Webpack to be able to keep the names the same across deployments and reduce the complexity of our build/deploy needing to pash hashes around.

`loadComponent`
```
const loadComponent = (remoteName: string, module: string) => {
  return async () => {
    await __webpack_init_sharing__('default');
    const container = window[remoteName];
    await container.init(__webpack_share_scopes__.default);
    const factory = await container.get(module);
    const Module = factory();
    return Module;
  };
};
```
`useDynamicScript`
```
/**
 * getRemoteEntryUrl - gets the remote entry URL from the remote
 * versioning worker. If there is a preview remote, the remote
 * entry URL is modified with the preview hash instead.
 */
const getRemoteEntryUrl = async (
  remoteName: string,
  previewHash?: string,
  devRemoteUrl?: string
) => {
  DRLLog(`useDynamicScript: getRemoteEntryUrl`);
  const isDev = process.env.NODE_ENV === 'development';
  if (isDev && devRemoteUrl) {
    DRLLog(`useDynamicScript: Using devRemoteUrl: ${devRemoteUrl}`);
    return devRemoteUrl;
  }

  const response = await fetch(
    `${process.env.REMOTE_VERSIONING_WORKER_URL}/remotes?remoteName=${remoteName}`
  ).then(remoteResponse => remoteResponse.json());

  if (response.remoteUrl) {
    if (previewHash) {
      const projectName = response.remoteUrl.split('.')[1];
      const mfePreviewLinkUrl = `https://${previewHash}.${projectName}.pages.dev/remoteEntry.js`;
      return mfePreviewLinkUrl;
    }
  }

  return response.remoteUrl;
};

/**
 * useDynamicScript - mounts a script tag to the DOM pointing to the
 * remoteEntry.js file to be used as a module by webpack.
 * See loadComponent.ts file.
 */
const useDynamicScript = (
  remoteName: string,
  module: string,
  previewHash?: string,
  devRemoteUrl?: string
) => {
  const [ready, setReady] = useState(false);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    const element = document.createElement('script');
    const scriptId = `mfe-${remoteName}`;

    getRemoteEntryUrl(remoteName, previewHash, devRemoteUrl).then(remoteUrl => {
      if (!remoteUrl) {
        return;
      }

      if (!document.getElementById(scriptId)) {
        DRLLog('useDynamicScript: creating script element');
        element.src = String(remoteUrl);
        element.type = 'text/javascript';
        element.async = true;
        element.id = scriptId;

        setReady(false);
        setFailed(false);

        element.onload = () => {
          setReady(true);
        };

        element.onerror = () => {
          setReady(false);
          setFailed(true);
        };

        document.head.appendChild(element);
      } else {
        setReady(true);
      }
    });

    return () => {
      const mfeScript = document.getElementById(scriptId);
      mfeScript && document.head.removeChild(mfeScript);
    };
  }, [remoteName, devRemoteUrl, module, previewHash]);

  return {
    ready,
    failed
  };
};
```

Usage of these in our DynamicRemoteLoadable effectively waits for the `useDynamicScript` hook to be ready, and then sets the new component module into state and triggers a re-render.

```
  const { ready, failed } = useDynamicScript(
    remoteName,
    module,
    previewHash,
    devRemoteUrl
  );

  useEffect(() => {
    if (ready) {
      const Comp = lazy(loadComponent(remoteName, module));
      setComponent(Comp);
    }
  }, [ready, failed, module, remoteName]);
```

**Comment by zhangHongEn** [comment]
Even if moduleFederation is not used, webpack jsonp will be mounted globally and appear in each chunk. You can add a version number to output.uniqueName and moduleFederation.name to avoid global variable conflicts, but the version number will appear in each chunk, which will cause the hash cache to fail

**Comment by pcostanz** [comment]
Is there a way for me to intentionally purge something from webpack's module cache? I'm assuming that the global variable conflict would cause the second script load to overwrite the first, but it seems like webpack is hanging onto something in this case. I'm not very familiar with internals of webpack so any pointers would be helpful. I'll try to see if versioning `moduleFederation.name` and `output.uniqueName` help. Honestly I'm not 100% sure I understand the explanation on module collision listed at https://webpack.js.org/concepts/module-federation/#collision-between-modules-from-different-remotes. 

One thing that I did note in testing was that if I load a new version of my module that did not have a global `moduleFederation.name` conflict (ie: loading `uiplatformdemo` first and then `uiplatformdemo2`), I was able to get the new React component to render and appropriately toggle between them. The confusing part about this was that I made no changes to my `loadComponent` function, so both components were still having the containers initialized from the original global on `window.uiplatformdemo`. This only worked if the original module container was initialized first, though, which leads me to believe that some internal webpack cache was appropriately updated when the script was loaded with a non-conflicting global window variable.

**Comment by zhangHongEn** [comment]
You can do this, but the generalization is very poor
``` js
const uniqueName = "app2"
const MFName = "app2"
delete window[`webpackChunk${uniqueName}`]
delete window[`${MFName}`]
loadRemote(MFName)
```

the standard solution is to add a version number to the global module to avoid conflicts
```js
app2_1_0_0
app2_1_0_1
```

**Comment by ScriptedAlchemy** [comment]
Yeah that works. I generally use unique name and make it the build hash so there's no change webpack chunk loading globals can collide. This is how Medusa manages multiple remotes on the page at once
