### ISSUE TITLE
Module Federation in offline Shell App

### ISSUE THREAD

**Issue by dennisstancu** [module-federation/module-federation-examples#2533]
Hey, 
I dont know if its possible, but i would like to build a shell App with Angular and Module-Federation. The App should load the MFEs and save them to a local database(sqlite etc). And If the User wont have access to the Internet the App should fetch the MFE from the database and not from the Remote. 
If alrdy. tried a few thinks and apparently Module Federation does not fetch the Remote in one Chunk but as i understand it as a Init manual with more remotes to download that work together. 
Is there any way to work around this? Or to get hold of the remotes to save them together ?

Thanks in advance

**Comment by schirrel** [comment]
Hey @dennisstancu i had the same approach, in my case is a offline pwa. I had make https://schirrel.dev/ModuleFederationEnhancedPlugin/ to help on it, to load all the modules on  initial.
And therefer, on my project we use cache strategies to maintan the chunks on cache and be used for webpack
