### ISSUE TITLE
bug: SSR issue in nextjs-ssr example in production mode

### ISSUE THREAD

**Issue by OlegLustenko** [module-federation/module-federation-examples#2536]
Hey, it seems [nextjs-ssr](https://github.com/module-federation/module-federation-examples/tree/master/nextjs-ssr)

Having an issue with the production version
I've tried mentioned version of  `@module-federation/nextjs-mf` and the latest one  `"@module-federation/nextjs-mf": "5.12.10"` won't help

Console log:
![image](https://user-images.githubusercontent.com/11524061/208423350-e9dd3692-fe47-49f7-89c9-1d7c2a981099.png)

Browser Network:
![image](https://user-images.githubusercontent.com/11524061/208423600-99f77fd3-50cf-4781-9f5b-bc22122e75b7.png)

However, client-side works fine here,

I'm willing to fix it on my own, but I need guidance on debugging such an error.

Any ideas?

**Comment by ScriptedAlchemy** [comment]
Seen this before. Something not quite right in one of the configs. I'll take a look
