### ISSUE TITLE
  remotes'propertyname  can't use alias

### ISSUE THREAD

**Issue by Calvin-for-AI** [module-federation/module-federation-examples#2552]
I try to use webpack-resolve-alias for modulefederation remotes. It's not work.
like: remotes:{ '@xxx/core102': 'xxxx_core@https://cdn.xxx.com/xxx-core.js' }
    resolve: {
      alias:{ '@xxx/core102': '@xxx/core' }
    }

and in my code: ```
import core from '@xxx/core/App';
```
build failed : Module not found

**Comment by ScriptedAlchemy** [comment]
Just make the remote name the alias you want it to be in Federation config. RemoteAlias:banannas@http

**Comment by Calvin-for-AI** [comment]
> Just make the remote name the alias you want it to be in Federation config. RemoteAlias:banannas@http

Thank u. I'll try
