### ISSUE TITLE
Sharing of Singleton from library does not work with secondary or /* entry points

### ISSUE THREAD

**Issue by parasharsh** [module-federation/module-federation-examples#2574]
I have an angular application and use module federation based on https://www.npmjs.com/package/@angular-architects/module-federation. 
The Remote application does load fine and is able to share the Singleton from the shell App if it's using the primary path. But If a library is a secondary entry point then sharing of the Singleton from that library does not work.
In the attached example .. there are 2 libraries auth-lib and ui-sdk. The sharing of the Service from auth-lib does work fine (in the FlightsSearchComponent of mf1 project) but sharing of the service from ui-sdk (this has secondary entry point ui-sdk/i18n) i18nservice does not work. 
Any clues on what is the issue here 
https://github.com/parasharsh/module-federation-plugin-example (This is based on https://github.com/manfredsteyer/module-federation-plugin-example with changes to show the issue)

**Comment by ScriptedAlchemy** [comment]
can you use a trailing slash like `@angular/`

**Comment by parasharsh** [comment]
Thanks Zack. Can you please elaborate on where to add the trailing slash. I tried adding in the tsconfig as well as in the webconfig (shared) and got the compilation error.

**Comment by parasharsh** [comment]
An update 

If I add the below entry in the shared property of the plugin then the sharing is working 

'ui-sdk/i18n': {
      singleton: true,
      eager: false,
      import: '<path>/dist/ui-sdk/fesm2020/ui-sdk-i18n.mjs'
    },

But I have to remove 
[@angular/platform-browser] from the shared list as I get shared module is not available for eager consumption error
