### ISSUE TITLE
Example with vite + dynamic remotes

### ISSUE THREAD

**Issue by fgatti675** [module-federation/module-federation-examples#2579]
Hi!

First of all, thank you so much for developing this feature. It is exactly what we need for a pretty complex project.

We have implemented a multi module project using vite, around 6 modules.
We switched from webpack to vite and saw a big productivity boost.
We offer a SaaS and would like our users to be able to upload their own modules to customize their instances, so module federation fits the glove perfectly!

The issue is, we have not been able to make dynamic remotes with vite.
There are examples of vite, and examples of dynamic imports with webpack.
Would it be too much to ask for an example of vite an dynamic imports?
Or some indications on how to proceed at least, would be great. :)

I have been trying to do it for a few days now and faced every possible error!!

Thanks in advance !

**Comment by omridevk** [comment]
@fgatti675  did you manage to solve the issue or moved back to webpack as the host?

**Comment by fgatti675** [comment]
Hi @fgatti675 
I am currently monitoring this PR, which should solve the issue:
https://github.com/originjs/vite-plugin-federation/pull/481
