### ISSUE TITLE
Cannot share packages

### ISSUE THREAD

**Issue by khanh-le-otsv** [module-federation/module-federation-examples#2580]
I'm using @module-federation/next-mf for 2 nextjs apps. The nextjs host app shares `react-intl` as singleton:

```
shared: {
          'react-intl/': { eager: true, import: 'react-intl', requiredVersion: '6.2.5', singleton: true },
        },
```

But in the nextjs remote app, when I consume React component with that uses react-intl, it shows this error:

![image](https://user-images.githubusercontent.com/85324726/211230229-e0c1e167-deab-428a-b780-20e503ede61d.png)

Could you please let me know how to properly share singleton packages? Thank you.

**Comment by ScriptedAlchemy** [comment]
You need to dynamic import and export the page files. See the examples. 

Or enable async boundary loader. Check readme for the option
