### ISSUE TITLE
Integration MF web assembly error

### ISSUE THREAD

**Issue by fernandoiwamoto** [module-federation/module-federation-examples#2636]
I don't know if the problem is with web assembly or module federation.
The sample I provided, the create-project-mf (with web assembly + Automerge lib) works fine if running standalone.
When running as MF, it fails and the it only works fine if the code of Automerge is commented.

`react-dom.development.js:28439 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports`

I used the example here and made some changes on the webpack to use web assembly because of the library automerge requires it.
[test-app.zip](https://github.com/module-federation/module-federation-examples/files/10428581/test-app.zip)

https://github.com/automerge/automerge

**Comment by ScriptedAlchemy** [comment]
libraryTarget: 'umd',

on mf config try library.type = umd and remoteType umd
