### ISSUE TITLE
genesis sample not working

### ISSUE THREAD

**Issue by lexasq** [module-federation/module-federation-examples#2647]
During my research on genesis example I found that initial issue that `genes-tsc`, `genesis-vue-tsc` and `genesis-ts-node` commands aren't working (I tried to find how to make those work and failed, then I looked inside @fmfe/genesis-compiler and saw that those are basically just wrappers for `typescript` and `ts-node`) so I removed `genesis-` from them and I could move on

![image](https://user-images.githubusercontent.com/26062537/212893282-ace80d1e-ee1d-440a-bc15-27d73580e00e.png)

The next issue was difference between `vue`  version and `vue-server-renderer` version
![image](https://user-images.githubusercontent.com/26062537/212894476-eac6ee1f-ba26-4fa8-b286-4fe5a56201b8.png)
So I had 2 ways, update, or downgrade. If we update we get this:  
![image](https://user-images.githubusercontent.com/26062537/212896276-a147b2ed-85fd-4260-88cc-dcc35337b0a0.png)
![image](https://user-images.githubusercontent.com/26062537/212897954-6373343a-54aa-4101-bea4-0e00de5272d6.png)
So it builds. but doesn't actually work since inside because `@fmfe/genesis-compiler` and `@fmfe/genesis-core` have incompatible vue versions inside. 2.7.4 and 2.6.14 respectively. So I tried downgrade (please note that I left  `@fmfe/genesis-core` the latest version, and only downgraded  `@fmfe/genesis-compiler` top 2.1.0:
![image](https://user-images.githubusercontent.com/26062537/212906121-86f640e4-75be-4d22-802c-827651cd5ce7.png)
We receive the same error, @fmfe package isn't yet documented in english to proceed investigating internal issues.

TODO
Fix the sample or maybe remove it, saince there wasn't any support in a while

**Comment by ScriptedAlchemy** [comment]
We can tag the author of genesis framework and see if they can lend a hand in update if need be

**Comment by CaioRolla** [comment]
Should be fixed on #2723
