### ISSUE TITLE
[Question] How to generate bundles only for the Module Federation part?

### ISSUE THREAD

**Issue by hskrishandi** [module-federation/module-federation-examples#2671]
First of all, thanks for developing this plugin! I really liked the idea where sub-apps are able to load the whole app, not just itself (as demonstrated in this [example](https://github.com/module-federation/module-federation-examples/tree/master/shared-routing) and [Youtube video](https://www.youtube.com/watch?v=-LNcpralkjM).

But there's one thing I would like to ask. In the `shared-routing` [example](https://github.com/module-federation/module-federation-examples/tree/master/shared-routing) above, each sub-apps will have their own `public/index.html`, `bootstrap.js` and `index.js` where they all just import from the `shell` app. If we run the build process in each sub-app, it will generate the bundles and static files to load the entire app, like the `index.html`, `main.js`, etc. It's great because it allows each sub-apps server to become an entry point to the whole app.

However, for deploying in production, we actually don't need all these, as we just need the `remoteEntry.js` file and the chunks related to the `exposes` field. Hence, I'm wondering whether it's possible for Webpack to generate just the things in Module Federation plugin?

**Comment by ScriptedAlchemy** [comment]
Just leave the entrypoint blank and skip html webpack plugin or whatever else for host mode. 

Host-remote example is super simple but I believe it's a one-way example. Not bidirectional

**Comment by hskrishandi** [comment]
Previously I tried removing the `entry` field in `webpack.config.js` but webpack threw the following error
```
ERROR in main
Module not found: Error: Can't resolve './src' in '/path/to/project'
resolve './src' in '/path/to/project'
  using description file: /path/to/project/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file:/path/to/project/package.json (relative path: ./src)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /path/to/project/src doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /path/to/project/src.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /path/to/project/src.ts doesn't exist
      as directory
        /path/to/project/src doesn't exist

webpack 5.74.0 compiled with 1 error in 516 m
```

If I set `entry: {}`, it can work successfully. Seems that if the `entry` field is not provided, webpack will default to search inside `src/`.

Thanks for the suggestion though 🙏
