### ISSUE TITLE
[umd-federation] Sample doesn't work on Safari

### ISSUE THREAD

**Issue by HEHOHADA** [module-federation/module-federation-examples#2682]
Safari: Version 16.1 (18614.2.9.1.12)

Node: 18.12.0

<img width="534" alt="image" src="https://user-images.githubusercontent.com/42976899/214308844-6b490109-360a-4136-99f7-d6d7c4ee11b1.png">

**Comment by ScriptedAlchemy** [comment]
Will try to look into it
