### ISSUE TITLE
Host and Remote both Server side rendered app with routing not working.

### ISSUE THREAD

**Issue by maulikprajapati** [module-federation/module-federation-examples#2691]
Hello,
I'm new to Micro frontend,
I've created Both Remote and Host app with React Server side Rendering (not used any framework like Next.js or Remix), I got error while running the Host app. 
Error: ** shared module is not available for eager consumption **
I've shared required dependencies as well.

and also i got one more error : ** scriptExternalLoadError: Loading script failed. **

**Comment by ScriptedAlchemy** [comment]
Are you using node federation plugin for the node SSR side? 

I'll need a repo to reproduce anything, but looks like you're missing a async import as the entrypoint of the application.

**Comment by maulikprajapati** [comment]
@ScriptedAlchemy | Yes, I'm using node federation plugin for SSR side.

I've pushed the code to Git Repo to reproduce the issue,
 https://github.com/maulikprajapati/mf-ssr-demo

steps i followed,
installed packages in both host and remote.
running remote app first via `npm run build` and `npm run serve` command.
then running host app via same commands.

**Comment by maulikprajapati** [comment]
@ScriptedAlchemy  | Any updates on this? or do we have any alternatives for Custom SSR MF ?

**Comment by ScriptedAlchemy** [comment]
import bootstrap needs to be async import()

**Comment by maulikprajapati** [comment]
Any example or sample app which could help me?

**Comment by ScriptedAlchemy** [comment]
every demo in this repo uses import(bootstrap) convention. Take your pick. the ssr ones do as well.
