### ISSUE TITLE
Is there way to debug module-federation exposes components?

### ISSUE THREAD

**Issue by sushil-kumr** [module-federation/module-federation-examples#2692]
I am implementing module-federation with the 2 of my projects. 

I am able to see in logs that all the assets have been logs in webpack while running the development server from the HOST application. 

Also showing the logs of the component in consume application but when I am using the components this error 

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')`
`at __webpack_require__(bootstrap)`
`at fn (hot_module_replacement)`
`at ./src/bootstrap.js (bootstrap)`
`at __webpack_require__(bootstrap)`
`at fn (hot_module_replacement)`
`at index.js`

The above error I was facing from 2 days, after researching, I have modify the HRM `{hot:true)` into `{hot:false}` and respectively other changes. From yesterday, I am start getting this error.

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')`
`at __webpack_require__(bootstrap)`
`at ./src/bootstrap.js (bootstrap)`
`at __webpack_require__(bootstrap)`
`at index.js`

When I click on `__webpack_require__` for details error it is showing 
//Execute the modules function
`__webpack_modules__[moduleId].call(module.exports, module, module.exports, __webpack_require__);`

Please give any lead to debug these to resolve the problem.

**Comment by ScriptedAlchemy** [comment]
Would need to see config. But looks like you don't have a async import at the top of the app, or you're using something that injects additional entry points.

**Comment by sushil-kumr** [comment]
Used the bootstrap configuration which is mentioned in all the apps for async import. As I mentioned that it showing in logs, when I am running the webpack dev server. 

```
log for app1 : asset components_chunks.js 144KiB
log for app2 : remote path_of_remotes 6 bytes(remote) 6 bytes(share-init)
```

For the entry config:-
`{ app:"./index.js",`
`externals:["react","react-redux]}`}// added all the react and redux path in externals

**Comment by ScriptedAlchemy** [comment]
dont use externals
