### ISSUE TITLE
Update the "Angular Universal SSR" example to Angular version 15

### ISSUE THREAD

**Issue by ViniChab** [module-federation/module-federation-examples#2714]
The Angular Universal SSR is currently using Angular version 10, we want to update it to version 15.

I'll be tackling this myself, this issue is here for documentation.

![image](https://user-images.githubusercontent.com/36959048/216065833-23426d1f-0c5e-4a31-801b-cff8c0cc4bac.png)

**Comment by ViniChab** [comment]
The PR for this issue is here (currently draft): https://github.com/module-federation/module-federation-examples/pull/2717

More info about its progress can be found there

**Comment by belinef** [comment]
PR based on 2717 
https://github.com/module-federation/module-federation-examples/pull/2775
