### ISSUE TITLE
Accessing package subpaths - Module federation

### ISSUE THREAD

**Issue by rakeshar3796** [module-federation/module-federation-examples#2737]
Hi, 

I noticed https://github.com/module-federation/module-federation-examples/blob/master/complete-react-case/lib-app/webpack.config.js#L18 here that package "react" and "react-dom" is exported from library package and used in host app. 

Everything works fine but my need is to consume "react-dom/client" in my host without changing any export in my library since i'm not aware of the exposed subpaths.

I need to use like this

`import { createRoot } from "lib/react-dom/client";`
`import duration from "lib/dayjs/plugin/duration";`

And I'm expecting my remote config should be like this
```
new ModuleFederationPlugin({
      name: 'lib',
      filename: 'remoteEntry.js',
      exposes: {
        './react-dom': 'react-dom',
        './dayjs': 'dayjs'
      },
    })
```

@ScriptedAlchemy Is there a way to solve this?

**Comment by ScriptedAlchemy** [comment]
you have to expose each individually or use "shared" with a trailing slash 

"react/" when sharing will walk used subpaths and make them available.

No option for exposes, youd have to manually grep the file system and build your own maps if your exposing it, not sharing it.

**Comment by rakeshar3796** [comment]
Thanks @ScriptedAlchemy will check and get back on this

**Comment by ScriptedAlchemy** [comment]
you could make index.js which exports everything as named export, but uses dynamic import maps to do so. however id would return promises, not sync functions

**Comment by saravanan10393** [comment]
> you could make index.js which exports everything as named export, but uses dynamic import maps to do so. however id would return promises, not sync functions

Not understanding clearly @ScriptedAlchemy . could you provide any code snippet, it would really help to understand better.
