### ISSUE TITLE
Styles(Css files) and Images are not loading from remote(mfe) to shell. It only attaching js to files to DM using custom elements.

### ISSUE THREAD

**Issue by AnandKatta** [module-federation/module-federation-examples#2747]
Hi Manfred,
  Good Morning,
I am trying to load angular mfe to angular shell using custom elements approach by https://www.angulararchitects.io/aktuelles/multi-framework-and-version-micro-frontends-with-module-federation-your-4-steps-guide/. But css file and images are not loading into shell. As i debugged, I can see only js files from mfe(angular) is loaded into browser DOM. Can someone help me to resolve this. Its critical for me. And also , its a common use case for most of the application. Any help would be highly appreciated.

**Comment by ScriptedAlchemy** [comment]
https://github.com/manfredsteyer/multi-framework-version

**Comment by AnandKatta** [comment]
@ScriptedAlchemy , the issue is not resolved. I have the checked the url, which you have given. But there is no place it is mentioned about css/assets loading from shell to mfe. I may be wrong. Could you guide me to the correct path. If any other informations needed i can provide you. Thanks Team,
