### ISSUE TITLE
Get Reducer from another application with Dynamic Remote

### ISSUE THREAD

**Issue by gustavojuneo** [module-federation/module-federation-examples#2755]
I would like to know if there is any way to retrieve a reducer.js file to use in combineReducer within my application using dynamic remotes so that the application does not have errors if the other application is not running.

Turning the code below into dynamic
![image](https://user-images.githubusercontent.com/44280939/217882893-6e4bdc04-006a-434c-948c-d213cb6f1902.png)

**Comment by ScriptedAlchemy** [comment]
top level await might work.
