### ISSUE TITLE
https://github.com/Styles(Css files) and Images are not loading from remote(mfe) to shell. It only attaching js to files to DM using custom elements. manfredsteyer/multi-framework-version

### ISSUE THREAD

**Issue by AnandKatta** [module-federation/module-federation-examples#2761]
https://github.com/manfredsteyer/multi-framework-version

_Originally posted by @ScriptedAlchemy in https://github.com/module-federation/module-federation-examples/issues/2747#issuecomment-1424647144_

**Comment by AnandKatta** [comment]
Hi Team,

@ScriptedAlchemy, The issue is not resolved and I didn't get perfect place to see how to load css/assets from mfe to shell. 
Please guide me to right path. The url which you have shared, its not mentioned anything about loading css/assets from mfe to shell. I may be wrong, please guide me to the right path. This is most common scenario which all required. Once again thanks for your effort

**Comment by stevebrowndotco** [comment]
For images, @AnandKatta I am solving this for now by referencing a direct link to the remote image. My example is with nextjs but it should work in principle:

```
export function Index() {
  return (
    <>
      <Image
        src="http://localhost:4201/logo.svg"
        width={100}
        height={100}
        alt="Next"
      />
      HEADER
    </>
  );
}
```

You can use env vars to change the hostname in prod.

For CSS, there is a draft PR on the examples here that seems interesting: https://github.com/module-federation/module-federation-examples/pull/2577 (i can only get inline working for now)

**Comment by AnandKatta** [comment]
@stevebrowndotco thank you. got it..

I have a follow doubt, please help me to clarify this or @ScriptedAlchemy.

Hi Team- @ScriptedAlchemy / all Developers,

I have worked with custom elements previously in angular. Now am trying to use Modular Federation approach to load mfe. I am using different versions in angular for different mfe's. I am using custom element approach in modular federation(https://www.angulararchitects.io/en/aktuelles/multi-framework-and-version-micro-frontends-with-module-federation-your-4-steps-guide/). As a Custom element it will work when we downloaded the build js files in browser and add the "tag or attribute" to dom.
My doubt is custom element can work independly we all aware of it, but how does the sharing libraries comes into picture, if its a modular federation web components. How it really now downloading the packages if we keep it shared library in shell. Even if we have same version and go with custom element approach in modular federation as it has its own bundled files. While building the application separately, it never knows the shell shares. I really don't know how it avoids the duplicate package to load again. On runtime how it negotiates. I may be wrong in conveying or getting things right.

"Your help to understand me is highly appreciable"

Thanks all for the support.
