### ISSUE TITLE
dynamic runtime remotes not re-rendering on change

### ISSUE THREAD

**Issue by itsBllue** [module-federation/module-federation-examples#2766]
Hi,
I'm currently working on a system which loads remotes once they need to be used, currently I'm able to load them just fine, but if I do something like:
App 1 unload App 2 load, it will render App 1. I would have to refresh the application to load App 2, and the issue is vice versa, only the first app that is loaded will stay loaded no matter what remote I pass, until refresh.

I've used the examples provided under the advanced-api/ dynamic remote runtime  and am coming across this issue.

**Comment by fxjs** [comment]
Confused...

**Comment by kj-fiddler** [comment]
Can u provide a minimal reproducible example? This works for me just fine

**Comment by KartheekJavvaji** [comment]
Can u provide a minimal reproducible example? This works for me just fine

**Comment by itsBllue** [comment]
After some testing I was able to figure out the issue came from the  way routes were being rendered.,
