### ISSUE TITLE
The Vue2-in-Vue3 slot appears underfind

### ISSUE THREAD

**Issue by a526672351** [module-federation/module-federation-examples#2774]
in the Vue2-in-Vue3 example, the vue2 shared component uses the vue slot feature. When vue2 is applied in vue3 with the slot attribute, the slot cannot be recognized, and the position of the slot template on the page appears underfind clearly
![image](https://user-images.githubusercontent.com/5345266/221112585-58bb02c3-9dec-4786-a61b-712ad77abb98.png)

**Comment by huangqicong** [comment]
Has this problem been solved by no one?
