### ISSUE TITLE
Apps are not working independently

### ISSUE THREAD

**Issue by simeon-raykov** [module-federation/module-federation-examples#2797]
Hi there,

My team is developing a React SSR app using NX, and we have observed that the individual apps are not able to function independently. For example, if we have one remote and one host app, when we shut down the remote app, the JavaScript in the host app also stops working. Is this the intended behavior? I could reproduce this with your example: https://github.com/module-federation/module-federation-examples/tree/master/server-side-rendering

**Comment by ScriptedAlchemy** [comment]
Thats because youve introduced binding dependencies in the host. Youd want to wrap them in a suspense boundary or something like a try catch to withstand a remote being offline, webpack and the app out the box wont know what to do if code is missing - naturally it will fail unless told to do something else.

**Comment by simeon-raykov** [comment]
> 

Could you provide a working example? I have already tried try catch / suspense, error boundary, none of these work.

**Comment by simeon-raykov** [comment]
> Thats because youve introduced binding dependencies in the host. Youd want to wrap them in a suspense boundary or something like a try catch to withstand a remote being offline, webpack and the app out the box wont know what to do if code is missing - naturally it will fail unless told to do something else.

Could you provide a working example? I have already tried try catch / suspense, error boundary, none of these work.

**Comment by ScriptedAlchemy** [comment]
Do you have samples snippet of how you import remote module that's offline? I'll go confirm my plugin offers soft catches and doesn't crash. In next I can withstand dead remotes but perhaps there's something I need to move to node federation, but it should withstand offline containers.

**Comment by simeon-raykov** [comment]
> Do you have samples snippet of how you import remote module that's offline? I'll go confirm my plugin offers soft catches and doesn't crash. In next I can withstand dead remotes but perhaps there's something I need to move to node federation, but it should withstand offline containers.

So basically we have tried things like:
```JSX

let UserBar: React.ComponentType<unknown> | null = null;
try {
  UserBar = React.lazy(() => import('remote/UserBar'));
} catch (error) {
  console.error('Failed to load UserBar component', error);
}

export function App() {
  return (
  <ErrorBoundary>
    <React.Suspense fallback={<p>Loading...</p>}>
      <Header>{UserBar && <UserBar />}</Header>
      <main className={styles.mainContent}>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
      </main>
    </React.Suspense>
    </ErrorBoundary>
  );
}


```
You may want to check out this app, which serves as a template for what we're currently using: https://github.com/simeon-raykov/react-custom-ssr-module-federation. Our project uses NX monorepo, and we've noticed that whenever we shut down a remote app, the JavaScript in the host app stops working. The server terminal displays a message like "Remote is offline, Loading fake remote...", but the remote never actually loads. We've raised the issue with nx nrwl/nx#15559 because we're using their withModuleFederation and withModuleFederationForSSR functions in our initial webpack configuration.

**Comment by ScriptedAlchemy** [comment]
What about import().catch()

Wrapping lazy in try catch won't work since react.lazy instantiates just fine, but at render when callback is fired - u get a render error.

**Comment by simeon-raykov** [comment]
> What about import().catch()
> 
> Wrapping lazy in try catch won't work since react.lazy instantiates just fine, but at render when callback is fired - u get a render error.

```JSX
import * as React from 'react';
import { Route, Routes, Navigate } from 'react-router-dom';
import Home from './home/home';
import { Header } from '@sw2.0/design-system/global-components';
import styles from './app.module.scss';

const loadUserBar = () =>
  import('remote/UserBar').catch((error) => {
    console.error('Failed to load UserBar component', error);
  });

const App = () => {
  const [userBar, setUserBar] = React.useState(false);

  React.useEffect(() => {
    loadUserBar().then((module) => {
      setUserBar(module.default);
    });
  }, []);

  return (
    <React.Suspense fallback={<p>Loading...</p>}>
      <Header>{userBar && userBar}</Header>
      <main className={styles.mainContent}>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
      </main>
    </React.Suspense>
  );
};

export default App;
```

I get this when I kill the remote server:
![Screenshot 2023-03-22 at 9 58 19](https://user-images.githubusercontent.com/125904541/226836920-201e21da-4129-4b11-9a6b-7b5e12d8184f.png)
If we put a button in the jsx with an onClick alert, it won't execute.

**Comment by ScriptedAlchemy** [comment]
Thanks for the info, I'm going to pull your repo and see what's up.

**Comment by CWSites** [comment]
Interested to see how this is supposed to function as well!

**Comment by ScriptedAlchemy** [comment]
Okay so I've not had a ton of time to look into this specifically. But I have some ideas on how to improve it. I'm going to try and play with the example to fine possible solutions in userland till I can try and find options to import it in pluginland
