### ISSUE TITLE
Dynamic Remote - NodeJS React SSR

### ISSUE THREAD

**Issue by bytekai** [module-federation/module-federation-examples#2812]
I'm trying to use module federation to dynamically get remotes to get the exposed react components to SSR them.

I've tried modifying the examples but cant seem to make it work, is there any example that uses dynamic remotes for react ssr?

**Comment by bytekai** [comment]
dove a bit deeper into the api of webpack

seems like for dynamically loading containers you should use  
```js 

__webpack_require__.l = function(url,callback,chunkId) {...}
```

the issue seems like it cant load in the chunks, spits out Error: Cannot find module './292.js'

found another fn called __webpack_require__.f.readFileVm  but unsure how its used exactly.

```js
__webpack_require__.f.readFileVm = function(chunkId, promises) {...}
```

seems like we are passing default require into the vm Context instead of our own. resulting in webpack trying to load the the chunk locally. im going to try to implement something to get it to work

**Comment by 7rulnik** [comment]
@panthyy take a look at these links https://github.com/webpack/webpack/issues/12084#issuecomment-868394680

**Comment by 7rulnik** [comment]
and also this https://github.com/module-federation/module-federation-examples/issues/399

**Comment by bytekai** [comment]
THANK YOU @7rulnik , been hitting my head for hours. worked perfectly.

any gotchas i should be aware of?

**Comment by 7rulnik** [comment]
@panthyy not really. I don't use mfe
