### ISSUE TITLE
Apply side-effects

### ISSUE THREAD

**Issue by althaf101** [module-federation/module-federation-examples#2824]
I have a react component library that exposes some components from the remote like the below

<pre>
// webpack.config.js
  new ModuleFederationPlugin({
      name: "component_lib",
      filename: "remoteEntry.js",
      exposes: {
        "./Button": "./src/components/Button/Button",
        "./Checkbox": "./src/components/Checkox/Checkbox",
        "./Shimmer": "./src/components/Shimmer/Shimmer",
        ...
      }
  })
</pre>

I have some side effects to execute whenever any host import any of these components. I do not want to add the side effect code in all components. 
So, is there any way to execute some piece of code centrally, whenever any host connect to my remote ?

**Comment by ScriptedAlchemy** [comment]
yes youd likely want to look at my delegate module examples which let you control the glue code - there's also `promise new promise` which is a simpler option but can only handle vanillia js in its syntax, it doesn'tget processed by webpack so require or anything else would not be bundled.

**Comment by althaf101** [comment]
@ScriptedAlchemy 

I went through your suggestions. From what I understood, both the delegate module and `promise new promise` works at the host side. But what I want is to execute some code on the remote, when a host connects to my remote.

eg: 
As described in the question, lets assume my remote exposes 3 components `Button`, `Checkbox` & `Shimmer`. 
Also, lets assume that all of these components depends on some data from an API call (same data for all components). 

Then what I can do is that, I can call the API from all the components. But this will be inefficient since if one component has already called the API, then ideally I should re-use that data. 
Also, I cannot have the API call in only one component since the host app might be importing a different component.

Because of this, I want some central place at remote side which will get triggered whenever a host imports any of the components mentioned above, so that I can do the data fetching there.

Please note that this is just an example scenario. My actual usecase is a bit different, but a solution to the above problem will solve mine as well.

**Comment by althaf101** [comment]
@ScriptedAlchemy 
Could you please help me for a solution ?
