### ISSUE TITLE
Update Dynamic System Host example with @module-federation/utilities

### ISSUE THREAD

**Issue by tadayosi** [module-federation/module-federation-examples#2831]
I found this example very useful, but it looks like it still uses the old gist version of `getOrLoadRemote` function.
https://github.com/module-federation/module-federation-examples/tree/master/dynamic-system-host

I think the more up-to-date method is to use `@module-federation/utilities` for dynamic remote loading. Could you update the example?  Thank you!

**Comment by ScriptedAlchemy** [comment]
Yes it needs to be updated, that example is very out of date. Feel free to send a PR starting on an update.

Ill add it to the backlog of things in the meantime

**Comment by tadayosi** [comment]
@ScriptedAlchemy OK, I've sent a pull req #2850. Please have a look.

**Comment by ScriptedAlchemy** [comment]
Thanks!!

**Comment by tadayosi** [comment]
Thanks for merging :slightly_smiling_face:
