### ISSUE TITLE
Apollo-client server side rendering doesn't render fetched data

### ISSUE THREAD

**Issue by LindaLuesink** [module-federation/module-federation-examples#2915]
I changed the apollo-client repo because the original repo returned an error in the browser that says
```Uncaught Error: The server did not finish this Suspense boundary: The server used "renderToString" which does not support Suspense. If you intended for this Suspense boundary to render the fallback content on the server consider throwing an Error somewhere within the Suspense boundary. If you intended to have the server wait for the suspended component please switch to "renderToPipeableStream" which supports Suspense on the server```

I used "renderToPipeableStream" on the server in app1 and replaced the apollo useQuery hook  with a custom hook so I didn't have to use the apollo provider.

What I see is that the html source doesn't contain the fetched data. 
I also use react Helmet. In app2 I added the title (HELMET APP2 TITLE) within Helmet tags, but on the server it didn't run. In the html source the title from app1 is present.

I made a pull request, you can see the changes I made: https://github.com/lindabeslist/module-federation-examples/pull/1/commits/372bb4011e1b9a8aad2ac075e16617a4f2202f87

![image](https://user-images.githubusercontent.com/7568777/229134067-5d284431-21a2-4e80-a026-b4fc3936b3d5.png)

Also I see that the renderToPipeableStream is finished before apolloClient has fetched:
![image](https://user-images.githubusercontent.com/7568777/229134693-9f44f35e-acc7-47ac-a8cb-f5c04b55576a.png)

I would be so grateful if you could look at this issue. Thanks in advance and looking forward to your reply.

**Comment by ScriptedAlchemy** [comment]
Double render the Apollo app?
