### ISSUE TITLE
NextJS - getServerSideProps is not executed in [...slug].js file

### ISSUE THREAD

**Issue by gitneeraj** [module-federation/module-federation-examples#2916]
Hi,

**My application description**
I have two apps bootstrapped with `create-next-app` (v13). `remote1` app shares all the pages so that `host` app can consume and render. I have `pages/[...slug].js` in `host` app which catches all the routes from `remote1`. This works fine until I use `getServerSideProps` in `remote1` app. It renders blank page and does nothing when I hit the path `/contact` in `host` app. It does work fine with `getInitialProps` but not with `getServerSideProps`.

Here are my repo links
1. Host - https://github.com/gitneeraj/nextjs-mf-host
2. Remote1 - https://github.com/gitneeraj/nextjs-mf-remote1

I am porting my existing application to Microfrontends and they are already using `getServerSideProps` and I cannot change it. Any help is very much appreciated!

Cheers & Peace
~Neeraj

**Comment by ScriptedAlchemy** [comment]
There’s a bug I’m trying to fix. Check the universe repo and you’ll see the workaround I posted in git issues. 

I already fixed the issue but have not yet released as I’ve been speaking at tech conference

**Comment by gitneeraj** [comment]
Hi @ScriptedAlchemy Thank you for the reply!
Are you referring to this issue https://github.com/module-federation/universe/issues/670 in universe? It has the below code which I tried but did no work.

```
// [...slug.js]
import dynamic from "next/dynamic"
const AsyncBoundary = dynamic(() => import("../realpage"), {suspense:true});
export default AsyncBoundary;
export const getServerSideProps = async (ctx) => {
  return import("../realpage").then((mod) => {
    return mod.getServerSideProps(ctx)
  })
}
```

```
// realpage.tsx
import { createFederatedCatchAll } from '@/components/shared';

export default createFederatedCatchAll();
```

On a side note, is it possible to return only the matched federated page URL(like `app1/pages/index`) from `createFederatedCatchAll` ?

**Comment by alibek-gao** [comment]
First. On your [host](https://github.com/gitneeraj/nextjs-mf-host/blob/main/pages/%5B...slug%5D.js#L3) you import from remote with name `realPages`:
```js
const Page = dynamic(() => import('../realPages/[...slug]'));
```
 But you have only one [remote](https://github.com/gitneeraj/nextjs-mf-host/blob/main/next.config.js#L12-L14) named `remote1`
```js
remote1: `remote1@http://localhost:6002/_next/static/${
  isServer ? 'ssr' : 'chunks'
}/remoteEntry_remote1.js`
```

And second, to have page `[...slug].js` in the way you want you "would have to use the low-level api as utils" like @ScriptedAlchemy  commented [here](https://github.com/module-federation/module-federation-examples/pull/2804#issuecomment-1460965561)

**Comment by gitneeraj** [comment]
Hi @ScriptedAlchemy

Could you please help me in resolving this above case or point me to the right link with the solution?

Just to re-iterate the issue, I have the `pages/[...slug].js` file in host app to catch all the routes that are exposed on remote apps and have them rendered. And I need the remote apps `getServerSideProps` to be executed when it is on host app with the `createFederatedCatchAll()` function.

Host - [https://github.com/gitneeraj/nextjs-mf-host](https://github.com/gitneeraj/nextjs-mf-host)
Remote1 - [https://github.com/gitneeraj/nextjs-mf-remote1](https://github.com/gitneeraj/nextjs-mf-remote1)

Please let me know to how fix this and let me know if you need more info. 

Thanks

**Comment by ScriptedAlchemy** [comment]
Ahh got it. You want dynamic remotes. It's possible. We would use the same concept but for get server props. So not a factory function.

**Comment by gitneeraj** [comment]
@ScriptedAlchemy 

I used the injectScript function in the `[...slug].js` file and I get the `getServerSideProps` function returned there.
```
// ./pages/[...slug].js
export default function CatchAll(initialProps) {
  // const { FederatedPage, ...props } = {
  //   ...initialProps
  // };
  // return (
  //   <ClientsWrapper>
  //     <FederatedPage {...props} />
  //   </ClientsWrapper>
  // );
  return <div>Catchall {JSON.stringify(initialProps)}</div>;
}
CatchAll.getInitialProps = async ctx => {
  const remote = 'app1';
  const mod = './pages/client';
  const container = await injectScript(remote);
  const FederatedPage = await container
    .get(mod)
    .then(factory => factory().default);

  const FederatedPageGSSP = await container.get(mod).then(factory =>
    factory()
      .getServerSideProps(ctx)
      .then(data => data)
  );
  if (FederatedPageGSSP) {
    return { ...FederatedPageGSSP, FederatedPage };
  }
  return {
    props: {}
  };
};
```
But I cannot figure out how can I return the FederatedPage. I tried like so above but it returns undefined.

Another way I was also trying to directly fetch the `getServerSideProps` from `FederatedCatchAll.getInitialProps` function placed in `createFederatedCatchAll` function of `./shared.js` file. But for some reason it isn't returning the `getServerSideProps` there. Below is the code
```
    FederatedCatchAll.getInitialProps = async ctx => {
      // Bot marks "req, res, AppTree" as unused but those are vital to not get circular-dependency error
      const { err, req, res, AppTree, ...props } = ctx;
      if (err) {
        // TODO: Run getInitialProps for error page
        return { renderError: true, ...props };
      }
      if (!process.browser) {
        role = getCookie('token', req?.headers?.cookie);

        return { needsReload: true, ...props, role, remotes };
      } else {
        role = cookieCutter.get('token');
      }

      // console.log('in browser', ctx.asPath);
      const matchedPage = await matchFederatedPage(ctx.asPath);

      try {
        // console.log('matchedPage', matchedPage);
        const remote = matchedPage?.value?.remote;
        const mod = matchedPage?.value?.module;
        // console.log(mod, 'mod');

        if (!remote || !mod) {
          // TODO: Run getInitialProps for 404 page
          return { render404: true, ...props };
        }

        // console.log('loading exposed module', mod, 'from remote', remote);
        const container = await injectScript(remote);
        const FederatedPage = await container
          .get(mod)
          .then(factory => factory().default);

        const container1 = await injectScript(remote);
        const FederatedPageGSSP = await container1
          .get(mod)
          .then(factory => factory());
        console.log(
          'FederatedPageGSSP',
          FederatedPageGSSP.getServerSideProps(ctx)  // <--- HERE `getServerSideProps` is undefined here, Why??
        );
        // console.log('FederatedPage', FederatedPage);
        if (!FederatedPage) {
          // TODO: Run getInitialProps for 404 page
          return { render404: true, ...props };
        }

        const modifiedContext = {
          ...ctx,
          query: matchedPage.params
        };
        const federatedPageProps =
          (await FederatedPage.getInitialProps?.(modifiedContext)) || {};
        return { ...federatedPageProps, FederatedPage, role, matchedPage };
      } catch (err) {
        console.log('err', err);
        // TODO: Run getInitialProps for error page
        return { renderError: true, ...props };
      }
    };

```

Please let me know how can I resolve this.

**Comment by gitneeraj** [comment]
I also tried with this PR https://github.com/module-federation/universe/pull/697 but it did not work. Please let me know what I am missing. Thanks a ton!

**Comment by gitneeraj** [comment]
> Ahh got it. You want dynamic remotes. It's possible. We would use the same concept but for get server props. So not a factory function.

Hi @ScriptedAlchemy Is it possible to elaborate on this. Am not sure what you meant by "_So not a factory function_" 

May be an example code snippet would help a lot here. Thanks!

**Comment by neerajtfo** [comment]
with nextjs-mf v6.3.0 and utilities v1.50 fixes the issue and can now execute `getServerSideProps` from server side.

**Comment by gitneeraj** [comment]
with nextjs-mf v6.3.0 and utilities v1.50 fixes the issue and can now execute `getServerSideProps` from server side.

**Comment by chaiyilin** [comment]
> with nextjs-mf v6.3.0 and utilities v1.50 fixes the issue and can now execute `getServerSideProps` from server side.

@gitneeraj what is the trick? could you post the sample code? thanks
