### ISSUE TITLE
Module federation remote if available or local alternetive (SSR + CSR)

### ISSUE THREAD

**Issue by expertup** [module-federation/module-federation-examples#2944]
I have a website with micro services that I load remotely. I want to add an exception handler and load an alternative local component when a given microservice is temporarily down.

E.g. login page:
when the login microservice is enabled, the form will be visible. Otherwise, there should be a message "come back later" in this place.

Below are the key code snippets.

Question: how to solve the problem of alternate loading of component content? I would like the availability of the remote component to be checked each time the website is accessed, not only when the main service is started.

Part:
```
(fetch("http://localhost:3002/server/remoteEntry.js"))
    ?'app2@http://localhost:3002/server/remoteEntry.js' //if available, load the remote version for the server
    :'./err/errors.js', //if not available, load the local version for the server
```
is to illustrate what I want to have.

app/index.js:

```
import React from 'react';
import loadable from '@loadable/component';
     
const Login_Register = loadable(() => import('app2/Login_Register'), {
  fallback: <div>loading content...</div>,
});

//Login_Register.load().then((ee)=>{console.log(ee.default() != null);});
    
function App() {
  return (
    <>
      gggg
        <Login_Register />
      fghfghfgh
    </>
  )
}

export default App;
```

moduleFederation.js:

    const { dependencies } = require('./package.json');
    const { ModuleFederationPlugin } = require('webpack').container;
    const { NodeFederationPlugin, StreamingTargetPlugin } = require('@module-federation/node');
    const { FederationStatsPlugin } = require('@mf/loadable-adapters');
    const FederationModuleIdPlugin = require("webpack-federation-module-id-plugin");
    
    function lazyLoadRemoteClient(remoteUrl, appName) {
      return `promise new Promise(resolve => {
      const script = document.createElement('script')
      script.src = '${remoteUrl}'
    
      console.log('lazyLoadRemote', script.src);
    
      script.onload = () => {
        // the injected script has loaded and is available on window
        // we can now resolve this Promise
        const proxy = {
          get: (request) => window.${appName}.get(request),
          init: (arg) => {
            try {
              return window.${appName}.init(arg)
            } catch(e) {
              console.log('remote container already initialized', e)
            }
          }
        }
        resolve(proxy)
      }
      // inject this script with the src set to the versioned remoteEntry.js
      document.head.appendChild(script);
    })`;
    }
    
    function lazyLoadRemoteServer(remoteUrl, appName) {
      return `promise new Promise((resolve, reject) => {
        fetch('${remoteUrl}')
          .then((response) => {
            if (!response) {
              throw Error(response.statusText);
            }
            response;
          })
          .then(function (response) {
            resolve(resopnse.text());
          }).catch(function (error) {
            promise Promise.resolve().then(() =>  import('./../../error/errors.js').then(({ default: render }) => render))
          });
      }); `
    }
    
    
    
    module.exports = {
      client: [
        new FederationStatsPlugin(),
        new FederationModuleIdPlugin(),
        new ModuleFederationPlugin({
          name: 'app1',
          filename: 'remoteEntry.js',
          remotes: {
            app2: (fetch("http://localhost:3002/server/remoteEntry.js"))
                  ?'app2@http://localhost:3002/server/remoteEntry.js' //if available, load the remote version for the client
                  :'./err/errors.js', //if not available, load the local version for the client
          },
        }),
      ],
      server: [
        new NodeFederationPlugin({
          name: 'app1',
          filename: 'remoteEntry.js',
          library: { type: 'commonjs-module' },
          //runtime: false,
          remotes: {
            app2: (fetch("http://localhost:3002/server/remoteEntry.js"))
                  ?'app2@http://localhost:3002/server/remoteEntry.js' //if available, load the remote version for the server
                  :'./err/errors.js', //if not available, load the local version for the server
          },
          shared: [
            {
              react: {
                requiredVersion: dependencies.react,
                singleton: true,
                eager: true,
              },
              'react-dom': {
                requiredVersion: dependencies['react-dom'],
                eager: false,
                singleton: true,
              },
            },
          ],
        }),
        new StreamingTargetPlugin({
          name: 'app1',
          library: { type: 'commonjs-module' },
          remotes: {
            app2: (fetch("http://localhost:3002/server/remoteEntry.js"))
                  ?'app2@http://localhost:3002/server/remoteEntry.js' //if available, load the remote version for the server
                  :'./err/errors.js', //if not available, load the local version for the server
          },
        }),
      ],
    };

**Comment by Carduelis** [comment]
Am I correct, you have managed to dynamically (in runtime) load Modules in the browser **and** on server?
Or it is the actual topic of how to make the `advanced-api/dynamic-remotes` [example](https://github.com/module-federation/module-federation-examples) to support SSR too?

I'm also struggling with SSR part. I do not understand, how to load modules not via `<script>` tag, but also on the server using `node-fetch` or similar.

**Comment by Carduelis** [comment]
@ScriptedAlchemy Can you help us to use Dynamic Module Federation supporting SSR too, please?

**Comment by expertup** [comment]
> Am I correct, you have managed to dynamically (in runtime) load Modules in the browser **and** on server? Or it is the actual topic of how to make the `advanced-api/dynamic-remotes` [example](https://github.com/module-federation/module-federation-examples) to support SSR too?
> 
> I'm also struggling with SSR part. I do not understand, how to load modules not via `<script>` tag, but also on the server using `node-fetch` or similar.

I was based on this example:
https://github.com/module-federation/module-federation-examples/tree/master/loadable-react-18

I am looking for how to load modules dynamically, on the fly, not just when starting the process. Especially in SSR, because this CSR fetches the `remoteEntry.js` file via <script> on browser refresh or dynamic load. But SSR loads data once and for all, and even when the microservice turns off, it still displays the content as if it was "on".

Just downloading the `remoteEntry.js` file via e.g. fetch does not give a result, because it needs to be properly processed under `moduleFederation` (if I understand it correctly) - and here the stairs begin. Because I would like to have the option (in case of disabling the remote microservice) to load a local component as a "replacement".

**Comment by Carduelis** [comment]
@expertup yep. I seek the same solution, tho, based on the:
1. [advanced-api/dynamic-remotes](https://github.com/module-federation/module-federation-examples/tree/master/advanced-api/dynamic-remotes)
2. [react-18-ssr](https://github.com/module-federation/module-federation-examples/tree/master/react-18-ssr)

I believe there is no need for `loadable` since React 18 supports `lazy()` in SSR, so, we can make the setup a little bit cleaner.
At the same time, I could not find a solution for SSR Dynamic Federation.

-----
Basically, what I'm trying to achieve is:
#### Ability to release a new version of a Remote Microfrontend without rebuilding a Host Microfrontend and solve a cache problem (content-hash should help) on SSR with Rehydration during CSR.
-----

1. We can either have `<RemoteComponent url="aws.s3.bucket/{content-hash}" app="product" module="Image" />` that uses `lazy` with SSR and consume the `content-hash` directly from HTML to avoid `useEffect`. So we need to teach our server to get those remote urls somehow and inject in HTML.
2. Or `remotes: { product: fetchUrlDuringRuntime }` with static `module-federation-remotes.json` consumption on the fly. and then use `lazy(() => import('product/Image'))`

Idk, maybe I miss something in the examples 1. and 2., but the idea, I hope, is clear.

**Comment by expertup** [comment]
> 1. advanced-api/dynamic-remotes

This idea look interesting, about loading components from code, not from webpack module federation. But load component to `window` will make problem, because on SSR You haven't window...

And a lot of examples are on Next or Angular...

**Comment by Carduelis** [comment]
> because on SSR You haven't window...

True, on CSR `remoteEntry.js` is mounting in runtime in HTML as `<script>` tag. Then a browser evaluates it, and we can execute `init()` or `run()` methods. Same thing we need to emulate on nodejs environment using `/server/remoteEntry.js`. 

Any ideas @ScriptedAlchemy ? 🙏

**Comment by expertup** [comment]
> > because on SSR You haven't window...
> 
> True, on CSR `remoteEntry.js` is mounting in runtime in HTML as `<script>` tag. Then a browser evaluates it, and we can execute `init()` or `run()` methods. Same thing we need to emulate on nodejs environment using `/server/remoteEntry.js`.
> 
> Any ideas @ScriptedAlchemy ? 🙏

I found and tested this resolve, but this isn't working:
https://github.com/module-federation/module-federation-examples/issues/399#issuecomment-744305275
```
const remote = `new Promise(async resolve => {
  const content =  await someFetchFunction('http://hostname/appB/b-entry.js')
  const chunk = {}
  require('vm').runInThisContext('(function(exports, require, __dirname, __filename) {' + content + '\\n})')(chunk, require, 'some-fake-path', 'b-entry.js');
  resolve(chunk)
})`

    new webpack.container.ModuleFederationPlugin({
      remotes: {
        'b-entry': `promise ${remote}`
      },
    }),
```

My code:
```
const remote = `new Promise(async resolve => {
  const content =  await fetch('http://localhost:3002/server/remoteEntry.js');
  const data = await content.text();
  const chunk = {}
  require('vm').runInThisContext('(function(exports, require, __dirname, __filename) {' + data + '\\n})')(chunk, require, 'app2', 'remoteEntry.js');
  resolve(chunk)
})`
......
new NodeFederationPlugin({
      name: 'app1',
      filename: 'remoteEntry.js',
      library: { type: 'commonjs-module' },
      //runtime: false,
      remotes: {
        app2: `promise ${remote}`
      },
      shared: [
        {
          react: {
            requiredVersion: dependencies.react,
            singleton: true,
            eager: true,
          },
          'react-dom': {
            requiredVersion: dependencies['react-dom'],
            eager: false,
            singleton: true,
          },
        },
      ],
    }),
    new StreamingTargetPlugin({
      name: 'app1',
      library: { type: 'commonjs-module' },
      remotes: {
        app2: `promise ${remote}`
      },
    }),
```

This library make "virtual machine" to emulate javascript code. But I had error:

```
server (webpack 5.75.0) compiled successfully in 5145 ms
[2023-04-12T14:30:13.740Z] App1 is running: 🌎 http://localhost:1234
(node:3546185) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
evalmachine.<anonymous>:3352
/******/        module.exports = __webpack_exports__;
                ^

ReferenceError: module is not defined
    at evalmachine.<anonymous>:3352:11
    at evalmachine.<anonymous>:3354:12
    at /new_moduleFederation/host/build/server/app.js:6907:105
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.7.0
```

Maybe need to do some configuration of the VM to node so that it handles the code from an external micro service 🤔

**Comment by ScriptedAlchemy** [comment]
Consider looking at delegate modules, my version 7 PR on /universe repo has some elegant ways to handle glue code between runtimes

**Comment by Carduelis** [comment]
I guess, the mentioned PR is this one https://github.com/module-federation/universe/tree/v7

**Comment by xAmaris** [comment]
Hi @ScriptedAlchemy,
`injectScript` utility works great to fetch dynamic remote on runtime from server but now since I'm using [dynamic remote containers](https://webpack.js.org/concepts/module-federation/#dynamic-remote-containers) on client-side which is async and requires using useEffect, I wonder how then could this be shown synchronously on init on client-side to avoid SSR mismatch. 

I saw your article mentioning [custom HTML to React code parser](https://scriptedalchemy.medium.com/server-side-rendering-tactics-for-federated-applications-765ec675d188#:~:text=custom%20parser%20to%20convert%20the%20HTML%20back%20into%20primitive%20react%20code) but is this still viable solution or maybe your current approach on[ v7](https://github.com/module-federation/universe/tree/v7) and delegate modules is somehow changing possible approaches.
 Would greatly appreciate an answer 🙏  🙇
