### ISSUE TITLE
Dynamic loading SSR modules

### ISSUE THREAD

**Issue by RussianDragon** [module-federation/module-federation-examples#2945]
Hi.
I have a problem with dynamic loading of server modules on Node.
My first problem. I don't understand how right load remote script.
Of course I can use "eval" but I'm not sure if that's correct.

```
fetch(`${info.url}/server/remoteEntry.js`)
  .then((res) => res.text())
  .then((code) => {
     eval(code);
     //vm.runInThisContext(scriptStr);
   });
```

My second problem. I don't understand how to use the component.
The documentation only says the browser version, but not Node.
```
private static async loadDynamicOutputInNode<T>(
    scope: string,
    path: string
  ): Promise<T | null> {
    await __webpack_init_sharing__("default");
    const container = global[scope];
    if (!container) {
      return null;
    }
    await container.init(__webpack_share_scopes__.default);
    const factory = await global[scope].get(`./${path}`);
    const externalModule = factory();
    return externalModule.default;
  }
```

Please, tell me, how to create a dynamically loaded module on the server.

**Comment by sood21-js** [comment]
used FlushedChunks from utils for preload chunck on server in your _document.tsx

`import React from 'react';
import Document, { Html, Head, Main, NextScript } from 'next/document';
import { revalidate, FlushedChunks, flushChunks } from '@module-federation/nextjs-mf/utils';
import { AnyType } from '@centra/centra-ui';

export default class MyDocument extends Document {
  static async getInitialProps(ctx: AnyType) {
    const initialProps = await Document.getInitialProps(ctx);
    const chunks = await flushChunks();
    ctx?.res?.on('finish', () => {
      revalidate().then((shouldUpdate) => {
        console.log('finished sending response', shouldUpdate);
      });
    });

    return {
      ...initialProps,
      chunks,
    };
  }

  render() {
    return (
      <Html lang="en">
        <Head>
          {/**@ts-ignore */}
          <FlushedChunks chunks={this.props.chunks} />
          {/* PWA primary color */}
          <meta name="theme-color" content={'#000'} />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}`
