### ISSUE TITLE
[@module-federation/native-federation-typescript] Enable support for remotes with versions (url/{version}/remoteEntry.js)

### ISSUE THREAD

**Issue by felipemotarocha** [module-federation/module-federation-examples#2949]
I am using a `remote` which has different versions. Each version is stored within a folder in a S3 Bucket. So, we have:

0.1.0/remoteEntry.js
0.1.0/@mf-types.zip

0.2.0/remoteEntry.js
0.2.0/@mf-types.zip

And so on.

The problem is: if I set `typesFolder` to `0.1.0/@mf-types.zip` in the plugin config in order to download the correct zip folder, the library downloads the type definitions to the `0.1.0/@mf-types` folder in my host's repository:

![image](https://user-images.githubusercontent.com/5685113/232122449-e88da551-8d7d-4d12-99a4-3cd3134e8380.png)

I wish I could define an out dir manually, in order to store the type definitions within a `@mf-types` folder inside my host's repository. I think this flexibility is crucial to anyone who is using the library alongside versioned remotes.

My module federation configuration:

```
 const moduleFederationConfig = {
    name: 'environment_and_printers',
    filename: 'remoteEntry.js',
    shared: {
      react: {
        singleton: true,
        requiredVersion: dependencies.react
      },
      'react-dom': {
        singleton: true,
        requiredVersion: dependencies['react-dom']
      }
    },
    remotes: {
      ui_components: `ui_components@https://ui-components-mfe.development.zak.app/0.1.0/remoteEntry.js`
    },
    exposes: {
      './EnvironmentAndPrinters':
        './src/modules/environment-and-printers/environment-and-printers.module'
    }
  }
```

Do you suggest any workaround? Thanks.

**Comment by ilteoood** [comment]
Hi,
In my opinion you could remove the "typesFolder" for the host plugin and achieve the result you need by modifiying the devServer.static.directory on your remote
