### ISSUE TITLE
Mount a remote React component into a vanilla host

### ISSUE THREAD

**Issue by oravecz** [module-federation/module-federation-examples#2954]
I went through the examples, but did not find an example of a Vanilla host.

Is it possible to load a remote React component and mount it into a vanilla JS host? Like a host without any React dependencies of its own, and doesn't even use the ModuleFederationPlugin.

**Comment by oravecz** [comment]
I think I figured out the broad strokes. The trick is to force the imported remote to bootstrap React, instead of depending on the host to do that step.

**host.ts**
- Contains no dependencies on React* or Module Federation plugin
- Does utilize importRemote from @module-federation/utilities
```ts
const component = await importRemote(
    url: 'https://example.org/path/to/remote',
    scope: 'app1',
    module: 'App',
);

const rootNode = document.querySelector('root');

// @ts-ignore
component.default(rootNode);
```

**remote_bootstrap.js**
```js
import React from 'react';
import {render} from 'react-dom';
import App from './App';

export default (rootNode) => {
   render(<App />, rootNode);
}
```

**webpack.config.js**
```js
...
    new ModuleFederationPlugin({
      name: 'app1',
      filename: 'remoteEntry.js',
      exposes: {
        './App': './src/remote_bootstrap',
      },
...
```

**Comment by ScriptedAlchemy** [comment]
Yep that'll work.

**Comment by oravecz** [comment]
When I build the host using `webpack --mode production`, my minified code no longer contains `__webpack_require__.l()` function resulting in a `l is not a function` error at runtime when attempting to execute `importRemote(...)`.

Is it possible this is being tree shaken out of my production build? I tried adding an empty `ModuleFederationPlugin` to my vanilla host in the hope this would trigger the retaining of the full complement of `__webpack_require__` functions. I should note that several properties _do_ exist on `__webpack_require__`, but not the one that enables the loading of the remote component.

**Comment by oravecz** [comment]
Webpack is tree-shaking the `__webpack_require__.l()` function in a production build.

This is a duplicate of:
https://github.com/module-federation/universe/issues/551
