### ISSUE TITLE
vite-vue module federation  - file not found error

### ISSUE THREAD

**Issue by SuperMohit** [module-federation/module-federation-examples#2959]
I am trying to serve a vue3 module with vite but landing on the following issue.

`Failed to load url vue (resolved id: vue) in C:/Users/c/code/photon_ui/apps/vite-vue-microfrontends/remote/src/bootstrap.ts. Does the file exist? (x10)`

`Failed to load url pinia (resolved id: pinia) in C:/Users/c/code/photon_ui/apps/vite-vue-microfrontends/remote/src/bootstrap.ts. Does the file exist?`

**vite config:**
```
export default defineConfig(async ({ command }) => ({
  server: {
    fs: {
      allow: [".", "../shared"],
    },
  },
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  },
  plugins: [
    await federation({
      options: {
        workspaceRoot: __dirname,
        outputPath: "dist",
        tsConfig: "tsconfig.json",
        federationConfig: "module-federation/federation.config.cjs",
        verbose: true,
        dev: command === "serve",
      },
      adapter: createEsBuildAdapter({ plugins: [pluginVue()] }),
    }),
    vue(),
    vueJsx(),
  ],
}));
```

**Comment by gioboa** [comment]
Hi @SuperMohit please move vue as devDependency in your package.json and try again. let me know
