### ISSUE TITLE
nextjs ssr - federated page doesn't hot reload in host on remote rebuild & restart

### ISSUE THREAD

**Issue by shivak12004** [module-federation/module-federation-examples#2972]
Hi,

I followed the [nextjs-ssr](https://github.com/module-federation/module-federation-examples/tree/master/nextjs-ssr) example and https://github.com/module-federation/module-federation-examples/issues/2832 to recreate a nextjs ssr example.

The ssr works great on initial load, however, if I make a change to a page in the remote and restart the remote, the federated page in the host doesn't reflect the changes on the server but does in the client which ends up with the following errors:

Text content does not match server-rendered HTML.

There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.

If I restart the host as well, then it takes the change. I'd expect the change to be reflected in the host without having to restart the host app

![Screen Shot 2023-04-19 at 5 29 41 PM](https://user-images.githubusercontent.com/120568599/233227281-0c59304d-575a-4bf3-b8c4-5a93320aea59.png)

Following is how I'm using it
Host app next-config
<img width="1148" alt="Screen Shot 2023-04-19 at 5 31 26 PM" src="https://user-images.githubusercontent.com/120568599/233227463-e5b04ba9-cac2-4071-ab03-35d225dd353f.png">

Federated page in host app (pages/catalog)
<img width="775" alt="Screen Shot 2023-04-19 at 5 31 56 PM" src="https://user-images.githubusercontent.com/120568599/233227535-69d47813-c419-49ad-8453-369cde42fa9e.png">

Remote app next-config
<img width="1092" alt="Screen Shot 2023-04-19 at 5 32 56 PM" src="https://user-images.githubusercontent.com/120568599/233227597-b5c0c768-0ba8-4bc5-8b13-e7f0f62b9850.png">

Remote app page
<img width="836" alt="Screen Shot 2023-04-19 at 5 32 43 PM" src="https://user-images.githubusercontent.com/120568599/233227610-feca3b53-af82-4efd-99d9-d0536b276d95.png">

Thanks for the help

**Comment by paribhasika** [comment]
Have you tried the `revalidate` util from the latest release?
https://github.com/module-federation/universe/tree/main/packages/nextjs-mf#utilities

**Comment by shivak12004** [comment]
Thank you for the response @paribhasika It looks like the revalidate has to happen, I assume restarting the host is on us. and the package itself isn't responsible for it?

Is there an example of a nextjs host that restarts on remote restart.

I tried adding the above example to host/pages/_document.js but no luck even with Flushchunks included.

**Comment by ScriptedAlchemy** [comment]
You should not need to restart the host. I'm working on a new major update which should improve this. 

Do you use express server by any chance? Express custom server needs an additional thing to flush its route stack in middleware

**Comment by shivak12004** [comment]
No. just the default server with nextjs app. Curious to know how remote restart will restart host server?

**Comment by ScriptedAlchemy** [comment]
Revalidate gets the hash of remote and deletes require cache

**Comment by stevebrowndotco** [comment]
Hello, i am using NextJs and if I make a change on a remote ONLY, the reload on the host does not seem to happen in production meaning that currently we have to refresh the host to fix the hydration issues (its "new" on the client but "old" on the server).

In my index.tsx I have this code:

```typescript
export async function getServerSideProps(context: GetServerSidePropsContext) {
    context?.res?.on('finish', () => {
        revalidate().then(shouldUpdate => {
            console.log('finished sending response', shouldUpdate);
        });
    });

    // @ts-expect-error TODO: support types for importing MF
    const page = await import('plp/index');

    if (page.getServerSideProps) {
        return page.getServerSideProps(context);
    }

}
```

Just wondering If I have done something wrong...

Edit: Have also moved to _document.tsx like in the example. In localhost development it **works** and the console.log is `true` when a remote federated module has changed. However in production, it's always `false`.

By the way, in production it is a nextJs standalone server (but not custom)
