### ISSUE TITLE
Multiple Dynamic Remotes with Same Name

### ISSUE THREAD

**Issue by raunakdoesdev** [module-federation/module-federation-examples#3040]
I had a question - not sure if this is the best place for it. If for some reason, I need to load multiple dynamic remotes that are distinct but have the same name specified in the ModuleFederation config in `webpack.config.js` how could I go about loading these in?

I imagine it's some mucking around with this function:
```
function loadComponent(scope: string, module: string) {
  return async () => {
    await __webpack_init_sharing__("default");
    // @ts-ignore
    const container = window[scope]; // or get the container somewhere else
    await container.init(__webpack_share_scopes__.default);
    // @ts-ignore
    const factory = await window[scope].get(module);
    const Module = factory();
    return Module;
  };
}
```

I was thinking to maybe call the above and then rename then move window[scope] to some custom name like this:
```
window[newScope] = window[scope];
delete window[scope];
```

This seems naive though so wanted to run it by this community first.

Aside:
The reason they need to have the same name is that I am packaging the prebuilt federated module into a python library. Seems hard to change the name after compiling the webpack down.

**Comment by ScriptedAlchemy** [comment]
Id suggest against it, but You also need to clear the webpackChunkLoadingGlobal as well as thats where the chunks are cached. open one of your chunks and youll see the chunkLoadGlobal.push([name],modules,runtime) - delete the global too
