### ISSUE TITLE
can't vue2 and vue3 be used as remote apps in react (container)?

### ISSUE THREAD

**Issue by taylous** [module-federation/module-federation-examples#3047]
load remote apps (vue2, vue3) in container (react v17) through module federation.

however, when I load vue2 app and load vue3 app, an error occurs. (An error occurs even if it is reversed.)

the error code displayed on the console is as follows.

```
TypeError: Cannot read properties of undefined (reading 'warn')
    at 6986 (index.mjs:6:12)
    at t (bootstrap:19:32)
    at sharing:42:130
    at t.m.<computed> (consumes:188:23)
    at t (bootstrap:19:32)
    at 2156 (156.62a56741.js:1:164907)
    at t (bootstrap:19:32)
    at container-entry:3:83
    at t.m.<computed> (remotes loading:57:23)
    at t (bootstrap:19:32)
```
looking up what warn is here in index.mjs... It comes out as `var warn = Vue.util.warn`.

what I'm wondering is,
1. if the installed module is supported by vue2 but not supported by vue3, can there be a problem with module federation?
2. even if the vue version of the remote app is different, each chunk file will be created. Does the remote have any effect?

any advice would be appreciated. 😭

**Comment by gioboa** [comment]
I created Vue2 and Vue3 examples. 
Here is the repo 
https://github.com/gioboa/vue-microfrontend-demo
You can find Vue 2 in a specific branch of this repo
