### ISSUE TITLE
react-hmr demo error

### ISSUE THREAD

**Issue by MakeBetterMe** [module-federation/module-federation-examples#3061]
When I use the react-hmr demo, everything works and hmr is active, but when I set the library: {type: "global", name: 'remote1'} for the ModuleFederationPlugin in remote1, I have a problem; here's what I did demo project and the screenshot of the error report, please take a look

<img width="762" alt="image" src="https://github.com/module-federation/module-federation-examples/assets/10847591/c59d1dea-353d-495c-9374-e9db747251fc">

demo: [react-hmr.zip](https://github.com/module-federation/module-federation-examples/files/11662965/react-hmr.zip)

**Comment by ScriptedAlchemy** [comment]
ByteDance has solved hmr, it will be released into https://modernjs.dev in the next week or two.
