### ISSUE TITLE
Compability @module-federation/nextjs-mf with serverless components

### ISSUE THREAD

**Issue by ronaldozup** [module-federation/module-federation-examples#3066]
Hi!

The plugin "@module-federation/nextjs-mf" is compatible with "sls-next/serverless-component"? 

When i try to setting @module-federation/nextjs-mf in my next.config.js i have some problems with deployed lambdas. It looks like something is missing in webpack.

Thanks for any help.

**Comment by ScriptedAlchemy** [comment]
npm install webpack or ensure that your trace in sls is copying over webpack. next ships its own bundled copy of webpack which doesnt provide deep imports required to make the plugin function at runtime, since i depend on several utilities from within webpack itself
