### ISSUE TITLE
HMR does not work when using the dynamic remote module 

### ISSUE THREAD

**Issue by KawayAlpaka** [module-federation/module-federation-examples#3068]
Based on the 'react-hmr' example and the 'dynamic-system-host' example. clone remote1 to remote2. import remote2 like this, the HMR does not work. interest is, if import another expose from 'remote2' in front of this file, like 'remote2/Button', it will work.

```javasrcipt
import React from 'libs/react';
import { importRemote } from '@module-federation/utilities/src/utils/importRemote';

// import Button2 from 'remote2/Button';

function System() {
  const Component = React.lazy(() => importRemote({
    url: "http://localhost:3003",
    scope:"remote2", 
    module:"./App"
  }));

  return (
    <React.Suspense fallback="Loading System">
      <Component />
    </React.Suspense>
  );
}
```
the full code in the demo1 branch
```
https://github.com/KawayAlpaka/mf-hmr-dynamic-example
```

**Comment by ScriptedAlchemy** [comment]
hmr of the host? like when changing files on the host its own hmr doesnt work? or are you changing the remote and expecting it to hmr the host

**Comment by KawayAlpaka** [comment]
changing the remote and expecting it to hmr the remoteComponent in the host.
![hmr](https://github.com/module-federation/module-federation-examples/assets/13232471/6085ad31-a736-4d9e-a40f-7d8581f7c6c8)

**Comment by wibed** [comment]
> changing the remote and expecting it to hmr the remoteComponent in the host.


do you have a repro or do you use the example and apply hmr to it?

**Comment by KawayAlpaka** [comment]
My repro:
```
https://github.com/KawayAlpaka/mf-hmr-dynamic-example/blob/demo1/host/src/remotes/remote2.js
```

it is base on ```https://github.com/module-federation/module-federation-examples/tree/master/react-hmr```, and then apply  ```https://github.com/module-federation/module-federation-examples/tree/master/dynamic-system-host``` to it

**Comment by ScriptedAlchemy** [comment]
ByteDance has solved HMR, it will be released into https://modernjs.dev in the next 2-3 weeks.
