### ISSUE TITLE
Singleton Angular service for all micro frontends

### ISSUE THREAD

**Issue by Xerathron** [module-federation/module-federation-examples#3100]
Hey,
currently im struggle to create an angular service that is a singleton for all micro frontends. For details you can find the code [in my repo](https://github.com/Xerathron/ModuleFederationExample_Angular_MF_Service_Problem)

## Problem
I have two mfs that getting injected by one service laying in a shared library. This service should be a singleton by setting the `providedIn: 'platform'` flag. But its not. Both mfs holding an isolated service instance.  

## Expected behaviour
It exists only serivce one single instance for all mfs. The Button component only getting injected by these single instance. All buttons have the same state. 

## Current behaviour
The button in the shell component is isolated from the other three buttons due to the mf has its own service.
![Peek 2023-07-02 18-54](https://github.com/module-federation/module-federation-examples/assets/37848084/350c344e-b1bf-45bb-8e41-663076af2640)

## Description

The whole project is simple treeshaked version of the [Angular 15 example](https://github.com/module-federation/module-federation-examples/tree/master/angular15-microfrontends-lazy-components). It contains two mfs that load a Button-Component from the shared library. It displays the state by setting a css class active or not based on the state. On button click it triggers the injected service to switch the boolean value. 

#### Service:
```
@Injectable({
  providedIn: 'platform',
})
export class MdmfSharedService {
  private subject = new ReplaySubject<boolean>(1);
  public observer = this.subject.asObservable();
  
  private subjectState = false;
  
  constructor() {}

  setClick() {
    this.subjectState = !this.subjectState;
    this.subject.next(this.subjectState);
  }
}

```

#### Button Component
```
@Component({
    selector: 'app-button',
    templateUrl: './button.component.html',
    styleUrls: ['./button.component.css'],
  })
  export class ButtonComponent implements OnInit {
  
    btnClicked: boolean = false;
  
    constructor(private service: MdmfSharedService) {
    }

    ngOnInit(): void {
        this.service.observer.subscribe(data => this.btnClicked = data);
    }

    clicked() {
        this.service.setClick();
    }
}
``` 

This Problem is also described by #904. I followed the suggestions from @ScriptedAlchemy but this doesn´t worked for me so far. Do you guys have any idea?

**Comment by Xerathron** [comment]
In the comments for Angular provider I found this: 

---
**NOTE**

A lazy-loaded module has its own injector, typically a child of the app root injector. Lazy-loaded services are scoped to the lazy-loaded module's injector. If a lazy-loaded module also provides the UserService, any component created within that module's context (such as by router navigation) gets the local instance of the service, not the instance in the root injector. Components in external modules continue to receive the instance provided by their injectors.

---

Seems like there is no current solution for this?
My current workaround is to use CustomEvents to inform other MFs

**Comment by bh3605** [comment]
Make sure your angular apps are using the same version of angular and using it as a shared dependency. That way they reference the same platform.
