### ISSUE TITLE
Next.js Text content does not match server-rendered HTML

### ISSUE THREAD

**Issue by artbelikov** [module-federation/module-federation-examples#3111]
Hi!
On a freshly cloned example nextjs-ssr-delegate-modules and nextjs-ssr (maybe more, haven't checked) an error appears about ssr and csr text mismatch after I change something inside, for example, "checkout" subdir.

Both development and production modes suffers from this. Only complete restart resolves it.
Is there anything I can do?
Thank you.

<img width="956" alt="Screenshot 2023-07-09 at 16 01 33" src="https://github.com/module-federation/module-federation-examples/assets/9851825/92f2ee2e-e377-45e9-9d3d-139dd94fa363">

**Comment by ScriptedAlchemy** [comment]
ill double check my revalidate() logic. Also delegates was in beta in v6 and that demo has not yet been updated to v7 where delegates are the default way of operation both internally and in userland.

**Comment by ScriptedAlchemy** [comment]
if you refresh the page a second time after this error, does it still have hydration issues?

**Comment by vcheeze** [comment]
I'm getting a similar hydration error with the Next.js v13 example. Any idea why this is happening @ScriptedAlchemy?

<img width="959" alt="Screenshot 2023-08-11 at 7 31 09 PM" src="https://github.com/module-federation/module-federation-examples/assets/17358717/c7182503-d6da-46c1-a8a7-ccdf681eea6a">

**Comment by ScriptedAlchemy** [comment]
use react lazy not next dynamic for remote imports
