### ISSUE TITLE
Cannot recognize promise remotes address in the right way

### ISSUE THREAD

**Issue by stone333** [module-federation/module-federation-examples#3113]
when i use 
`const { NativeFederationTypeScriptHost } = require('@module-federation/native-federation-typescript/webpack')
const { NativeFederationTestsHost } = require('@module-federation/native-federation-tests/webpack')`
` remotes: {
    itsmshared: `promise new Promise(resolve => {
          const remoteUrlWithVersion = 'http://localhost:8080/remoteEntry.js'
          const script = document.createElement('script')
          script.src = remoteUrlWithVersion
          script.onload = () => {
            // the injected script has loaded and is available on window
            // we can now resolve this Promise
            const proxy = {
              get: (request) => window.itsmshared.get(request),
              init: (arg) => {
                console.log('arg',arg)
                try {
                  return window.itsmshared.init(arg)
                } catch(e) {
                  console.log('remote container already initialized')
                }
              }
            }
            resolve(proxy)
          }
          // inject this script with the src set to the versioned remoteEntry.js
          document.head.appendChild(script);
        })
        `,
  },`

it well tell error message
![image](https://github.com/module-federation/module-federation-examples/assets/38901220/320f29b5-fc20-4b59-9f88-911f2d06ea6f)

**Comment by ScriptedAlchemy** [comment]
console log the url and see wha is actually getting
