### ISSUE TITLE
@loadable not working with StreamingTargetPlugin plugin

### ISSUE THREAD

**Issue by saifislamrepos** [module-federation/module-federation-examples#3121]
when adding StreamingTargetPlugin as it is updating the chunkLoading = 'async-node' so @loadable/compoents is not working with this with react ssr error: "loadable-components: failed to synchronously load component, which expected to be available "
example shared in the repo module-federation examples/loadable-react 16 is first loading the LoadableButton without loadable that's why its working there, is there any workaround?

**Comment by ScriptedAlchemy** [comment]
@brunos3d may have one

**Comment by ScriptedAlchemy** [comment]
https://modernjs.dev will support this properly - not sure if it can be extracted to oss as standalone tho
