### ISSUE TITLE
Compilation Problems During Build

### ISSUE THREAD

**Issue by umgu** [module-federation/module-federation-examples#3129]
Thank you for your work, I tried the below example and it seems to work fine.
[https://github.com/module-federation/module-federation-examples/tree/master/nextjs-v13](url)

But not able to create build, getting some errors related to webpack while running command 'npm run build'
![ss](https://github.com/module-federation/module-federation-examples/assets/96438212/d63c2a9d-2f23-4e04-adc0-cb6b934f014b)

**Comment by ScriptedAlchemy** [comment]
should be fixed, ensure mf packages are up to date
