### ISSUE TITLE
Navigate from one app to another app

### ISSUE THREAD

**Issue by AmeyKhoje** [module-federation/module-federation-examples#3131]
Hello,
I have implemented same routing in my boilerplate.
How to navigate from one app to another app is not provided.
I have tried some possible ways but not successful.

Is there any suggestions for implementing this ?

**Comment by gitnupur** [comment]
https://github.com/module-federation/module-federation-examples/tree/master/react-nested-routers

**Comment by gitnupur** [comment]
> Hello, I have implemented same routing in my boilerplate. How to navigate from one app to another app is not provided. I have tried some possible ways but not successful.
> 
> Is there any suggestions for implementing this ?

Check this, app routing is available. 
https://github.com/jagadish-k/routing-module-federation - This is using Browsing Router in both shell and remote apps.

Here one Browser Router is used. 
It is available [in the link that I have provided earlier](https://github.com/module-federation/module-federation-examples/tree/master/react-nested-routers) as well.

**Comment by ScriptedAlchemy** [comment]
Modernjs.dev/en would provide the best experience for federation
