### ISSUE TITLE
Component renders only when link is clicked, browsing directly doesnt load the component in case of using dynamic remots.

### ISSUE THREAD

**Issue by gitnupur** [module-federation/module-federation-examples#3134]
[routing-module-federation.zip](https://github.com/module-federation/module-federation-examples/files/12422479/routing-module-federation.zip)
I am using lazy loading in the above example. There is no link tab in host app. http://localhost:8000 is the host. and child component can be loaded directly by typing http://localhost:800/admin in the browser.
<img width="335" alt="working solution" src="https://github.com/module-federation/module-federation-examples/assets/113530765/088c9484-edae-4052-8d9a-65270da94fba">

[routing-module-typescript-federation.zip](https://github.com/module-federation/module-federation-examples/files/12422495/routing-module-typescript-federation.zip)

In the above example I am using dynamic routes. The child component only loads on clicking the link . else it does not load.

Kindly help.

**Comment by ScriptedAlchemy** [comment]
provide git repo i can inspect
