### ISSUE TITLE
Help: Example with Angular host and Next JS remote

### ISSUE THREAD

**Issue by peplocanto** [module-federation/module-federation-examples#3144]
Hi there,
as per title I need help with the integration of a Next JS app/component into an Angular host.
I tried - practically - everything but nothing seems to work.

##### Setup
- Host: Angular 15 w/ `@angular-architects/module-federation` plugins. Everything works with angular and react (web components are generated with `@r2wc/react-to-web-component`) remotes.
This is host `webpack.config` file:
```js
module.exports = merge(
  withModuleFederationPlugin({
    shared: {
      ...shareAll({
        singleton: true,
        strictVersion: true,
        requiredVersion: 'auto',
      }),
    },
  }),
  {
    experiments: {
      topLevelAwait: true,
    },
    output: {
      uniqueName: 'host',
      publicPath: 'auto',
      scriptType: 'text/javascript',
    }
  }
);
```

- Remote: Next JS 13 w/ `@module-federation/nextjs-mf` plugin.
This is the `next.config` file with the webpack configuration:
```js
const nextConfig = {
  webpack(config, options) {
    if (!options.isServer) {
      config.plugins.push(
        new NextFederationPlugin({
          name: 'mf-next',
          filename: 'static/chunks/remoteEntry.js',
          exposes: {
            './mf-next': './remote/remote-entry.tsx',
          },
        })
      );
    }
    config.output.uniqueName = 'mf-next';
    return config;
  },
};
```

##### Implementation
In Angular host I use a `@module-federation/nextjs-mf` utility to load the exposed module:
```ts
async ngAfterViewInit() {
    injectScript({
      global: 'mf-next',
      url: 'http://localhost:3003/_next/static/chunks/remoteEntry.js',
    })
      .then((container) => container.get('./mf-next'))
      .then((loader) => {
        this.appendWebComponent(loader().default);
      });
  }
```

but I receive this error message:
>  Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'call')
    TypeError: Cannot read properties of undefined (reading 'call')
    at options.factory (remoteEntry.js:774:31)
    at __webpack_require__ (remoteEntry.js:82:33)
    at remoteEntry.js:1118:162
    at __webpack_require__.m.<computed> (remoteEntry.js:1128:31)
    at options.factory (remoteEntry.js:774:31)
    at __webpack_require__ (remoteEntry.js:82:33)
    at fn (remoteEntry.js:414:21)
    at eval (react-jsx-dev-runtime.development.js:17:13)
    at eval (react-jsx-dev-runtime.development.js:1295:4)
    at ../../node_modules/.pnpm/react@18.2.0/node_modules/react/cjs/react-jsx-dev-runtime.development.js (node_modules_pnpm_react_18_2_0_node_modules_react_jsx-dev-runtime_js.js:18:1)

##### Considerations
I already tried to:
- set `runtimeChunk: 'single', splitChunks: false` in next config.
- use the normal `ModuleFederationPlugin`.
- export directly the component, not `remoteEntry.tsx`.
- Angular host app already uses index -> bootstrap pattern.
- Play with all combinations of `extraoptions` the `NextFederationPlugin` allows.

what works with other frameworks:
- dynamic loading of modules via fetch of remote manifest.
- react component well wrapped as web component.
- full angular support.

##### Resources

- https://github.com/angular-architects/module-federation-plugin
- https://github.com/brunos3d/nextjs-mf-runtime-remote-injection/blob/12b0c3a95736d92acd0e1033f6c21a582f0eb161/apps/host/pages/page-with-props.tsx#L16
- https://github.com/module-federation/module-federation-examples/tree/master/angular14-react

**Comment by ScriptedAlchemy** [comment]
Contact @zackarychapple

**Comment by thisizkp** [comment]
@peplocanto were you able to solve this issue?
