### ISSUE TITLE
Can Module federation be used without hosting the microapps?

### ISSUE THREAD

**Issue by dassum03-BH** [module-federation/module-federation-examples#3147]
Can I use module federation without hosting microapps for the remotes? If yes, any example?

**Comment by XavierLeTohic** [comment]
Yes you don't need to only exposes standalone applications, Module Federation works with everything you exposes that is compatible with Webpack, you can look at [this example](https://github.com/module-federation/module-federation-examples/tree/master/shared-store-cross-framework) which uses remote components and not remote standalone applications

**Comment by chelsumz007** [comment]
@XavierLeTohic I saw the example but the remotes are still been served using some server i.e localhost: 3003.. is it not possible to get the exposed component without running it on a server?

**Comment by ScriptedAlchemy** [comment]
You'd need the build at least, and however you consume it someone's going to have to serve the code over the network somehow. You can't bundle it in. It's an external module so it needs to be served externally

**Comment by ScriptedAlchemy** [comment]
Look at BuildHttp experiment. In future I will support offline remotes. Where webpack or rspack downloads and bundles the content at compile time
