### ISSUE TITLE
module-federation with Next.js 13 App Router

### ISSUE THREAD

**Issue by natashasq** [module-federation/module-federation-examples#3151]
Hi everyone. 

Is there any example of how to implement @module-federation/nextjs-mf with Next.js 13 **App router** instead of pages router? 
I have a working app based on https://github.com/module-federation/module-federation-examples/tree/master/nextjs-v13, with **pages** from Next.js, but I want to switch to **app** folder now..

I tried to do this with guidelines from Next.js docs, but I'm not sure how to move from _document.tsx with getinitialProps (pages router) to layout.tsx  (app router).

If anyone has some examples, I'd appreciate the help. 

Thank you!

**Comment by ScriptedAlchemy** [comment]
No app router support. Focus is on federation in https://modernjs.dev/en and RSC will be supported there before looking at next further. Next is very incompatible, modernjs on the other hand was designed for micro-frontends.
