### ISSUE TITLE
Examples of Next js 13 App router as host and vite-react as remote for MFE

### ISSUE THREAD

**Issue by AsuraKev** [module-federation/module-federation-examples#3153]

**Comment by ScriptedAlchemy** [comment]
No app router support. Focus is on federation in modernjs.dev/en and RSC will be supported there before looking at next further. Im also rewriting module federation, so vite may not work with the more powerful federation

**Comment by AsuraKev** [comment]
@ScriptedAlchemy thanks for the information. Is the module federation rewrite still based on webpack?

**Comment by ScriptedAlchemy** [comment]
@AsuraKev yep, its a fork - https://github.com/module-federation/universe/discussions/1170

Will also be in https://rspack.dev as a first class rust implementation, but will too be a webpack plugin :)

**Comment by ScriptedAlchemy** [comment]
Also i see this is app router, which is completely unsupported and I dont have any plans to do so unless modernjs is able to backport the solution

**Comment by AsuraKev** [comment]
awesome @ScriptedAlchemy. Vite is currently behind of module federation feature. Is https://www.rspack.dev/ considered to be an alternative to Vite and is for people who continues to use webpack? Will there be a Cli command to scaffold a react project that uses rspack as the bundler? 

My company is currently looking at building microfrontends so I am researching on the available tools  to do the best job :)

thanks a lot

**Comment by ScriptedAlchemy** [comment]
Rspack is webpack 1:1 in rust, this Q we are implementing federation in rust

https://modernjs.dev/en is our "nextjs" for micro-frontends. It works with Rspack too and webpack. If you use micro-frontends, this is the best I have ever seen. I quit my job to go work at Bytedance on these projects. 

Through this Q we will be preparing to publish a new version of modernjs with major enhancements for MFE and MFP.

I use it internally and ive seen most of the worlds MFE implementations, nothing compares.

Id strongly recommend against using something else as it will inevitably provide a very poor developer experience in comparison.

**Comment by AsuraKev** [comment]
@ScriptedAlchemy thanks I ll try it out :). Most likely to opt into using rspack over webpack, but is module federation baked into rspack yet or its coming soon?

**Comment by ScriptedAlchemy** [comment]
Itll be here this Q :) so you can try rspack out and when adding MFP, just switch to webpack for 2/3 months, then just change "webpack --config" to "rspack --config"

**Comment by AsuraKev** [comment]
Looking forward to it! Hopefully when it’s available on rspack, there will be an example of micro front end using modern js with rspack as well as handling host and remote routing 😃. Thanks

**Comment by Lc0rE** [comment]
Does this mean that MF support and developments for Vite.js will be limited, by choice, to prioritize the focus rspack in the future?

**Comment by ScriptedAlchemy** [comment]
No, i wont limit anything. If someone wants to implement module-federation/runtime and /sdk for vite, go for it, federation runtime is not hard coupled to webpack or rspack anymore. 

Next.js is a low priority since its impossibly incompatible. 
Vite, I'm waiting for rolldown where we can share rust crates between the two and copy rspack implementation for vite. But rolldown isn't baked yet and I'm not going to implement it till vite has a decent build tool to work with.
