### ISSUE TITLE
Question: Do we support nextjs 13 app router?

### ISSUE THREAD

**Issue by Elvis116** [module-federation/module-federation-examples#3159]
Do we support nextjs 13 app router? Any examples?

**Comment by antonytrupe** [comment]
https://github.com/module-federation/universe/issues/1400
If I'm reading it right: no.

**Comment by ScriptedAlchemy** [comment]
not currently

**Comment by rahimimo** [comment]
Is is still not yet supported? I tried the latest "canary" and I could not get it working.
