### ISSUE TITLE
Dynamic Remotes Query

### ISSUE THREAD

**Issue by dassum03-BH** [module-federation/module-federation-examples#3165]
My use case:

`remotes: {
		mfe2: 'http://localhost:3000/mfe2/v1/remoteEntry.js',
		mfe3: 'http://localhost:3000/mfe3/v1/remoteEntry.js',
		mfe4: 'http://localhost:3000/mfe4/v1/remoteEntry.js',
	},`
	
I'm using a node service to serve the remoteEntry.js file of the MFEs and using resolveComponentFactory to return the instance of the component:
`async loadRemoteComponent() {
		const component = await import('mfe3/HomeCmp');
		const factory = this.componentFactoryResolver.resolveComponentFactory(component.HomeComponent);
		this.weatherComponentRef = factory.create(this.injector);
		this.appRef.attachView(this.weatherComponentRef.hostView);
		const container = document.getElementById('dynamic-container');
		container.appendChild(this.weatherComponentRef.location.nativeElement);
	}`
	
However, is it possible to add the remotes dynamically? I don't want to mention the remotes in webpack.config.js.. Instead while loading the exposed component, I want to pass the url and load it..

**Comment by dassum03-BH** [comment]
@ScriptedAlchemy some help here pls

**Comment by RussellCanfield** [comment]
There are a few options available for this: Delegate Modules or the @mf/utilities package. The exact code depends on if you're using Next or React.

This should work in Next or React:
https://github.com/module-federation/module-federation-examples/tree/master/nextjs-ssr-delegate-modules/home

Next and React have different utility methods:
https://github.com/module-federation/universe/tree/main/packages/utilities

**Comment by dassum03-BH** [comment]
> There are a few options available for this: Delegate Modules or the @mf/utilities package. The exact code depends on if you're using Next or React.
> 
> This should work in Next or React: https://github.com/module-federation/module-federation-examples/tree/master/nextjs-ssr-delegate-modules/home
> 
> Next and React have different utility methods: https://github.com/module-federation/universe/tree/main/packages/utilities

Is there anything with Angular v15?

**Comment by ScriptedAlchemy** [comment]
https://github.com/module-federation/universe/tree/main/packages/runtime
https://github.com/module-federation/universe/tree/main/packages/enhanced
