### ISSUE TITLE
CSS from styled-jsx/css not coming from server

### ISSUE THREAD

**Issue by MaykonMorais** [module-federation/module-federation-examples#3172]
I'm try to add some styles in a component and we have two files: 
- styles.ts
- index.tsx

In styles.ts we define some styles 
```css
import css from "styled-jsx/css";
.test {
    background: red;
 }
```

in index.tsx we have a simple component just returning:

```tsx
return (
    <div className="l-header">
      TESTANDO
      <style jsx>{styles}</style>
    </div>
  );
```

As we can see in the images below, the 'test' class is being applied to the element. But in the preview we can see that it is not coming from the server with the style applied.
![image](https://github.com/module-federation/module-federation-examples/assets/43121724/10905d93-6052-4e03-9921-3a2daaae5f13)
![image](https://github.com/module-federation/module-federation-examples/assets/43121724/00c97a1b-d3f2-4848-b2a8-abe39019e5db)

package versions:
"@module-federation/nextjs-mf": "7.0.8",
"next": "13.4.18",
"webpack": "^5.88.2"
"react": "^18.2.0"

Do you have any suggestions of what its happening?

**Comment by leondavidtb** [comment]
I am facing the same issue.
