### ISSUE TITLE
Module federation works with "quasar dev" but not with "quasar build" or "quasar serve"

### ISSUE THREAD

**Issue by goldyfruit** [module-federation/module-federation-examples#3173]
Hi,

I followed the example for Quasar and Vue 3 but I got a very strange issue. Everything works fine if I run `quasar dev` on the host and the remote but when I run `quasar build` on the host and the remote I got this error:

![image](https://github.com/module-federation/module-federation-examples/assets/614115/c01513dd-b30e-46e4-ab9d-f1069b2914e4)

If I run `quasar build` on the host and `quasar dev` on the remote, everything work so I guess this is related to something I missed on the remote configuration.

```javascript
      // Host configuration
      extendWebpack(cfg) {
        cfg.entry = path.resolve(__dirname, './.quasar/main.js');
        cfg.plugins.push(
          new ModuleFederationPlugin({
            name: 'app_general',
            filename: 'remoteEntry.js',
            remotes: {},
            exposes: {},
            shared: {
              ...dependencies,
            },
          })
        );
      },
```

```javascript
      // Remote configuration
      extendWebpack(cfg) {
        cfg.entry = path.resolve(__dirname, './.quasar/main.js');
        cfg.plugins.push(
          new ModuleFederationPlugin({
            name: 'app_expose',
            filename: 'remoteEntry.js',
            exposes: {
              './RemoteSkill.vue': './src/components/RemoteSkillComponent.vue',
            },
            shared: {
              ...dependencies,
            },
          })
        );
```

Here is the file with the "syntax error" `140.c3d0a1b4.js`:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Quasar App</title>
    <meta charset=utf-8>
    <meta name=description content="A Quasar Project">
    <meta name=format-detection content="telephone=no">
    <meta name=msapplication-tap-highlight content=no>
    <meta name=viewport content="user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1,width=device-width">
    <link rel=icon type=image/png sizes=128x128 href=icons/favicon-128x128.png>
    <link rel=icon type=image/png sizes=96x96 href=icons/favicon-96x96.png>
    <link rel=icon type=image/png sizes=32x32 href=icons/favicon-32x32.png>
    <link rel=icon type=image/png sizes=16x16 href=icons/favicon-16x16.png>
    <link rel=icon type=image/ico href=favicon.ico>
    <script defer src=js/main.c57f4dd9.js></script>
  </head>
  <body>
    <div id=q-app></div>
  </body>
</html>
```

I think I should not have HTML but Javascript in this file _(I'm pretty new with all of these)_.

This is the procedure I followed to work with Quasar, Webpack and the module federation https://github.com/module-federation/module-federation-examples/tree/master/quasar-cli-vue3-webpack-javascript

I tried with `singleton` and `eager` but same behaviour.

Thanks for your help.

**Comment by goldyfruit** [comment]
Here is the file with the "syntax error"

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Quasar App</title>
    <meta charset=utf-8>
    <meta name=description content="A Quasar Project">
    <meta name=format-detection content="telephone=no">
    <meta name=msapplication-tap-highlight content=no>
    <meta name=viewport content="user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1,width=device-width">
    <link rel=icon type=image/png sizes=128x128 href=icons/favicon-128x128.png>
    <link rel=icon type=image/png sizes=96x96 href=icons/favicon-96x96.png>
    <link rel=icon type=image/png sizes=32x32 href=icons/favicon-32x32.png>
    <link rel=icon type=image/png sizes=16x16 href=icons/favicon-16x16.png>
    <link rel=icon type=image/ico href=favicon.ico>
    <script defer src=js/main.c57f4dd9.js></script>
  </head>
  <body>
    <div id=q-app></div>
  </body>
</html>
```

**Comment by goldyfruit** [comment]
Closing since I opened a discussion https://github.com/quasarframework/quasar/discussions/16452

**Comment by goldyfruit** [comment]
In `remoteEntry.js` I got this `Module "' + e + '" does not exist in container.` and this `Container initialization failed as it has already been initialized with a different share scope` which I guess I got because of `Unexpected token '<' (at 140.c3d0a1b4.js:1:1)`.

**Comment by goldyfruit** [comment]
I tested the https://github.com/module-federation/module-federation-examples/tree/master/quasar-cli-vue3-webpack-javascript as well and I got the same behaviour, everything works with `quasar dev` but not with `quasar build`.

![image](https://github.com/module-federation/module-federation-examples/assets/614115/1c0dedff-591b-4d5b-9845-3e23cb0b86e8)

**Comment by goldyfruit** [comment]
Any help on this will be really appreciated.

**Comment by ScriptedAlchemy** [comment]
set output.publicPath: auto
