### ISSUE TITLE
Container is offline, returning fake remote in BUILD time

### ISSUE THREAD

**Issue by santiagozsh** [module-federation/module-federation-examples#3297]
Hello, I need help with this error when executing `npm run build`, I have tried to solve it on my own and by asking in communities but no one has given me a correct answer

package.json in the 2 projects
![image](https://github.com/module-federation/module-federation-examples/assets/96670508/09198094-cf04-4e0e-8286-47bbcdf6894e)

Host App: next.config.js: 
![image](https://github.com/module-federation/module-federation-examples/assets/96670508/3dc834e4-1463-4b5d-9768-eee580ec1f16)

Remote App: next.config.js
![image](https://github.com/module-federation/module-federation-examples/assets/96670508/76115726-6aed-4688-9b72-5eda4f0e0d6f)

Error in console:
![image](https://github.com/module-federation/module-federation-examples/assets/96670508/3c175a36-2c4e-4136-9b08-7bb21d9c5290)

This same thing appears in the 2 projects when building them, any ideas on how to solve it?, thanks

**Comment by ScriptedAlchemy** [comment]
try newer version of the plugin, builds remote is always offline if its pointing at localhost, since localhost isnt online. As long as app doesnt crash its not a real issue - if you point it to deployed remote, it wont error.
