### ISSUE TITLE
CSS for federated components is not loading server side on module-federation/nextjs-mf v7 or v8

### ISSUE THREAD

**Issue by K-Cheddar** [module-federation/module-federation-examples#3318]
I demonstrated this using the examples repo. The below screenshots and video show "this is from checkout!" becomes red after load, resulting in a flash of unstyled content. This was demonstrated by forking the repo: https://github.com/K-Cheddar/module-federation-examples/tree/master/nextjs-ssr

Before JS loads:
![Screenshot 2023-11-10 at 10 21 40 AM](https://github.com/module-federation/module-federation-examples/assets/10645324/8f3e0970-da86-4924-8424-588fb07fa866)

After JS loads:
![Screenshot 2023-11-10 at 10 21 54 AM](https://github.com/module-federation/module-federation-examples/assets/10645324/aa1075f6-31d4-4a74-af30-6fc4b4da7e1a)

Video:
![v8fouc](https://github.com/module-federation/module-federation-examples/assets/10645324/f854d5ba-a9d5-49f0-aa17-414ea2b88dab)

The chunks that should include the css on the server is an empty array:

![Screenshot 2023-11-10 at 11 14 09 AM](https://github.com/module-federation/module-federation-examples/assets/10645324/b4f27c7d-c672-444e-85de-4f066d838d5c)

This is all run with the dependencies as given in the examples repo:
```
  "dependencies": {
    "@module-federation/nextjs-mf": "^8.1.0-canary.1",
    "lodash": "4.17.21",
    "next": "^13.5.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "webpack": "5.89.0"
  }
```
Also happens in 7.x and 8.1.0-canary.5

**Comment by ScriptedAlchemy** [comment]
is this in production mode? dev mode doesnt flush css chunks as its style-loader

**Comment by K-Cheddar** [comment]
Yes, this is in production mode.

**Comment by ScriptedAlchemy** [comment]
Okay. We are rewriting federation and will circle back to this after rewrite.

**Comment by K-Cheddar** [comment]
Thanks for letting me know. Do you have a rough eta for when you plan to release the rewrite?
