### ISSUE TITLE
Not able to run React with vite from the example

### ISSUE THREAD

**Issue by AshwinPetari** [module-federation/module-federation-examples#3326]
Im trying to see if Vite can work with React as I saw there are some issues for module federation for React. I'm not sure what is wrong, but when I clone this [repo](https://github.com/module-federation/module-federation-examples/tree/master/vite-react-microfrontends) and run this locally with the commands mentioned, it throws the following error and doesn't load anything.

<img width="1728" alt="image" src="https://github.com/module-federation/module-federation-examples/assets/145899559/13f88432-bb7a-4a5a-8e33-9ec898080703">

Even with this other [repo](https://github.com/module-federation/module-federation-examples/tree/master/vite-react-simple), it throws the following error. It leads me to believe one of the dependencies might have broken

<img width="1728" alt="image" src="https://github.com/module-federation/module-federation-examples/assets/145899559/2542b97a-b193-4b00-85e0-1b10c0bd3327">

**Comment by ScriptedAlchemy** [comment]
try enabling CORS, looks like a cors issue potentially, also check its using right react version which has createRoot

**Comment by AshwinPetari** [comment]
Vite by default have all origins enabled and using browser based extensions throw the same error. Requesting to reopen this ticket and actually run this locally to reproduce the error.

<img width="1728" alt="image" src="https://github.com/module-federation/module-federation-examples/assets/145899559/ac3bbf42-5e0c-45cb-86a6-8a5f21c50112">

**Comment by ScriptedAlchemy** [comment]
Ive fixed the example partially, but there are still some issues on the webpack side, i think it needs html webpack plugin if you want to send a pr adding it.

**Comment by AshwinPetari** [comment]
Let me try it out

**Comment by ScriptedAlchemy** [comment]
Send pr if you make any progress, its likely missing html webpack plugin setup - it loos like some new version removes some presets that used to exist there.

**Comment by danielm2402** [comment]
I cloned this example and am getting the same issue. How could I solve it? Could you post a PR if you show me the problem.

**Comment by nzeroxed** [comment]
Any progress on this issue ?

**Comment by bharatwaj** [comment]
I am running into the same issue with example vite-react-microfrontends. react-dom and react are getting downloaded as expected but it is not getting set as expected.

<img width="1062" alt="createRoot-error" src="https://github.com/module-federation/module-federation-examples/assets/9925019/01209194-7ab0-4bb9-a67b-5ab3521a2445">

@ScriptedAlchemy  Any thoughts? Could you please clarify on your comment wrt html webpack plugin. This example does not use webpack plugin right?
