### ISSUE TITLE
shared modules cannot be really shared!

### ISSUE THREAD

**Issue by whu12yz** [module-federation/module-federation-examples#336]
As followings, my app federation configs.
```javascript
// app1
output: {
  publickPath: 'http://localhost:3000'
}
plugins:[
  new ModuleFederationPlugin({
      name: 'main_app',
      library: {
        type: 'var',
        name: 'main_app',
      },
      shared: ['react', 'react-dom', 'prop-types', 'lodash'],
  });
]
```
```javascript
// app2
output: {
  publickPath: 'http://localhost:3001'
}
plugins:[
  new ModuleFederationPlugin({
      name: 'app2',
      library: {
        type: 'var',
        name: 'app2',
      },
      remotes: {
        main_app: 'main_app',
      },
      shared: ['react', 'react-dom', 'prop-types', 'lodash'],
  }),
]
```
app2 build into a chunk, app1 import this chunk as a sub app.
so, app2 will use it‘s own react/react-dom/prop-types/lodash from http://localhost:3001.
the shared config not working. 
How to make app2 use react/react-dom/prop-types/lodash from app1?

**Comment by TheCodingGorilla** [comment]
Not 100% as I am getting my head around this myself but you have no exposed any modules from app2.

Try checking your code against https://module-federation.github.io/blog/get-started#start-federating to see if that resolves your issue.

**Comment by ScriptedAlchemy** [comment]
Also you're sharing strings. You probably want to use the spread operator and import package json dependencies with key and version so webpack knows semver matches and won't get confused. That config is an older implementation. Check any of my configs in the repo. I share using a more modern api
