### ISSUE TITLE
NextJS 13 - Hydration error in example code

### ISSUE THREAD

**Issue by jstebenne** [module-federation/module-federation-examples#3392]
I cloned the [example code for NextJS 13](https://github.com/module-federation/module-federation-examples/tree/master/nextjs-v13) in an attempt to help me understand how to troubleshoot issues we are having in our project, but I am consistently getting an hydration error on every refresh of the example app.

In total, two errors are triggered at the same time:

```
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

Warning: Expected server HTML to contain a matching <nav> in <div>.

See more info here: https://nextjs.org/docs/messages/react-hydration-error

Component Stack
nav
Nav
MyApp
```

```
Unhandled Runtime Error
Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.

Component Stack
nav
Nav
MyApp
```

I saw in another issue that using Lazy from React instead of next/dynamic should fix the issue, but it did not help in this case.

Any idea what's going on and what would be the issue?

**Comment by pneedham-mdsol** [comment]
I was getting the same error. Within `/home/pages/_app.js` I had to add this prior to the current jsx being returned:

```
const [mounted, setMounted] = useState(false);
  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) return <></>;
```

**Comment by ScriptedAlchemy** [comment]
I fixed the example, issue is next/dynamic use. And since these examples dont have SSR like the next-ssr sample does. It will fail to load them. 
dont use next/dynamic with federation
