### ISSUE TITLE
Modern.js example missing remoteEntry.js in production

### ISSUE THREAD

**Issue by bradysimon** [module-federation/module-federation-examples#3408]
## Overview

The [Modern.js example project](https://github.com/module-federation/module-federation-examples/tree/master/modernjs) works as expected in dev but is having issues when built for production. 

## Details

In dev (`pnpm dev`) both projects work fine and the host app is able to consume the provider, but in production (`pnpm serve`) the remote entry is unavailable. In dev, you can access the provider's `remoteEntry.js` at `localhost:3002/remoteEntry.js` and see the federated code, but this path results in a 404 when in production. This is the error you'll see in the host app:

```
ScriptExternalLoadError: Loading script failed.
(missing: http://localhost:3002/remoteEntry.js)
while loading "./Button" from webpack/container/reference/provider
while loading "./Button" from webpack/container/reference/provider
    at webpack/container/reference/provider (http://localhost:3001/static/js/main.js:7:25)
    at options.factory (http://localhost:3001/static/js/builder-runtime.js:759:31)
    at __webpack_require__ (http://localhost:3001/static/js/builder-runtime.js:28:33)
    at initExternal (http://localhost:3001/static/js/builder-runtime.js:331:28)
    at __webpack_require__.I (http://localhost:3001/static/js/builder-runtime.js:344:15)
    at http://localhost:3001/static/js/builder-runtime.js:897:47
    at webpack/sharing/consume/default/react/react?766e (http://localhost:3001/static/js/builder-runtime.js:951:85)
    at http://localhost:3001/static/js/builder-runtime.js:996:56
    at Array.forEach (<anonymous>)
    at __webpack_require__.f.consumes (http://localhost:3001/static/js/builder-runtime.js:979:36)
```

I first thought this was happening because the `assetPrefix` is only set in dev and not prod but setting `output.assetPrefix` results in a different error. I was able to get the remote to at least be viewable on the provider site by changing the provider's `filename` from `remoteEntry.js` to `static/js/remoteEntry.js` to match where Modern.js puts its other assets, but this results in the following errors on the host app after updating the remote URL:

```
Uncaught SyntaxError: Unexpected token '<' (at lib-react.648d92fc.js:1:1)

remoteEntry.js:1  Uncaught (in promise) ChunkLoadError: Loading chunk 193 failed.
(missing: http://localhost:3001/static/js/async/lib-react.648d92fc.js)

Uncaught SyntaxError: Unexpected token '<' (at 458.7d15056d.js:1:1)
```

## Steps to Reproduce

Clone the `module-federation-examples` repo, install deps for both the `modernjs/host` and `modernjs/provider` packages, then build and serve the production apps. The host app (localhost:3001) should fail to import the remote app.

**Comment by ScriptedAlchemy** [comment]
Ill check it out

**Comment by ScriptedAlchemy** [comment]
https://github.com/module-federation/module-federation-examples/pull/3430

**Comment by bradysimon** [comment]
This fixes it for me. Thank you!
