### ISSUE TITLE
Module not found: Remote module can't be resolved

### ISSUE THREAD

**Issue by evgeny-chuvelev-sveasolar** [module-federation/module-federation-examples#3416]
I follow the example `react-nextjs/nextjs-host-react-remote/` but use TypeScript instead of JavaScript. 

I get the exception in the host app when I try to import  the remote app:
```
Module not found: Can't resolve 'remote/Nav'
  10 | import dynamic from 'next/dynamic';
  11 |
> 12 | const ReactRemoteComponent = dynamic(() => import('remote/Nav'), {
     |                                           ^
  13 |   ssr: false,
  14 | });
```

Here: https://github.com/module-federation/module-federation-examples/blob/7e646e63efbe3bb3913248a5158bde9527e2ba8d/react-nextjs/nextjs-host-react-remote/host/pages/index.js#L6

Are there any examples where nextjs is used with typescript as a host with @module-federation/nextjs-mf and react app as remote also with typescript?

**Comment by ScriptedAlchemy** [comment]
use react lazy instead

**Comment by ScriptedAlchemy** [comment]
Ive opened a pull request, should merge in an hour or so, which should resolve the issue in example
