### ISSUE TITLE
Does module federation work with iframes? 

### ISSUE THREAD

**Issue by 98mux** [module-federation/module-federation-examples#345]

**Comment by ScriptedAlchemy** [comment]
Not unless you own the iframe. And can create a global object between the two.

**Comment by Miwa199739** [comment]
@ScriptedAlchemy, could you please share an example to use module federation with iframes? Thank you!

**Comment by ScriptedAlchemy** [comment]
No capacity

**Comment by DiogoVCS** [comment]
> Not unless you own the iframe. And can create a global object between the two.

@ScriptedAlchemy  what kind of object would be used in this example? Can you give not a full example, but a more detailed suggestion on how to achieve this? For example, sharing a library "rxjs", with an app A that has an iframe inside of it, where both are in the same domain? I have done a couple of attempts and could not achieve the same  results i ahve achieved with web-components and so one. thank you.
