### ISSUE TITLE
Dynamically loading remoteEntry

### ISSUE THREAD

**Issue by Cybbin** [module-federation/module-federation-examples#3458]
Now i have only one `container` app and having the following configuration:

```js
new ModuleFederationPlugin({
  name: "container",
  filename: "remoteEntry.js",
  exposes: {
    "./utils": "./src/utils.js",
  },
  shared: {
    vue: { singleton: true },
  },
}),
```

I want to dynamically loading `remoteEntry.js` file, but it seems to directly inserted into the HTML.

<img width="1175" alt="image" src="https://github.com/module-federation/module-federation-examples/assets/21078700/db7a7799-f48d-45ee-952b-be31e51972ee">

I want to control the cache through timestamp(?v=[Date.now]), how can i do?

**Comment by fcano-ut** [comment]
Looks like you need to look the configuration of the `HTMLWebpackPlugin` to see how it's generating your HTML. In that configuration you might be able to specify a timestamp as query param...

**Comment by ScriptedAlchemy** [comment]
look at runtime-plugins folder in here, you can write runtime plugin to do stuff like that. look at module-federation/enhanced
