### ISSUE TITLE
[HMR] Update failed: ChunkLoadError: Loading hot update chunk main failed.

### ISSUE THREAD

**Issue by ttttttw** [module-federation/module-federation-examples#3469]
![image](https://github.com/module-federation/module-federation-examples/assets/24540969/2f4ddd43-68dd-4adc-aad8-a5a43701ef54)

Have plans to support HMR ？

**Comment by ScriptedAlchemy** [comment]
Yes we have HMR working internally but have not pushed it to OSS users yet
