### ISSUE TITLE
can i use resolve.alias?

### ISSUE THREAD

**Issue by ttttttw** [module-federation/module-federation-examples#3472]
can i use resolve.alias?
i want to set alias,but get some error

<img width="488" alt="image" src="https://github.com/module-federation/module-federation-examples/assets/24540969/fe81c475-810c-4145-870f-e0444f13618a">

<img width="381" alt="image" src="https://github.com/module-federation/module-federation-examples/assets/24540969/c30ee4fb-69b3-4e05-ac03-1fb056f5fa51">

<img width="491" alt="image" src="https://github.com/module-federation/module-federation-examples/assets/24540969/eea53363-2ea3-4a0d-ab16-fb3832148621">

**Comment by ttttttw** [comment]
<img width="623" alt="image" src="https://github.com/module-federation/module-federation-examples/assets/24540969/14ffa0a5-8122-401d-9481-7247b74dd3c9">

**Comment by ScriptedAlchemy** [comment]
cant you call it "@federation": 'federation@http'

the key is the alias already

**Comment by ttttttw** [comment]
谢谢，呵呵！~~
