### ISSUE TITLE
How to deal with d. ts

### ISSUE THREAD

**Issue by ttttttw** [module-federation/module-federation-examples#3473]
I use @modulefederation/typescript to generate d.ts. And how to use it?
Do I need to copy it into the consumer？
Is it because I used it incorrectly? Can plugins automatically synchronize d. ts？

**Comment by ScriptedAlchemy** [comment]
We will be releasing new TS sync support sometime soon.

**Comment by ttttttw** [comment]
谢谢，呵呵！~~
