### ISSUE TITLE
Remote is not defined in nextjs-mf v8

### ISSUE THREAD

**Issue by haghsheno** [module-federation/module-federation-examples#3487]
I'm using @module-federation/nextjs-mf in my NextJS app with typescript.
After upgrading to version 8.1.1, i'm getting this error:
```
ReferenceError: remote is not defined
while loading "./login" from webpack/container/reference/app-remote
```
I also tried `React.Lazy` and dynamic import with `ssr: false` and wrapping it in Suspense.

```
@module-federation/nextjs-mf: 8.1.1
next: 13.1.6
webpack: 5.89.0
```

**Comment by ScriptedAlchemy** [comment]
try with 8.0.5
