### ISSUE TITLE
esm modules possible?

### ISSUE THREAD

**Issue by wibed** [module-federation/module-federation-examples#3537]
given this link:
https://github.com/module-federation/universe/blob/6d8a65fc6cb175520f0cb2a64df0695538e9c9a5/packages/utilities/src/utils/importRemote.ts#L29

can i federate esm based modules from remotes?

**Comment by ScriptedAlchemy** [comment]
Server, not yet. Client - should be.

youd have to put webpack / rspack into esm output.

You should also use module-federation/enhanced instead of the webpack version, read module-federation/runtime, and not need to use importRemote or utilities package anymore.
