### ISSUE TITLE
nested paths, optimizations and bundle size effects on shared vendor

### ISSUE THREAD

**Issue by wibed** [module-federation/module-federation-examples#3574]
taken from examples here:
https://github.com/module-federation/module-federation-examples/tree/master/advanced-api

```ts
...
const deps = require('./package.json').dependencies;
...
      shared: {
        moment: deps.moment,
...
```

will load the moment.js package from the module with the highest version.

the comment here:
https://github.com/module-federation/module-federation-examples/blob/master/advanced-api/automatic-vendor-sharing/app1/rspack.config.js
```
// adds all your dependencies as shared modules
// version is inferred from package.json in the dependencies
// requiredVersion is used from your package.json
// dependencies will automatically use the highest available package
// in the federated app, based on version requirement in package.json
// multiple different versions might coexist in the federated app
// Note that this will not affect nested paths like "lodash/pluck"
// Note that this will disable some optimization on these packages
// with might lead the bundle size problems
```

what does `will not affect nested paths` meant exactly?
what kind of optimizations are meant exactly?
what kind of bundle size problem do i have to expect?

**Comment by ScriptedAlchemy** [comment]
if you share something like lodash/pluck, it will wont share that, it will share lodash, the index file. 

If you wantto share more effeciently you can use trailing slash, like `lodash/` that tells it "dont share the index file, but share anything it imports thats used"  makes more chunks, but smaller chunks vs huge payload
