### ISSUE TITLE
circular dependency on federated router

### ISSUE THREAD

**Issue by wibed** [module-federation/module-federation-examples#3580]
i might have a circular dependency at hand, which is problematic. 
if i rely on the example of federated redux, i import the app from the remote to decorate it with the store.

yet want to import slices selectors etc into the remote to access state from other modules.

which would cause a circular dependency

**Comment by ScriptedAlchemy** [comment]
I need to update redux. It still uses v1 of M-F and is very old, not built by me. I'll take a look next week
