### ISSUE TITLE
no vite-side remoteEntry.js

### ISSUE THREAD

**Issue by tonylua** [module-federation/module-federation-examples#3607]
vue3-demo-federation-with-vite

after `pnpm start`

can not access `http://localhost:5173/assets/remoteEntry.js` from webpack-side (5001)

**Comment by ScriptedAlchemy** [comment]
is 5173 webpack or vite?

**Comment by tonylua** [comment]
> is 5173 webpack or vite?

5173 is vite, and `pnpm build && pnpm serve` is ok, but directly `pnpm start` not, I do not know how to config it

**Comment by ScriptedAlchemy** [comment]
Look for the package author of vite federation, i dont maintain it.
