### ISSUE TITLE
Why do exposes use relative path string for key value.

### ISSUE THREAD

**Issue by cpitt** [module-federation/module-federation-examples#361]
I want to start by saying that these examples are awesome and have been invaluable.

One thing I'm trying to understand is the pattern of using a relative path string as a key in the exposes config entry.

example:

```javascript
 exposes: {
        "./Button": "./src/Button",
      },
```

Is there some kind of convention here or reason not to just use `Button` as the key?

**Comment by cpitt** [comment]
Found the answer digging through blog posts

ESM compatibility with node 14 

https://medium.com/dev-genius/module-federation-advanced-api-inwebpack-5-0-0-beta-17-71cd4d42e534#7dbf

I'm looking now to better understand this compatibility. If anyone can point me in the right direction it would be appreciated

**Comment by ScriptedAlchemy** [comment]
follows ESM modling in node 14, more natural based on the future

it also lets us prefix things right - ./button becomes webpack/container/entry/Button.js under the hood

**Comment by cpitt** [comment]
Thanks for the explanation, it's appreciated
