### ISSUE TITLE
rspack-webpack-offload no work!

### ISSUE THREAD

**Issue by ckken** [module-federation/module-federation-examples#3610]
[rspack-webpack-offload](https://github.com/module-federation/module-federation-examples/tree/master/rspack-webpack-offload)
lib and main use rspack,page use main's react in my case

**Comment by ckken** [comment]
in rspack

**Comment by ScriptedAlchemy** [comment]
Ill look into it, thanks for letting me know!

**Comment by ScriptedAlchemy** [comment]
@ckken it seems to be working
