### ISSUE TITLE
404 pages are rendered in federated URLs in nextjs v13 with nextjs-mf v8.

### ISSUE THREAD

**Issue by yusukegoto** [module-federation/module-federation-examples#3619]
Federated pages in nextjs-v13 start rendering "404 Not Found" since I pulled this repo with nextjs-mf v8. e.g. http://localhost:3001/shop
I'm using nextjs-mf 8.1.7.
Federated components look like having no issues. I can see a RemoteTitle rendered from checkout in /home.
Pages work with nextjs-mf v7.0.8 like a commit 5165f2d.

I roughly spotted that `process.env.REMOTES` returned `undefined` with nextjs-mf v8, while it returned values with nextjs-mf v7.
https://github.com/module-federation/module-federation-examples/blob/022ebb2c19ed2638305c82899f85bc2037459afa/nextjs-v13/shared/index.js#L4

**Comment by ScriptedAlchemy** [comment]
@yusukegoto https://github.com/module-federation/module-federation-examples/pull/3672

**Comment by yusukegoto** [comment]
Thank you!! It worked!!! 🎉
