### ISSUE TITLE
App router support

### ISSUE THREAD

**Issue by HesamDanaee** [module-federation/module-federation-examples#3623]
I've switched from page router to the app router but on build time module federation throws error. it's main error is about react-dom which it couldn't find. I was using the 6.4.0 version of module federation and right now it's 8.1.7. did app router support was added in this version? If there is any workarounds please tell me.

**Comment by Akshay090** [comment]
App router support is not there currently in the  module-federation/nextjs-mf plugin https://github.com/module-federation/universe/issues/1183

You can follow this https://github.com/module-federation/universe/pull/2002 for more updates

**Comment by HesamDanaee** [comment]
Thanks for the response. when would they add support? I'm working on company project which is  micro front-end. they asked me to add SSR to the project and I moved from pages router to app router but it just gave me build time errors. I couldn't find the issue because there was no clear error about this problem. would they consider adding app router later?

**Comment by ManuelcsNuant** [comment]
Hello, does anyone know the progress on this one or if its going to be supported anytime soon?

**Comment by pvsfair** [comment]
As @Akshay090 pointed out, people are trying to contribute so this can work, you can follow this https://github.com/module-federation/universe/pull/2002 to get some updates.

I think for now they only have had finished the support for the SSR part, and the react is still giving errors.

**Comment by ScriptedAlchemy** [comment]
No app router support. If someone sends a PR to support it, otherwise I am not working on the issue as it is low priority. 

Maybe in 6 months time ill look at it again.

**Comment by marshallcool** [comment]
`If someone sends a PR to support it`, but Is this not the [PR](https://github.com/module-federation/universe/pull/2002) that is needed ?

**Comment by ScriptedAlchemy** [comment]
no that does not fix it.
