### ISSUE TITLE
Module not found: Can't resolve 'encoding' in '../node_modules/node-fetch/lib'

### ISSUE THREAD

**Issue by Kishok978** [module-federation/module-federation-examples#3636]
./node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '../node_modules/node-fetch/lib'

Import trace for requested module:
./node_modules/node-fetch/lib/index.js
./node_modules/@module-federation/node/dist/src/utils/hot-reload.js
./node_modules/@module-federation/node/dist/src/utils/index.js
./node_modules/@module-federation/nextjs-mf/dist/utils/index.js
./pages/_document.js

./node_modules/@module-federation/utilities/dist/index.cjs.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/@module-federation/utilities/dist/index.cjs.js
consume shared module (default) @module-federation/utilities@=3.0.5 (strict) (fallback: ./node_modules/@module-federation/utilities/dist/index.cjs.js) (eager)
./node_modules/@module-federation/nextjs-mf/dist/utils/index.js
./pages/_document.js

@ScriptedAlchemy Can you please look into this problem? I'm getting an error while using @module-federation version 8.1.0.

**Comment by ScriptedAlchemy** [comment]
npm install encoding, ill fix it in the package too

**Comment by ScriptedAlchemy** [comment]
PR opened

**Comment by ScriptedAlchemy** [comment]
try the `next` tag on npm - which should contain this released code
