### ISSUE TITLE
Please use Angular17.2 as the shell, use the Native Federation package, Angular12 as the remote, use the Module Federation package. Is there any such example?

### ISSUE THREAD

**Issue by huajian123** [module-federation/module-federation-examples#3637]
Please use Angular17.2 as the shell, use the Native Federation package, Angular12 as the remote, use the Module Federation package. Is there any such example?

**Comment by ScriptedAlchemy** [comment]
Native federation is incompatible with module federation. Its a copy of federation, not interoperable with its interfaces. 

In the future module-federation/runtime will support import maps, you can watch for that otherwise youre out of luck without a webpack or rspack build
