### ISSUE TITLE
vite-react-microfrontends demo missing file

### ISSUE THREAD

**Issue by tomas-light** [module-federation/module-federation-examples#3645]
There is no such file as `vite-importmap-shim.ts` that is described in `tscconfig.node.json` `include` statement. I assume there is something important, please add it to git, if it so.

![image](https://github.com/module-federation/module-federation-examples/assets/20392714/3abfa28e-2051-44da-abe3-35ed6915b97d)

**Comment by ScriptedAlchemy** [comment]
Im not sure, does the example work? If so i guess not

**Comment by phuynh-cm** [comment]
@ScriptedAlchemy  No, the example does not seem to render properly. Although there don't seem to be any errors in the console, the remote and host pages are rendering a blank screen. This may or may not be due to the missing file mentioned in this issue.

**Comment by ScriptedAlchemy** [comment]
Yeah the example probs needs to be rewritten. 

Sadly i dont know vite and not sure whats wrong here or how to fix. 

Might be worth trying to send a PR and re-implement with originjs or something

**Comment by hans-ts** [comment]
Unfortunately originjs does not do live-reloading or HMR, and going back to manually refreshing on changes is asking a bit too much.

**Comment by ScriptedAlchemy** [comment]
All implementations of MFP don't support hmr. We will soon support hmr in rspack and webpack but vite isn't going to get any of that.
