### ISSUE TITLE
Any Next.js 14 example?

### ISSUE THREAD

**Issue by moparlakci** [module-federation/module-federation-examples#3675]
Hi there

I recently upgraded our Main App shell from Next.js13 to Next.js 14 (App router), gave us too many problems with used packages like MUI and @emotion css-in-js.

Host: Next.js 14 
Remotes: React (CRA)

Any simple example that works?

**Comment by ScriptedAlchemy** [comment]
No app router support. No work in progress to support it at this time.

**Comment by rahulsale** [comment]
So, what is the way around ? If we don't have App Route, what alternate we have to opt ?
