### ISSUE TITLE
nextjs-v13 getServerSideProps not working

### ISSUE THREAD

**Issue by mimre73** [module-federation/module-federation-examples#3686]
I used the getServerSideProps method in the checkout app, but when it comes to the home page, it does not recognize the getServerSideProps method, and the getServerSideProps passed through it is undefined.

**Comment by ScriptedAlchemy** [comment]
How are you implementing it

**Comment by mimre73** [comment]
in checkout page from cheackout app:
`
export async function getServerSideProps(context) {
  
  return {
    props: {
      name: 'John Doe',
    },
  };
}
`
when we use checkout as [...slug].js in home app we can not access getServerSideProps that defined on checkout page.

**Comment by ScriptedAlchemy** [comment]
try the `next` tag on npm

**Comment by ScriptedAlchemy** [comment]
https://github.com/module-federation/universe/pull/2156

**Comment by JFKelly68** [comment]
I'm having a similar issue - I've installed `next` and I'm still seeing the code before the changes from https://github.com/module-federation/universe/pull/2156 

any timeline on when the code in this ^^ PR will be released on the `next` tag?

**Comment by ScriptedAlchemy** [comment]
Okay ill merge and ship the PR now. Please let me know if it fixes it.

**Comment by ScriptedAlchemy** [comment]
@JFKelly68 try with 8.2.2

**Comment by JFKelly68** [comment]
Hmm, seeing the updated runtimePlugin code, but still getting undefined for `getServerSideProps` in the host app.

you should be able to reproduce with this:
https://github.com/JFKelly68/test-next-mf/blob/main/module-federation/shell/pages/subposts.js

**Comment by ScriptedAlchemy** [comment]
Your trying to access static function method, GSSP is not static method on function. 

import * as MicroAppOnePage from 'm1localref/m1';

returns {default,GSSP} 

What you are doing is default.getServerProps - that dont exist.

**Comment by JFKelly68** [comment]
Amazing - assumed it was bundled differently somehow, but this makes a lot of sense. Really appreciate the quick response
