### ISSUE TITLE
react_devtools_backend.js:2273 TypeError: i(...).get is not a function

### ISSUE THREAD

**Issue by xileliu** [module-federation/module-federation-examples#369]
master-app:
1. ![image](https://user-images.githubusercontent.com/13429648/93090718-c01cd680-f6cf-11ea-89af-9e4d4db8b403.png)
2.helper:
![image](https://user-images.githubusercontent.com/13429648/93090865-f35f6580-f6cf-11ea-8987-b6508210c2d1.png)

other-app:
1.![image](https://user-images.githubusercontent.com/13429648/93090993-1db12300-f6d0-11ea-9081-6354f60bc7b7.png)
2.![image](https://user-images.githubusercontent.com/13429648/93091025-2b66a880-f6d0-11ea-948e-2c24a7ed2ce3.png)

master-app:
1.![image](https://user-images.githubusercontent.com/13429648/93091108-4507f000-f6d0-11ea-827f-afdf5878bf2c.png)

2.![image](https://user-images.githubusercontent.com/13429648/93091144-518c4880-f6d0-11ea-8577-34818d8d46ae.png)

error：production
![image](https://user-images.githubusercontent.com/13429648/93090628-9e235400-f6cf-11ea-8fa1-edf5d990fefa.png)

dev: success! no error

**Comment by ScriptedAlchemy** [comment]
It looks like you're not attaching the remote correctly in prod. Check what window.remoteName returns. 

Also you should use dynamic imports on federated modules when possible. Static imports hoist a lot to the upper async scope. If suspense or dynamic import can be used, use that. 

Are you inclining script manually or adding the url via the remote syntax in the plugin. 

Dev tools backend might be appending an entrypoint which messed up the module federation container
