### ISSUE TITLE
Why all example is using html-webpack-plugin off a github repo

### ISSUE THREAD

**Issue by matthewma7** [module-federation/module-federation-examples#373]
Hi,

I am wondering the reason why all examples are using html-webpack-plugin off a github repo, is that related to Module Federation?

Sincerely,

**Comment by ScriptedAlchemy** [comment]
theres a bug that needs to be patched in the actual project. Theres an open issue on their reoo, if you want to push some pressure on the author to update HTML webpack plugin, head to githib

**Comment by ScriptedAlchemy** [comment]
You can now use the normal plugin. Previous issues have been fixed in origin repo
