### ISSUE TITLE
Using external-remotes-plugin with @module-federation/nextjs-mf

### ISSUE THREAD

**Issue by adit-shah-devrev** [module-federation/module-federation-examples#3757]
I am trying to use `external-remotes-plugin` with `@module-federation/nextjs-mf`. I am running into following error:

```
GET http://localhost:3000/[window.templateAppUrl]/_next/static/chunks/remoteEntry.js net::ERR_ABORTED 404 (Not Found)
```

It looks like it's not able resolve `window.templateAppUrl`.
Also I need help to achieve SSR with this. How do I do that?

Here is the [repo](https://github.com/adit-shah-devrev/nextjs-mf-demo-app) where this issue is reproducible.

Steps to reproduce the error:
1. `npm ci`
2. `npx nx serve remote-app`
3. `npx nx serve template-app`
4. `npx nx serve host-app`
5. go to `/directories` page in host app

**Comment by ScriptedAlchemy** [comment]
Make a runtime plugin. Search universe repo for git issue. Someone supplied an example already or you can roll whatever you want in runtime plugin. Look at runtime plugins directory in this repo to see some samples etc.
