### ISSUE TITLE
Uncaught SyntaxError: Unexpected token function when use module federation v1.5

### ISSUE THREAD

**Issue by ckken** [module-federation/module-federation-examples#3759]
use agent : Mozilla/5.0 (Linux; U; Android 7.1.1; zh-cn; MI 6 Build/NMF26X) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.146 Mobile Safari/537.36 XiaoMi/MiuiBrowser/9.2.11
use rspack

**Comment by ckken** [comment]
​ Uncaught SyntaxError: Invalid regular expression: /(?<=[-0-9A-Za-z])\s+/: Invalid group use rspack.container.ModuleFederationPluginV1

**Comment by ScriptedAlchemy** [comment]
File issue with rspack

**Comment by ckken** [comment]
v1 https://github.com/web-infra-dev/rspack/issues/5969
