### ISSUE TITLE
http.js:5 Uncaught (in promise) ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization

### ISSUE THREAD

**Issue by xileliu** [module-federation/module-federation-examples#376]
![image](https://user-images.githubusercontent.com/13429648/94236985-b5203c80-ff40-11ea-904e-04be6cf32bb9.png)
![image](https://user-images.githubusercontent.com/13429648/94236997-b94c5a00-ff40-11ea-9d1a-902c10e6f204.png)

error:
![image](https://user-images.githubusercontent.com/13429648/94237018-c49f8580-ff40-11ea-943b-47ccd01c36a6.png)

**Comment by xileliu** [comment]
@ScriptedAlchemy

**Comment by ScriptedAlchemy** [comment]
Not enough context

**Comment by Inchill** [comment]
@xileliu I encountered the same error, did u find out the solution?
