### ISSUE TITLE
Code Nextjs-v14 throws error when try to run

### ISSUE THREAD

**Issue by tomani77** [module-federation/module-federation-examples#3760]
Getting Error while running NextJs code from Next-v14.

#1. after running yarn start, it throws following error - 

Error: Cannot find module 'webpack/lib/javascript/BasicEvaluatedExpression'
[1] Require stack:
[1] - /Folder/module-federation-examples/nextjs-v14/node_modules/next/dist/compiled/webpack/webpack.js

Seems above error is due to missing webpack.

#2. executed yarn add webpack in both the folders i.e. home and shop.

#3 from root i.e. nextjs-v14 run yarn start
terminal shows following message - 

[ Module Federation Manifest Plugin ]: Manifest will not generate, because publicPath can only be absolute path, but got 'auto'
[1] (node:32415) [DEP_WEBPACK_PRE_COMPILED_SCHEMA_INVALID] DeprecationWarning: webpack bug: Pre-compiled schema reports error while real schema is happy. This has performance drawbacks.

#4 Access application using  http://localhost:3001.

Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

_Warning: Expected server HTML to contain a matching <html> in <div>.
See more info here: https://nextjs.org/docs/messages/react-hydration-error_

_Unhandled Runtime Error
Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering._

runtime environment - Mac
Node version - v21.5.0
yarn version - 1.22.15

**Comment by ScriptedAlchemy** [comment]
You need env var for local webpack to get past next error 1. 

Hydration error depends on setup. If MFP is not applied server side and only client side then it'll throw that. If you use next dynamic of MF imports not not react lazy. It'll have hydration error too.

**Comment by tomani77** [comment]
Hi @ScriptedAlchemy, I am getting error while running the module federation sample application 

https://github.com/module-federation/module-federation-examples/tree/master/nextjs-v14

Any changes required in this sample code? I am able to by pass #1 by installing webpack

**Comment by ScriptedAlchemy** [comment]
The only real issue I see here is 4. 

Which is hydration issue because Mf only running in client. Look at ssr next example or use set state to render component after hydration.

**Comment by Dannymx** [comment]
> The only real issue I see here is 4.
> 
> Which is hydration issue because Mf only running in client. Look at ssr next example or use set state to render component after hydration.

The error # 4 is still an error out of the box with the example.

**Comment by ScriptedAlchemy** [comment]
Yes it is, because im not using set state or something to mount component client side only. 
Send PR if you would like to patch it.

**Comment by ScriptedAlchemy** [comment]
https://github.com/module-federation/module-federation-examples/pull/3764
