### ISSUE TITLE
[Feature request/discussion] Allow having multiple instances of shared dependencies

### ISSUE THREAD

**Issue by GuilleX7** [module-federation/module-federation-examples#3763]
As submitted in https://github.com/module-federation/module-federation-examples/pull/3762, we have some scenarios where we load some containers that have no interaction between them apart from the parent mounting the child (imagine a parent application that loads a child application). However, both use and configure the global Vue 2.x instance. If we shared dependencies in the regular way, we would end up having conflicts because both containers share the same instance.

Not sharing dependencies means both applications would have to download the Vue 2.x chunk twice, which is quite inefficient, especially in large projects with many dependencies that can be shared. Therefore, we aim at a solution that allows us to download code once, then "run" it twice. Right now, a plugin can handle it in a "hacky" way, since we require manipulating other container's webpack cache, but maybe this could be implemented as a feature.

**Comment by ScriptedAlchemy** [comment]
Does the same functionality happen with standard webpack federation (v1)?

**Comment by GuilleX7** [comment]
If you mean if reusing the same instance of a dependency is a common behavior of MF 1.0 and 1.5, yes it is.

The behavior of sharing dependencies but having multiple instances is implemented by my [MF 1.5 plugin here](https://github.com/module-federation/module-federation-examples/pull/3762). It's not part of MF 1.0 nor 1.5, but it does use MF 1.5 Plugin API to hook into the runtime.

Since MF 1.0 does not have a plugin API at all, it would need to be implemented as a Webpack plugin or directly implemented in the Module Federation 1.0 plugin. Ideally, this would be a feature implemented in MF 1.0 and 1.5, no need for additional plugins.

**Comment by ScriptedAlchemy** [comment]
Yeah no i was more asking about if our new enhanced plugin had a issue that webpack did not. 

Okay so generally, these instances are shared as you see. 

You can patch it in and out of the webpack cache, which tbh may be the only way to do this type of thing (you should check what happens in production when module id is numeric) 

I dont think there is a good option here to make "forgetful" modules, without possibly creating a new module type and module factory on the compiler end to do this. Like EagerIsolatedModule or something
