### ISSUE TITLE
Can I Remove remote.js?[hash] for cache remote.js

### ISSUE THREAD

**Issue by ohdonguri** [module-federation/module-federation-examples#3797]
My App folder architecture
 l -- services
   l -- pages
     l -- remoteApp
     l -- login
     l -- etc ..

when I open any services pages, remote.js always loading.
but I don't want to load remote.js where I'm not use
So, is there any solution that cache remote.js?
or dynamic import when remote.js used page open

**Comment by ScriptedAlchemy** [comment]
You can, but you need another way to resolve the remote url. 

Something like this would work, using the module snapshot system we have built in.

https://github.com/2heal1/module-federation-incorrect-version-resolution/tree/chore/use-enhanced

**Comment by ohdonguri** [comment]
thanks !
