### ISSUE TITLE
[Bug][Nextjs13] Uncaught TypeError: Cannot read properties of undefined (reading 'consumes')

### ISSUE THREAD

**Issue by gjndual** [module-federation/module-federation-examples#3803]
I am getting error while running the module federation sample application 
[https://github.com/module-federation/module-federation-examples/tree/master/nextjs-v13](https://github.com/module-federation/module-federation-examples/tree/master/nextjs-v13)

when try to access Home app: http://localhost:3001/ on local (npm run dev) the error appear in chrome browser console:

`webpack.js?ts=1712024559181:1613 Uncaught TypeError: Cannot read properties of undefined (reading 'consumes')
    at __webpack_require__.f.consumes (webpack.js?ts=1712024559181:1613:59)
    at react-refresh.js?ts=1712024559181:60:94
    at webpackJsonpCallback (webpack.js?ts=1712024559181:2180:39)
    at Array.forEach (<anonymous>)
    at webpack.js?ts=1712024559181:2194:31
    at webpack.js?ts=1712024559181:2196:12
    at webpack.js?ts=1712024559181:2218:12`

**note: Try to run in build version (npm run build + npm run start) it works normally, the issue appear only on local (npm run dev)**

**Comment by ScriptedAlchemy** [comment]
Try it now, i merged a new update

**Comment by gjndual** [comment]
@ScriptedAlchemy  It is working perfect now, thank you
