### ISSUE TITLE
Examples issue

### ISSUE THREAD

**Issue by saeedghasemi72** [module-federation/module-federation-examples#3804]
Please check the Examples project. I previously and recently pulled the examples and want to use nextjs-v13, but every time there is an error.

<img width="1267" alt="Screenshot 2024-04-02 at 11 52 40 am" src="https://github.com/module-federation/module-federation-examples/assets/36558885/d25011cf-f189-47fe-8f38-e369245fa06d">

**Comment by mayconrr13** [comment]
Same thing here

**Comment by ScriptedAlchemy** [comment]
v13 should be working

**Comment by ScriptedAlchemy** [comment]
otherwise try pnpm install 'typescript' in the workspace
