### ISSUE TITLE
Dynamic-remotes shared config not work

### ISSUE THREAD

**Issue by huanghlun** [module-federation/module-federation-examples#3838]
I just cloned the git and try to run the demo in `advanced-api/dynamic-remotes`.  I did not modified any code and just run. 
When I click the button 'Load App 2 Widget', I found that the `react` package which considered to be shared, load twice in my project. But in the `rspack.config.js` file, the `react` package is in the `shared` scope, so I think it is an issue.
![bug](https://github.com/module-federation/module-federation-examples/assets/28281750/d74bb609-0aa5-46e5-8c95-fb85a4780c3f)
![rspack](https://github.com/module-federation/module-federation-examples/assets/28281750/f83bd897-ca3b-479b-ac85-35877229866e)

**Comment by ScriptedAlchemy** [comment]
Chunks are two different file sizes. name might look misleading but thats not two copies of the same module


you can also share         'react/jsx-dev-runtime': {},

**Comment by huanghlun** [comment]
Ok thanks. I got it.
