### ISSUE TITLE
Add ability to reduce requests waterfall for host-ui 

### ISSUE THREAD

**Issue by sowtame** [module-federation/module-federation-examples#3846]
![image](https://github.com/module-federation/module-federation-examples/assets/53125967/182b26af-d569-4b19-86c0-2f80ab79886a)
with the new announcement of mf-manifest, can the initialChunks field be added?

**Comment by ScriptedAlchemy** [comment]
whats `initialChunks` field mean?

**Comment by sowtame** [comment]
by the initialChunks field, I mean that this field will contain the names of the chunks necessary for rendering the initial page. The screenshot shows that we firstly load the index.js file, and then all the other modules.

1 this can be solved by removing the wrapper that imports bootstrap.js file (but that's not possible)
2 and the option with the initialChunks field, which will contain the necessary chunks, reducing the waterfall of requests

i have a little example of initial assets plugin [here](https://github.com/sowtame/server-module-federation/blob/feat/try-initial-plugin/dynamic-node/host/config/plugins/initial-assets-plugin.js#L43) 

with waterfall
![image](https://github.com/module-federation/module-federation-examples/assets/53125967/5881791c-060a-4d8e-bc7f-db480686c6de)

with parallel requests
![image](https://github.com/module-federation/module-federation-examples/assets/53125967/c892a409-74e0-4d63-a733-dc3bafc70e28)

**Comment by ScriptedAlchemy** [comment]
You can use the MF-manifest.json
