### ISSUE TITLE
vite-react-microfrontends example is broken

### ISSUE THREAD

**Issue by OscarLijoBusto** [module-federation/module-federation-examples#3987]
The example of vite and react with microfrontends that uses native federation does not work, I have already tried it months ago and it seems that the problem seemed to be this https://github.com/module-federation/vite/issues/16.
Now I saw that you updated the code last week and I tried it again and it's still broken.
I don't know if you are far from finding a solution, today I think it is important because vite and react are the most used front library and packager

**Comment by ScriptedAlchemy** [comment]
deleting all vite examples
