### ISSUE TITLE
Lost css style of remote app when call from host at production mode

### ISSUE THREAD

**Issue by lecong** [module-federation/module-federation-examples#3995]
Hi,

I use Tailwind CSS for a remote app. In production mode, the CSS styles of the remote app are lost if the remote app is accessed from the host. On the other hand, if the remote app is accessed directly, the CSS styles of the remote app are not lost.

At dev mode, CSS styles of the remote app are not lost.

How to resolve it.

**Comment by ScriptedAlchemy** [comment]
Disable optimization or tree shaking of unused tailwind assets
