### ISSUE TITLE
Cannot export _app.js with Next module federation

### ISSUE THREAD

**Issue by AndreaCominelli** [module-federation/module-federation-examples#4007]
**Description:**

We are experiencing an issue where we need to export our entire app as a microfrontend using Next.js and React. The specifics of our setup are as follows:
•	Next.js Version: 14.1.4
•	React Version: 18.2.0
•	Next Module Federation Version: 8.3.5

**Problem Description**

We are trying to leverage Next.js to create a microfrontend architecture for our application, starting from your boilerplate in nextjs-v14 example directory. Our host and remote are both running on Nextjs 14. The goal is to export the entire app as a microfrontend, but we are encountering difficulties in doing so. In general, the code seems working as long as we are running it in its standalone mode. On the contrary, when we try to import _app.js on the host counterpart, the app throws the error shown in the image below.

![immagine (3)](https://github.com/module-federation/nextjs-ssr/assets/55619596/57a4b31b-c4ae-4469-8207-7460436a175f)

This error seems due to the fact that the "Component" prop is undefined when _app.js is imported in the host application.

**Remote**

![immagine (4)](https://github.com/module-federation/nextjs-ssr/assets/55619596/2d55a1e3-dad3-4c41-8129-3fee5260b7fb)

**Host**

![immagine (5)](https://github.com/module-federation/nextjs-ssr/assets/55619596/063e834a-1289-42a1-9497-faa47202aeda)

We also tried to export the _document.js file but it does not seem to work.

**Steps to Reproduce**

1.	Set up a Next.js project with version 14.1.4.
2.	Integrate React with version 18.2.0.
3.	Configure Next Module Federation with version 8.3.5.
4.	Attempt to export the app as a microfrontend (as shown below in next.config.js)

**Expected Behavior**

The entire app should be successfully exported as a microfrontend, enabling us to integrate it seamlessly with other microfrontends or container applications.

**Actual Behavior**

The export process fails, and we are unable to generate the microfrontend as expected. See the images below to better understand how we implemented the microfrontend architecture.

**Next Federation Plugin configuration**

```js
const NextFederationPlugin = require('@module-federation/nextjs-mf');

module.exports = {
  webpack(config, options) {
    if (!options.isServer) {
      config.plugins.push(
        new NextFederationPlugin({
          name: 'shop',
          filename: 'static/chunks/remoteEntry.js',
          remotes: {
            home: 'home@http://localhost:3001/_next/static/chunks/remoteEntry.js',
            checkout: 'checkout@http://localhost:3000/_next/static/chunks/remoteEntry.js',
          },
          exposes: {
            './shop': './pages/shop',
            './pdp': './pages/p/[...slug].js',
            './main': './pages/_app.js',
            './pages-map': './pages-map.js',
            './customHook': './components/someHook.js',
          },
        }),
      );
    }
    return config;
  },
};
```

**Comment by ScriptedAlchemy** [comment]
Seems like you are trying to dynamically do it - you cant do that with next.js - next is very limited and cannot do much in MFE
