### ISSUE TITLE
Duplication of shared libs in prod - react-manifest-example

### ISSUE THREAD

**Issue by kubahrom** [module-federation/module-federation-examples#4022]
Tried the react-manifest-example which is showcased in module-federation 2.0 video and when I build all the apps and preview the built app React is not shared and it's downloaded multiple times.

Only change I made is add `output: { assetPrefix: "http://localhost:3001" },` to the remotes rsbuild.config.ts.

Am I missing something?

![image](https://github.com/module-federation/module-federation-examples/assets/32403046/a6c8ea40-b8bb-4410-99a0-28cdecdb46cb)

**Comment by ScriptedAlchemy** [comment]
```js
  plugins: [pluginReact({
    splitChunks: {
      react: false,
      router: false
    }
  })],
```
