### ISSUE TITLE
The entry point "react" cannot be marked as external

### ISSUE THREAD

**Issue by XQY279** [module-federation/module-federation-examples#4032]
<img width="1000" alt="image" src="https://github.com/module-federation/module-federation-examples/assets/45452939/5be0e994-ef05-413e-bf0f-4a2683b9921a">
Here is the translation of your text into English:

"When I was running the vite-react-microfrontends demo, I encountered the error The entry point "react" cannot be marked as external. I tried changing the shared in federation.config.cjs to

```js
shared: ['react', 'react-dom']
```

After that, the error was fixed, but another error occurred in the project:
<img width="785" alt="image" src="https://github.com/module-federation/module-federation-examples/assets/45452939/612abed5-6712-4dff-9ad5-ab3f0e32ce2d">

**Comment by ScriptedAlchemy** [comment]
Will delete all vite examples
