### ISSUE TITLE
Vite examples were removed 

### ISSUE THREAD

**Issue by renansoares** [module-federation/module-federation-examples#4142]
Hi, I see the examples to use with Vite was removed in [this](https://github.com/module-federation/module-federation-examples/commit/cd5ef1658dbdf7d8ed20f90b52b9080c2a1cf855) commit.

I've been trying to understand if there's a way to make Webpack (host) + Vite (remote) for module federation to work. 

The old examples with Vite were using a package `@module-federation/vite` which was a implementation using Native Federation. Could you explain why was it removed?

As far as I understood, it is not possible to have a Module Federation host + Native Federation remote, at least it's not supported because Native Federation creates a `remoteEntry.json` instead of a `remoteEntry.js`. Is there a way to make these two compatibles? If yes, what are the challenges involved?

Could you please help me by giving suggestions if it is possible and that would be the approach to have the setup Webpack (host) + Vite (remote) ?

I'm happy to contribute if needed.

**Comment by ScriptedAlchemy** [comment]
that package under our org is community based, since it had problems and did not work with my v2 architecture, i have removed all examples that do not implement my runtime reliably
