### ISSUE TITLE
Error: Cannot find module , node_modules\next\dist\compiled\lib\util\makeSerializable' 

### ISSUE THREAD

**Issue by Mahmoud-Haraba** [module-federation/module-federation-examples#4242]
Hi, 
i appreciate your work on the module federation library.

I'm using Next 14.2.4 and i installed the following 
`npm install webpack webpack-cli webpack-dev-server --save-dev` and 
 `npm install @module-federation/nextjs-mf`
 and this is the next.config.mjs file : 

```
 import { NextFederationPlugin } from "@module-federation/nextjs-mf";
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  webpack: (config, options) => {
    const { isServer } = options;
    config.plugins.push(
      new NextFederationPlugin({
        name: "main",
        remotes: {
          secondary: `secondary@http://localhost:3001/_next/static/${
            isServer ? `ssr` : `chunks`
          }/remoteEntry.js`,
        },
        filename: "static/chunks/remoteEntry.js",
      })
    );
    return config;
  },
};

export default nextConfig;
```
i added the `NEXT_PRIVATE_LOCAL_WEBPACK=true` in .env.local file ;

this is the package.json file : 

```
{
  "name": "main",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@module-federation/nextjs-mf": "^8.3.28",
    "next": "14.2.4",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "eslint": "^8",
    "eslint-config-next": "14.2.4",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "webpack": "^5.92.1",
    "webpack-cli": "^5.1.4",
    "webpack-dev-server": "^5.0.4"
  }
}
```

and im getting this error upon running `npm run dev` : 

No ModuleFederationPlugin(s) found.
Error: Cannot find module 'C:\Users\Mahmoud Haraba\Desktop\main\node_modules\next\dist\compiled\lib\util\makeSerializable'
Require stack:
- C:\Users\Mahmoud Haraba\Desktop\main\node_modules\@module-federation\enhanced\dist\src\lib\container\ContainerExposedDependency.js
- C:\Users\Mahmoud Haraba\Desktop\main\node_modules\@module-federation\enhanced\dist\src\lib\container\ContainerEntryModule.js
- C:\Users\Mahmoud Haraba\Desktop\main\node_modules\@module-federation\enhanced\dist\src\lib\container\HoistContainerReferencesPlugin.js
- C:\Users\Mahmoud Haraba\Desktop\main\node_modules\@module-federation\enhanced\dist\src\wrapper\HoistContainerReferencesPlugin.js
- C:\Users\Mahmoud Haraba\Desktop\main\node_modules\@module-federation\enhanced\dist\src\index.js
- C:\Users\Mahmoud Haraba\Desktop\main\node_modules\@module-federation\nextjs-mf\dist\src\plugins\NextFederationPlugin\apply-server-plugins.js    
- C:\Users\Mahmoud Haraba\Desktop\main\node_modules\@module-federation\nextjs-mf\dist\src\plugins\NextFederationPlugin\index.js
- C:\Users\Mahmoud Haraba\Desktop\main\node_modules\@module-federation\nextjs-mf\dist\src\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at C:\Users\Mahmoud Haraba\Desktop\main\node_modules\next\dist\server\require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at mod.require (C:\Users\Mahmoud Haraba\Desktop\main\node_modules\next\dist\server\require-hook.js:65:28)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (C:\Users\Mahmoud Haraba\Desktop\main\node_modules\@module-federation\enhanced\dist\src\lib\container\ContainerExposedDependency.js:8:26)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32) {
  code: 'MODULE_NOT_FOUND',

  i tried everything on the internet , nothing helped . Any help would be appreciated .
  Thanks in advance.

**Comment by Mahmoud-Haraba** [comment]
@ScriptedAlchemy I'm sorry for the tag but i cant find any thing .

**Comment by osahbudak7** [comment]
Hello,

Here are the steps to fix the issue:

` npm install --save-dev cross-env` //Install cross-env to ensure environment variables are set correctly across different platforms.

Update the scripts section in package.json:

```
"scripts": {
  "dev": "cross-env NEXT_PRIVATE_LOCAL_WEBPACK=true next dev -p 3001",
  "build": "cross-env NEXT_PRIVATE_LOCAL_WEBPACK=true next build",
  "start": "cross-env NEXT_PRIVATE_LOCAL_WEBPACK=true NODE_ENV=production next start -p 3001"
}
```

After following these steps, the build process should work correctly.

 `npm run build`

**Comment by ScriptedAlchemy** [comment]
Correct ^^
