### ISSUE TITLE
Question: @mf-types in source control or no?

### ISSUE THREAD

**Issue by lestersconyers** [module-federation/module-federation-examples#4243]
Real simple question: Do you recommend @mf-types be included or excluded from source control?

**Comment by ScriptedAlchemy** [comment]
Some do so that during initial startup, if someone is offline etc, it can still get the types etc. Helpful for race conditions.

**Comment by lestersconyers** [comment]
Sorry. Super late following up here but it appears that it's required to push @mf-types into source control. Otherwise the build fails. I do not see a way to generate the definitions on build. Only on run dev. Am I missing something?

**Comment by ScriptedAlchemy** [comment]
All builds pull types afik 
You can commit them tho. Some do. Others don't
