### ISSUE TITLE
HELP WANTED: A simple unit test that webpack builds dont throw errors

### ISSUE THREAD

**Issue by ScriptedAlchemy** [module-federation/module-federation-examples#425]
as the number of examples grow, its getting very hard to verify everything works as i update dependencies. 

If anyone would be willing to create a jest test that loops over the examples directory and runs a `yarn build` if the build doesn't error, its a pass.

**Comment by rajasekarm** [comment]
I can give a PR for this.

**Comment by ScriptedAlchemy** [comment]
Omg thank you! 

Some of them will likely fail. I'm half way through the webpack 5 stable update. 

You can check out mini css tests or webpack/cases in the webpack repo. They have a loop that does prey much this. I'm just slammed on time trying to release new MF tools 

Would really appreciate any assistance and happy to add on to it as time permits (maybe I'll bring in  some dev server and serve pings, to make sure they boot in client)

The main need really is just "did it build"?

**Comment by rajasekarm** [comment]
I'm getting this error when I try to run the example.

https://github.com/webpack/webpack/issues/11633

**Comment by hamstu** [comment]
Happy to help as well 🤚 – maybe a Github Action check that runs these checks when you push, so you don't need to even worry about doing it manually?

**Comment by rajasekarm** [comment]
Yeah, that make sense. we can run this on every PR.

**Comment by rajasekarm** [comment]
Switched to update-to-v5-stable and it worked!

**Comment by ScriptedAlchemy** [comment]
Thanks everyone! Sorry I didn't expect a quick response 😁 I was right in the middle of the upgrade and that's what caused me to reach out! Master was broken for a few hours after renovate not update everything. Half the battle is running them all 😂

**Comment by armujahid** [comment]
@ScriptedAlchemy Why can't we just add build script in root package.json using lerna. I think this will do the job.

**Comment by ScriptedAlchemy** [comment]
Ill likely want to extend it further to support E2E testing with jest-puppeteer or something to confirm dev and prod mode build + don't error out in the client. @armujahid 

Ill merge the build script and test it out, it'll be helpful to run litmus checks at a very high level :)

**Comment by armujahid** [comment]
Linking https://github.com/module-federation/module-federation-examples/pull/441 that closed this issue :+1:
