### ISSUE TITLE
I encountered a hydration error while integrating i18n, as demonstrated in the example provided in the repository

### ISSUE THREAD

**Issue by darshan82** [module-federation/module-federation-examples#4252]
Language detection is based on the value stored in local storage. However, when the page is rendered on the server, an error occurs because the language used during server-side rendering is the fallback language, while the client uses the language stored in local storage.
Host and remote both apps are on next js latest version with page routing and using turbo mono repo with it
```[tasklist]
### Tasks
```

**Comment by ScriptedAlchemy** [comment]
You need to set it as a cookie then or something in the route path so server knows how to handle it. Same as with any SSR app.
