### ISSUE TITLE
[Question] styles.scss not reflecting in remote app when injected in shell

### ISSUE THREAD

**Issue by dassum03-BH** [module-federation/module-federation-examples#4283]
Using angular v17, currently all the styles/media queries in my styles.scss are not reflected in the mfe when injected in shell application.. I read it is a limitation.. is there any workaround?

Reference: https://github.com/nrwl/nx/issues/17945

@ScriptedAlchemy please guide/assist

**Comment by ScriptedAlchemy** [comment]
Does a federated module you exposed import the stylesheet? You must explicitly import the styles. In an exposed module, if it's just something that is implicitly inherited from higher up in the app, then the exposed module doesn't know that there's any dependency on that file. Therefore, you should import it in the file to ensure that it will be loaded with the exposed module.
