### ISSUE TITLE
rollup-federation-demo doesn't work

### ISSUE THREAD

**Issue by davewthompson** [module-federation/module-federation-examples#442]
The Rollup demo at https://github.com/module-federation/module-federation-examples/tree/master/rollup-federation-demo doesn't work.

The instructions state you should run `yarn start` but there is no `package.json` file in the directory.
In addition, manually running `yarn` and `yarn start` in both directories starts up servers but browsing to both URLs results in various console errors and nothing being shown.

Could you please fix this?

**Comment by ScriptedAlchemy** [comment]
@jacob-ebey do we have any updated rollup code in one of your repos? Im not sure if my rollup updates of v5 messed something up

**Comment by davewthompson** [comment]
I actually managed to hack together a solution by extending the `rollup-federation` plugin to generate the same code that the Webpack module federation demo does - it creates a `script` tag and then waits until the script is dynamically loaded into the DOM before it then resolves the promise that the `__federation__` runtime waits on. I'll talk to my corporate counsel today and see if I can raise a MR with the changes.

**Comment by ScriptedAlchemy** [comment]
Yeah it would be great to see how it was fixed. I can apply this back to the rollup plugin / I'll accept a pr to that plugin directly if you know what needs to be done.

**Comment by davewthompson** [comment]
@ScriptedAlchemy I have referenced the code we used to dynamically load federated modules in https://github.com/webpack/webpack/issues/11033#issuecomment-711693729. There's a bug I need to file, though, and it involves two modules served from Webpack running in HMR mode - components in different modules with the same name collide.

**Comment by ScriptedAlchemy** [comment]
HMR will not work with MF. Use live reload for now.
