### ISSUE TITLE
Vue2 remote with Vue3 host: "selfHook.bind is not a function".

### ISSUE THREAD

**Issue by matrunchyk** [module-federation/module-federation-examples#456]
Thank you for Module Federation feature, this is amazing! I've seen all your videos on YouTube and finishing reading your book and I love it!!!

A case in our company to try MF with Vue3 in a new project while still reusing MF in Vue2 (WP5).

Here is my **Vue2** `webpack.config.js`:

```
new ModuleFederationPlugin({
      name: 'shared_ui',
      filename: 'remoteEntry.js',
      library: { type: 'var', name: 'shared_ui' },
      remotes: {},
      exposes: {
        './TestButton.vue': './src/TestButton.vue',
        './helpers': './src/shared/helpers',
      },
      shared: {
        vue2: 'vue',
      },
    }),
```

Here is my **Vue3** `webpack.config.js`:

```
new ModuleFederationPlugin({
      name: 'mf_app',
      filename: 'remoteEntry.js',
      remotes: {
        shared_ui: 'shared_ui@http://localhost:9092/remoteEntry.js',
      },
      exposes: {
      },
      shared: {
        vue3: 'vue',
      },
    }),
```

and how I use it in Vue3:

```
<script lang="ts">
import { defineAsyncComponent, defineComponent } from 'vue';

export default defineComponent({
  name: 'About',
  components: {
    TestButton: defineAsyncComponent(() => import('shared_ui/TestButton.vue')),
  },
});
</script>

```

It doesn't render the component and gives the following error:

![image](https://user-images.githubusercontent.com/2089828/96346507-d3dba400-10a4-11eb-977f-c4dddc34bbb0.png)

I suspect that my vue2-based component uses vue3. However, I followed "different react versions" examples and specified different keys for vue versions.

Btw, the federation itself works for regular JS/TS files (via exposed `helpers`). The problem here is with different Vue versions.

I also think it would be very very helpful for Vue community to add examples for this case. (Vue2 host and Vue3 as a remote and vice versa).

**Comment by nicholaslopiccolo** [comment]
I reproduced the problem. If hooks are used as property instead of functions.

Bug generated:
`const VerificaSezioniConfig = {
        delimiters:['[[',']]'],
        data(){
            return{
                sezioni:[1,2]
            }
        },
        mounted:{}
    }`

No Bug:
`const VerificaSezioniConfig = {
        delimiters:['[[',']]'],
        data(){
            return{
                sezioni:[1,2]
            }
        },
        mounted(){}
    }`
