### ISSUE TITLE
angular11-microfrontends - not working

### ISSUE THREAD

**Issue by vjangari** [module-federation/module-federation-examples#462]
Angular 11 micro frontend sample is not working at stuck at 23% when we serve examples. Tried on Windows 10 and Windows 7 and with angular cli@11.0.0-next.5 

> 23% building 1/4 entries 56/58 dependencies 30/32 modules(node:16496) [DEP_WEBPACK_CHUNK_MODULES_ITERABLE] DeprecationWarning: Chunk.modulesIterable: Use new ChunkGraph API
> (node:16496) [DEP_WEBPACK_CHUNK_ENTRY_MODULE] DeprecationWarning: Chunk.entryModule: Use new ChunkGraph API
>

**Comment by mellondev** [comment]
It appears angular 11-next..7 has broken it, the package.json had "~11.0.0-next5", removing the ~ and re-running yarn will lock it to next.5 and then it should run ok, will push up a PR to lock the version for now, below is the updated dependencies:

```
"dependencies": {
    "@angular/animations": "11.0.0-next.5",
    "@angular/common": "11.0.0-next.5",
    "@angular/compiler": "11.0.0-next.5",
    "@angular/core": "11.0.0-next.5",
    "@angular/forms": "11.0.0-next.5",
    "@angular/platform-browser": "11.0.0-next.5",
    "@angular/platform-browser-dynamic": "11.0.0-next.5",
    "@angular/router": "11.0.0-next.5",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^10.0.1",
    "@angular-devkit/build-angular": "0.1100.0-next.5",
    "@angular/cli": "11.0.0-next.5",
    "@angular/compiler-cli": "11.0.0-next.5",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.2.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "ngx-build-plus": "^10.1.1",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
```

**Comment by mellondev** [comment]
Pull request in https://github.com/module-federation/module-federation-examples/pull/465

**Comment by Coolpix** [comment]
I think what breaks the compilation is version next-6 of CLI. It has a breaking change that affects ngx-build-plus. As @mellondev says, you must lock next-5 in order to build and run the app.

**Comment by vjangari** [comment]
Thank you. It is working with 11.0.0-next.5

**Comment by vjangari** [comment]
> I think what breaks the compilation is version next-6 of CLI. It has a breaking change that affects ngx-build-plus. As @mellondev says, you must lock next-5 in order to build and run the app.

true. build is working where as serve broken it seems
