### ISSUE TITLE
There is no hash for remoteEntry. How do you ensure that you get the latest Page component in browser cache

### ISSUE THREAD

**Issue by luxuryXu** [module-federation/module-federation-examples#491]

**Comment by matthewma7** [comment]
Hi, you could give the plugin I wrote a try.
https://github.com/module-federation/module-federation-examples/issues/566

**Comment by ScriptedAlchemy** [comment]
304 cache-control headers or query string time stamps

**Comment by JasonKleban** [comment]
But why doesn't remoteEntry's references to the various bundles have '[contenthash]' ?  I understand that remoteEntry.js should have a stable name and short caching, but the files it refers to should have hashed names and cached long-term.  No?
