### ISSUE TITLE
git@github.com:module-federation/proprietary-tools.git not accessible

### ISSUE THREAD

**Issue by julienfroidefond** [module-federation/module-federation-examples#50]
Hi,

I'm really interested to make work this code samples @home :) But I can't access a repo.

Error: Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git@github.com:module-federation/proprietary-tools.git
Directory: /Users/julien.froidefond/Sites/module-federation-examples/basic-host-remote/app1
Output:
Host key verification failed.
fatal: Could not read from remote repository.

**Comment by jacob-ebey** [comment]
Federated streaming (static orchestration) is currently proprietary code.

**Comment by maraisr** [comment]
Hi @julienfroidefond, yeah its as @jacob-ebey has said. Currently this is a feature we are exploring and not something we have opened up. I do believe that if you don't run any of the submodule init commands, you should be okay to use the repo error free.

Let me know how you go!

**Comment by kenkozheng** [comment]
@julienfroidefond 
I just delete all things about `proprietary-tools.git`, and yarn install.
Then, it works for me.

Before this, I doubt about my github ssh config, and try 100+ method to solve. But at last, I found proprietary-tools.git is not exist ! oops~~~

**Comment by julienfroidefond** [comment]
Thx all; I'll try the @kenkozheng method ;) I'll resolve this issue if ok; thx for the support

**Comment by julienfroidefond** [comment]
By the way, for public; it should be nice to have a line in the readme. I think I am not the only one in this case. The error is at _yarn install_.

**Comment by julienfroidefond** [comment]
Yes, it works ! basic remote is running now.
