### ISSUE TITLE
comprehensive demo doesn't load svelte app

### ISSUE THREAD

**Issue by khanzzirfan** [module-federation/module-federation-examples#502]
Network has 404 error for bundle.css
Main app on port 3001 also fails for the same reason.

![image](https://user-images.githubusercontent.com/8625166/97766182-772ebd80-1b69-11eb-802f-df675bbecf03.png)

![image](https://user-images.githubusercontent.com/8625166/97766197-87df3380-1b69-11eb-98a3-432683ba893c.png)

**Comment by khanzzirfan** [comment]
ok it seems like the issue is tracked here 
[https://github.com/sveltejs/svelte-loader/issues/139](svelte)

**Comment by JB1905** [comment]
@khanzzirfan please check my PR #792. I updated svelte-loader and html-webpack-plugin.
