### ISSUE TITLE
Using v3 app inside of Vue2 app

### ISSUE THREAD

**Issue by matrunchyk** [module-federation/module-federation-examples#504]
Hello! Thank you for the great book and for Module Federation feature set!

In our company we have two big Vue2 apps (which we'll gradually plan to migrate to Vue3). Also we've started working on a new Vue3 application and we'd like to use some part of it in both Vue2 apps.

Does MF covers this case somehow?

**Comment by ScriptedAlchemy** [comment]
Open a PR if you got it working. Others would likely be interested
