### ISSUE TITLE
How can i share a component in Angular?

### ISSUE THREAD

**Issue by Coolpix** [module-federation/module-federation-examples#506]
Hi, this is just a question instead of an issue.

All the examples and documentation that i read about federation in angular are related to modules and all the modules are loaded using router´s lazy load, so they are all linked to an url.

My question is how can i share a component or a module that are not related to an url but to just a shared module/component/service with just a bunch of code?

**Comment by ydmitry** [comment]
Hello,
yesterday created an example for issue in custom-webpack builder repo:
https://github.com/ydmitry/angular11-webpack-module-federation-custom-webpack-builder
E.g. this loads a component lazily without router:
https://github.com/ydmitry/angular11-webpack-module-federation-custom-webpack-builder/blob/main/src/app/app.component.ts#L21

**Comment by jimyhdolores** [comment]
Hello, I tried to load a component according to the example but it throws many errors, will you have an updated example?

I am using "@angular-architects/module-federation": "^14.3.9"

Angular version: 14.0.4
