### ISSUE TITLE
Page refresh in shared-routing 404s when using dev server

### ISSUE THREAD

**Issue by ChrisLincoln** [module-federation/module-federation-examples#507]
It's the kind of classic react-router issue that is solved with url-rewrites on the server, but I don't know how to do the same with the webpack-dev-server. I thought historyApiFallback: true was supposed to deal with this, but it doesn't seem to. Part of my problem is knowing exactly which webpack.config to target.  I would think the one in shell, because I presume it is the one 404-ing when http://localhost:3000/dashboard is the initial route.

When I use "yarn start", everything works as expected.

When I use "yarn build" followed by "yarn serve", I must start at 'http://localhost:3000', then all links work.  But a page refresh 404s.

**Comment by Ruchi1990** [comment]
@ChrisLincoln were you able to find the solution, i am also facing the same issue.

**Comment by ChrisLincoln** [comment]
@Ruchi1990 No I did not.  I was only dabbling and probably shouldn't have created this issue without more serious intent to follow through.

**Comment by ScriptedAlchemy** [comment]
Static import the route logic or have a catch all that can parse and figure out what remote container to call
