### ISSUE TITLE
How to change a normal npm node to remote module

### ISSUE THREAD

**Issue by gaoletian** [module-federation/module-federation-examples#513]
I have a large project, i want split to multiple repo, 
- appshell
- foo
- bar

but they all need a common package named `@remote/app-service`, and updates are frequent, so i want make it as a remote module, when i publish this module , all repo will update.

**before**

- complie by `tsc`, and still keeped all file structure

**after** 

- complie by webpack + babel,  file structure can not keep

**What's best practice to do it? it there have a example?**

**Comment by matthewma7** [comment]
I think you are on the right track and can just go ahead and do it? Any blockers?
Of course, you would need a server to constantly serve the webpack output.

**Comment by jacob-ebey** [comment]
I do not recommend sharing an entire lib unless you have very strict versioning implemented where you work. Someone *will* publish a breaking change and you're going to bring down your whole stack.

With that said, you can do something like the storybook plugin and just dump all the input files into the exposes: https://github.com/xolvio/storybook-webpack-federation-plugin/blob/master/src/index.js
