### ISSUE TITLE
How to use multiple version remotes like shared?

### ISSUE THREAD

**Issue by stonexer** [module-federation/module-federation-examples#515]
For example.

1. An application contains the packages `profile`, `home` and `search`. The package `profile` provides the `Profile` component, and the packages `home` and `search` use the `Profile` component from the remote package.

2. The code of the `Profile` component was modified (some breaking changes were introduced) and the version was upgraded from `1.0` to `2.0`, at which point the `home` package updated its code to use the latest version of `2.0`.  However, the code in the `search` package has not been updated yet, and should use the `1.0` version.

As far as I can tell, it is possible to use shared version control (e.g. using multiple versions at the same time) in managing third party dependencies such as lodash. But I haven't found a solution in the remote package yet.

Thanks for any input.

**Comment by unbugx** [comment]
Module federation looks amazing but I need to find a solution for same problem. Maybe keep different built versions of package with Profile and consume only needed one for given host?

**Comment by jacob-ebey** [comment]
@stonexer @unbugx check out this twitter thread on using unpkg for controlling what version of a remote container your host app consumes: https://twitter.com/ebey_jacob/status/1349585067765506048

Here are the source examples:
Versioned Container: https://github.com/jacob-ebey/versioned-federated-module
Consuming Remote: https://github.com/jacob-ebey/consume-versioned-federated-module

This is also something that the federation dashboard project and accompanying plugins are addressing: https://hub.docker.com/r/scriptedalchemy/mf-dashboard.

**Comment by unbugx** [comment]
@jacob-ebey thx, but unfortunately this approach is not suitable for me as I want to keep all repositories as private. The simplest solution I see is keeping different build versions of container on my own host.

**Comment by ScriptedAlchemy** [comment]
Append the name to the remotes name property and file name . Then you can lol unique files and resolve to the right global like app1:app1v2_0

**Comment by penguintree** [comment]
@ScriptedAlchemy I have the same concern as the OP. I'm not sure I understand your answer, can you provide a more detailed example ?
In my remote webpack.config.js (profile package from the OP example), I changed the `name` and the `filename` of the package like this :
``` 
   new ModuleFederationPlugin({
      name: 'profile_2_0',
      filename: 'profile.2.0.entrypoint.js',
      exposes: {
         ...exposed
      },
      shared: {
         ...packageJsonDependencies
      }
   })
```

The `home` package points to the `2.0` entry point (`profile_2_0@localhost:8001/profile20/profile.2.0.entrypoint.js`) while the `search` package points to the `1.0` entry point.

The 2 versions of entry points are requested, but only one version of the component is loaded. The first that is `import`ed wins.

Note : I can somehow make this work only when on version is compiled in `dev` mode and the other in `production` mode.

Edit : I created [this issue](https://github.com/webpack/webpack/issues/14011) to address this specific behavior.

**Comment by maheshshah196** [comment]
@unbugx you can use [unpkg-server](https://www.npmjs.com/package/unpkg-server) on your own network and then use this [solution](https://www.npmjs.com/package/unpkg-server) as described by @jacob-ebey
