### ISSUE TITLE
How to use with optimization.splitChunks

### ISSUE THREAD

**Issue by leezng** [module-federation/module-federation-examples#516]
When I make the following configuration in conjunction with module-federation, the page will be blank, but there is no error emit:
```js
optimization: {
    splitChunks: {
      chunks: 'all',
      minSize: 30000,
      cacheGroups: {
        asyncs: {
          chunks: 'async',
          minChunks: 2,
          name: 'asyncs',
          maxInitialRequests: 1, // The default limit is too small to showcase the effect
          minSize: 0, // This is example is too small to create commons chunks
          priority: -4,
          reuseExistingChunk: true,
        },
      },

new ModuleFederationPlugin({
      name: 'app1',
      remotes: {
        app2: 'app2@http://localhost:3002/remoteEntry.js',
      },
      shared: {
        react: { singleton: true },
        'react-dom': { singleton: true },
      },
    }),
```

But if you add a test attribute in splitChunks with a value of '', it can be loaded normally.

```js
optimization: {
    splitChunks: {
      chunks: 'all',
      minSize: 30000,
      cacheGroups: {
        asyncs: {
          test: '',
```

**Comment by jacob-ebey** [comment]
Unless you have a really good reason, the webpack 5 default chunk configuration should be all you need. I recommend *not* changing this manually, we're not on webpack 3 anymore.

**Comment by jacob-ebey** [comment]
@leezng This is something you probably want to report to webpack with a repro. https://github.com/webpack/webpack/issues/new/choose

**Comment by ScriptedAlchemy** [comment]
In general I don’t mix chunking with federation

**Comment by krutoo** [comment]
@ScriptedAlchemy i have similar question - i need to make one css chunk for bundle
https://github.com/webpack/webpack/discussions/18099

**Comment by ScriptedAlchemy** [comment]
Module federation enhanced package should have support for chunk split
