### ISSUE TITLE
Simple dynamic remote url

### ISSUE THREAD

**Issue by matthewma7** [module-federation/module-federation-examples#517]
Hi, thank you for this game changer library and answering my previous questions. 🙂 

As we know, the standard way to define remote module is like this,
![image](https://user-images.githubusercontent.com/3123478/99456606-aaa67180-28f7-11eb-9a0f-54058c87ec23.png)
However, we would like to be able to determine the url not at compile time but at runtime. 
I don't know if [Dynamic Remote Containers](https://webpack.js.org/concepts/module-federation/#dynamic-remote-containers) and [dynamic-system-host](https://github.com/module-federation/module-federation-examples/tree/master/dynamic-system-host) are supposed to provide what I need, but they look more complex than I would like. 

When stepping through the code, I saw this code snippet.
![Screenshot at Nov 17 16-45-51](https://user-images.githubusercontent.com/3123478/99457050-59e34880-28f8-11eb-9662-09444c36e412.png)
So, I am wondering if it is possible to allow the remotes as a function or some thing like that so I can possibly read some value from global scope at runtime. (I don't need async support for such a function)
Disclaimer: NOT REAL CODE BELOW
![Screenshot at Nov 17 17-21-21](https://user-images.githubusercontent.com/3123478/99457675-569c8c80-28f9-11eb-96ed-f863ef52db47.png)

**Comment by matthewma7** [comment]
I feel it is possible to write a webpack plugin to make the URL string a template string or something after the above snippet has been produced by the webpack ExternalModule, but I don't know how to write such plugin at this moment.

**Comment by sbrichardson** [comment]
I posted this comment, I believe I originally meant to reference this issue, 
https://github.com/module-federation/module-federation-examples/issues/529#issuecomment-733194028

**Comment by ScriptedAlchemy** [comment]
use new promise or external function, as mentioned in other issue

**Comment by davekiss** [comment]
@ScriptedAlchemy any chance you can provide a simple example of the correct value to provide to `remotes` for loading a remote from a window variable? I can't seem to get the configuration right on my end.

**Comment by matthewma7** [comment]
Hi @davekiss, I believe ScriptedAlchemy meant that to load the remoteentry.js with a dynamic custom script, and make it wait the remote module be loaded before start of the webpack main.bunble.js.
Basically, stop using the config to define the url of the remoteentry.js but with the a custom script.

**Comment by matthewma7** [comment]
Hi @davekiss, this plugin I wrote would allow you to read from the window.
https://github.com/module-federation/module-federation-examples/issues/566
