### ISSUE TITLE
Anything wrong with putting remoteEntry.js back in the <head>?

### ISSUE THREAD

**Issue by matthewma7** [module-federation/module-federation-examples#518]
I noticed as Module Federation has became more mature, a new syntax was introduced to load remoteEntry.js.
Instead of adding remoteEntry.js to the `<head>` of the page, it is define in webpack.config.js. however this makes the URL a build type fixed value. 

I just found out it is still possible (only tried with my code and the [basic-host-example](https://github.com/module-federation/module-federation-examples/tree/master/basic-host-remote)) to move the remoteEntry.js back to the '<head>' and remove the content after @ to make it possible to determine the URL of the remoteEntry.js later. 

![image](https://user-images.githubusercontent.com/3123478/99473371-71322e00-2918-11eb-9165-1d007d5a788a.png)
ignore the async there, async might not work if the remote host is slow. 

![image](https://user-images.githubusercontent.com/3123478/99473285-48aa3400-2918-11eb-9e96-a4e1cd89b4e9.png)

Anything wrong with moving it back to the `<head>`?

PS: This is related to https://github.com/module-federation/module-federation-examples/issues/517

---

Update:
I have a plugin to avoid need to fall back to use this approach.
https://github.com/module-federation/module-federation-examples/issues/566

**Comment by todda00** [comment]
I have gotten Module Federation to work dynamically following the example here: https://github.com/module-federation/module-federation-examples/blob/master/dynamic-system-host/app1/src/App.js 

This dynamically adds the script tag to the head, which you can do during runtime instead of build. We are using this concept to allow some custom routes to render a micro app / front end during runtime in [Konvert](https://konvertapp.com)

**Comment by sbrichardson** [comment]
@todda00 I think he's referring to changing the url of the remote dynamically, 
which is currently hardcoded by webpack in the remoteEntry.js and main.js files. I also have the dynamic loading
working properly, but not this use case example.

```js
// Example snippet from a nested app's remoteEntry.js

Promise(((e,r)=>{if("undefined"!=typeof app3)
return e();t.l("http://192.168.0.200:3003/remoteEntry.js",(t=>{if("undefined"!=ty
```

**Comment by jacob-ebey** [comment]
Nothing wrong with manually writing a script tag to the head. Just make sure your "remotes" config is pointed at the name of the remote you are manually adding.
