### ISSUE TITLE
Dynamic Routing Issue (Module Federation)

### ISSUE THREAD

**Issue by XiaofengXie16** [module-federation/module-federation-examples#529]
Hello, I recently started to experiment with module federation. I encountered a problem with dynamic routing.
I was trying with 3 different publicPath options. However, when I used option 2, I saw the error below(Both option 1 and option 3 worked fine):

`Uncaught ChunkLoadError: Loading chunk vendor failed`

option 1:  publicPath: `http://localhost:3021${config.get("contextPath")}`,
option 2:  publicPath: config.get("contextPath")
option 3:  publicPath: "auto"

I wonder what would cause option 2 to fail?

**Comment by sbrichardson** [comment]
(This may actually be more relevant to https://github.com/module-federation/module-federation-examples/issues/517)

One hack that works, although not ideal at all:
Use a plugin or script to manually replace the value of the url  in `remoteEntry.js` and `main.js` etc.

For kicks, I tried running the output through a second webpack build, with only a replace plugin. It would replace the value properly but would break the app/module-federation.

I had the best results just replacing the string value in `remoteEntry.js` with a function (IIFE) or direct value/global property, using a basic script after the build.

@ScriptedAlchemy ?

```js


// Snippet from original minified remoteEntry.js
return e();t.l(
  "http://localhost:3003/remoteEntry.js"
,(t=>{if("undefined"

// Replacing with an example self invoking function
return e();t.l(
  (() => { 
     console.log("hello", { t, window, this: this }); // t.g is window also
     return t.g.REMOTE_URL; }
  )()
,(t=>{if("undefined"

```
**Further experimenting**

These also work but only have access to the window. You would have to 
call the load module functions from web pack with the correct name/url etc.

```js
{
  remotes: {
    app3: "function (function() { console.log('hi', {this: this, window, arguments: arguments});})()",
    app3: "promise Promise.resolve().then(function() { console.log('hi', {this: this, window, arguments: arguments});})"
  }
}

```


This isn't applicable, but could show there are potentially other uncommon 
solutions available. I saw the below in a test within the webpack source, but this
runs during the build.

https://github.com/webpack/webpack/compare/mf/initial-shared#diff-908447074c08de1d2897868db69420a87874c8006420cce91d6b33f2badaaf71R25

```js
{
  remotes: {
     app3: "promise Promise.resolve().then(() => require('./container2.js'))"
  }
}
```

**Comment by matthewma7** [comment]
If you don't care about IE 11. Having 'auto' should just work. 'auto' is actually the new default value.

**Comment by ScriptedAlchemy** [comment]
`auto` is the right way to handle it, you can also do it with startup code or, like in the diff above, you could inject the script with your own promise.

**Comment by XiaofengXie16** [comment]
Thank you for all the recommendations above!

**Comment by rahul-ranjan-me** [comment]
How to handle publicPath in IE 11 which doesn't support "auto"
