### ISSUE TITLE
TSX errors not detected in TypeScript example

### ISSUE THREAD

**Issue by b12-144** [module-federation/module-federation-examples#532]
Hi, I tried the `Typescript` example and both apps work fine (app1 and app2) , but It doesn't detect any compiler errors in tsx files. Ex:, if you open app1/src/App.tsx and type some invalid code in it, the webpack configuration used in app1 project doesn't detect the error. I tried to use ts-loader instead of babel-loader to solve this issue, but I now HMR is not working. 
Any ideas on how to solve this? 
Thanks

**Comment by ScriptedAlchemy** [comment]
I don't know TS, cant helo with any of those. 

Send a PR if you fix it

**Comment by pedrodurek** [comment]
Hey @b12-144. It seems to be working fine 🤔 

<img width="961" alt="Screenshot 2021-03-30 at 10 14 12 PM" src="https://user-images.githubusercontent.com/12190482/113085423-5ebce080-91a5-11eb-9a2d-467d8b955b30.png">
<img width="1047" alt="Screenshot 2021-03-30 at 10 14 32 PM" src="https://user-images.githubusercontent.com/12190482/113085427-6086a400-91a5-11eb-8046-36c97f4298bb.png">
