### ISSUE TITLE
is there any way to provide a sandbox runtime for module 

### ISSUE THREAD

**Issue by lili21** [module-federation/module-federation-examples#533]
I want to prevent the remote module rewrite global stuff. or maybe inject some global stuff to remote module while running

**Comment by jacob-ebey** [comment]
Sandboxing, no. Injecting global stuff, yes: https://twitter.com/ebey_jacob/status/1336593664680710144

**Comment by ScriptedAlchemy** [comment]
Maybe when realms come out. But this is a limit of v8 currently
