### ISSUE TITLE
Shared configuration is not supported when dynamic load remote module ??

### ISSUE THREAD

**Issue by yellowbeee** [module-federation/module-federation-examples#537]
webpack.config.js
```
shared: {
          react: {eager: true, singleton: true, requiredVersion: '^16.13.1'},
          'react-dom': {
            eager: true,
            singleton: true,
            requiredVersion: '^16.13.1',
          },
          'react-router-dom': {requiredVersion: '^5.1.2'},
          'mobx-react-lite': {requiredVersion: '^1.5.2'},
          mobx: {requiredVersion: '^5.15.4'},
          axios: {requiredVersion: '^0.19.2'},
 }

```

when i dynamic loading remote module, it throw error:

![image](https://user-images.githubusercontent.com/16685984/101144939-068d2c00-3654-11eb-9c7c-212ed3796edc.png)

Then i find the error is the 'factory' is not a function, it return a Promise

![image](https://user-images.githubusercontent.com/16685984/101144870-eeb5a800-3653-11eb-9547-19067b189c5f.png)

and then i find the step of register shared module, it use '__webpack_require__.e', not use '__webpack_require__', it will return a Promise

![image](https://user-images.githubusercontent.com/16685984/101144665-a0080e00-3653-11eb-9741-ca3e1b7fb3f1.png)

How can I solve this problem ?

**Comment by matthewma7** [comment]
Based on my experience and understanding.
The error "Shared module is not available for eager consumption" could means that you have a module marked as eager, but it is requiring a shared module that doesn't not have the _eager_ flag. The solution could be marking all shared module _eager_.

**Comment by matthewma7** [comment]
I just noticed that even with `eager` flag, the `import('./bootstrap.js')` is still needed, otherwise, this error would be thrown.

**Comment by ScriptedAlchemy** [comment]
if you have multiple entry points, or use runtimeChunk:single - this could happen. We see it with setups like next.js

**Comment by lynnic26** [comment]
> if you have multiple entry points, or use runtimeChunk:single - this could happen. We see it with setups like next.js

I have only one entry point and runtimeChunk use default, this still happen. 
Any solutions?

**Comment by Rfank2021** [comment]
@yellowbeee have you solved the problem?

**Comment by Rfank2021** [comment]
I found if I follow https://github.com/module-federation/module-federation-examples/tree/master/basic-host-remote/app1, and also remove the remote app's eager:true, it will work, but seems the page load time is too long, not sure if it's because of it.

**Comment by Rfank2021** [comment]
@ScriptedAlchemy I feel most people don't understand what `eager consumption` means, maybe it's better to have a wiki explaining what it really means? If we don't understand, when we meet the issue, we can only treat it as black box, and try randomly.

**Comment by Rfank2021** [comment]
If remote set to `eager:true`, local should also set to `eager:true`, also bootstrap is needed to make sure only one react is in the initial chunk. Also don't forget to use `bundle-loader` or for most new cases just add `"module": "esnext"` to tsconfig, otherwise typescript will have problem on dynamic import.
