### ISSUE TITLE
Incomplete Docs on Dashboard

### ISSUE THREAD

**Issue by blink1073** [module-federation/module-federation-examples#54]
The dashboard example is not mentioned in the top level README, and its own README is the README from `bi-directional`.  

The note in the top level README should have the proprietary icon.

**Comment by blink1073** [comment]
I'd add the docs, but since I can't run the app, I'm not sure how to describe it :smile:

**Comment by zhangwilling** [comment]
It is not totally open source. one of dependencies is a private repo. So close this issue.

**Comment by blink1073** [comment]
Fair enough, but may I humbly suggest splitting the proprietary parts into another repo then?

**Comment by zhangwilling** [comment]
that private repo would be open source. I  am also waiting fot it 😉.

**Comment by ScriptedAlchemy** [comment]
Keeping things in one repo helps us as authors run things and not juggle multiple code bases. I’ll put on the readme that it will not work without authorization from the org. 

Some tools will be free or will include limited features. Some will be under BSD-3. 

There are monetary possibilities with some proprietary work. Module Federation was designed without hooks. Modifying or extending aspects requires author level understanding of the core. 

Dashboard will get OSS release next week. But will only work in read only mode.

**Comment by ScriptedAlchemy** [comment]
The harsh reality is that we need funding support to progress the platform. Licensing code seems like a good way to keep us going without throwing the little guy under the bus. We are working out free fully featured systems for personal use. When it comes to OSS projects - we will have to work out what code you need and how we can supply functionality safely to OSs products.

**Comment by blink1073** [comment]
Fully agree, my broader point was about more explicit transparency and making sure that everyone can easily play along and become a direct paid supporter or an advocate.

**Comment by ScriptedAlchemy** [comment]
CN you clarify

**Comment by blink1073** [comment]
I meant transparency about which parts are proprietary and making sure anyone can use the other ones easily.  It would also help to have screencasts of the proprietary ones in order to drive up interest.

**Comment by ScriptedAlchemy** [comment]
Working on it man. But I’m excruciatingly overwhelmed. Trying my best. Will release come content tomorrow and work on  transparency. Demand has outweighed supply. I spent 6 hours in back to back calls with companies about architecture reviews and system redesign for module Federation. 

This is also very complex code. 

I’ll address it soon and have fresh content to release soon as in wake up

Appreciate the sponsor’s and it really helps. Thanks for your feedback and patience

**Comment by blink1073** [comment]
I hear you my friend.  I'm not trying to add stress, only trying to help from an outside perspective.   Be well.

**Comment by ScriptedAlchemy** [comment]
Very much valued input!
