### ISSUE TITLE
lerna not found

### ISSUE THREAD

**Issue by EnricoBeltramo** [module-federation/module-federation-examples#542]
I have similar issue as #460:

$ lerna run --scope @different-react-versions/* --parallel start
"lerna" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 but the solution proposed (to run yarn at the root of repository and after inside the project doesn't work). I'm working on win10.
Some idea?

**Comment by EnricoBeltramo** [comment]
Installing lerna globally, the command works:
yarn global add lerna
Anyway, running yarn start the project doesn't start. Write that and stop immediately:
info cli using local version of lerna
lerna notice cli v3.22.1
lerna notice filter including "@different-react-versions/*"
lerna info filter [ '@different-react-versions/*' ]
lerna info Executing command in 2 packages: "yarn run start"
@different-react-versions/app1: $ webpack-cli serve
@different-react-versions/app2: $ webpack-cli serve
@different-react-versions/app1: [webpack-cli] The command moved into a separate package: @webpack-cli/serve
@different-react-versions/app1: ? Would you like to install @webpack-cli/serve? (That will run yarn add -D @webpack-cli/serve) (Y/n) ‣ true
@different-react-versions/app2: [webpack-cli] The command moved into a separate package: @webpack-cli/serve
@different-react-versions/app2: ? Would you like to install @webpack-cli/serve? (That will run yarn add -D @webpack-cli/serve) (Y/n) ‣ true
lerna success run Ran npm script 'start' in 2 packages in 0.6s:
lerna success - @different-react-versions/app1
lerna success - @different-react-versions/app2
Done in 1.10s.

**Comment by guifeliper** [comment]
Same here

**Comment by kirzharov** [comment]
I sent PR #553  which solves this issue.
