### ISSUE TITLE
How to load a React remote micro frontend into a Vue3 host (app shell)?

### ISSUE THREAD

**Issue by d-koppenhagen** [module-federation/module-federation-examples#547]
Hi!

I was playing around with webpack5 module federation and I have a hosting frontend based on Vue3.
Furthermore I have two micro frontends that should be loaded via module federation into my app shell (host).

* micro frontend 1 (Vue3)
* micro frontend 2 (Vue2)
* micro frontend 3 (React)

All micro frontend will work as standalone versions and when running everything together using module federation, the compilation works fine but the React based micro frontend seems not to work in the host.

<img width="1430" alt="Screenshot 2020-12-23 at 16 14 11" src="https://user-images.githubusercontent.com/4279702/103011392-21a7d900-453a-11eb-8ff7-b4ae14d6cf62.png">

I published the playground repo here:

https://github.com/d-koppenhagen/vue-micro-frontend-playground

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/tree/main/projects/reactVue-vue

**Comment by d-koppenhagen** [comment]
@ckken I see your approach but it's using `vuera` which provides an explicit way for using Vue in React and React in Vue. It's nothing that comes from Webpacks module federation plugin using web component doesn't it?

**Comment by jacob-ebey** [comment]
This is not a concern of module federation. You can't just render a react component in vue... You have to either mount it separately or within a vue component after you have a reference to a dom element.

I'm going to refer you to [vuera](https://github.com/akxcv/vuera) and close this issue.

**Comment by jacob-ebey** [comment]
And to clarify, module federation has nothing to do with web components, react, vue or any other component library or framework. Module federation is just the part that stitches together your separate builds and allows you to `import a from "remote/a"`.
