### ISSUE TITLE
Best practices for avoiding duplicate contexts in re-export scenarios

### ISSUE THREAD

**Issue by EricMCornelius** [module-federation/module-federation-examples#548]
Hi there,

First off, thanks for all your work on this, should be a very useful feature in the future.

Many of your examples seem to be using @material-ui, so I'm curious if you've hit upon the same issue I'm currently having:

FWIW: I'm trying to create an icon lazy-loader bundle from both @material-ui/icons and mdi-material-ui so that we can allow runtime resolution of any of the full set of icons by name in a minimal bundle.

What's I've discovered is that material-ui exports its ThemeProvider via two separate entrypoints:

@material-ui/core
@material-ui/core/styles

This seems to cause issues where various dependencies of an application (e.g. @material-ui/lab) import via one entry path and various others import via the other.  Basically, I believe I'm winding up with two separate instances of the ThemeProvider depending on which import path was used.

This occurred as soon as I tried to put @material-ui/core into a shared federated dependency.

So, my question is what's the best solution? Is this already solved and I just need a nudge in the right direction?

Presumably I can import *both* entrypoints and use both of the duplicate ThemeProvider instances - but that seems pretty kludgy.

Is it possible to create a "shared" definition that is used recursively when any matching prefix is used for an import path?

Is this situation already solved where we have multiple independent import paths resolving to what's supposed to be a singleton dependency internally?

**Comment by ScriptedAlchemy** [comment]
A trailing slash will on the key will crawl and share anything in the project like shared: @materialui/
