### ISSUE TITLE
Singleton instantiated multiple times, despite same version being provided to all modules

### ISSUE THREAD

**Issue by csvan** [module-federation/module-federation-examples#549]
Unfortunately, my repro for this is in a complex proprietary project, so I will do my best to explain what is going on.

The closest example project to my use-case is this one: https://github.com/module-federation/module-federation-examples/tree/master/dynamic-system-host

Essentially, I have an omnidirectional setup where a single Shell App consumes a set of Remote Apps. Remote Apps are discovered during runtime, and are hence not specified in the Webpack config. The shell loads the Remotes in exactly the same way as the example project above does (see https://github.com/module-federation/module-federation-examples/blob/master/dynamic-system-host/app1/src/App.js#L3)

The Shell, as well as all Remotes, have a dependency on a shared library, `my-shared-lib`:

```
"dependencies": {
    "my-shared-lib": "^1.0.0"
}
```

The Shell, in its Webpack config, exposes this lib as an eager singleton:

```
new ModuleFederationPlugin({
  name: 'shell',
  filename: 'shellDefinition.js',
  shared: {
      'my-shared-lib': { singleton: true, eager: true, requiredVersion: '^1.0.0' }
  },
})
```

The Remotes, in their configs, also have it as shared, but not eagerly:

```
new ModuleFederationPlugin({
  name: 'remoteNameHere',
  filename: 'remoteDefinition.js',
  exposes: {
    './app': path.join(modulePath, 'app.js'),
  },
  shared: {
      'my-shared-lib': { singleton: true, eager: false, requiredVersion: '^1.0.0' }
  },
})
```

The problem is this: I have verified both by runtime debugging and inspecting the bundles generated by Webpack that this lib is being included and instantiated several times - once for the shell, and once for each remote. The code for the lib is even present in the bundle for the Remote which Webpack loads when fetching the exposed `./app.js`.

I am at a loss for understanding what is going on here. I have tried to also share every single dependency of `my-shared-lib`, but this does not help.

My expectation would be that the Remotes use the instance of `my-shared-lib` which is shared by the Shell, rather than creating their own instances.

Have I completely misunderstood how dependency sharing works, or am I doing something else wrong?

It should be noted that both the Shell and the Remots all have single entry points.

**Comment by csvan** [comment]
Another note: I have observed this behavior for third-party libraries as well, notably https://github.com/styled-components/styled-components, the entire code for that library is also a part of the Remote bundle even though it is specified as a shared singleton in both Shell and Remote.

**Comment by csvan** [comment]
And another - studying the generated chunks, I notice that ALL my shared dependencies in the Remote are loaded up-front. They are all given the same ID as well, e.g. this occurs both in the Shell and Remote:

```
/***/ 4200:
/***/ ((__unused_webpack_module, exports, __webpack_require__) => {

"use strict";

var _interopRequireDefault = __webpack_require__(95318);

// ....
```

I don't understand why this is happening - it seems the Remote is loading what it declared itself rather than using what is available in the Shell. It also (seemingly) leads to a large overhead in transmitted data since all the shared deps are (seemingly) loaded up-front in the Remote even if they are already provided by the Shell.

**Comment by csvan** [comment]
Ah, I _think_ I understand what is happening. Sharing only works at the _root_ level of a package. So for example, the following will be properly shared:

```
import { myThing } from 'my-shared-library'
```

But this will not:

```
import myThing from 'my-shared-library/myThing'
```

Is there any way to get around this behavior? I.e. is there a way for Webpack to understand that sub-imports from a package should also be shared?

**Comment by csvan** [comment]
However, this still doesn't help me understand why _all_ my shared dependencies in the Remote _seem_ to be loaded up-front, including the ones which only have root-level imports. This imposes quite an overhead in terms of bundle size - each Remote is almost as big in KB as the shell itself in terms of dependencies.

I again have probably misunderstood how it works, but I thought that the Remote would only fetch a dependency if it could not find it in the host - not fetch it and then check if it's available in the host.

**Comment by jacob-ebey** [comment]
Eager = load everything upfront. Avoid it unless there is a real reason you need to use it. I'm betting if you remove eager, you'll be in business.

**Comment by jacob-ebey** [comment]
@csvan Can I close this or is there more to it than just having everything marked eager?

**Comment by csvan** [comment]
@jacob-ebey sorry for the late reply here.

I could not remove eager from the host - it keeps crashing with `Uncaught Error: Shared module is not available for eager consumption`. I don't have eager in the remotes at all.

**Comment by jacob-ebey** [comment]
@csvan add a bootstrap and remove eager.

**Comment by csvan** [comment]
@jacob-ebey thanks, I'll accept that as the solution (could not get it to work, but I suppose that is a project-specific problem).

**Comment by jacob-ebey** [comment]
@csvan If you can provide a repo case I'm happy to look into it. Without a repo case there is nothing I can do for you.

**Comment by csvan** [comment]
@jacob-ebey I fully understand that, and as I mentioned this is unfortunately a pretty complex proprietary project, so not much I can share that fully reproduces the issue. I appreciate your help and will leave another comment here if I get bootstrapping to work.

**Comment by csvan** [comment]
Same issue with helpful workarounds: https://github.com/module-federation/module-federation-examples/issues/666

**Comment by PessimusDea** [comment]
> @jacob-ebey I fully understand that, and as I mentioned this is unfortunately a pretty complex proprietary project, so not much I can share that fully reproduces the issue. I appreciate your help and will leave another comment here if I get bootstrapping to work.

Hey, sorry for ur attention. But i have the similar problem at my big project with using webpack module federation. I have the shared libraries, i added necessary libraries with similar version at my configs, but it loads my HOST, and then every MFE loads it again........... I thought if HOST already have these libraries - MFE will not load them again, but loads only that HOST no have 

So mb u founded the solution for this problem? Cuz i tried to fix it 1 mouth and have 0 progress
