### ISSUE TITLE
SSR : loading chunks async by main.js : not html ?

### ISSUE THREAD

**Issue by julienfroidefond** [module-federation/module-federation-examples#55]
![image](https://user-images.githubusercontent.com/2108171/82661323-1602d580-9c2c-11ea-80ff-f26900946805.png)

I see that flow on SSR exemple. I'm wondering if this remote's chunks could be on the host html (for async html side and not by js).
If this is the case; for performance this could be cool, no ? 
Even if I feel that this is not the way webpack handle things; I wanted your opinion

**Comment by julienfroidefond** [comment]
I want to complete my issue.
I already have a solution without federated modules for MFE. In that solution, the real bottleneck, is that we have to fix vendors and there versions. 
The solution is based on multiple SSR which all send their manifest; and for shared libraries, a vendor "fragment" to distribute a main ressource (with externals and a file that expose in global vars the libraries); so we need to set, for all applications/fragments, the versions of the vendors. 
The beauty of federated modules is that we handle this huge problem in an elegant way BUT, it costs an xhr resolution (I think).

A scheme of what I'm understanding :

![image](https://user-images.githubusercontent.com/2108171/82781699-c9511180-9e5a-11ea-8118-22d51399d800.png)

We see here that there is a blocking event in mod fed, the xhrs to resolve components and vendors dynamically.

Am I right on this ? Because I really care about performance and TTI, FID (first input delay) ... 
If so, I'm wondering if there is a way to get the bunch of resources dynamically, in the host SSR when sending the response ?

**Comment by julienfroidefond** [comment]
Maybe the question is simplier : how to prefetch/preload bundles ^^

**Comment by julienfroidefond** [comment]
I've just think about a possible way : read the stats json from website2 on website1, dynamically, and insert prefetches of all js. But, this is not the good way; it will just prefetch all the other site files static. I don't see how to be more precise.
In server.js of website 1 
```
import statsFileWebSite2 from "../../website2/buildClient/static/stats.json";

const assetsRemote = statsFileWebSite2.assets.filter(asset => asset.name.endsWith(".js"));
assetsRemote.forEach((val, i, arr)=>{
  arr[i] = `<link rel="preload" as="script" href="http://localhost:3002/static/${val.name}">`
});
```
Then in head
```
 ${assetsRemote.join('')}
```
Gives : 

![image](https://user-images.githubusercontent.com/2108171/82950029-ebef4180-9fa4-11ea-965e-75eaa4c27c68.png)

No more xhrs but prefetching in head

**Comment by julienfroidefond** [comment]
Is it a bad question ? Anyone else ? @ScriptedAlchemy, ô, god of fedmod ❤️; your opinion could be so interesting for me, pleeeeeaase ? 😃

**Comment by ScriptedAlchemy** [comment]
Valid problem but easy to solve. The challenge is my bandwidth is maxed out right now

**Comment by ScriptedAlchemy** [comment]
I’ll read I’ve the issue again and try to help but the demand heavily outweighs supply

**Comment by julienfroidefond** [comment]
Nice ! Thank you very much, really good news if it's easy to solve. Hope you will find time later :wink: . By the way I'm so excited about module federation, this is amazing work with amazing promises. Have a nice day @ScriptedAlchemy !

**Comment by ScriptedAlchemy** [comment]
about to drop a screencast that literally left me in awe. Ill post here once done. Last night my own mind was blown

**Comment by ScriptedAlchemy** [comment]
so the async RTT issue, related to flushing chunks out of a build - will be fixed but likely in beta 18 unless i deal with some custom thing. beta 18 should report metadata showing you the chunks that its got - allowing for preloading and so on

**Comment by ScriptedAlchemy** [comment]
you can preload code (not html) with window.remote.get('./module')

that'll put scripts on the page but never invoke them (preload)

**Comment by mikebrits** [comment]
> about to drop a screencast that literally left me in awe. Ill post here once done. Last night my own mind was blown

Bated breath!

**Comment by ScriptedAlchemy** [comment]
https://youtu.be/kOuoSBTCzl4
