### ISSUE TITLE
Vue child components are not rendered

### ISSUE THREAD

**Issue by michalpaukert** [module-federation/module-federation-examples#550]
I forked from [vue3-demo][1] which is working as expected. (simple example without child components)

But when I create more complex component which contains another child component it is not rendered.
In my case it is TextField which contains TextInput.

I created minimal version where I want to show you my issue with module federation webpack plugin.
I received answer someone from vue community, that there is a warning
`VNode type: Symbol(Fragment) (symbol)`  
and 
`resolveComponent can only be used in render() or setup()`

Which is caused by having two colliding copies of Vue
So I tried to use this configuration:

`new 
ModuleFederationPlugin(
{

      name: "home",
      filename: "remoteEntry.js",     
      remotes: {},      
      library: { type: "var", name: "home" }, exposes: {      
        "./TextField": "./src/components/TextField",        
        "./TextInput": "./src/components/TextInput",        
      },      
      shared: ["vue"],      
    }),
`
But results are same.

So I commited my example [in here][2]

Could you please help me anyone, why it is not working?
Is it a bug?
I tried same with React and but it works as expected.

![Alt Text](https://dev-to-uploads.s3.amazonaws.com/i/mdm8smkyihq2ueq6h75y.PNG)

  [1]: https://github.com/module-federation/module-federation-examples/tree/master/vue3-demo
  [2]: https://github.com/michalpaukert/module-federation

**Comment by theoribeiro** [comment]
Having the same problem here @michalpaukert. Have you solved this? 

I can't help but think we're missing some needed configuration here. 

@ScriptedAlchemy can you shed any lights here?

**Comment by AndTheGodsMadeLove** [comment]
I am currently looking for an architecture for our project, is this issue still relevant?

**Comment by michalpaukert** [comment]
It looks like it is not, in newer version.

**Comment by ScriptedAlchemy** [comment]
I dont know vue, if you can please send a PR or git blame the original contributor and mention them on this issue

**Comment by ScriptedAlchemy** [comment]
I dont know vue at all - but try adding the required version to the share config. it looks a little dated

https://medium.com/dev-genius/module-federation-advanced-api-inwebpack-5-0-0-beta-17-71cd4d42e534

**Comment by p18813748529** [comment]
我也遇到这个问题，请问是怎么解决的，我的vue版本是3.0.11

**Comment by p18813748529** [comment]
I also encountered this problem, may I ask how to solve it? My VUE version is 3.0.11

**Comment by ScriptedAlchemy** [comment]
Help wanted on fixing this - I'm not a vue user
