### ISSUE TITLE
TypeError: Class constructor ServeCommand cannot be invoked without 'new'

### ISSUE THREAD

**Issue by EnricoBeltramo** [module-federation/module-federation-examples#551]
When I run any example (i.e. https://github.com/module-federation/module-federation-examples/tree/master/advanced-api/dynamic-remotes)
I have follow error:

D:\Progetti\Inventio\InMindSO\module-federation-examples\advanced-api\dynamic-remotes>yarn start
yarn run v1.22.5
$ lerna run --scope @dynamic-remotes/* --parallel start
lerna notice cli v3.22.1
lerna notice filter including "@dynamic-remotes/*"
lerna info filter [ '@dynamic-remotes/*' ]
lerna info Executing command in 3 packages: "yarn run start"
@dynamic-remotes/app1: $ webpack-cli serve
@dynamic-remotes/app2: $ webpack-cli serve
@dynamic-remotes/app3: $ webpack-cli serve
@dynamic-remotes/app1: [webpack-cli] Promise rejection: TypeError: Class constructor ServeCommand cannot be invoked without 'new'
@dynamic-remotes/app3: [webpack-cli] Promise rejection: TypeError: Class constructor ServeCommand cannot be invoked without 'new'
@dynamic-remotes/app2: [webpack-cli] Promise rejection: TypeError: Class constructor ServeCommand cannot be invoked without 'new'
@dynamic-remotes/app2: [webpack-cli] TypeError: Class constructor ServeCommand cannot be invoked without 'new'
@dynamic-remotes/app2:     at run (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\lib\utils\resolve-command.js:33:12)
@dynamic-remotes/app2:     at Command.<anonymous> (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\lib\utils\arg-parser.js:32:58)
@dynamic-remotes/app2:     at Command.listener [as _actionHandler] (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\node_modules\commander\index.js:426:31)
@dynamic-remotes/app2:     at Command._parseCommand (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\node_modules\commander\index.js:1002:14)
@dynamic-remotes/app2:     at Command._dispatchSubcommand (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\node_modules\commander\index.js:953:18)
@dynamic-remotes/app2:     at Command._parseCommand (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\node_modules\commander\index.js:970:12)
@dynamic-remotes/app2:     at Command.parse (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\node_modules\commander\index.js:801:10)
@dynamic-remotes/app2:     at argParser (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\lib\utils\arg-parser.js:145:27)
@dynamic-remotes/app2:     at parseArgs (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\lib\bootstrap.js:18:29)
@dynamic-remotes/app2:     at runCLI (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\lib\bootstrap.js:24:24)
@dynamic-remotes/app1: [webpack-cli] TypeError: Class constructor ServeCommand cannot be invoked without 'new'
@dynamic-remotes/app1:     at run (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\lib\utils\resolve-command.js:33:12)
@dynamic-remotes/app1:     at Command.<anonymous> (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\lib\utils\arg-parser.js:32:58)
@dynamic-remotes/app1:     at Command.listener [as _actionHandler] (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\node_modules\commander\index.js:426:31)
@dynamic-remotes/app1:     at Command._parseCommand (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\node_modules\commander\index.js:1002:14)
@dynamic-remotes/app1:     at Command._dispatchSubcommand (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\node_modules\commander\index.js:953:18)
@dynamic-remotes/app1:     at Command._parseCommand (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\node_modules\commander\index.js:970:12)
@dynamic-remotes/app1:     at Command.parse (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\node_modules\commander\index.js:801:10)
@dynamic-remotes/app1:     at argParser (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\lib\utils\arg-parser.js:145:27)
@dynamic-remotes/app1:     at parseArgs (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\lib\bootstrap.js:18:29)
@dynamic-remotes/app1:     at runCLI (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\lib\bootstrap.js:24:24)
@dynamic-remotes/app3: [webpack-cli] TypeError: Class constructor ServeCommand cannot be invoked without 'new'
@dynamic-remotes/app3:     at run (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\lib\utils\resolve-command.js:33:12)
@dynamic-remotes/app3:     at Command.<anonymous> (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\lib\utils\arg-parser.js:32:58)
@dynamic-remotes/app3:     at Command.listener [as _actionHandler] (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\node_modules\commander\index.js:426:31)
@dynamic-remotes/app3:     at Command._parseCommand (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\node_modules\commander\index.js:1002:14)
@dynamic-remotes/app3:     at Command._dispatchSubcommand (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\node_modules\commander\index.js:953:18)
@dynamic-remotes/app3:     at Command._parseCommand (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\node_modules\commander\index.js:970:12)
@dynamic-remotes/app3:     at Command.parse (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\node_modules\commander\index.js:801:10)
@dynamic-remotes/app3:     at argParser (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\lib\utils\arg-parser.js:145:27)
@dynamic-remotes/app3:     at parseArgs (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\lib\bootstrap.js:18:29)
@dynamic-remotes/app3:     at runCLI (D:\Progetti\Inventio\InMindSO\module-federation-examples\node_modules\webpack-cli\lib\bootstrap.js:24:24)
lerna success run Ran npm script 'start' in 3 packages in 1.6s:
lerna success - @dynamic-remotes/app1
lerna success - @dynamic-remotes/app2
lerna success - @dynamic-remotes/app3

**Comment by EnricoBeltramo** [comment]
Fixed updating webpack-cli to version 4.3.0
"webpack-cli": "4.3.0",

**Comment by kirzharov** [comment]
Thanks @EnricoBeltramo for creating this issue! I also faced this problem. I sent PR #552 which solves this issue.

**Comment by jacob-ebey** [comment]
@EnricoBeltramo @kirzharov I have merged the PR. Please close the issue if it's resolved.
