### ISSUE TITLE
Accessing multiple service workers from host/shell app

### ISSUE THREAD

**Issue by inamsrinu** [module-federation/module-federation-examples#554]
This is more of a question than an issue for this particular scenario of PWA apps with service workers.

We have successfully implemented module federation for our shell and remote angular apps running on two different servers. We converted both apps to PWA’s. When running the remote as a standalone app, service worker’s offline functionalities such as sync methods gets executed as expected but when accessing the remote app from shell app, the same sync method is not executed.
One solution I tried to expose the remote’s service worker as well with minimize=false so that I can get raw service worker file(remote’s). But the chunk file also has the pre appended stuff from webpack and moreover it will be hard to inject the content of imported remote’s service worker to the shell’s service worker. I am looking for a solution for this scenario of dealing with multiple service workers when accessed from shell app.

**Comment by ScriptedAlchemy** [comment]
Haven’t tried in workers. Likely you need to know the module I’d and low level call it
