### ISSUE TITLE
Can you load multiple remotes on the same page? -- Angular

### ISSUE THREAD

**Issue by xTavi** [module-federation/module-federation-examples#556]
I am using Angular 11 and I have multiple remotes and I can access them, but I would like to load 2 or more remotes on the same page. Is there a way to do that?

**Comment by ydmitry** [comment]
Yes, why not? You may use non-router based lazy loading - by component (new feature in ivy engine) or by module (need to import angular/compiler for this)

**Comment by xTavi** [comment]
Thank you! Do you have any examples? ( links )

**Comment by ydmitry** [comment]
@xTavi here is example with component lazy loading with module federation https://github.com/ydmitry/angular11-webpack-module-federation-custom-webpack-builder/blob/main/src/app/app.component.ts#L21 

For `@angular/compiler` usage you can follow this guide https://medium.com/@ckyidr9/lazy-load-feature-modules-without-routing-in-angular-9-ivy-220851cc7751

**Comment by xTavi** [comment]
Thank you very much for your help! You can label this Issue with a question tag, maybe this will help other people too.
