### ISSUE TITLE
WASM Example

### ISSUE THREAD

**Issue by cawfeecoder** [module-federation/module-federation-examples#558]
I was wondering if you all had plans to add WASM to the Module Federation examples (or atleast some direction around working with WASM, particular in light of frameworks such as Yew).

**Comment by alexUXUI** [comment]
Hey, @nfrush, thanks for opening this issue. I have created a Wasm example here: https://github.com/alexUXUI/wasm-federation-demo. 

If you have node installed, you should be able to clone the repo and run `yarn && yarn start` to get it running locally. Let me know if you have any questions about the code or config! 

@ScriptedAlchemy Would it be ok if I had permission to open up a PR against this repo with the Wasm example? Would be awesome to contribute!

**Comment by ScriptedAlchemy** [comment]
@alexUXUI please consider a pull request to our repo :) We are actively working on polyglot architecture via aegis and MF
