### ISSUE TITLE
yarn install error 

### ISSUE THREAD

**Issue by yt253284494** [module-federation/module-federation-examples#56]
when I press 'yarn install' in the root directory，I get such error

![image](https://user-images.githubusercontent.com/21187581/82879270-4b325f00-9f6f-11ea-9eac-e547ed695c3f.png)
![image](https://user-images.githubusercontent.com/21187581/82880064-76697e00-9f70-11ea-8a3a-4a3162fac806.png)

it likes util.promisify not found

node version
![image](https://user-images.githubusercontent.com/21187581/82880200-a9ac0d00-9f70-11ea-9531-810c877ebc87.png)

 yarn version
![image](https://user-images.githubusercontent.com/21187581/82880254-bb8db000-9f70-11ea-8abf-af4a0a9da562.png)

**Comment by julienfroidefond** [comment]
Hi, I think same than #50

**Comment by yt253284494** [comment]
it works for me. thank you!

**Comment by julienfroidefond** [comment]
FYI, https://github.com/module-federation/module-federation-examples/pull/53
