### ISSUE TITLE
Why didn't SHARED generate a separate chunk?

### ISSUE THREAD

**Issue by zenotsai066** [module-federation/module-federation-examples#57]
version
```json
"webpack": "5.0.0-beta.16",
"webpack-cli": "3.3.11",
```

config
```js
new ModuleFederationPlugin({
      name: "app1",
      library: { type: "var", name: "app1" },
      remotes: {
        app2: "app2",
      },
      shared: ["react", "react-dom"],
    }),
```

run

```webpack --mode production```

result
![image](https://user-images.githubusercontent.com/66027308/83046941-4dcdab00-a07a-11ea-9ca5-8d12154cf099.png)

The modules of the share configuration are packaged into main.js(react、react-dom)

Shouldn't the shared configuration module generate chunks?

The expected build result is this

![image](https://user-images.githubusercontent.com/66027308/83047662-41961d80-a07b-11ea-8d00-ca2ab0b9bf99.png)

**Comment by zhangwilling** [comment]
so limited info, please supply repreducible demo.

It should output hashed or digital (depend on your config) named vendors.

or try to  refresh explorer of your vscode ?
