### ISSUE TITLE
What is the rationale of disabling tree-shaking for shared dependencies?

### ISSUE THREAD

**Issue by XiaofengXie16** [module-federation/module-federation-examples#582]
Hello,
I noticed that tree-shaking seems to be disabled for shared libraries. I am wondering what is the rationale behind it and what would be the best practices if I want to enable tree-shaking for the shared libraries (it would be great if there is an example)?

**Comment by jacob-ebey** [comment]
If you treeshake something that's "shared" and someone tries to use functionality that should be there but was tree-shaken stuff is going to break. "Sharing" something means you're sharing *all* of it for that reason.
