### ISSUE TITLE
questions about the config of ModuleFederationPlugin

### ISSUE THREAD

**Issue by yt253284494** [module-federation/module-federation-examples#64]
![image](https://user-images.githubusercontent.com/21187581/83106685-7a6fda00-a0ef-11ea-8641-69083b27cbf3.png)
 I find the .d.ts about library.type
![image](https://user-images.githubusercontent.com/21187581/83106756-96737b80-a0ef-11ea-9168-2f7e47578b7e.png)
is there other way to config library? I just tried umd, commonjs and commonjs2, it not worked and I konw there is no module and require provided

**Comment by ScriptedAlchemy** [comment]
too little info cant help. Works in all use cases and tests done at webpack 🤷
