### ISSUE TITLE
Exposed modules stops working with default webpack 5 optimizations runtimeChunk: 'single'

### ISSUE THREAD

**Issue by Guriqbal-Singh-Alida** [module-federation/module-federation-examples#646]
By adding following to optimizations in webpack config, the exposed module stops working in dependent apps.

```
splitChunks: {
        chunks: 'all',
},
runtimeChunk: 'single'
```

Output error in module consumer app:
![image](https://user-images.githubusercontent.com/71792252/105417110-f45d5200-5bef-11eb-9ca0-bd28a06c2a49.png)

**Comment by Guriqbal-Singh-Alida** [comment]
@ScriptedAlchemy @jacob-ebey @maraisr your help is appreciated, this blocks us from using default optimizations

**Comment by jacob-ebey** [comment]
@Guriqbal-Singh-Alida Got a repo case?

**Comment by Guriqbal-Singh-Alida** [comment]
yup basically with any basic setup if you turn above on, will blow up

**Comment by Guriqbal-Singh-Alida** [comment]
will create a repo soon, cannot reproduce with module-federation-examples repo let me check whats the difference on our side

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey the issue is due to runtimeChunk:'single', updated the comment and error message above and is reproducible at https://github.com/Guriqbal-Singh-Alida/basic-remote-runtime-single

**Comment by jacob-ebey** [comment]
@maraisr Do you have time to look into runtime chunks? I don't know much on this topic to be honest.

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey  thanks for quick reply.
@maraisr any ideas how we can solve or get around it.

I have also mentioned this in another issue shown above, but not sure if it is directly related or not

**Comment by Guriqbal-Singh-Alida** [comment]
@maraisr @ScriptedAlchemy can any of you please provide some direction?

**Comment by jacob-ebey** [comment]
@Guriqbal-Singh-Alida @maraisr said he would look into it. We are scattered throughout the world though and have day jobs, please be patient. 😄

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey Thanks for reaching out to @maraisr. Sorry for being impatient,  was hitting on issue one after another and you know the feeling when sprint is closing and one is trying to chase deadline 😆
Plus your quick replies are addictive lol

**Comment by jacob-ebey** [comment]
@Guriqbal-Singh-Alida, does your company know about sponsors? If it's something that want quick responses on, I'd honestly point then at sponsoring the webpack organization or Tobias at a level where he would dedicate time for your problems. Let them know if they want people working for them, they should pay them. Otherwise I'd let them know tasks will carry as no one else here cares about their goals or priorities.

**Comment by jacob-ebey** [comment]
I looked into this a bit but still not 100% sure the issue still. There seems to be an extra callback in the bootstrap that's generated/not passed. Removing it manually from the build file seems to allow it to execute without issue. @ScriptedAlchemy  recommended looking at the next-mf repo as this is apparently an issue there as well he worked around.

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey thanks for the suggestions and help. Just pushed **new changes** to https://github.com/Guriqbal-Singh-Alida/basic-remote-runtime-single based on @ScriptedAlchemy https://github.com/module-federation/nextjs-mf which makes it **work**

**Comment by jacob-ebey** [comment]
@Guriqbal-Singh-Alida Please keep that repo up as is if possible until the plugin can be documented somewhere else. Good job on finding a fix 🎉

For others, this is a plugin that merges the runtimes to get around runtimeChunk: single https://github.com/Guriqbal-Singh-Alida/basic-remote-runtime-single/blob/master/apps/app2/plugins/moduleFedSingleRuntime.js

**Comment by Guriqbal-Singh-Alida** [comment]
But to add; feels that https://github.com/webpack/webpack/pull/11843 should be merged  in order to resolve the issue in package itself. It is hanging there from quite a while

**Comment by jacob-ebey** [comment]
```js
//Reference: https://github.com/module-federation/nextjs-mf

const ConcatSource = require('webpack-sources/lib/ConcatSource');

module.exports = class ModuleFedSingleRuntimePlugin {
  constructor(options) {
    this._options = {fileName: 'remoteEntry.js', ...options};
  }
  // Define `apply` as its prototype method which is supplied with compiler as its argument
  apply(compiler) {
    if (!this._options) return null;
    const options = this._options;

    // Specify the event hook to attach to
    compiler.hooks.emit.tap("EnableSingleRunTimeForFederationPlugin", (compilation) => {
      const { assets } = compilation;
      const runtime  = assets['runtime.js'];
      const remoteEntry = assets[this._options.fileName];
      const mergedSource = new ConcatSource(runtime, remoteEntry);
      assets[this._options.fileName] = mergedSource;
    });
  }
};
```

**Comment by Guriqbal-Singh-Alida** [comment]
In addition to above, please make sure to use remoteEntryMerged.js instead of remoteEntry.js as remote file name in consumer app

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey i pushed new changes to optimize so that we don't create an extra file. Also previous solution had a limitation where it did not worked when ran in dev mode, it required the files to be in build folder.
Overall please check the new solution. Also probably will create it as plugin unless WMF folks advice otherwise.
if possible please update your above comments based on new solution.

**Comment by jacob-ebey** [comment]
That is very elegant @Guriqbal-Singh-Alida. Good job.

**Comment by jacob-ebey** [comment]
@Guriqbal-Singh-Alida, I think @ScriptedAlchemy will pull this into the MF org for others to use.

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey thanks for kind words. I will also try to create a PR against the repo and see if @ScriptedAlchemy can approve then

**Comment by 17biubiu** [comment]
@Guriqbal-Singh-Alida it seems not work, in the production mode, 
![image](https://user-images.githubusercontent.com/13295895/105794689-7a014900-5fc6-11eb-816e-973b60fda362.png)

**Comment by Guriqbal-Singh-Alida** [comment]
@17biubiu did you copied above or one from repo direct because I made some more changes related to chunks hash handling
here: https://github.com/Guriqbal-Singh-Alida/basic-remote-runtime-single/blob/master/apps/app2/plugins/moduleFedSingleRuntime.js

**Comment by 17biubiu** [comment]
@Guriqbal-Singh-Alida yeah I copied it. on the beginning, i use runtimechunk: true, it show errors fn is not function. then i change the config runtimechunk: 'single'。 same error。

**Comment by 17biubiu** [comment]
app1: 
![image](https://user-images.githubusercontent.com/13295895/105798623-8a68f200-5fcd-11eb-9b54-806147fb0e60.png)
![image](https://user-images.githubusercontent.com/13295895/105798651-9ce32b80-5fcd-11eb-893d-cc450227289e.png)


app2:
![image](https://user-images.githubusercontent.com/13295895/105800882-cbafd080-5fd2-11eb-8e7b-5c206bd5e404.png)
![image](https://user-images.githubusercontent.com/13295895/105798739-cef48d80-5fcd-11eb-880e-b4838d34bf41.png)

**Comment by Guriqbal-Singh-Alida** [comment]
@17biubiu i was able to run https://github.com/Guriqbal-Singh-Alida/basic-remote-runtime-single in prod as well as dev mode.
I would suggest reducing your webpack configs to match and then slowly start adding functionality from there.
Also i don't see new plugin called anywhere in your configs like:
```
plugins: [
    new ModuleFedSingleRuntimePlugin(),
    new ModuleFederationPlugin({....

```

**Comment by 17biubiu** [comment]
@Guriqbal-Singh-Alida the config above
the types.js and external.js like this
![image](https://user-images.githubusercontent.com/13295895/105801516-3c0b2180-5fd4-11eb-899b-1674f4566110.png)

**Comment by Guriqbal-Singh-Alida** [comment]
@17biubiu I noticed that your path for non prod is /static/app1/remoteEntry.js,
try passing 
```
new ModuleFedSingleRuntimePlugin({fileName: `${prod ? '/static/app1/' : ''}remoteEntry.js\`});
```
else i would say put a break point inside plugin and see if it is able to find the file

**Comment by 17biubiu** [comment]
@Guriqbal-Singh-Alida yeah. it can find. you can ignore it. you can run npm run build, then you can try with local server

**Comment by 17biubiu** [comment]
Error: No remote entry /static/app1/remoteEntry.js found, please make sure module federation configured properly else you dont need this plugin
    at compiler.hooks.emit.tap

**Comment by 17biubiu** [comment]
@Guriqbal-Singh-Alida it also throw err:
 if (err) throw err;
             ^

Error: No remote entry /static/app1/remoteEntry.js found, please make sure module federation configured properly else you dont need this plugin

**Comment by 17biubiu** [comment]
@Guriqbal-Singh-Alida @jacob-ebey  it is my Initial project， it can reproduce [https://github.com/17biubiu/w5-v2](https://github.com/17biubiu/w5-v2)

**Comment by Guriqbal-Singh-Alida** [comment]
@17biubiu the above error says you havenot specified **filename** or **exposes** property of ModuleFederationPlugin

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey so this solution works for normal but as soon as we add externals in same way as done in https://github.com/jacob-ebey/fed-internal-remote-browser/blob/main/webpack.config.js, It breaks. 
I tried figuring out but no luck see if you can help
Further i improved plugin as follows which allows to add extraAssests as well as follows (not pushed to repo yet)
```
/* eslint-disable consistent-return */
/* eslint-disable no-underscore-dangle */
// Reference: https://github.com/module-federation/nextjs-mf

// eslint-disable-next-line import/no-extraneous-dependencies
const ConcatSource = require('webpack-sources/lib/ConcatSource');

module.exports = class ModuleFedSingleRuntimePlugin {
  constructor(options) {
    const defaultOptions = { fileName: 'remoteEntry.js', extraAssets: [] };
    this._options = { ...defaultOptions, ...options };
  }

  // Define `apply` as its prototype method which is supplied with compiler as its argument
  apply(compiler) {
    // Specify the event hook to attach to
    compiler.hooks.emit.tap('ModuleFedSingleRuntimePlugin', (compilation) => {
      const { assets, namedChunks } = compilation;
      const runtimeChunk = namedChunks.get('runtime');
      if (!runtimeChunk) {
        throw new Error('No runtime single configured, so use of the plugin not required');
      }
      const runtime = assets[runtimeChunk.files[0]];

      const remoteName = this._options.fileName;
      if (!remoteName) {
        throw new Error('No remote file configured, please pass fileName:{myRemote.js} in options');
      }
      const remoteEntry = assets[remoteName];
      if (!remoteEntry) {
        throw new Error(
          `No remote entry ${remoteName} found, please make sure module federation configured properly else you dont need this plugin`
        );
      }

      const extraAssets = this._options.extraAssets.map((assetName) => {
        const assetChunk = namedChunks.get(assetName);
        if (!assetChunk) {
          throw new Error(
            `No ${assetName} found, please make sure is available else remove it from options.extraAssets`
          );
        }

        return assets[assetChunk.files[0]];
      });
      const mergedSource = new ConcatSource(runtime, '\n',...extraAssets, '\n', remoteEntry );
      assets[this._options.fileName] = mergedSource;
    });
  }
};

```
this can be called e.g:
`new ModuleFedSingleRuntimePlugin({extraAssets:['internal-load']});`

**Comment by Guriqbal-Singh-Alida** [comment]
@17biubiu based on your repo, looks like you are not exposing any components so technically you dont need this plugin or otherwise need to set exposes

![image](https://user-images.githubusercontent.com/71792252/106078344-1a8b6200-60c8-11eb-9547-6426b213b36f.png)

VS
correct config

![image](https://user-images.githubusercontent.com/71792252/106078518-6938fc00-60c8-11eb-8feb-f9d1510d28ee.png)

To clarify, this plugin is  to be used in library package instead in consumer package.
Hope this helps

**Comment by 17biubiu** [comment]
@Guriqbal-Singh-Alida in the app1. build/webpack.base.conf.js
![image](https://user-images.githubusercontent.com/13295895/106116549-fcd40080-618c-11eb-96e8-4f698c3ef564.png)

**Comment by 17biubiu** [comment]
> @17biubiu the above error says you havenot specified **filename** or **exposes** property of ModuleFederationPlugin

i has been set the filename, 
you can try it, when you build it ,it throw the error.Error: No remote entry /static/app1/remoteEntry.js found, please make sure module federation configured properly else you
