### ISSUE TITLE
Issue when sharing a treeshaked library

### ISSUE THREAD

**Issue by alex-vukov** [module-federation/module-federation-examples#666]
I have the following setup:
**Application A loads a button from react-bootstrap like this:**
```import Button from "react-bootstrap/Button"```
In shared I have:
```"shared": {"react-bootstrap" : {}}```
I can see in the bundle that only the code for Button is bundled and shared and not the entire library which is ok.

**I have application B which loads a modal from react-bootstrap like this:**
```import { Modal } from "react-bootsrap"```
In shared I have:
```"shared": {"react-bootstrap" : {}}```
I can see that the entire "react-bootstrap" library is bundled because of the unoptimized import which is ok.

I run application A and dynamically import application B and render it inside it.
**Expectation:** Application A doesn't provide the Modal so application B will load its own chunk which contains it and take it from there.
**Reality:** Application B cannot find Modal and is not rendered correctly.

If i change the import in application A to ```import { Button } from "react-bootstrap"``` then the sharing happens correctly.
Does that mean that only entire libraries can be shared and not pieces of them?

**Comment by jacob-ebey** [comment]
I believe you will have to share each imported module from the library if you wish to go this route. If we share a library I always make sure that we are importing from the root to make things easy.

Try adding `"shared": {"react-bootstrap/Button": {}}` and let me know if that solves the issue.

**Comment by alex-vukov** [comment]
Thank you @jacob-ebey  for the suggestion! Sharing single components works, however it brings the inconvenience that you have to track each component you have used in the code in order to add it to "shared". Another option that I found useful is to use ```"shared": {"react-bootstrap/": {}}```. Adding the trailing slash at the end shares all the single components in the folder at once but if you use only 3-4 of them the other (probably around 80) unused chunks take extra space on the server. So I guess I am looking for something in the middle between the two options i.e. "share only those components from a library which are used by my application without having to specify them one by one". Maybe this is more of a feature request but I believe it would be helpful

**Comment by jacob-ebey** [comment]
The whole concept of "sharing" and tree-shaking do not play will together. Imagine you "share" a subset of a library, and a host application ends up loading in the shared library before their own copy. Now the host is missing large chunks of the shared library it requires to run because the remote decided to optimize them away.

This is why I only recommend sharing libraries that can not be tree-shaken to begin with.

**Comment by jacob-ebey** [comment]
I just noticed the "takes up extra space on the server" comment. Why does this matter? Your SSR node bundle does not impact clients...

**Comment by alex-vukov** [comment]
I agree on your point about sharing tree-shaken libraries. In the case of react-bootstrap maybe tree-shaking is not the correct term because I believe all the components in it are independent from each other. This is what confused me in the beginning and I was just guessing how it would work since I couldn't find a mention about it anywhere.

**Comment by alex-vukov** [comment]
As per the "extra space on the server" - even if it's not a big issue with server space having ```"shared": {"react-bootstrap/": {}}``` will most likely make the remoteEntry file bigger because of each unneeded chunk that it will keep a reference to...

**Comment by mjhenkes** [comment]
>Another option that I found useful is to use "shared": {"react-bootstrap/": {}}. Adding the trailing slash at the end shares all the single components in the folder at once but if you use only 3-4 of them the other (probably around 80) unused chunks take extra space on the server.

This should be documented somewhere. This wisdom was pretty hard to find.

**Comment by ScriptedAlchemy** [comment]
trailing slash on the end of shared will make it walk the directory and split it into either a larger chunk or a bunch of smaller chunks depending on module concatenation. 

All this is explained in the book or authors can be reached for paid support. 

Feel free to document it though!

**Comment by mjhenkes** [comment]
Thanks @ScriptedAlchemy !
What book are you referring to?

edit: Derp, never mind i found it :)
