### ISSUE TITLE
dashboard example not work

### ISSUE THREAD

**Issue by lili21** [module-federation/module-federation-examples#690]
<img width="1265" alt="Screen Shot 2021-02-01 at 8 10 50 PM" src="https://user-images.githubusercontent.com/4456380/106457365-d8985c80-64c9-11eb-9a09-6b952813f12e.png">

I have already fixed some issue with this https://github.com/module-federation/module-federation-examples/pull/688. and upgrade the webpack to the latest version (5.19.0)

**Comment by VovaSv** [comment]
Same issue but not from example:
![image](https://user-images.githubusercontent.com/3116365/108133531-67f26200-70bd-11eb-8079-de4d8e2ff637.png)

    new DashboardPlugin({
      dashboardURL: "http://localhost:3000/api/update",
      metadata: {
        remote: "http://localhost:8081/remoteEntry.js",
      },
    })


```
new ModuleFederationPlugin({
        name: "hostreact",
        library: { type: "var", name: "hostreact" },
        filename: "remoteEntry.js",
        remotes: {
          growlers: "growlers@http://localhost:8080/remoteEntry.js",
        },
        exposes: {},
        shared: {
          ...deps,
          react: {
            singleton: true,
            requiredVersion: deps.react,
          },
          "react-dom": {
            singleton: true,
            requiredVersion: deps["react-dom"],
          },
        },
      }),  
```

```
    "webpack": "^5.21.2",
    "webpack-cli": "^4.5.0",
    "webpack-dev-server": "^3.11.2"
    "@module-federation/dashboard-plugin": "^2.1.0",
```

**Comment by tklepzig** [comment]
I've run into this issue as well. I'm using the current version `2.1.1` of the dashboard plugin with webpack `5.26.3`. I looked into the code and it seems there is any kind of version expected anywhere in the plugin options which is undefined, therefore the error. (@module-federation/dashboard-plugin/FederationDashboardPlugin.js:155:56).
