### ISSUE TITLE
Shared modules are duplicate in main and polyfills

### ISSUE THREAD

**Issue by tonnguyen** [module-federation/module-federation-examples#693]
By using webpack-bundle-analyzer to analyze the shell app, we can see all shared modules are included in both main.js, polyfills.js, even in styles.js. Here is what we have by analyzing the [angular11-microfrontends](https://github.com/module-federation/module-federation-examples/tree/master/angular11-microfrontends) example:

![image](https://user-images.githubusercontent.com/887772/106945286-e8ad7780-6727-11eb-9561-3d14d4949329.png)

**Comment by cstefan** [comment]
Can confirm. Any solution for it?

**Comment by jacob-ebey** [comment]
Try sharing the module that's showing up in all of them.

**Comment by tonnguyen** [comment]
They are shared https://github.com/module-federation/module-federation-examples/blob/master/angular11-microfrontends/projects/mdmf-shell/webpack.config.js

**Comment by cstefan** [comment]
Hi there. **eager: true** is triggering this issue. 
In the Profile App I can remove it and then it has multiple and smaller bundles. Everything works 👍

In the Shell App if I remove it, it fails and I can't find a configuration where it works.
In theory in the shell I dont want to load the angular dependencies from somewhere else....it is the Shell. For the Profile Frontend you do want to reuse the dependencies from Shell.

**Comment by tonnguyen** [comment]
Yes @cstefan , the Profile App can have eager as false to solve the problem. However, I believe the issue in Shell App should also be fixed, to avoid having big and duplicate output files.

**Comment by jacob-ebey** [comment]
For what feels like the 1000th time: Eager will bundle the module as part of the entrypoint for *eager* consumption. DO NOT USE EAGER UNLESS YOU KNOW WHAT IT IS AND HAVE A VALID REASON TO DO SO.

**Comment by tonnguyen** [comment]
I have no problem of having those modules be bundled as part of the entrypoint. The problem is it is duplicate in every files, even styles.js, which to me does not seem to be an entrypoint. 

And the issue can be reproduced without any modification to the code, every examples we have.

**Comment by cstefan** [comment]
When serving the Shell App with eager: **false** I get this error:
**Shared module is not available for eager consumption: 1548**

**Comment by jacob-ebey** [comment]
@cstefan Bootstrap your app with an async import.

**Comment by cstefan** [comment]
@jacob-ebey you are **the Man** It just clicked when I read your reply.
In the main.ts file from the Shell I made this change:

Instead of: 
`import "./bootstrap";`

I wrote 
`import('./bootstrap')`

This is all it takes and the shell works. I think that webpack will compile that line as an async import

**Comment by jacob-ebey** [comment]
Yep, that's all it takes. @cstefan if you can keep an eye out and just comment "Bootstrap your app with an async import." on issues like this I'd be appreciative. I'm getting tired of seeing the same thing over and over again.

**Comment by csvan** [comment]
@jacob-ebey so what *is* a valid usecase for eager over bootstrap?

**Comment by jacob-ebey** [comment]
I have yet to find one.

**Comment by csvan** [comment]
Then why is eager not simply deprecated?

**Comment by jacob-ebey** [comment]
Because it does have uses, but in 99.99% of cases it's not what you want.

**Comment by jacob-ebey** [comment]
One kinda valid reason I guess would be if you had a 1kb library. At that point why worry about downloading multiple copies?

**Comment by jacob-ebey** [comment]
Can this be closed?

**Comment by giggio** [comment]
I just tested the [angular12-microfrontends example](https://github.com/module-federation/module-federation-examples/tree/master/angular12-microfrontends) and it is still bundling `@angular/core` twice, for `main` and `polyfills`.
Here is the analysis:

![image](https://user-images.githubusercontent.com/334958/137198652-9b66afbb-5900-439e-a3a9-986418aa2105.png)

How to run this report:

````bash
ng build --configuration production --stats-json
npx webpack-bundle-analyzer dist/mdmf-shell/stats.json
````

I need to bundle the shared dependencies only once, and I haven't been able to do it, at least not with Angular, which is what I'm using. I really don't care what configuration needs to be set, I saw some criticism with `eager` previously in the comments, and I don't need to use it. I just need the shared dependencies to bundle only once, in a single file. It can be in the `main` entrypoint file, or another.

Is this possible at all with module federation?

**Comment by manfredsteyer** [comment]
Has anyone found a solution for this?

**Comment by ggradnig** [comment]
Asynchronously importing both polyfills.js and main.js solved the problem for me. (i.e. with bootstrap.js and bootstrap-polyfills.js)

**Comment by sachintavisca** [comment]
@ggradnig could you please add more info on how you did it?

**Comment by michalma** [comment]
Anyone figured out how to fix this?

**Comment by murli2308** [comment]
it is causing performance issue. Any solution on this ?

**Comment by erdysson** [comment]
for me, changing main ts from
```
import './bootstrap';
```
to
```
import('./bootstrap');
```
solved the duplication issue.

But now all the bundle is in bootstrap_ts.js file

**Comment by cmayankc** [comment]
This is definitely an issue, I have tried async import but doesn't work. @ScriptedAlchemy do you have a solution for this?
