### ISSUE TITLE
Angular MF with assets (images) in embedded app

### ISSUE THREAD

**Issue by sevaru** [module-federation/module-federation-examples#697]
It's more question then issue.

Is there any practice on use images in html and css
cause by defaul if I use pathes like ../../assets/pic.png

when I open embedded app in shell app urls looking in shell app host e.g. localhost:4200 instead of localhost:4201 in angular example.

I would really appreciate any suggestions on that

**Comment by cstefan** [comment]
Good point! For small SVGs I would just inline them in the compilation. When working with **Less** you have `data-uri('startup.svg')`
For bigger pictures I would look at setting the whole path with the help of a variable with the entry-point.
`background-image: url($entry-point + '/startup.png');`

But, ... I see many issues.
Have you found anything else?

**Comment by sevaru** [comment]
yes @cstefan thank, we inline small assets too.

but we have problems with fonts, and big assets for now.

No i have to postpone my research for now.
But if I came back to it I'll let you now.

**Comment by ScriptedAlchemy** [comment]
anything webpack can process can be federated, images, css, side effects, the works.  Im not sure if this is an angular specific issue

**Comment by vaindil** [comment]
I'm running into this issue as well. Angular typically loads assets against the base URL of its site, which is set with the `<base>` tag in `index.html`. (I have no idea if this is typical of other frameworks too, I only have experience with Angular.) The sub-app's base path is apparently ignored with the standard Webpack setup for federation--only the shell app's base is used, which leads to this issue.

Still trying to work on this, but I'm new to Webpack config stuff since Angular has handled it all for me in the past.

**Comment by ScriptedAlchemy** [comment]
Don't know how to handle angular specific. But in webpack the file-loader accepts a post transform option which you could use to infer the url internally

Webpack usually figures it out with some parsing of document.currentScript

**Comment by ScriptedAlchemy** [comment]
Looks like there's a way to set this in webpack instead of depending on markup. Not sure how but someone told me it's possible. If so then we can get an at runtime base assignment

**Comment by axell9641** [comment]
Did anybody find a way to share static resources (images) between the remotes and the shell?

**Comment by neubs-bsi** [comment]
You can declare shared assets from a library in the webpack config in the shared option of your ModuleFederationPlugin:
```
          '.shared/assets': {
            singleton: true,
            eager: true,
            import: './shared/assets',
            requiredVersion: require("../../package.json").version,
          },
```
Just add this to both webpack configurations. It should then use the assets from your remote as well as your shell. This works if you have a monorepo and a shared assets library.

**Comment by Markiewic** [comment]
I think I solved this problem relatively well, but I still want to explore a more convenient solution.

You need to use the variable `__webpack_public_path__` from webpack to access the base address from which any remote module was loaded.

For example, to access an asset from a remote module, you can specify its path like this:
`some.component.ts` (component from remote)
```ts
declare const __webpack_public_path__: string;

@Component(...)
export class SomeComponent {
  public publicPath = __webpack_public_path__; // here will be smth like `localhost:4201/`
}
```
`some.component.html`
```html
<img [src]="publicPath + 'assets/some-asset.png'" />
```

`some-asset.png` is served by remote, but will be available from both the host and remote, since we are building the correct link to it.

To simplify your development, you can provide a variable in the exposed modules and make pipe that will build the correct link itself.
```html
<img [src]="'assets/some-asset.png' | localAsset" />
```

**Comment by JonWallsten** [comment]
Thank you @Markiewic for the inspiration to finally solve this once for all!
I can add to anyone stumbling upon this that if you put your pipes and/or utils methods in a separate library, like we do, you might want to use an InjectionToken or similar to set the public path somewhere in you apps context, to make it's not using the wrong path, if for example, your host app is sharing the library with the remotes.

I have it working now for both 
```html
<img [src]="'assets/test.svg' | assetUrl" /> 
```
 and 
```js
const url = assetUrl('assets/test.svg', document);
this.domSanitizer.bypassSecurityTrustResourceUrl(url)
```

It works for all remote, both as remote entry, and when running standalone on it's own port.
It works for serve as well as build:dev and build:prod, both locally and deployed with the pipeline.
It also works with `<base href="/sub-path/">` 

You will need to add CORS headers to make it work on localhost if you have any scenario when a XHR request is made.

**Comment by spierala** [comment]
> I think I solved this problem relatively well, but I still want to explore a more convenient solution.
> 
> You need to use the variable `__webpack_public_path__` from webpack to access the base address from which any remote module was loaded.
> 
> For example, to access an asset from a remote module, you can specify its path like this: `some.component.ts` (component from remote)
> 
> declare const __webpack_public_path__: string;
> 
> @Component(...)
> export class SomeComponent {
>   public publicPath = __webpack_public_path__; // here will be smth like `localhost:4201/`
> }
> `some.component.html`
> 
> <img [src]="publicPath + 'assets/some-asset.png'" />
> `some-asset.png` is served by remote, but will be available from both the host and remote, since we are building the correct link to it.
> 
> To simplify your development, you can provide a variable in the exposed modules and make pipe that will build the correct link itself.
> 
> <img [src]="'assets/some-asset.png' | localAsset" />

how would that work in Native Federation? `__webpack_public_path__` does not seem to exist anymore. Because it is not webpack anymore in Native Federation. Is there an alternative for esbuild, which is used for NF?

**Comment by ScriptedAlchemy** [comment]
> > I think I solved this problem relatively well, but I still want to explore a more convenient solution.
> > 
> > You need to use the variable `__webpack_public_path__` from webpack to access the base address from which any remote module was loaded.
> > 
> > For example, to access an asset from a remote module, you can specify its path like this: `some.component.ts` (component from remote)
> > 
> > declare const __webpack_public_path__: string;
> > 
> > @Component(...)
> > export class SomeComponent {
> >   public publicPath = __webpack_public_path__; // here will be smth like `localhost:4201/`
> > }
> > `some.component.html`
> > 
> > <img [src]="publicPath + 'assets/some-asset.png'" />
> > `some-asset.png` is served by remote, but will be available from both the host and remote, since we are building the correct link to it.
> > 
> > To simplify your development, you can provide a variable in the exposed modules and make pipe that will build the correct link itself.
> > 
> > <img [src]="'assets/some-asset.png' | localAsset" />
> 
> how would that work in Native Federation? `__webpack_public_path__` does not seem to exist anymore. Because it is not webpack anymore in Native Federation. Is there an alternative for esbuild, which is used for NF?

Welcome to the hellscape of weak build tooling.
