### ISSUE TITLE
Next.js - getting "ReferenceError: __webpack_modules__ is not defined"

### ISSUE THREAD

**Issue by bchurlinov** [module-federation/module-federation-examples#698]
I have "app1" that exports a few components. Then the "app2" consumes those components.

When the "app2" loads everything works fine however when I navigate to another page ( and if this page uses certain components that "app1" exposes ) I get  "ReferenceError: __webpack_modules__ is not defined". If I refresh the page everything seems to be working and this error is gone.

Anyone else has this issue?

I am using:
"next": "10.0.2",
"@module-federation/nextjs-mf": "^0.0.2",
"react": "17.0.1",
"react-dom": "17.0.1",

"resolutions": {
 "webpack": "5.18.0"
},

**Comment by animecyc** [comment]
I've submitted a potential fix for this issue here: https://github.com/webpack/webpack/pull/12831
