### ISSUE TITLE
NextJS Error: Module Federation only works with Webpack 5

### ISSUE THREAD

**Issue by MichaelDurfey** [module-federation/module-federation-examples#699]
I'm getting this error when trying to add in webpack 5 locally in my own project and also on the nextjs project here in this repo. It appears to be an issue with webpack 5 resolution in package.json file. Do we need to use `yarn v 2` or something? 
Error is coming from the withModuleFederation function and the container check.

**Comment by JakubSlonka** [comment]
Hi Michael, this issue could be solved by using following configuration

```
  "resolutions": {
    "webpack": "5.11.1"
  },
  "dependencies": {
    "@module-federation/nextjs-mf": "0.1.0",
    "next": "10.0.0",
    "react": "17.0.1",
    "react-dom": "17.0.1"
  },
```

somehow module federation works only with specific version of webpack and next.js

**Comment by JakubSlonka** [comment]
After updating your package.json do not forget to clear node modules for 

linux: `rm -rf node_modules`
windows: `rm -r -fo node_modules`

after clearing modules run
`yarn`
and then you should be able to call
`yarn dev` successfully


the only requirement for yarn is to use version that supports resolutions

**Comment by MichaelDurfey** [comment]
Thanks, @JakubSlonka. I solved this issue by downgrading `next` to 9.5.5 in my resolutions file. Appears to be an issue with next.

**Comment by jacob-ebey** [comment]
There is an experimental next.config.js option you have to enable for webpack 5 support in the latest versions.

**Comment by JakubSlonka** [comment]
> There is an experimental next.config.js option you have to enable for webpack 5 support in the latest versions.

That is not the issue Michael was running into.

Next.js version higher then 10.0.0 does not work with webpack 5

To fix this issue you have to lower the next version.

**Comment by jacob-ebey** [comment]
> > There is an experimental next.config.js option you have to enable for webpack 5 support in the latest versions.
> 
> That is not the issue Michael was running into.
> 
> Next.js version higher then 10.0.0 does not work with webpack 5
> 
> To fix this issue you have to lower the next version.

That is not true at all.

**Comment by JakubSlonka** [comment]
> > > There is an experimental next.config.js option you have to enable for webpack 5 support in the latest versions.
> > 
> > 
> > That is not the issue Michael was running into.
> > Next.js version higher then 10.0.0 does not work with webpack 5
> > To fix this issue you have to lower the next version.
> 
> That is not true at all.

Did you try the examples in this repoat all? 

You see lowering version actually helped Michael and also my self to run the module federation.

If you just pull the repo and try to build the examples, it fails with described error.

**Comment by JakubSlonka** [comment]
> There is an experimental next.config.js option you have to enable for webpack 5 support in the latest versions.

This option is not mentioned in any of the examples with next.js in this repository.

Also if you just pull the repo, the examples cannot be build. 

Would be really nice if someone could fix it.

**Comment by jacob-ebey** [comment]
next.config.js
```js
module.exports = {
  future: { webpack5: true },
};
```

**Comment by MichaelDurfey** [comment]
Nice, thanks @jacob-ebey. That works for me. I must have overlooked that in the documentation 🤔
