### ISSUE TITLE
Dashboard Not Working | FederationDashboardPlugin Error | HookWebpackError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by VovaSv** [module-federation/module-federation-examples#700]
Can not load dashboard get an error.
![image](https://user-images.githubusercontent.com/3116365/108134435-e69bcf00-70be-11eb-8b93-ca7cf75f154c.png)
![image](https://user-images.githubusercontent.com/3116365/108134477-f4515480-70be-11eb-814a-30ea359ae92f.png)
![image](https://user-images.githubusercontent.com/3116365/108134717-61fd8080-70bf-11eb-84db-44a73dd6c374.png)

```
    "webpack": "^5.21.2",
    "webpack-cli": "^4.5.0",
    "webpack-dev-server": "^3.11.2"
    "@module-federation/dashboard-plugin": "^2.1.0",
```

× ｢wdm｣: HookWebpackError: Cannot read property 'split' of undefined
    at makeWebpackError (C:\Coding\harmony-boilerplate-master\node_modules\webpack\lib\HookWebpackError.js:49:9)
    at C:\Coding\harmony-boilerplate-master\node_modules\webpack\lib\Compilation.js:2383:12
    at eval (eval at create (C:\Coding\harmony-boilerplate-master\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:18:1)
-- inner error --
TypeError: Cannot read property 'split' of undefined
    at C:\Coding\harmony-boilerplate-master\node_modules\@module-federation\dashboard-plugin\FederationDashboardPlugin.js:155:56
× ｢wdm｣: caused by plugins in Compilation.hooks.processAssets
TypeError: Cannot read property 'split' of undefined
    at C:\Coding\harmony-boilerplate-master\node_modules\@module-federation\dashboard-plugin\FederationDashboardPlugin.js:155:56
Error posting data to dashboard URL: http://localhost:3000/api/update
i ｢wdm｣: wait until bundle finished: /

**Comment by XiaofengXie16** [comment]
if you just want to just get the dashboard to work, V1 of the dashboard plugin still works.

**Comment by binerdy** [comment]
The problem is that the FederationDashboardPlugin is not providing a default version for publishVersion if not provided. As a workaround you can set the publishVersion in the options like so:

```ts
new DashboardPlugin({
  ...,
  publishVersion: "1.0.0",
  ...
})
```

Let me know if this solved your problem.

**Comment by ScriptedAlchemy** [comment]
read the publishVersion from package.json as a reliable workaround - ill work on patching the requirement

**Comment by ScriptedAlchemy** [comment]
contributions can be made here: https://github.com/module-federation/medusa
