### ISSUE TITLE
Framework agnostic app with module federation

### ISSUE THREAD

**Issue by bullypb23** [module-federation/module-federation-examples#704]
Hi @ScriptedAlchemy,

My use case is that I need a micro frontend dashboard app that consists of multiple widgets that can be written in different frameworks and imported into the dashboard. Also, I need that widget to be accessible to existing SPA written in angular or any other framework. Is that possible with the module federation? Really would appreciate your response.

**Comment by jacob-ebey** [comment]
Nothing to do with module federation. Zero, zilch, nada. Look into solutions like single-spa.
