### ISSUE TITLE
vue3-demo not working

### ISSUE THREAD

**Issue by yuArimer** [module-federation/module-federation-examples#705]
need webpack-cli Upgrade to webpack-cli@4.5.0

**Comment by ScriptedAlchemy** [comment]
Please open a PR :D

**Comment by ironytr** [comment]
hello, im noob, i have used vue on laravel... i want to learn how to start a vue project from scratch. first using vue cli? then add webpack modules? what is the order of terminal commands to make a vue micro frontend? if any1 helps thx (just need order of terminal commands to create a project, i have found react version of it https://levelup.gitconnected.com/micro-frontends-step-by-step-using-react-webpack-5-and-module-federation-e4b9d840ec71 so easy to create but no vue lessons :( ).
