### ISSUE TITLE
[MF-Dashboard]Missing Code Link  in development section on dockerhub

### ISSUE THREAD

**Issue by prashankMT** [module-federation/module-federation-examples#710]
Development section of [this](https://hub.docker.com/r/scriptedalchemy/mf-dashboard) link doesn't contain link for code. People can't develop or make changes to dashboard create by @ScriptedAlchemy

**Comment by XiaofengXie16** [comment]
I believe this tool is still not open sourced yet but it seems the author plans to do it. (Hint: Check his twitter)

**Comment by ScriptedAlchemy** [comment]
Planning on it but neeed to create some kind of api.  We are working on aegis, once released we will work on connecting it to what will become Medusa

**Comment by ScriptedAlchemy** [comment]
contributions can be made here: https://github.com/module-federation/medusa
