### ISSUE TITLE
SSR with CSS

### ISSUE THREAD

**Issue by piniTayeb** [module-federation/module-federation-examples#715]
I am looking for a SSR example with CSS,
A shared component with simple CSS file... (not inline), like this:

```
import React from "react"
import './styles.css'

const SharedComponent = () => <div>Shared Component</div>

export default SharedComponent
```

Can anyone help?

**Comment by ScriptedAlchemy** [comment]
Css should share. I think what you’re wanting is the chunk “flushing” to correlate the SSR chunks with their browser side counterparts. 

This is something I’m working on

**Comment by piniTayeb** [comment]
Thank you @ScriptedAlchemy :)

What do you mean "Css should share" ? share it in the ModuleFederationPlugin like a component?

**Comment by ScriptedAlchemy** [comment]
Yeah you can share css or any file via MF plugin either via exposes or shared

**Comment by ubercooluk** [comment]
@ScriptedAlchemy ..how to share a css/scss file from one MF to another. I need to access this shared css in another css as an @import.

tried in exposes like this 

exposes: {
          "./mycss": "./src/css/sample.css"
 },
 
 How can i import the above in any other MF ?
