### ISSUE TITLE
Integration of Module Federation with Material-UI overriding parent theme with defaults

### ISSUE THREAD

**Issue by edwards-afterpay** [module-federation/module-federation-examples#730]
I ran into material-ui ThemeProvider issue. Every time I render a remote federated component which has Mui-Components I will see more default Mui `<style>` getting injected into shell `<head>` tag. I would have assumed the ThemeProvider from the parent shell will propagate all the way to the remote child apps. It didn't but instead injects additional default theme to my parent app once I import the remote child app.

I am not really sure where should I post this problem - Mui or Module Federation. But feels like it's a combination of both.

### Before Module Fed - Setup:
`shell` app bootstraps the ThemeProvider with custom theme. The Button rendered in the `shell` shows correct custom theme.
```
import React from 'react';
import { theme } from './theme'
import { ThemeProvider } from "@material-ui/core/styles";
import { Button, CssBaseline } from "@material-ui/core";

const App = () => {
    return (
            <ThemeProvider theme={theme}>
                <CssBaseline />
                 <Button variant='contained' color='primary'>Parent button</Button>
            </ThemeProvider>
    )
}

export default App;
```
`index.html` source
![image](https://user-images.githubusercontent.com/53719593/113370431-6becf180-9396-11eb-9cdc-195d6b5aefac.png)

### After - Problem as soon as I start adding Federated component:
```
import React from 'react';
import { theme } from './theme'
import { ThemeProvider } from "@material-ui/core/styles";
import { Button, CssBaseline } from "@material-ui/core";
import RemoteApp1 from "webRemoveApp1/App";
const RemoteApp2 = React.lazy(() => import("webRemoveApp2/App"));

const App = () => {
    return (
            <ThemeProvider theme={theme}>
                <CssBaseline />
                 <Button variant='contained' color='primary'>Parent button</Button>
                 <RemoteApp1 />
                 <RemoteApp2 />
            </ThemeProvider>
    )
}

export default App;
```
`index.html` source, you will find 2 additional sets of `<style>` being injected from each App (`MuiTouchRipple, MuiButtonBase, MuiButton`), and because they have higher priority, it overwrites my parent Button's theme back to defaults, same as the children.

![image](https://user-images.githubusercontent.com/53719593/113370805-67750880-9397-11eb-8198-dcd770f2d834.png)

theme.js
```
import { createMuiTheme } from '@material-ui/core/styles'
const themeConfig = {
  palette: {
    primary: {
      main: '#008000', // green
    }
  }
}
export const theme = createMuiTheme(themeConfig)
```

RemoteApp1
```
import React from "react";
import { Button } from "@material-ui/core";

const App = () => {
    return (
            <div>App1
                <Button variant='contained' color="primary">Child App1</Button>
            </div>
    )
}
export default App;
```

RemoteApp2
```
import React from "react";
import { Button } from "@material-ui/core";

const App = () => {
    return (
            <div>App2
                <Button variant='contained' color="primary">Child App2</Button>
            </div>
    )
}
export default App;
```

**Comment by edwards-afterpay** [comment]
I may have figured it out, it seems under the hood `@material-ui/styles` used has to be singleton. Just like React has to be singleton to ensure React Context behaves correctly.
Once I added both the `@material-ui/core` and `@material-ui/styles` in the `ModuleFederationPlugin->shared` the problem seems to go away.
```
shared: {
   react: {
    singleton: true,
    requiredVersion: deps.react,
  },
  "react-dom": {
    singleton: true,
    requiredVersion: deps["react-dom"],
  },
  "@material-ui/core": {
    singleton: true,
    requiredVersion: deps["@material-ui/core"]
  },
  "@material-ui/styles": {
    singleton: true,
    requiredVersion: deps["@material-ui/styles"]
  }
}
```

**Comment by ScriptedAlchemy** [comment]
yes, anything that passed context needs to be a singleton, theming and styling usually have caches or context busses that needs to be centralized and shared. If context-related stuff isn't working, its most likely a missing `shared` key, take a look in the node module folder and see what else it depends on that might be a nested dep of something you're sharing. like a cache

**Comment by jgarcia77** [comment]
@ScriptedAlchemy ,

I am a big fan of your YouTube channel!  

I am currently working on an MFE that has a higher version of 'react-redux' than the host app.  The MFE is using react-redux 8.x and the host app is using react-redux 7.x.  When sharing 'react-redux' from the MFE (via module federation config) I encounter errors due to one of the host's dependencies (react-beautiful-dnd) that requires react-redux 7.x.  

Is there a away a way to share dependencies to the host app only and NOT to any vendor modules within the host app?

**Comment by ScriptedAlchemy** [comment]
You can put them in two different share scopes. Each shared module can have a key shareScope: "something" so you can share multiple singletons to different scopes. You will however end up with two different instances of redux and would need to deal with syncing between them or accept that state would tear

**Comment by jgarcia77** [comment]
@ScriptedAlchemy 

Thanks for the response.  We ended up replacing the vendor module that was causing the issue and we are now using the same react-redux version in both the host app and MFE.  Thanks again for responding!!!
