### ISSUE TITLE
Could angularjs be part of this game?

### ISSUE THREAD

**Issue by piscke** [module-federation/module-federation-examples#731]
I really liked this project and I think it could solve a big problem with a legacy application. I am trying to make a simple example using angularjs but I am not having success. 

Do you think it is possible to use the module federation with angularjs?

**Comment by ScriptedAlchemy** [comment]
yes easily, but i dont write angular apps, anyone who contributes an angular example in any form will be happily accepted. I only code examples of the framework i specialize in :/
