### ISSUE TITLE
Webpack Module federation plugin for react in angular

### ISSUE THREAD

**Issue by anilakuzum** [module-federation/module-federation-examples#750]
I am using Webpack 5, I want to add the angular project component to the react project, but it does not work. My codes are as follows.

this angular webpack code as follows

      const HtmlWebPackPlugin = require("html-webpack-plugin");
      const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");
    
      module.exports = {
      mode: "development",
      entry: {
        main: "./src/main.ts",
      },
      output: {
        publicPath: "http://localhost:8083/",
        uniqueName: "content",
      },
      resolve: {
        extensions: [".ts", ".jsx", ".js", ".json"],
      },
    
      devServer: {
        port: 8083,
      },
    
      module: {
        rules: [
          {
            test: /\.tsx?$/,
            loader: "ts-loader",
          },
    
          {
            test: /\.css$/i,
            use: ["style-loader", "css-loader"],
          },
          {
            test: /\.(js)$/,
            exclude: /node_modules/,
            use: {
              loader: "babel-loader",
            },
          },
        ],
      },
      plugins: [
        new ModuleFederationPlugin({
          name: "content",
          filename: "remoteEntry.js",
          exposes: {
            "./content": "./src/app/app.module.ts",
          },
          library: { type: "var", name: "content" },
          shared: {
            "@angular/core": { eager: true, singleton: true },
            "@angular/common": { eager: true, singleton: true },
            "@angular/router": { eager: true, singleton: true },
          },
        }),
        new HtmlWebPackPlugin({
         
          template: "./src/app/app.component.html",
        }),
      ],
    };

   
this react webpack code as follows

    const HtmlWebPackPlugin = require("html-webpack-plugin");
    const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");
    module.exports = {
      mode: "development",
      devServer: {
        port: 8002,
      },
    
      plugins: [
        new ModuleFederationPlugin({
          name: "skeleton",
          filename: "remoteEntry.js",
          
          remotes: {
            header: "header@http://localhost:8081/remoteEntry.js",
            content: "content@http://localhost:8083/remoteEntry.js",
            starter:'starter@http://localhost:8089/remoteEntry.js',
          },
        }),
        new HtmlWebPackPlugin({
          template: "./public/index.html",
        }),
      ],
      module: {
        rules: [
          {
            test: /\.js?$/,
            loader: "babel-loader",
            options: {
              presets: ["@babel/preset-env", "@babel/preset-react"],
            },
          },
        ],
      },
    };

In this way, I import but the component does not come.

```
import React, { lazy, Suspense, useEffect } from "react";
import mountHeader from "starter/mountHeader"; 
import Content from "content/content";
const Header = lazy(() => import("header/App")); 

const App = () => {
  return (
    <div>
      <div>
        <Suspense fallback="Loading Button">
          <Header />
        </Suspense>
      </div>
      {Content}
      {mountHeader("#menu")}
    </div>
  );
};
export default App;
```

**Comment by pedronaveszup** [comment]
If I understood your case, you are exporting a module from Angular and importing in React as a Component.

If that is, you will have to do other things to do this happen. And that it's not a limitation or problem with Module Federation. You can have both frameworks/libs together.

I think [this article](https://www.angulararchitects.io/aktuelles/multi-framework-and-version-micro-frontends-with-module-federation-the-good-the-bad-the-ugly/) can be helpful for you. The source code for this case study can be found [here](https://github.com/manfredsteyer/multi-framework-micro-frontend). 

In this approach, he uses [customElements](https://developer.mozilla.org/en-US/docs/Web/API/Window/customElements)
