### ISSUE TITLE
Is server-side-rendering still broken?

### ISSUE THREAD

**Issue by GitProdEnv** [module-federation/module-federation-examples#751]
Can you fix the server-side-rendering example or does the issue still exist with @loadable/component almost a half year later.

Since this problem is a huge barrier to use module-federation where ssr support is needed.

**Comment by jacob-ebey** [comment]
SSR was never broken and isn't broken. Chunk collection methods just haven't been made generally available yet. It comes down to generating stats for your federated builds and getting those to the consuming SSR'd applications to know what chunks to pre-render. Have a gander at this repo if you want to implement it yourself: https://github.com/jacob-ebey/ssr-react-streaming-example

**Comment by ScriptedAlchemy** [comment]
react-lazy-ssr is also a viable solution. @jacob-ebey and myself will likely need to build something to resolve any missing chunk flushing capabilities for work in the near future

**Comment by ScriptedAlchemy** [comment]
ive also use react-lazy-hydration to have SSR chunks hydrate only after the parts of code are ready, then render it into a react component from static HTML

**Comment by ScriptedAlchemy** [comment]
We have solved this problem but the solution is only available through paid workshops
