### ISSUE TITLE
Can we use module federation with create-react-app without ejecting?

### ISSUE THREAD

**Issue by harishv6665** [module-federation/module-federation-examples#756]

**Comment by JB1905** [comment]
@harishv6665 No, for now ejecting is only option as I know. Please check CRA issue for module federation support https://github.com/facebook/create-react-app/issues/9510.

**Comment by ScriptedAlchemy** [comment]
Keep on nagging them and get your friends to do it as well :) power in numbers

**Comment by neysimoes** [comment]
https://github.com/module-federation/module-federation-examples/pull/2028
