### ISSUE TITLE
Angular MFE that uses Angular Material/CDK does not render properly

### ISSUE THREAD

**Issue by alincc** [module-federation/module-federation-examples#759]
I simple added `@angular/cdk` and `@angular/material` to Profile MFE to open a simple dialog.
When switching between **Home** and **Profile** page the content is not refreshing.

I suspect it's related to Overlay from CDK. I also tried older versions of cdk and material, but still the same.

This is how it looks like:
![image](https://user-images.githubusercontent.com/1649645/116726829-7bd71000-a9ec-11eb-8500-4457087eb69b.png)

I created a PR to reproduce the issue:
https://github.com/module-federation/module-federation-examples/pull/758

**Comment by ScriptedAlchemy** [comment]
Likely something nested isn’t being shared that needs to be

**Comment by JohnBelland** [comment]
Running into the same issue, ever resolve?
