### ISSUE TITLE
Example nextjs has a wrong registry in yarn.lock

### ISSUE THREAD

**Issue by poteirard** [module-federation/module-federation-examples#761]
Seems someone left the PayPal registry URLs here which breaks the installation for non-paypal workers.

https://github.com/module-federation/module-federation-examples/blob/master/nextjs/yarn.lock

**Comment by poteirard** [comment]
@MichaelDurfey

**Comment by ScriptedAlchemy** [comment]
re-yarn and PR if its still an issue
