### ISSUE TITLE
angular11-microfrontends-lazy-components | styles not getting applied for shared component

### ISSUE THREAD

**Issue by hardikpatel043** [module-federation/module-federation-examples#762]
![image](https://user-images.githubusercontent.com/13534287/116973481-424b2100-acda-11eb-9089-236e0e687a0e.png)

I was trying to run one of the example of angular.

I observed that styles of shared component "lib-mdmf-shared" are not applied when I run shell or profile app.

![image](https://user-images.githubusercontent.com/13534287/116973662-7b839100-acda-11eb-86bd-c2bbb9e56c69.png)

Any solution to this?

**Comment by ScriptedAlchemy** [comment]
likely a design issue but i dont know angular unfortunately 
In react is was because the shell needed to share the style vendor or some service as well as expose it to the shell itself depends on it

**Comment by ydmitry** [comment]
Did you rebuild mdmf-shared?

**Comment by hardikpatel043** [comment]
This is not working because module federation with Angular CLI 11 doesn't support styleUrl in component.

![image](https://user-images.githubusercontent.com/13534287/120096616-2193b100-c14a-11eb-9735-cdc481f6a184.png)

Putting styles in html as below worked.

![image](https://user-images.githubusercontent.com/13534287/120096631-36704480-c14a-11eb-81fb-d8276fa7ed0b.png)

However, this issue is fixed with Angular 12. 

@ScriptedAlchemy Do you want me to upgrade all angular examples to angular 12? I would love to contribute.

**Comment by smasala** [comment]
@hardikpatel043 that would be great. I can't seem to get my local examples working on NG 12 - seems to try and load the lazy modules from the host origin rather than the remote 🤷‍♂️

**Comment by smasala** [comment]
@hardikpatel043  if you do update the example you'll need this: https://github.com/angular-architects/module-federation-plugin/issues/36

**Comment by ScriptedAlchemy** [comment]
Yes please any updates that need to be made should be. I don't really use angular so I don't know how to fix them if they break. 

Happy to accept PRS

**Comment by edarioq** [comment]
I can confirm `styleUrls` works perfectly fine, not sure what the issue is here. I'm currently using Angular 11. Either way getting an update to Angular 12 would be awesome.
