### ISSUE TITLE
MF Angular 11 Hot Module Reloading Not Working

### ISSUE THREAD

**Issue by edarioq** [module-federation/module-federation-examples#763]
As the title says, I have a MF with a shell and dashboard so far, whenever I make a change in HTML, CSS, or TS files the browser doesn't auto refresh.

I have also tried cloning an example project here and it also isn't auto reloading. Is this a known bug or what am I missing?

Using Angular 11 and pretty much following the example app of *angular11-microfrontends-lazy-components*

**Comment by vrapalis** [comment]
Same issue, i believe webpack 5 and angular cli 11 yet not properly work together.

I have same issue: https://github.com/angular-architects/module-federation-plugin/issues/38

Maybe we have to wait until angular cli 12 release which will fully integrate webpack 5.

**Comment by vrapalis** [comment]
> As the title says, I have a MF with a shell and dashboard so far, whenever I make a change in HTML, CSS, or TS files the browser doesn't auto refresh.
> 
> I have also tried cloning an example project here and it also isn't auto reloading. Is this a known bug or what am I missing?
> 
> Using Angular 11 and pretty much following the example app of _angular11-microfrontends-lazy-components_

If you have some updates can you write here?

**Comment by jacob-ebey** [comment]
This has nothing to do with federation. Webpack itself does not support cross container HMR at the moment. https://github.com/webpack/webpack/issues/11182

**Comment by edarioq** [comment]
Right but is there a quick fix ? Or should we configure it manually somehow via webpack itself for now ?

**Comment by edarioq** [comment]
I see Angular 12 has been recently released with native Webpack 5 support. Can we just plug this in and expect HMR to work again ?

**Comment by jacob-ebey** [comment]
@edarioq  https://github.com/webpack/webpack/issues/11182

**Comment by ScriptedAlchemy** [comment]
Vote for it on webpack https://github.com/webpack/webpack/issues/11182#issuecomment-777334625
