### ISSUE TITLE
vue-cli examples shared library not work

### ISSUE THREAD

**Issue by rubickecho** [module-federation/module-federation-examples#791]
hi, I'm having some problems

# step1

clone `module-federation-examples`
```
cd vue-cli
```
and

```
# cd core/consumer
yarn add element-ui
```

# step2
update `vue.config.js`, shared `element-ui`, 
`core` project like this:
![image](https://user-images.githubusercontent.com/14804014/117536071-9c761a00-b02b-11eb-9b75-028fa5e2151a.png)

update `core`、`consumer` project `main.js`, like this:

![image](https://user-images.githubusercontent.com/14804014/117536121-e19a4c00-b02b-11eb-8ba3-e306acb5cfb7.png)

![image](https://user-images.githubusercontent.com/14804014/117536111-d6472080-b02b-11eb-98e3-78a86a068a57.png)

# step3
run project, but observe resource loading
why did no `consumer` fail to load the Elemental-UI shared by `core`? 
the expectation should be only tens of 600kb, not 6MB

![Xnip2021-05-08_18-25-29](https://user-images.githubusercontent.com/14804014/117536261-a8aea700-b02c-11eb-83aa-4059d3dc70bb.jpg)

![Xnip2021-05-08_18-24-35](https://user-images.githubusercontent.com/14804014/117536267-acdac480-b02c-11eb-907e-f731836ce459.jpg)

**Comment by ScriptedAlchemy** [comment]
PR welcome, i dont write vue and cannot resolve this

**Comment by schirrel** [comment]
HI @peakcool and @ScriptedAlchemy i was studyin this yesterday and saw the same.
I've open a pr about it if you guys dont mind.
#949
