### ISSUE TITLE
Error running examples - problem with html-webpack-plugin

### ISSUE THREAD

**Issue by JB1905** [module-federation/module-federation-examples#793]
Examples crash on startup. This is a problem with `html-webpack-plugin`. After update to `5.3.1` everything works.

Tested examples:
- comprehensive demo
- typescript
- basic-host-remote

Probably visible in most or all of the examples.

![Zrzut ekranu 2021-05-9 o 10 25 55](https://user-images.githubusercontent.com/28870390/117565452-a3477000-b0b1-11eb-9d27-82fc5306a896.png)

**Comment by ScriptedAlchemy** [comment]
update the plugin
