### ISSUE TITLE
Micro frontend urls don't work when refreshing or writing manually

### ISSUE THREAD

**Issue by Ruchi1990** [module-federation/module-federation-examples#879]
I am using react-router.it works fine while I'm clicking on link buttons for microfrontends, but when I refresh my webpage or writing manually, microfrontends are not loading.

**Comment by jacob-ebey** [comment]
Do you have an html page at the route? If you hard refresh on a page that 404's this is expected.

**Comment by Ruchi1990** [comment]
I have html page at the route, it doesn't show 404. it just shows blank page. without hard refresh, i am facing this issue.

**Comment by ScriptedAlchemy** [comment]
You want something like a catch all that's able to then look up the slug and route you somewhere I'd imagine

**Comment by SurjitSahoo** [comment]
even I was stuck with this issue for weeks!!, it doesn't even go to 404, it throws a syntax error in the console. But finally, I found the solution

if somebody else still is having this issue...
make sure your public path is correct. 
Note: "auto" doesn't work. 
In dev, give the proper URL, it'll work
