### ISSUE TITLE
Css are not loading when running micro frontends in isolation.

### ISSUE THREAD

**Issue by Ruchi1990** [module-federation/module-federation-examples#880]
In react, I am using common css for container and micro frontends apps. Css are not loading when running micro frontends in isolation.

**Comment by jacob-ebey** [comment]
If you don't import shared styles in the host, or in each shared component how are they going to be loaded?

**Comment by Ruchi1990** [comment]
I am loading styles in all shared components as well, but still its not loading when i am running microfrontends in isolation.

**Comment by ScriptedAlchemy** [comment]
Do you ever import the CSS or is it just shared? Webpack disposes of unimported shared modules
