### ISSUE TITLE
using next/Image component between remote apps uses wrong base url

### ISSUE THREAD

**Issue by davidhu2000** [module-federation/module-federation-examples#884]
Using two nextjs apps to share code between them, I'm running into an issue with using next's image component. 

```js
// app1 localhost:3000
export default TestImage = () => {
  return (
    <div>
      <h1>Shows Image</h1>
      <Image src="/some_image.png" height={50} width={50} />
    </div>
  );
};
```

that Test component is exposed in via the module federation. 

```js
// app2 localhost:3001
const TestImage = dynamic(
  async () => {
    // Sleep, for demoing purposes
    // await new Promise((res) => setTimeout(res, 1500));
    // @ts-ignore
    return await import('app1/TestImage');
  },
  {
    ssr: false,
    loading: ({ error }) => {
      if (error) {
        return (
          <div>
            Error: {error.name} {error.message}
          </div>
        );
      }
      return <div>Loading External Module</div>;
    },
  }
);

export default App2 = () => {
  return (
    <div>
      <TestImage />
    </div>
  );
};
```

Doing this shows an error. Notice that it's trying to grab the image from App2

```
http://localhost:3001/_next/image?url=%2Fsome_image.png&w=50&q=50
```

This generates a 400 error with the message
> The requested resource isn't a valid image.

Is there a way I can set the path of the image so it's get loaded properly from App1?

**Comment by ScriptedAlchemy** [comment]
I haven't used nexts image component, but does it have a way to set a base url somewhere in the config?

**Comment by ScriptedAlchemy** [comment]
Might need to extend image so you can infer the url at runtime
