### ISSUE TITLE
Dynamic Public Path doesn't work

### ISSUE THREAD

**Issue by Lyukx** [module-federation/module-federation-examples#886]
I've read the resources below:
- https://webpack.js.org/concepts/module-federation/#dynamic-public-path
- https://scriptedalchemy.medium.com/micro-fe-architecture-webpack-5-module-federation-and-custom-startup-code-9cb3fcd066c

### Problem statement:
In my product, I need to give the federated module a different `publicPath`. The path is a static CDN path so I followed the approach in the above articles, but just set the `publicPath` in remote repository to the CDN path. However, I got a `Uncaught TypeError: fn is not a function` error.

My questions are:
- Is this a known issue? If yes do we have a plan to fix it?
- Do we have any work around, if I just need to customize the public path for the federated module?

### Reproduce:
Here's the minimum code for reproduction (I use the `basic-host-remote` example): https://github.com/Lyukx/module-federation-examples/commit/5ca4422d6376aad4030ad676fb7553029cbf1c3b
And this is the result I got:
![Screenshot from 2021-06-15 19-37-13](https://user-images.githubusercontent.com/8170657/122039030-32624900-ce11-11eb-9ebf-4f4fa0ddf0e4.png)

Thanks in advance :-)

**Comment by ScriptedAlchemy** [comment]
PublicPath: auto or external remotes plugin ( look in my MF org for the repo)

**Comment by olivierlacan** [comment]
@ScriptedAlchemy Do you have a URL for this? It's difficult to know what you're referring to.

**Comment by ScriptedAlchemy** [comment]
Heck federated docs or search my repo for publicPath. Basically all examples use “auto”

**Comment by Lyukx** [comment]
So finally, we found out the root cause is a webpack dev-server bug: https://github.com/webpack/webpack-dev-server/issues/2484

@ScriptedAlchemy has mentioned it in the README in https://github.com/module-federation/module-federation-examples/tree/master/startup-code.

> Currently, webpack-dev-server has a bug that incorrectly appends an entrypoint to the end of the remote.

However, since it is the dev-server bug, we found out it works properly in the production mode and we already used it.
Some alternative solutions for your local development:

1. Upgrade webpack-dev-server vertion newer than `webpack-dev-server:4.0.0-beta.2` (as suggested in the webpack-dev-server issue)
2. If your requirement is not dynamically load it in the client webapp but override module federation public path without changing the whole project's public path, you can create a separate webpack config, or follow an idae from @ScriptedAlchemy to use https://www.npmjs.com/package/external-remotes-plugin
