### ISSUE TITLE
Module Federation communication between micro frontends

### ISSUE THREAD

**Issue by tmonikat** [module-federation/module-federation-examples#889]
Hi,
I am trying to evaluate Module Federation as a microfrontend solution for our projects. Have been deep diving into the various features of Module federation and find them very useful. I have a query regarding communication between various micro frontends in an application.

For example:
Shell App : Integrates App1 and App2
App1: App1 exposes user component
App2: App2 exposes user sports activities details

Here App1 has user details which is needed in App2 to get user sport activity details.

The basic requirement here is:
App1 able to pass data to App2
App1 and App2 are not tightly coupled

Following are few approaches 
1. App1 and App2 has no interaction and user details is loaded by each of them independently
2. App1 and App2 communicate via Custom Events
3. App1 and App2 share state via Reducer injection via shell 
4. Shell App contains an EventBus which is subscribed by App1 and App2, events are used to shared data 

Wanted to understand what is the recommended Module Frontend way for such scenarios.

**Comment by KaustubhBadrike-GEP** [comment]
This seems to belong in [discussions](https://github.com/module-federation/module-federation-examples/discussions) rather than being an issue.

**Comment by ScriptedAlchemy** [comment]
Agreed. This should be a discussion.
