### ISSUE TITLE
Content Security Policy CSP with module federation

### ISSUE THREAD

**Issue by edward-sia** [module-federation/module-federation-examples#890]
How does people go about if there is a already CSP setup in place? What is the best practice when we use this with a CSP protected site?

Because of how Module Federation works, the main/shell app will have to download remoteEntry.js from all the other locations (different URL domains because I'm using S3), and later on download a bunch of JS modules as well. Assuming the shell app is CSP protected, this means we will run into violations in script-src unless we:

1. Add all the other remotes domain in our script-src directive. This could easily become a long list to maintain if there is a lot of Microfrontends/remotes if the split is granular.
2. Somehow push the shell and the other Module federation remotes into a location with the same domain, like all MF served via single S3 location but split with prefix. This approach allows us to maintain limited script-src URLs but will require more work as more there might be some complication at the app routing layer.
3. The above setup works only if the assumption is all ModuleFed remotes belong to the same parent, there is a strong chance we have another shell2 (different parent all together with CSP setup as well) which might want to reference same remotes in the first domain. Do we then also deploy this shell2 to the same domain? Fyi those 2 shells have very different audience base with 1 of them with restricted access to some features.

What do we think is the best practices to address this setup when CSP is a hard requirement for the apps. 

Happy for any suggestions or discussions to understand if anyone has gone through these type of challenges before and if anything works well for you.

**Comment by ScriptedAlchemy** [comment]
- Edge network proxy
- CDN path mapping to multiple buckets 
- Some kind of ingress/ reverse proxy

In the request path I'll usually have the team or repo name so that I know where I'm going for the deployed assets at the ingress level
