### ISSUE TITLE
beta.17: Shared module is not available for eager consumption

### ISSUE THREAD

**Issue by mlassbo** [module-federation/module-federation-examples#90]
The version-discrepancy example breaks a little when upgrading to from beta.16 to beta.17.

It is no longer possible to run app2 standalone without getting "Uncaught Error: Shared module is not available for eager consumption: webpack/sharing/consume/default/react/react"

Steps to reproduce:
```
cd version-discrepancy/app2
npm i webpack@next
npm run start

**Comment by ScriptedAlchemy** [comment]
Import bootstrap at the top works. Heavy hammer solution but @sokra has better solutions that I’ve not explored

**Comment by ScriptedAlchemy** [comment]
https://github.com/module-federation/module-federation-examples/pull/99
