### ISSUE TITLE
Getting  Loading chunk error for remote

### ISSUE THREAD

**Issue by jaslloyd** [module-federation/module-federation-examples#91]
Hey,

I am trying to use a federated module in a personal project I am doing and I am running into issues. My webpack configuration is a bit different than ones in the examples but the federated modules part is exactly the same. The setup:

Two apps:
- dashboard-shell consumes ui-components as a remote, runs on port 3001
```js
      new ModuleFederationPlugin({
        name: "dashboardshell",
        library: { type: "var", name: "dashboardshell" },
        filename: "remoteEntry.js",
        exposes: {},
        remotes: {
          uicomponents: "uicomponents",
        },
        shared: ["react", "react-dom"],
      }),
```
- ui-components only exposes Navbar and has no remotes runs on port 3002
```js
      new ModuleFederationPlugin({
        name: "uicomponents",
        library: { type: "var", name: "uicomponents" },
        filename: "remoteEntry.js",
        exposes: {
          Navbar: "./src/Navbar",
        },
        shared: ["react", "react-dom"],
      }),
```

Both are react apps.

The error I am seeing is when I load up localhost:3001 is:
```js
jsonp chunk loading:69 GET http://localhost:3001/static/js/src_Navbar_tsx.chunk.js net::ERR_ABORTED 404 (Not Found)
__webpack_require__.f.j @ jsonp chunk loading:68
(anonymous) @ ensure chunk:5
__webpack_require__.e @ ensure chunk:4
Navbar @ container-entry:3
get @ container-entry:9
(anonymous) @ remotes loading:31
__webpack_require__.f.remotes @ remotes loading:15
(anonymous) @ ensure chunk:5
__webpack_require__.e @ ensure chunk:4
./src/index.ts @ index.ts:1
__webpack_require__ @ bootstrap:17
(anonymous) @ startup:3
(anonymous) @ startup:5
jsonp chunk loading:45 Uncaught (in promise) ChunkLoadError: Loading chunk src_Navbar_tsx failed.
(error: http://localhost:3001/static/js/src_Navbar_tsx.chunk.js)
while loading "Navbar" from webpack/container/reference/uicomponents
    at Object.__webpack_require__.f.j (http://localhost:3002/remoteEntry.js:215:29)
    at http://localhost:3002/remoteEntry.js:101:40
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (http://localhost:3002/remoteEntry.js:100:67)
    at Object.Navbar (http://localhost:3002/remoteEntry.js:17:30)
    at Object.get (http://localhost:3002/remoteEntry.js:23:23)
    at http://localhost:3001/static/js/bundle.js:9901:89
    at Array.forEach (<anonymous>)
    at Object.__webpack_require__.f.remotes (http://localhost:3001/static/js/bundle.js:9885:36)
    at http://localhost:3001/static/js/bundle.js:9811:40
__webpack_require__.f.j @ jsonp chunk loading:44
...
```

The code can be seen [here](https://github.com/jaslloyd/life-dashboard)

Let me know if you need anything else.

**Comment by jaslloyd** [comment]
It seems like your publicPath has to be:  publicPath: "http://localhost:XXXX/" it cannot be /...  More specifically remote modules have to localhost path, is that a requirement?

**Comment by zhangwilling** [comment]
yes , you should do that. 

if you use '/', it will load source from current host (3001), and your app would crashed.

**Comment by ScriptedAlchemy** [comment]
Working on it https://github.com/module-federation/module-federation-examples/pull/99 could be because of webpack 5 beta 17

**Comment by ScriptedAlchemy** [comment]
also yeah publicPath must be statically set until we allow custom code to be executed during remote initialization to dynamically set public path.

**Comment by jaslloyd** [comment]
thanks @ScriptedAlchemy, really loving Module federation!

**Comment by ScriptedAlchemy** [comment]
Thanks! We just did a silent release of the dashboard! Its not open-source its got a free use mode, that operates in read-only mode. 

https://youtu.be/RS3t5obRQZ0

This allows you to see who uses what and where within a federated system. If anyone wants to try it early in the first alpha - ill can send over instructions till the docs are pushed up and some publicity is created around it. 

read-write mode will support instant rollback and versioning of remotes, basically deployless orchestration across a stack

**Comment by ScriptedAlchemy** [comment]
to reiterate. `./Navbar` will fix it
