### ISSUE TITLE
Hashed Remote Entry + SSR

### ISSUE THREAD

**Issue by wvanrensselaer** [module-federation/module-federation-examples#948]
Hello, I'm trying to get an SSR'd React app running with a hashed remote entry:

`header-app`
```js
new ModuleFederationPlugin({
  name: 'Header',
  filename: 'remoteEntry.[contenthash:8].js',
  exposes: {
    './Header': './src/components/Header'
  },
  library: {type: 'commonjs2'}
})
```

This is necessary to avoid hydration mismatches around deploys between when the client assets are uploaded to a bucket and the SSR server rerolls. But we currently need to know the container file at build time for consuming apps:

`main-app`
```js
new ModuleFederationPlugin({
  remotes: {
    '@header': '/path/to/header-app/public/remoteEntry.???.js'
  },
  library: {type: 'commonjs2'}
})
```

The `external-remotes-plugin` described in https://github.com/module-federation/module-federation-examples/issues/566 works nicely for this on the client side, but doesn't seem to work on the server bundle:

```js
new ModuleFederationPlugin({
  remotes: {
    '@header': 'Header@[global.HeaderRemoteEntryPath]
  },
  library: {type: 'commonjs2'}
})

// Gets compiled to this:
require("Header@[global.HeaderRemoteEntryPath]");
// But want:
require(global.HeaderRemoteEntryPath);
```

Is there another way to make this work that I'm missing? The SSR example in this repo doesn't use a hashed remote entry. Any guidance would be appreciated. Webpack internals are not my mamma jamma, but happy to try to contribute if this functionality is missing. Thanks!

**Comment by ScriptedAlchemy** [comment]
You cannot use the require or import syntax. You’d need to use the low level api and inject the remote yourself as a dynamic remote. The parser won’t know what you’re trying to import. You could also use the promise new Promise syntax (check webpack docs)

**Comment by wvanrensselaer** [comment]
Ah, yeah dynamic remotes solved this, thanks @ScriptedAlchemy
