### ISSUE TITLE
vue-cli TypeError: Cannot read property 'parseComponent' of undefined

### ISSUE THREAD

**Issue by junsen313** [module-federation/module-federation-examples#967]
i has clone this repo, and follow this step to run vue-cli:
  1. yarn
  2. cd vue-cli
  3. yarn serve
  then, throw error like this:
@vue-cli/other:  ERROR  Failed to compile with 1 error上午11:53:00
@vue-cli/other: Syntax Error: TypeError: Cannot read property 'parseComponent' of undefined
@vue-cli/other: You may use special comments to disable some warnings.
@vue-cli/other: Use // eslint-disable-next-line to ignore the next line.
@vue-cli/other: Use /* eslint-disable */ to ignore all warnings in a file.

**Comment by schirrel** [comment]
@junsen313 please, try installing webpack-cli globally

**Comment by ScriptedAlchemy** [comment]
Help wanted solving this if it’s still an issue

**Comment by junsen313** [comment]
> @junsen313 please, try installing webpack-cli globally

it's work! thank you. but why ?

**Comment by acongy** [comment]
Hello 你们解决了？
已经困扰了我一下午

`$ vue-cli-service serve
 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 error                                                                                                        3:01:55 PM

Syntax Error: TypeError: Cannot read property 'parseComponent' of undefined


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
`
