### ISSUE TITLE
Dynamic system host example crashing because react loaded twice

### ISSUE THREAD

**Issue by ocdi** [module-federation/module-federation-examples#97]
I'm really excited by federated modules, however when I tried to apply it to my application I had the dreaded invalid hook call. I can see from the network tab that the host is providing react, but the remote is also requesting and loading its own copy of react. This doesn't match my expectations for what federated modules is supposed to be doing.

I have cloned on this repo, ran yarn in the root and for the `dynamic-system-host` example, individually started `app1`, `app2`, `app3`. For some reason lerna wasn't running in the parent directory. Note I am using Windows as my OS.

The app loads fine initially:
![image](https://user-images.githubusercontent.com/2775804/83993266-4cfc1980-a996-11ea-810d-9e58a01996b9.png)

Clearing the network tab and then clicking `Load App 3 Widget`

results in these network requests

![image](https://user-images.githubusercontent.com/2775804/83993391-a2d0c180-a996-11ea-80f7-8507121d3f0d.png)

And then it crashes out
![image](https://user-images.githubusercontent.com/2775804/83993367-8df42e00-a996-11ea-8b46-ffe8d2d06389.png)

I would like to understand if this example is broken, or whether there is a bug in the module federation. Some hints to why it isn't correctly federating and/or how to diagnose what is going on, would be appreciated.

**Comment by ocdi** [comment]
I did some digging and I spotted that along with the .get method, there is a .override method. Also watched 

![image](https://user-images.githubusercontent.com/2775804/83995889-fe527d80-a99d-11ea-84e9-06aca535b8c9.png)

I can see by the breakpoints here that the override isn't being called here.

I noticed in beta17 the initialization has been reworked, override is now init, so there is possibly no point fixing this against beta16.

It also suffers the same problem.

![image](https://user-images.githubusercontent.com/2775804/83995741-9439d880-a99d-11ea-84f2-41d93c314d4d.png)

Digging further, when this is loaded by the system in the remotes, it appears to call the init method with the value in `__webpack_require__.S.default`. I made a PR #98 that actually seems to work as intended here.

I am unsure if this broke due to the unstable API at this time, and while it works, this doesn't seem the most reliable method to solve this.

**Comment by zhangwilling** [comment]
aha, it seems that @ScriptedAlchemy  forgot to remove the test code 🤣. 

 This problem was talked at Issue #51.

**Comment by zhangwilling** [comment]
you can find the solution at `advanced-api/dynamic-remotes` .

**Comment by ocdi** [comment]
ahh thanks @zhangwilling that makes more sense! also seems slightly less hacky than my version. I imagine the folder I was working in should be removed to avoid future confusion.

**Comment by ScriptedAlchemy** [comment]
incorrect upgrade of webpack 5 beta 17 which has breaking changes. Im working through the repo 

https://github.com/module-federation/module-federation-examples/pull/99
